# Import thư viện + Load data

In [1]:
import os
import polars as pl
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [2]:
def read_parquet_by_type(train_path: str):
    # Lấy tất cả các file parquet trong thư mục
    files = [os.path.join(train_path, f) for f in os.listdir(train_path) if f.endswith('.parquet')]
    
    # Phân loại các file theo loại tên
    user_chunk_files = [file for file in files if 'user_chunk' in file]
    purchase_history_chunk_files = [file for file in files if 'purchase_history_daily_chunk' in file]
    item_chunk_files = [file for file in files if 'item_chunk' in file]
    
    # Đọc các file riêng biệt thành DataFrame
    user_chunk_df = pl.concat([pl.read_parquet(file) for file in user_chunk_files]) if user_chunk_files else None
    purchase_history_chunk_df = pl.concat([pl.read_parquet(file) for file in purchase_history_chunk_files]) if purchase_history_chunk_files else None
    item_chunk_df = pl.concat([pl.read_parquet(file) for file in item_chunk_files]) if item_chunk_files else None
    
    # Trả về một dictionary chứa các DataFrame
    return {
        "user_chunk": user_chunk_df,
        "purchase_history_chunk": purchase_history_chunk_df,
        "item_chunk": item_chunk_df
    }

In [3]:
data = read_parquet_by_type("C:/Users/tncn2/Downloads/recommendation dataset")

# history_df = data["purchase_history_chunk"]
# user_df = data["user_chunk"]
item_df = data["item_chunk"]

# description & description_new

## Kiểm tra

In [41]:
cols_to_show = [
    "volume", "material", "gender_target"
]

# --- Cấu hình để hiển thị đầy đủ text ---
pl.Config.set_tbl_cols(-1)           # Hiển thị tất cả các cột
pl.Config.set_tbl_width_chars(100)  # Tăng độ rộng bảng để tránh bị '...'

# --- Lấy 5 hàng đầu ---
subset_df = item_df.select(cols_to_show).head(5)

# --- In ra ---
print(subset_df)

shape: (5, 3)
┌────────────────┬─────────────────────────────────┬────────────────┐
│ volume         ┆ material                        ┆ gender_target  │
│ ---            ┆ ---                             ┆ ---            │
│ str            ┆ str                             ┆ str            │
╞════════════════╪═════════════════════════════════╪════════════════╡
│ Không xác định ┆ Không xác định                  ┆ Không xác định │
│ Không xác định ┆ Không xác định                  ┆ Bé Gái         │
│ Không xác định ┆ Không xác định                  ┆ Không xác định │
│ Không xác định ┆ Giấy, bột giấy, vải không dệt,… ┆ Không xác định │
│ Không xác định ┆ Giấy, bột giấy, vải không dệt,… ┆ Không xác định │
└────────────────┴─────────────────────────────────┴────────────────┘

### Xem thử 2 cột

In [6]:
pl.Config.set_tbl_rows(50)             # số dòng tối đa hiển thị
pl.Config.set_tbl_cols(10)             # số cột tối đa hiển thị
pl.Config.set_tbl_width_chars(200)     # tổng chiều rộng bảng ký tự
pl.Config.set_fmt_str_lengths(2000)     # độ dài chuỗi tối đa hiển thị (quan trọng nhất!)

item_df.select(["description", "description_new", "item_type"]).head(10)

shape: (10, 3)
┌──────────────────────────────────────────────────────────────────────────────────────────┬──────────────────────────────────────────────────────────────────────────────────────────┬────────────────┐
│ description                                                                              ┆ description_new                                                                          ┆ item_type      │
│ ---                                                                                      ┆ ---                                                                                      ┆ ---            │
│ str                                                                                      ┆ str                                                                                      ┆ str            │
╞══════════════════════════════════════════════════════════════════════════════════════════╪══════════════════════════════════════════════════════════════════════════════════════════╪════════════════╡
│ Không xác định                                                                           ┆ Chi tiết sản phẩm                     Tên sản phẩm: Hộp 2 núm ty DrBrown's Options Plus  ┆ Không xác định │
│                                                                                          ┆ cổ rộng Y cut (Trên 9 tháng)         Loại sản phẩm: Núm ty         Đối tượng sử dụng:    ┆                │
│                                                                                          ┆ Trẻ trên 9 tháng         Thương hiệu: DrBrown's         Điểm nổi bật: Núm vú silicon     ┆                │
│                                                                                          ┆ siêu mềm giúp phát triển cơ hàm của bé thông qua sự cử động lưỡi tự nhiên.               ┆                │
│                                                                                          ┆ Hộp 2 núm ty DrBrown's Options Plus cổ rộng Y cut (Trên 9 tháng) là núm ty dành cho trẻ  ┆                │
│                                                                                          ┆ trên 9 tháng của thương hiệu DrBrown's đến từ Mỹ. Núm vú silicon siêu mềm giúp phát      ┆                │
│                                                                                          ┆ triển cơ hàm của bé thông qua sự cử động lưỡi một cách tự nhiên.                         ┆                │
│                                                                                          ┆ Núm ty silicon mềm mại            Núm vú silicon siêu mềm giúp phát triển cơ hàm của bé  ┆                │
│                                                                                          ┆ thông qua sự cử động lưỡi một cách tự nhiên. Thiết kế đầu núm vừa vặn với vòm miệng bé,  ┆                │
│                                                                                          ┆ mang lại sự thoải mái khi sử dụng.               Thiết kế thông minh            Núm ty   ┆                │
│                                                                                          ┆ DrBrown's Options Plus được thiết kế với lỗ tiết sữa Y cut, phù hợp với nhu cầu ăn cháo  ┆                │
│                                                                                          ┆ đặc của bé trên 9 tháng tuổi, từ đó giúp bé có cảm giác gần gũi hơn trong từng lần bú.   ┆                │
│                                                                                          ┆ Hướng dẫn sử dụng               Rửa sạch núm ty bằng nước rửa chuyên dụng trước khi sử   ┆                │
│                                                                                          ┆ dụng lần đầu.         Đun sôi núm vú trong vòng 3-5 phút để tiệt trùng sau mỗi lần sử    ┆                │
│                                                                                          ┆ dụng.         Kiểm tra núm vú trước khi cho bé sử dụng, đảm bảo không có dấu hiệu rách   ┆                │
│                                                                                          ┆ hoặc thủng.         Không cho trẻ bú bình khi không có sự giám sát của người lớn.        ┆                │
│                                                                                          ┆ Hướng dẫn bảo quản               Bảo quản ở nhiệt độ phòng, nơi khô ráo, thoáng mát.     ┆                │
│                                                                                          ┆ Tránh ánh nắng mặt trời trực tiếp.         Thay núm ty mới sau khi sử dụng từ 1 - 2      ┆                │
│                                                                                          ┆ tháng để đảm bảo vệ sinh cho trẻ.                     Lưu ý               Không rửa núm  ┆                │
│                                                                                          ┆ ty bằng xà phòng hoặc nước tẩy rửa.         Không tiệt trùng núm ty bằng lò vi sóng.     ┆                │
│                                                                                          ┆ Kiểm tra núm vú thường xuyên trước khi sử dụng.                     Thành phần           ┆                │
│                                                                                          ┆ Silicon cao cấp         Không chứa BPA         Chất đàn hồi tốt                          ┆                │
│ Không xác định                                                                           ┆ Không xác định                                                                           ┆ Bộ quần áo     │
│ - Chất liệu: Sản phẩm được làm bằng chất liệu silicone mềm, dẻo và nước đã được chưng    ┆ Chi tiết sản phẩm                     Tên sản phẩm: Miếng Gặm Nướu Papa (CEQ004) (Cá     ┆ Không xác định │
│ cất đảm bảo an toàn cho bé. - Dành cho các bé trong giai đoạn mọc răng, giúp làm giảm    ┆ hồng)         Chất liệu: Silicone mềm, dẻo và nước đã được chưng cất         Đối tượng   ┆                │
│ đau, ngứa lợi cho bé. - Bề mặt có các núm mát-xa nhỏ, mềm mịn, tạo cảm giác dễ chịu cho  ┆ sử dụng: Dành cho các bé trong giai đoạn mọc răng         Thương hiệu: Papa         Xuất ┆                │
│ bé. - Có độ đàn hồi tốt, dễ dàng uốn dẻo, bền đẹp không gây ảnh hưởng tới sức khỏe cho   ┆ xứ: Thái Lan         Giá: 45.000₫                     **Miếng Gặm Nướu Papa (CEQ004) (Cá ┆                │
│ bé. - Thiết kế dạng hình các con vật đồ dùng ngộ nghỉnh, đặc biệt có tay cầm, giúp bé dễ ┆ hồng)** là một sản phẩm giúp bé giảm đau trong giai đoạn mọc răng của thương hiệu **Papa ┆                │
│ cầm nắm. - Trước khi cho bé sử dụng, bạn có thể cho vào tủ lạnh tạo cảm giác mát lạnh bé ┆ đến từ Thái Lan**. Sản phẩm được thiết kế đặc biệt để tạo cảm giác dễ chịu cho bé khi    ┆                │
│ thích thú Lưu ý: Không sử dụng nước sôi để khử trùng sản phẩm. Xuất xứ: Thái Lan﻿﻿         ┆ nhai.                        Chất liệu an toàn: Silicone mềm, dẻo           Miếng gặm    ┆                │
│                                                                                          ┆ nướu được làm bằng chất liệu silicone mềm, dẻo và nước đã được chưng cất, đảm bảo an     ┆                │
│                                                                                          ┆ toàn tuyệt đối cho sức khỏe của bé.            Cảm giác dễ chịu: Bề mặt núm mát-xa       ┆                │
│                                                                                          ┆ Bề mặt có các núm mát-xa nhỏ, mềm mịn, tạo cảm giác dễ chịu và thích thú khi bé sử dụng. ┆                │
│                                                                                          ┆ Thiết kế ngộ nghĩnh: Hình động vật với tay cầm           Sản phẩm được thiết kế dạng     ┆                │
│                                                                                          ┆ hình các con vật đồ dùng ngộ nghĩnh, đặc biệt có tay cầm giúp bé dễ cầm nắm và chơi đùa. ┆                │
│                                                                                          ┆ Độ đàn hồi tốt: Bền đẹp và dễ sử dụng           Miếng gặm nướu có độ đàn hồi tốt, dễ     ┆                │
│                                                                                          ┆ dàng uốn dẻo, bền đẹp mà không gây ảnh hưởng đến sức khỏe cho bé.            Cảm giác    ┆                │
│                                                                                          ┆ mát lạnh: Hỗ trợ giảm đau           Trước khi cho bé sử dụng, bạn có thể cho vào tủ lạnh ┆                │
│                                                                                          ┆ tạo cảm giác mát lạnh, giúp bé thích thú và giảm đau nướu.               Hướng dẫn sử    ┆                │
│                                                                                          ┆ dụng               Rửa sạch sản phẩm trước khi cho bé sử dụng.         Để sản phẩm trong ┆                │
│                                                                                          ┆ tủ lạnh trước khi cho bé sử dụng để tạo cảm giác mát lạnh.         Giám sát bé khi sử    ┆                │
│                                                                                          ┆ dụng để đảm bảo an toàn.                     Hướng dẫn bảo quản               Bảo quản   ┆                │
│                                                                                          ┆ sản phẩm ở nơi khô ráo, thoáng mát.         Không sử dụng nước sôi để khử trùng sản      ┆                │
│                                                                                          ┆ phẩm.         Thường xuyên kiểm tra sản phẩm để đảm bảo không bị hư hỏng.                ┆                │
│                                                                                          ┆ Lưu ý               Sản phẩm chỉ dành cho bé trong giai đoạn mọc răng.         Khi sản   ┆                │
│                                                                                          ┆ phẩm có dấu hiệu hư hỏng, không nên cho bé sử dụng.  …                                   ┆                │
│ ﻿﻿Tã dán Merries size S 82 miếng là sản phẩm dành cho bé 4-8kg đến từ thương hiệu uy tín   ┆ Không xác định                                                                           ┆ Không xác định │
│ Merries của Nhật Bản. Ra đời với công nghệ "4 siêu" - siêu mềm mại, siêu thông thoáng,   ┆                                                                                          ┆                │
│ siêu thấm hút, siêu linh hoạt, tã dán Merries trở thành "người bạn" của hàng ngàn em bé  ┆                                                                                          ┆                │
│ trên toàn thế giới.﻿﻿﻿Ưu điểm nổi bật. Siêu mềm mại: được làm từ bông siêu mỏng và các hạt  ┆                                                                                          ┆                │
│ thấm hút nhanh, có bề mặt mềm mại, xốp mịn, tiếp xúc nhẹ nhàng, không gây hằn đỏ trên da ┆                                                                                          ┆                │
│ bé.. Siêu thông thoáng: dựa vào công nghệ siêu thoát khí từ chất liệu màng đáy thoát khí ┆                                                                                          ┆                │
│ đặc biệt giúp bé yêu cảm thấy luôn dễ chịu, thoải mái. Cha mẹ có thể xóa tan nỗi lo nóng ┆                                                                                          ┆                │
│ ẩm và hầm hơi do nước tiểu và mồ hôi cũng như kích ứng da do các tác nhân gây hại.. Siêu ┆                                                                                          ┆                │
│ thấm hút: thiết kế chống tràn khóa chặt chất lỏng đến 6-8 tiếng và không vón cục. Các    ┆                                                                                          ┆                │
│ hạt thấm hút kép cùng với bề mặt tiếp xúc điểm xốp mịn tạo ra những khoảng trống giúp    ┆                                                                                          ┆                │
│ thấm chất lỏng cực nhanh và không bị lan ra khắp bề mặt tã.. Siêu linh hoạt: thiết kế    ┆                                                                                          ┆                │
│ vừa vặn với cơ thể bé với vách chống tràn co dãn và phần eo mềm mại ôm khít, thiết kế    ┆                                                                                          ┆                │
│ phần đáy hình chữ "W" không gây cảm giác vướng víu và linh hoạt theo từng chuyển động    ┆                                                                                          ┆                │
│ của bé.. Vạch báo thời gian thay tã thông minh: thay đổi sang màu xanh lá đậm sẽ giúp bố ┆                                                                                          ┆                │
│ mẹ dễ dàng nhận biết thời điểm cần thiết để thay tã cho bé.Hướng dẫn sử dụng             ┆                                                                                          ┆                │
│ ﻿﻿﻿Bỉm tã quần Merries size M 58 miếng là sản phẩm dành cho bé từ 6-11kg đến từ thương hiệu ┆ Không xác định                                                                           ┆ Không xác định │
│ uy tín Merries của Nhật Bản. ﻿﻿﻿﻿Tã quần Merries – một sản phẩm mang tính đột phá đến từ     ┆                                                                                          ┆                │
│ Nhật Bản, khác biệt hoàn toàn so với những loại tã giấy khác trên thị trường, đặc biệt   ┆                                                                                          ┆                │
│ mỏng nhẹ giúp bé tung tăng chạy nhảy suốt 24h mà vẫn khô thoáng và êm dịu.Ưu điểm nổi    ┆                                                                                          ┆                │
│ bật﻿. Siêu mềm mại với bề mặt tiếp xúc điểm xốp mịn và chất liệu mỏng nhẹ, không gây kích ┆                                                                                          ┆                │
│ ứng lên làn da mỏng manh của bé.. Siêu thông thoáng với chất liệu màng đáy thoát khí đặc ┆                                                                                          ┆                │
│ biệt. Các đường thun được thiết kế để không khí dễ dàng thổi qua giữa miếng tã và da. Bé ┆                                                                                          ┆                │
│ sẽ luôn cảm thấy khô ráo ngay cả khi vân động nhiều.. Siêu thấm hút với lõi siêu thấm    ┆                                                                                          ┆                │
│ trung tâm độc đáo giúp thấm hút và khoá chặt một lượng lớn chất lỏng ngay lập tức. Đặc   ┆                                                                                          ┆                │
│ biệt tã không bị vón cục sau khi thấm hút.. Siêu linh hoạt trong chuyển động với thiết   ┆                                                                                          ┆                │
│ kế chữ “W” biến đổi linh hoạt với đáy quần thích ứng theo chuyển động của bé. Đường thun ┆                                                                                          ┆                │
│ ôm vừa vặn không để lại vết hằn trên da.. Vạch báo thời gian thay tã thông minh: Thay tã ┆                                                                                          ┆                │
│ khi vạch đổi sang màu xanh lá đậmHướng dẫn sử dụng ﻿﻿                                      ┆                                                                                          ┆                │
│ Áo thun bé trai tay ngắn CF B078010 Xanh  là sản phẩm với chất liệu cotton mềm mại, thấm ┆ Không xác định                                                                           ┆ Áo             │
│ hút mồ hôi, đường may kỹ lưỡng chắc chắn sẽ giúp bé thoải mái vận động. Bên cạnh đó, sản ┆                                                                                          ┆                │
│ phẩm có kiểu dáng cá tính cùng họa tiết đáng yêu sẽ giúp bé thêm phần thời trang. ĐẶC    ┆                                                                                          ┆                │
│ ĐIỂM NỔI BẬT Chất liệu cotton mềm mại Sản phẩm được may từ vải cotton mềm mại cho phép   ┆                                                                                          ┆                │
│ bé thoải mái chơi đùa, vận động mà không cảm thấy khó chịu. Bên cạnh đó, chất liệu       ┆                                                                                          ┆                │
│ cotton không gây kích ứng da và có khả năng thấm hút mồ hôi tốt nên Mẹ không phải lo     ┆                                                                                          ┆                │
│ lắng bé yêu bị nổi rôm, tuyệt đối an toàn khi sử dụng. Thiết kế thoải mái, đáng yêu      ┆                                                                                          ┆                │
│ Thiết kế thoải mái phối cùng họa tiết cá tính sẽ mang đến phong cách thoải mái và không  ┆                                                                                          ┆                │
│ kém phần thời trang cho bé của bạn. Ngoài ra, các đường nối, đường cuốn biên trên sản    ┆                                                                                          ┆                │
│ phẩm không bị nổi cộm gây khó chịu và ngứa da bé cho phép bé vận động dễ dàng. THÔNG TIN ┆                                                                                          ┆                │
│ SẢN PHẨM Tên sản phẩm: Áo thun bé trai tay ngắn CF B078010 Xanh Thương hiệu: CF Sản xuất ┆                                                                                          ┆                │
│ tại: CÔNG TY TNHH MAY MẶC HẢI NAM , Việt Nam Chất liệu: 95% Cotton5% Spandex BẢO QUẢN    ┆                                                                                          ┆                │
│ SẢN PHẨM - Hạn chế dùng sản phẩm giặt tẩy - Không ngâm, giặt chung với sản phẩm ra màu - ┆                                                                                          ┆                │
│ Không giặt trong nước nóng trên 40°C - Nên ủi/là mặt trái sản phẩm                       ┆                                                                                          ┆                │
│ - Sản phẩm dành cho bé từ 3 - 36 tháng tuổi. - Nguyên liệu được làm bằng cao su có tính  ┆ Chi tiết sản phẩm                     Tên sản phẩm: Thảm xốp hình chữ 30x30cm, 26 miếng  ┆ Không xác định │
│ đàn hồi tốt, dùng lót sàn. Giúp bé vừa học vừa chơi mà không lo bị bé yêu bị va đập. -   ┆ Chất liệu: Cao su         Kích thước: 30x30x1cm/miếng         Khối lượng tịnh: 58g/miếng ┆                │
│ Thảm có nhiều màu sắc, hình các chữ cái và số kích thích bé vừa học vừa chơi, mẹ yên tâm ┆ Xuất xứ: Việt Nam         Năm sản xuất: 2018         Sản xuất tại: Công Ty TNHH SX-TM    ┆                │
│ làm việc nhà. Hướng dẫn sử dụng: Nối các tấm xốp với nhau bằng răng nối. Cảnh báo: Không ┆ THOẠI TÂN THÀNH (28/36/23 Lương Thế Vinh, P.Tân Thới Hoà, Q.Tân phú, TP.HCM)             ┆                │
│ nên cho bé ngậm, cắn hay đưa sản phẩm vào miệng. Thông tin sản phẩm - Tên sản phẩm: Thảm ┆ Chịu trách nhiệm hàng hóa: CÔNG TY CỔ PHẦN CON CƯNG (101-103 Trần Quang Khải, P.Tân      ┆                │
│ xốp hình chữ 30x30cm, 26 miếng - Chất liệu: Cao su - Kích thước: 30x30x1cm/ miếng. -     ┆ Định, Q.1, HCM)                        **Thảm xốp hình chữ 30x30cm, 26 miếng** là thảm   ┆                │

**Độ phủ hai cột mô tả: `description_new` vs `description`**

**Bảng tóm tắt (đếm theo NULL thuần):**

| Trường hợp | Số dòng | Tỷ lệ (%) |
|---|---:|---:|
| **Cả hai đều có** (`both_present`) | **6,308** | **23.08** |
| **Chỉ có `description_new`** | **3,194** | **11.69** |
| **Chỉ có `description`** | **2,395** | **8.76** |
| **Không có cả hai** (`neither_present`) | **15,435** | **56.47** |
| **Tổng** | **27,332** | **100.00** |

- Hàng **có `description_new`** = 6,308 + 3,194 = **9,502** (**34.77%**).  
  ⟶ **Thiếu `description_new`** ≈ **17,830**.
- Hàng **có `description`** = 6,308 + 2,395 = **8,703** (**31.84%**).  
  ⟶ **Thiếu `description`** ≈ **18,629**.
- Hàng **có ít nhất một** mô tả = 27,332 − 15,435 = **11,897** (**43.53%**).  
  ⟶ Dù **gộp/điền qua lại**, vẫn còn **56.47%** dòng **không có mô tả**.


### Gợi ý tiền xử lý
- Tạo cột hợp nhất **`description_merged`**: ưu tiên `description_new`, nếu thiếu thì dùng `description`.
- Với nhóm **thiếu cả hai**:
  - Loại/giảm trọng số nếu mô hình cần văn bản, **hoặc**
  - Bổ sung đặc trưng từ metadata (brand, material, category, …), **hoặc**
  - Sinh mô tả tóm tắt từ metadata (nếu phù hợp).

In [12]:
kxd_list = ["không xác định","null"]

s_new = pl.col("description_new").cast(pl.Utf8).str.to_lowercase().str.strip_chars()
s_old = pl.col("description").cast(pl.Utf8).str.to_lowercase().str.strip_chars()

new_has_text = pl.col("description_new").is_not_null() & (s_new.str.len_chars() > 0) & (~s_new.is_in(kxd_list))
old_has_text = pl.col("description").is_not_null() & (s_old.str.len_chars() > 0) & (~s_old.is_in(kxd_list))

counts_value = (
    item_df.select(
        (new_has_text & old_has_text).sum().alias("both_present"),
        (new_has_text & ~old_has_text).sum().alias("only_description_new"),
        (~new_has_text & old_has_text).sum().alias("only_description"),
        (~new_has_text & ~old_has_text).sum().alias("neither_present"),
    )
    .with_columns(
        total = pl.sum_horizontal(pl.all())
    )
    .with_columns(
        *[(pl.col(c) / pl.col("total") * 100).round(2).alias(f"{c}_pct")
          for c in ["both_present","only_description_new","only_description","neither_present"]]
    )
)
print(counts_value)

shape: (1, 9)
┌──────────────┬──────────────────────┬──────────────────┬─────────────────┬───────┬──────────────────┬──────────────────────────┬──────────────────────┬─────────────────────┐
│ both_present ┆ only_description_new ┆ only_description ┆ neither_present ┆ total ┆ both_present_pct ┆ only_description_new_pct ┆ only_description_pct ┆ neither_present_pct │
│ ---          ┆ ---                  ┆ ---              ┆ ---             ┆ ---   ┆ ---              ┆ ---                      ┆ ---                  ┆ ---                 │
│ u32          ┆ u32                  ┆ u32              ┆ u32             ┆ u32   ┆ f64              ┆ f64                      ┆ f64                  ┆ f64                 │
╞══════════════╪══════════════════════╪══════════════════╪═════════════════╪═══════╪══════════════════╪══════════════════════════╪══════════════════════╪═════════════════════╡
│ 6308         ┆ 3194                 ┆ 2395             ┆ 15435           ┆ 27332 ┆ 23.08            ┆ 11.69                    ┆ 8.76                 ┆ 56.47               │
└──────────────┴──────────────────────┴──────────────────┴─────────────────┴───────┴──────────────────┴──────────────────────────┴──────────────────────┴─────────────────────┘

In [ ]:
# df_item = item_df.with_columns(
#     pl.when(pl.col("description_new").is_not_null() & (pl.col("description_new").str.len_chars()>0))
#       .then(pl.col("description_new"))
#       .otherwise(pl.col("description"))
#       .alias("description_merged")
# )

### Tính Cramer's V giữa des_new và des với một số feature có thể liên quan

In [5]:
import polars as pl
from math import sqrt

def cramers_v_fast_pl(df: pl.DataFrame, x: str, y: str):
    """
    Cramér's V (raw) giữa 2 cột phân loại x, y.
    - Chỉ drop NULL ở x,y (giữ nguyên dữ liệu gốc).
    - Không tạo cross-join r*c nên rất nhẹ.
    Trả về: (V, n, r, c)
    """
    d = df.select([x, y]).drop_nulls()
    n = d.height
    if n == 0:
        return float("nan"), 0, 0, 0

    # O_ij
    obs = d.group_by([x, y]).len().rename({"len": "obs"})
    # Tổng hàng & cột
    row = d.group_by(x).len().rename({"len": "row"})
    col = d.group_by(y).len().rename({"len": "col"})
    t = obs.join(row, on=x, how="left").join(col, on=y, how="left")

    # Chi-square: sum(O^2 / E) - N, với E = row_i * col_j / N
    term_sum = t.select(
        ((pl.col("obs") ** 2) / (pl.col("row") * pl.col("col") / n)).sum()
    ).to_series()[0]
    chi2 = term_sum - n
    r, c = d.select(pl.col(x).n_unique().alias("r"),
                    pl.col(y).n_unique().alias("c")).row(0)
    if r < 2 or c < 2:
        return float("nan"), n, r, c
    phi2 = chi2 / n
    V = sqrt(phi2 / min(r - 1, c - 1))
    return float(V), n, r, c

def compare_feature_pl(df: pl.DataFrame, feature: str) -> pl.DataFrame:
    rows = []
    for txt in ["description_new", "description"]:
        v, n, r, c = cramers_v_fast_pl(df, txt, feature)
        rows.append({"feature": feature, "text_col": txt,
                     "n_used": n, "x_levels": r, "y_levels": c,
                     "cramers_v": None if v != v else round(v, 3)})
    return pl.DataFrame(rows)

In [8]:
# 1 feature
print(compare_feature_pl(item_df, "material"))

# Nhiều feature
features = ["material","origin","size","color","item_type",
            "age_group","gender_target","brand","manufacturer","category"]
res = pl.concat([compare_feature_pl(item_df, f) for f in features])
print(res.select(["feature","text_col","cramers_v"])
         .pivot(values="cramers_v", index="feature", columns="text_col")
         .sort("feature"))

shape: (2, 6)
┌──────────┬─────────────────┬────────┬──────────┬──────────┬───────────┐
│ feature  ┆ text_col        ┆ n_used ┆ x_levels ┆ y_levels ┆ cramers_v │
│ ---      ┆ ---             ┆ ---    ┆ ---      ┆ ---      ┆ ---       │
│ str      ┆ str             ┆ i64    ┆ i64      ┆ i64      ┆ f64       │
╞══════════╪═════════════════╪════════╪══════════╪══════════╪═══════════╡
│ material ┆ description_new ┆ 22317  ┆ 9501     ┆ 583      ┆ 0.884     │
│ material ┆ description     ┆ 27332  ┆ 8583     ┆ 583      ┆ 0.964     │
└──────────┴─────────────────┴────────┴──────────┴──────────┴───────────┘
shape: (10, 3)
┌───────────────┬─────────────────┬─────────────┐
│ feature       ┆ description_new ┆ description │
│ ---           ┆ ---             ┆ ---         │
│ str           ┆ f64             ┆ f64         │
╞═══════════════╪═════════════════╪═════════════╡
│ age_group     ┆ 0.762           ┆ 0.818       │
│ brand         ┆ 0.867           ┆ 0.837       │
│ category      ┆ 0.838           ┆ 0.813       │
│ color         ┆ 0.623           ┆ 0.755       │
│ gender_target ┆ 0.612           ┆ 0.597       │
│ item_type     ┆ 0.868           ┆ 0.83        │
│ manufacturer  ┆ 0.889           ┆ 0.951       │
│ material      ┆ 0.884           ┆ 0.964       │
│ origin        ┆ 0.821           ┆ 0.869       │
│ size          ┆ 0.654           ┆ 0.84        │
└───────────────┴─────────────────┴─────────────┘

C:\Users\tncn2\AppData\Local\Temp\ipykernel_16480\1476810371.py:9: DeprecationWarning: the argument `columns` for `DataFrame.pivot` is deprecated. It was renamed to `on` in version 1.0.0.
  .pivot(values="cramers_v", index="feature", columns="text_col")

### Tính contain_ratio cho những dòng both present des_new và des

In [12]:
import polars as pl
import re

# =======================
# 1) Tham số có thể chỉnh
# =======================
LEVEL = "word"   # "word" (theo từ) hoặc "char" (theo ký tự)
N     = 2        # n-gram: word bigram (2) / trigram (3) ; hoặc char-gram (ví dụ 5)

# =======================
# 2) Hàm tiện ích
# =======================
def tokenize(s: str):
    # Tách từ đơn giản, giữ unicode (phù hợp TV/TViệt)
    return re.findall(r"\w+", s.lower())

def ngrams(tokens, n=2):
    if len(tokens) < n: 
        return []
    return [" ".join(tokens[i:i+n]) for i in range(len(tokens)-n+1)]

def build_set(s: str, level="word", n=2):
    if not s:
        return set()
    if level == "char":
        s_norm = re.sub(r"\s+", " ", s.lower())
        if len(s_norm) < n:
            return set()
        return set(s_norm[i:i+n] for i in range(len(s_norm)-n+1))
    elif level == "word":
        toks = tokenize(s)
        if n == 1:
            return set(toks)
        else:
            return set(ngrams(toks, n))
    else:
        raise ValueError("LEVEL phải là 'word' hoặc 'char'.")

def contain_ratio_sets(A_set: set, B_set: set) -> float:
    return 0.0 if not A_set else len(A_set & B_set) / len(A_set)

def contain_pair(a: str, b: str, level="word", n=2):
    """
    Trả về (recall=A|B, precision=B|A, F1, sizeA, sizeB)
    """
    A = build_set(a, level=level, n=n)
    B = build_set(b, level=level, n=n)
    r = contain_ratio_sets(A, B)  # A nằm trong B bao nhiêu %
    p = contain_ratio_sets(B, A)  # B nằm trong A bao nhiêu %
    f1 = 0.0 if (p + r) == 0 else 2 * p * r / (p + r)
    return (r, p, f1, len(A), len(B))

# ===========================================
# 3) Mask both_present & báo cáo tình trạng null
# ===========================================
mask_both = (
    pl.col("description").is_not_null() & pl.col("description_new").is_not_null() &
    (pl.col("description").str.len_chars() > 0) &
    (pl.col("description_new").str.len_chars() > 0)
)

null_report = item_df.select([
    (pl.col("description").is_null() & pl.col("description_new").is_null()).mean().alias("both_null_frac"),
    (pl.col("description").is_null() & pl.col("description_new").is_not_null()).mean().alias("desc_null_only_frac"),
    (pl.col("description").is_not_null() & pl.col("description_new").is_null()).mean().alias("desc_new_null_only_frac"),
    mask_both.mean().alias("both_present_frac"),
])
print("=== Null report (fraction) ===")
print(null_report)

# ===========================================
# 4) Tính contain trên tập both_present
# ===========================================
both_df = item_df.filter(mask_both)

# Thêm 3 cột: recall(A|B), precision(B|A), F1
res = both_df.with_columns([
    pl.struct(["description", "description_new"]).map_elements(
        lambda row: contain_pair(row["description"], row["description_new"], level=LEVEL, n=N)[0]
    ).alias("contain_desc_in_descnew"),  # recall: A|B

    pl.struct(["description", "description_new"]).map_elements(
        lambda row: contain_pair(row["description"], row["description_new"], level=LEVEL, n=N)[1]
    ).alias("contain_descnew_in_desc"),  # precision: B|A

    pl.struct(["description", "description_new"]).map_elements(
        lambda row: contain_pair(row["description"], row["description_new"], level=LEVEL, n=N)[2]
    ).alias("contain_f1"),
])

# Tóm tắt nhanh
summary = res.select([
    pl.len().alias("n_both_present"),
    pl.col("contain_desc_in_descnew").mean().alias("mean_contain(A|B)"),
    pl.col("contain_descnew_in_desc").mean().alias("mean_contain(B|A)"),
    pl.col("contain_f1").mean().alias("mean_contain_F1"),
    pl.col("contain_desc_in_descnew").quantile(0.5).alias("median_contain(A|B)"),
    pl.col("contain_desc_in_descnew").quantile(0.9).alias("p90_contain(A|B)"),
])
print("=== Containment summary (LEVEL={}, N={}) ===".format(LEVEL, N))
print(summary)

# (Tuỳ chọn) xem vài dòng có F1 cao để sanity-check
print(res.select(["description", "description_new", "contain_desc_in_descnew", "contain_descnew_in_desc", "contain_f1"])
        .sort("contain_f1", descending=True)
        .head(10))

=== Null report (fraction) ===
shape: (1, 4)
┌────────────────┬─────────────────────┬─────────────────────────┬───────────────────┐
│ both_null_frac ┆ desc_null_only_frac ┆ desc_new_null_only_frac ┆ both_present_frac │
│ ---            ┆ ---                 ┆ ---                     ┆ ---               │
│ f64            ┆ f64                 ┆ f64                     ┆ f64               │
╞════════════════╪═════════════════════╪═════════════════════════╪═══════════════════╡
│ 0.0            ┆ 0.0                 ┆ 0.183485                ┆ 0.816515          │
└────────────────┴─────────────────────┴─────────────────────────┴───────────────────┘
=== Containment summary (LEVEL=word, N=2) ===
shape: (1, 6)
┌────────────────┬───────────────────┬───────────────────┬─────────────────┬─────────────────────┬──────────────────┐
│ n_both_present ┆ mean_contain(A|B) ┆ mean_contain(B|A) ┆ mean_contain_F1 ┆ median_contain(A|B) ┆ p90_contain(A|B) │
│ ---            ┆ ---               ┆ ---               ┆ ---             ┆ ---                 ┆ ---              │
│ u32            ┆ f64               ┆ f64               ┆ f64             ┆ f64                 ┆ f64              │
╞════════════════╪═══════════════════╪═══════════════════╪═════════════════╪═════════════════════╪══════════════════╡
│ 22317          ┆ 0.644364          ┆ 0.559282          ┆ 0.581978        ┆ 0.795139            ┆ 1.0              │
└────────────────┴───────────────────┴───────────────────┴─────────────────┴─────────────────────┴──────────────────┘
shape: (10, 5)
┌────────────────┬─────────────────┬─────────────────────────┬─────────────────────────┬────────────┐
│ description    ┆ description_new ┆ contain_desc_in_descnew ┆ contain_descnew_in_desc ┆ contain_f1 │
│ ---            ┆ ---             ┆ ---                     ┆ ---                     ┆ ---        │
│ str            ┆ str             ┆ f64                     ┆ f64                     ┆ f64        │
╞════════════════╪═════════════════╪═════════════════════════╪═════════════════════════╪════════════╡
│ Không xác định ┆ Không xác định  ┆ 1.0                     ┆ 1.0                     ┆ 1.0        │
│ Không xác định ┆ Không xác định  ┆ 1.0                     ┆ 1.0                     ┆ 1.0        │
│ Không xác định ┆ Không xác định  ┆ 1.0                     ┆ 1.0                     ┆ 1.0        │
│ Không xác định ┆ Không xác định  ┆ 1.0                     ┆ 1.0                     ┆ 1.0        │
│ Không xác định ┆ Không xác định  ┆ 1.0                     ┆ 1.0                     ┆ 1.0        │
│ Không xác định ┆ Không xác định  ┆ 1.0                     ┆ 1.0                     ┆ 1.0        │
│ Không xác định ┆ Không xác định  ┆ 1.0                     ┆ 1.0                     ┆ 1.0        │
│ Không xác định ┆ Không xác định  ┆ 1.0                     ┆ 1.0                     ┆ 1.0        │
│ Không xác định ┆ Không xác định  ┆ 1.0                     ┆ 1.0                     ┆ 1.0        │
│ Không xác định ┆ Không xác định  ┆ 1.0                     ┆ 1.0                     ┆ 1.0        │
└────────────────┴─────────────────┴─────────────────────────┴─────────────────────────┴────────────┘

Ở trên chưa bỏ Không xác định -> sai

In [13]:
import polars as pl
import re

# ===== 1) Cấu hình =====
LEVEL = "word"   # "word" hoặc "char"
N = 2            # n-gram: 1/2/3... ; ví dụ word-bigram = 2

# Các giá trị được coi là "thiếu"
PLACEHOLDERS = [
    "", "-", "--",
    "không xác định", "khong xac dinh", "không xac dinh",
    "không rõ", "chưa rõ", "không có thông tin",
    "n/a", "na", "none", "null", "unk", "unknown"
]

# ===== 2) Hàm tiện ích =====
def tokenize(s: str):
    return re.findall(r"\w+", s.lower())

def ngrams(tokens, n=2):
    if len(tokens) < n: 
        return []
    return [" ".join(tokens[i:i+n]) for i in range(len(tokens)-n+1)]

def build_set(s: str, level="word", n=2):
    if not s:
        return set()
    if level == "char":
        s_norm = re.sub(r"\s+", " ", s.lower()).strip()
        if len(s_norm) < n:
            return set()
        return set(s_norm[i:i+n] for i in range(len(s_norm)-n+1))
    else:
        toks = tokenize(s)
        return set(toks) if n == 1 else set(ngrams(toks, n))

def contain_ratio_sets(A_set: set, B_set: set) -> float:
    return 0.0 if not A_set else len(A_set & B_set) / len(A_set)

def contain_pair(a: str, b: str, level="word", n=2):
    A = build_set(a, level=level, n=n)
    B = build_set(b, level=level, n=n)
    r = contain_ratio_sets(A, B)  # Contain(A|B)
    p = contain_ratio_sets(B, A)  # Contain(B|A)
    f1 = 0.0 if (p + r) == 0 else 2 * p * r / (p + r)
    return (r, p, f1, len(A), len(B))

# Chuẩn hoá text để so đối chiếu placeholder
def norm_expr(colname: str):
    return (
        pl.col(colname).cast(pl.Utf8)
        .str.to_lowercase()
        .str.replace_all(r"\s+", " ")
        .str.strip_chars(" .,-:;—–_/\\|\"'`")  # bỏ dấu câu ở đầu/cuối
        .str.strip_chars()                     # bỏ khoảng trắng thừa
    )

def is_missing(colname: str):
    n = norm_expr(colname)
    return pl.col(colname).is_null() | n.is_in(PLACEHOLDERS)

# ===== 3) Mask both_present với định nghĩa "thiếu" mới =====
miss_desc     = is_missing("description")
miss_desc_new = is_missing("description_new")
both_present  = (~miss_desc) & (~miss_desc_new)

# Báo cáo thiếu dữ liệu (fraction)
null_report = item_df.select([
    (miss_desc & miss_desc_new).mean().alias("both_null_frac"),
    (miss_desc & (~miss_desc_new)).mean().alias("desc_null_only_frac"),
    ((~miss_desc) & miss_desc_new).mean().alias("desc_new_null_only_frac"),
    both_present.mean().alias("both_present_frac"),
])
print("=== Null report (fraction) — placeholders treated as null ===")
print(null_report)

# ===== 4) Tính containment chỉ trên both_present =====
both_df = item_df.filter(both_present)

res = both_df.with_columns([
    pl.struct(["description", "description_new"]).map_elements(
        lambda row: contain_pair(row["description"], row["description_new"], level=LEVEL, n=N)[0]
    ).alias("contain_desc_in_descnew"),   # recall: A|B

    pl.struct(["description", "description_new"]).map_elements(
        lambda row: contain_pair(row["description"], row["description_new"], level=LEVEL, n=N)[1]
    ).alias("contain_descnew_in_desc"),   # precision: B|A

    pl.struct(["description", "description_new"]).map_elements(
        lambda row: contain_pair(row["description"], row["description_new"], level=LEVEL, n=N)[2]
    ).alias("contain_f1"),
])

summary = res.select([
    pl.len().alias("n_both_present"),
    pl.col("contain_desc_in_descnew").mean().alias("mean_contain(A|B)"),
    pl.col("contain_descnew_in_desc").mean().alias("mean_contain(B|A)"),
    pl.col("contain_f1").mean().alias("mean_contain_F1"),
    pl.col("contain_desc_in_descnew").quantile(0.5).alias("median_contain(A|B)"),
    pl.col("contain_desc_in_descnew").quantile(0.9).alias("p90_contain(A|B)"),
])
print(f"=== Containment summary (LEVEL={LEVEL}, N={N}) — after placeholder filtering ===")
print(summary)

# (Tuỳ chọn) kiểm tra vài dòng F1 cao
print(res.select(["description", "description_new", "contain_desc_in_descnew", "contain_descnew_in_desc", "contain_f1"])
        .sort("contain_f1", descending=True)
        .head(10))

=== Null report (fraction) — placeholders treated as null ===
shape: (1, 4)
┌────────────────┬─────────────────────┬─────────────────────────┬───────────────────┐
│ both_null_frac ┆ desc_null_only_frac ┆ desc_new_null_only_frac ┆ both_present_frac │
│ ---            ┆ ---                 ┆ ---                     ┆ ---               │
│ f64            ┆ f64                 ┆ f64                     ┆ f64               │
╞════════════════╪═════════════════════╪═════════════════════════╪═══════════════════╡
│ 0.564723       ┆ 0.116859            ┆ 0.087626                ┆ 0.230792          │
└────────────────┴─────────────────────┴─────────────────────────┴───────────────────┘
=== Containment summary (LEVEL=word, N=2) — after placeholder filtering ===
shape: (1, 6)
┌────────────────┬───────────────────┬───────────────────┬─────────────────┬─────────────────────┬──────────────────┐
│ n_both_present ┆ mean_contain(A|B) ┆ mean_contain(B|A) ┆ mean_contain_F1 ┆ median_contain(A|B) ┆ p90_contain(A|B) │
│ ---            ┆ ---               ┆ ---               ┆ ---             ┆ ---                 ┆ ---              │
│ u32            ┆ f64               ┆ f64               ┆ f64             ┆ f64                 ┆ f64              │
╞════════════════╪═══════════════════╪═══════════════════╪═════════════════╪═════════════════════╪══════════════════╡
│ 6308           ┆ 0.623212          ┆ 0.324248          ┆ 0.40546         ┆ 0.62                ┆ 0.807292         │
└────────────────┴───────────────────┴───────────────────┴─────────────────┴─────────────────────┴──────────────────┘
shape: (10, 5)
┌──────────────────────────────────────────────────────────────────┬──────────────────────────────────────────────────────────────────┬─────────────────────────┬─────────────────────────┬────────────┐
│ description                                                      ┆ description_new                                                  ┆ contain_desc_in_descnew ┆ contain_descnew_in_desc ┆ contain_f1 │
│ ---                                                              ┆ ---                                                              ┆ ---                     ┆ ---                     ┆ ---        │
│ str                                                              ┆ str                                                              ┆ f64                     ┆ f64                     ┆ f64        │
╞══════════════════════════════════════════════════════════════════╪══════════════════════════════════════════════════════════════════╪═════════════════════════╪═════════════════════════╪════════════╡
│ Chất liệu nhựa an toàn - Xe đẩy quầy thức ăn 33pcs TOYCITY được  ┆ Chi tiết sản phẩm                     Tên sản phẩm: Xe đẩy quầy  ┆ 0.966361                ┆ 0.940476                ┆ 0.953243   │
│ làm từ chất liệu nhựa cao cấp, rất nhẹ, có độ bền cao .Với chất  ┆ thức ăn 33pcs TOYCITY         Thương hiệu: Toycity         Xuất  ┆                         ┆                         ┆            │
│ liệu nhựa cao cấp, tuyệt đối an toàn cho sức khỏe của bé và thân ┆ xứ: Trung Quốc         Chi tiết sản phẩm: Nhựa HIPS              ┆                         ┆                         ┆            │
│ thiện với môi trường. - Bề mặt các chi tiết cua bộ đồ chơi nhẵn  ┆ Trọng lượng: 0.83 kg         Kích thước: Dài x Rộng x Cao:       ┆                         ┆                         ┆            │
│ mịn, không có các vi ba sắc nhọn không làm trầy xước làn da nhạy ┆ 24x20x10(cm)                        Xe đẩy quầy thức ăn 33pcs    ┆                         ┆                         ┆            │
│ cảm của bé khi tiếp xúc, giúp mẹ an tâm mỗi khi bé chơi. Phát    ┆ TOYCITY là xe đẩy quầy thức ăn dành cho bé từ 3 tuổi của thương  ┆                         ┆                         ┆            │
│ huy trí tưởng tượng - Bộ đồ chơi quầy thức ăn gồm những chai gia ┆ hiệu Toycity xuất xứ Trung Quốc. Được làm từ chất liệu nhựa cao  ┆                         ┆                         ┆            │
│ vị, menu, đồ ăn...  có màu sắc nổi bật, bắt mắt tạo cho bé cảm   ┆ cấp, sản phẩm tuyệt đối an toàn cho sức khỏe của bé.             ┆                         ┆                         ┆            │
│ giác thích thú và hứng khởi hơn khi chơi, đồng thời kích thích   ┆ Chất liệu nhựa an toàn            Xe đẩy quầy thức ăn 33pcs      ┆                         ┆                         ┆            │
│ thị giác bé phát triển. Mẹ có thể hướng dẫn cho bé cách nhận     ┆ TOYCITY được làm từ chất liệu nhựa cao cấp, rất nhẹ, có độ bền   ┆                         ┆                         ┆            │
│ biết màu sắc từ các dụng và hỏi lại giúp tăng khả năng ghi nhớ   ┆ cao. Với chất liệu nhựa cao cấp, sản phẩm tuyệt đối an toàn cho  ┆                         ┆                         ┆            │
│ của bé. Bộ đồ chơi mang tính chất hướng nghiệp - Đây là một trò  ┆ sức khỏe của bé và thân thiện với môi trường. Bề mặt các chi     ┆                         ┆                         ┆            │
│ chơi thật sự bổ ích giúp bé hiểu thêm và yêu thích công việc bán ┆ tiết của bộ đồ chơi nhẵn mịn, không có các vi ba sắc nhọn không  ┆                         ┆                         ┆            │
│ đồ ăn cũng là những bước khởi đầu trong việc định hướng nghề     ┆ làm trầy xước làn da nhạy cảm của bé khi tiếp xúc, giúp mẹ an    ┆                         ┆                         ┆            │
│ nghiệp tương lai cho bé. Bé có thể hình dung được công việc nấu  ┆ tâm mỗi khi bé chơi.            Phát huy trí tưởng tượng         ┆                         ┆                         ┆            │
│ ăn và có thể ý thức để phụ giúp bố mẹ trong việc lấy dụng cụ nấu ┆ Bộ đồ chơi quầy thức ăn gồm những chai gia vị, menu, đồ ăn... có ┆                         ┆                         ┆            │
│ bếp hay gia vị cho bố mẹ. - Không chỉ vậy bộ đồ chơi quầy thức   ┆ màu sắc nổi bật, bắt mắt tạo cho bé cảm giác thích thú và hứng   ┆                         ┆                         ┆            │
│ ăn được  đựng trong hộp xe đẩy  gọn nhẹ và xinh xắn, giúp bé có  ┆ khởi hơn khi chơi, đồng thời kích thích thị giác bé phát triển.  ┆                         ┆                         ┆            │
│ ý thức xếp gọn đồ sau khi chơi, rèn tính ngăn nắp cho bé ngay từ ┆ Mẹ có thể hướng dẫn cho bé cách nhận biết màu sắc từ các dụng cụ ┆                         ┆                         ┆            │
│ khi còn nhỏ. Và bé dễ dàng mang theo khi ra ngoài đi chơi. - Bộ  ┆ và hỏi lại giúp tăng khả năng ghi nhớ của bé.            Bộ đồ   ┆                         ┆                         ┆            │
│ sản phẩm có nhãn dán kèm theo để bé trang trí cho hộp đồ chơi    ┆ chơi mang tính chất hướng nghiệp           Đây là một trò chơi   ┆                         ┆                         ┆            │
│ của mình thêm phần sinh động hơn. THÔNG TIN SẢN PHẨM - Tên sản   ┆ thật sự bổ ích giúp bé hiểu thêm và yêu thích công việc bán đồ   ┆                         ┆                         ┆            │
│ phẩm : Xe đẩy quầy thức ăn 33pcs TOYCITY - Thương hiệu : Toycity ┆ ăn, đồng thời cũng là những bước khởi đầu trong việc định hướng  ┆                         ┆                         ┆            │
│ - Xuất Xứ:  Trung Quốc - Chi tiết sản phẩm : Nhựa HIPS - Trọng   ┆ nghề nghiệp tương lai cho bé. Bé có thể hình dung được công việc ┆                         ┆                         ┆            │
│ lượng :0.83 kg - Kích thước: Dài x Rộng X Cao: 24x20x10(cm)      ┆ nấu ăn và ý thức để phụ giúp bố mẹ trong việc lấy dụng cụ nấu    ┆                         ┆                         ┆            │
│ HƯỚNG DẪN BẢO QUẢN - Vệ sinh sản phẩm trước và sau khi sử dụng.  ┆ bếp hay gia vị cho bố mẹ. Không chỉ vậy, bộ đồ chơi quầy thức ăn ┆                         ┆                         ┆            │
│ - Cảnh báo : không sử dụng sản phẩm cho bé dưới 3 tuổi.          ┆ được đựng trong hộp xe đẩy gọn nhẹ và xinh xắn, giúp bé có ý     ┆                         ┆                         ┆            │
│                                                                  ┆ thức xếp gọn đồ sau khi chơi, rèn tính ngăn nắp cho bé ngay từ   ┆                         ┆                         ┆            │
│                                                                  ┆ khi còn nhỏ, và bé dễ dàng mang theo khi ra ngoài đi chơi. Bộ    ┆                         ┆                         ┆            │
│                                                                  ┆ sản phẩm có nhãn dán kèm theo để bé trang trí cho hộp đồ chơi    ┆                         ┆                         ┆            │
│                                                                  ┆ của mình thêm phần sinh động hơn.               Hướng dẫn bảo    ┆                         ┆                         ┆            │
│                                                                  ┆ quản               Vệ sinh s…                                    ┆                         ┆                         ┆            │
│ Chất liệu nhựa an toàn Xẻng nhựa RFD276556 được làm từ chất liệu ┆ Chi tiết sản phẩm                     Tên sản phẩm: Xẻng nhựa    ┆ 0.976331                ┆ 0.926966                ┆ 0.951009   │
│ nhựa an toàn, không độc hại, không gây ảnh hưởng đến sức khỏe    ┆ RFD276556         Thương hiệu: YUANHONG TOYS         Xuất xứ:    ┆                         ┆                         ┆            │
│ của bé. Chất liệu nhựa cứng cáp được sơn phủ sáng bóng đem đến   ┆ Trung Quốc         Trọng lượng: 0.1 kg         Nguyên liệu: Nhựa ┆                         ┆                         ┆            │
│ độ bền đẹp theo thời gian sử dụng. - Bề mặt các chi tiết trơn    ┆ PP         Dành cho: Bé 3 tuổi trở lên         Kích thước chiều  ┆                         ┆                         ┆            │
│ tru láng mịn không có các cạnh sắc nhọn, do đó không làm trầy    ┆ dài: 50cm                        Xẻng nhựa RFD276556 là đồ chơi  ┆                         ┆                         ┆            │
│ xước làn da nhạy cảm của bé khi tiếp xúc, bố mẹ có thể hoàn toàn ┆ dành cho bé 3 tuổi trở lên của thương hiệu YUANHONG TOYS xuất xứ ┆                         ┆                         ┆            │
│ an tâm khi bé chơi. Màu sắc nổi bật, thiết kế bắt mắt - Chi tiết ┆ từ Trung Quốc. Sản phẩm được làm từ chất liệu nhựa an toàn,      ┆                         ┆                         ┆            │
│ được thiết kế với kiểu dáng vô cùng dễ thương chắc chắn sẽ thu   ┆ không độc hại, đảm bảo sức khỏe cho bé.                          ┆                         ┆                         ┆            │
│ hút sự chú ý của các bé ngay từ cái nhìn đầu tiên. Không chỉ vậy ┆ Chất liệu nhựa an toàn            Xẻng nhựa RFD276556 được làm   ┆                         ┆                         ┆            │
│ đồ chơi có màu sắc sinh động, bắt mắt sẽ làm bé thích thú và     ┆ từ chất liệu nhựa an toàn, không độc hại, không gây ảnh hưởng    ┆                         ┆                         ┆            │
│ hứng khởi khi chơi. - Kích thước vừa tay bé, giúp bé dễ dàng cầm ┆ đến sức khỏe của bé. Chất liệu nhựa cứng cáp được sơn phủ sáng   ┆                         ┆                         ┆            │
│ nắm để thực hiện các thao tác khi chơi. Giúp bé phát triển các   ┆ bóng đem đến độ bền đẹp theo thời gian sử dụng. Bề mặt các chi   ┆                         ┆                         ┆            │
│ kỹ năng - Thông qua các thao tác: đào cát, xúc cát các kỹ năng   ┆ tiết trơn tru láng mịn không có các cạnh sắc nhọn, do đó không   ┆                         ┆                         ┆            │
│ của bé sẽ dần được phát triển và hoàn thiện hơn. Bên cạnh đó,    ┆ làm trầy xước làn da nhạy cảm của bé khi tiếp xúc, bố mẹ có thể  ┆                         ┆                         ┆            │
│ việc xúc cát cũng như vui chơi bên ngoài giúp bé tăng khả năng   ┆ hoàn toàn an tâm khi bé chơi.               Màu sắc nổi bật,     ┆                         ┆                         ┆            │
│ vận động để cơ thể khỏe mạnh và nhanh nhẹn hơn. - Mỗi dụng cụ    ┆ thiết kế bắt mắt            Chi tiết được thiết kế với kiểu dáng ┆                         ┆                         ┆            │
│ của bộ đồ chơi có màu sắc và công dụng khác nhau, mẹ có thể      ┆ vô cùng dễ thương chắc chắn sẽ thu hút sự chú ý của các bé ngay  ┆                         ┆                         ┆            │
│ hướng dẫn bé nhận biết và phân biệt màu sắc, cũng như học cách   ┆ từ cái nhìn đầu tiên. Không chỉ vậy đồ chơi có màu sắc sinh      ┆                         ┆                         ┆            │
│ sử dụng dựa trên công dụng của từng dụng cụ và sau đó hỏi lại,   ┆ động, bắt mắt sẽ làm bé thích thú và hứng khởi khi chơi. Kích    ┆                         ┆                         ┆            │
│ từ đó giúp tăng khả năng học hỏi và ghi nhớ của bé. - Với đồ     ┆ thước vừa tay bé, giúp bé dễ dàng cầm nắm để thực hiện các thao  ┆                         ┆                         ┆            │
│ chơi này bé có thể vui chơi cùng bố mẹ hay bạn bè từ đó tăng khả ┆ tác khi chơi.               Giúp bé phát triển các kỹ năng       ┆                         ┆                         ┆            │
│ năng giao tiếp và gắn kết tình cảm. THÔNG TIN SẢN PHẨM - Thương  ┆ Thông qua các thao tác: đào cát, xúc cát, các kỹ năng của bé sẽ  ┆                         ┆                         ┆            │
│ hiệu: YUANHONG TOYS - Xuất xứ: Trung Quốc - Trọng lượng : 0.1 kg ┆ dần được phát triển và hoàn thiện hơn. Bên cạnh đó, việc xúc cát ┆                         ┆                         ┆            │
│ - Nguyên liệu: Nhựa PP - Dành cho bé 3 tuổi trở lên - Kích thước ┆ cũng như vui chơi bên ngoài giúp bé tăng khả năng vận động để cơ ┆                         ┆                         ┆            │
│ chiều dài : 50cm HƯỚNG DẪN BẢO QUẢN - Vệ sinh trước và sau sử    ┆ thể khỏe mạnh và nhanh nhẹn hơn. Mỗi dụng cụ của bộ đồ chơi có   ┆                         ┆                         ┆            │
│ dụng, tránh va đập mạnh. - Tránh xa nguồn nhiệt. Cảnh báo :      ┆ màu sắc và công dụng khác nhau, mẹ có thể hướng dẫn bé nhận biết ┆                         ┆                         ┆            │
│ + Sản phẩm có chi tiết nhỏ, không phù hợp với trẻ em dưới 3      ┆ và phân biệt màu sắc, cũng như học cách sử dụng dựa trên công    ┆                         ┆                         ┆            │
│ tuổi. + Sử dụng dưới sự giám sát của người lớn.                  ┆ dụng của từng dụng cụ và sau đó hỏi lại, từ đó giúp tăng khả     ┆                         ┆                         ┆            │
│                                                                  ┆ năng học hỏi và ghi nhớ của bé. Với đồ chơi này bé có thể vui    ┆                         ┆                         ┆            │
│                                                                  ┆ chơi cùng bố mẹ hay bạn bè từ đó tăng khả năng giao tiếp và gắn  ┆                         ┆                         ┆            │
│                                                                  ┆ kết tình cảm.               Hướng dẫn bảo quản               Vệ  ┆                         ┆                         ┆            │
│                                                                  ┆ sinh trước và sau sử dụng, tránh va đập mạ…                      ┆                         ┆                         ┆            │
│ Chất liệu bền đẹp, an toàn - Áo phao bơi Z802007-T được làm từ   ┆ Chi tiết sản phẩm                     Tên sản phẩm: Áo phao bơi  ┆ 0.982323                ┆ 0.900463                ┆ 0.939614   │
│ chất liệu cao cấp, đảm bảo đạt tiêu chuẩn an toàn với độ đàn hồi ┆ Z802007-T         Thương hiệu: Mesuca         Xuất xứ: Trung     ┆                         ┆                         ┆            │
│ rất tốt, ít bị biến dạng cùng bề mặt mềm mại, láng mịn, bảo vệ   ┆ Quốc         Kích thước: 40x35x25(cm)         Dành cho bé khoảng ┆                         ┆                         ┆            │
│ làn da bé và không gây kích ứng cho da, giúp bé thoải mái khi    ┆ từ: 12-16kg         Phù hợp cho bé từ: 3 tuổi trở lên            ┆                         ┆                         ┆            │
│ vui chơi. Thiết kế thông minh - Áo phao bơi Z802007-T sử dụng    ┆ **Áo phao bơi Z802007-T** là áo phao bơi dành cho bé từ 3 tuổi   ┆                         ┆                         ┆            │
│ van 1 chiều thông minh nên hơi bên trong rất khó thoát ra ngoài. ┆ trở lên của thương hiệu Mesuca đến từ Trung Quốc. Sản phẩm nổi   ┆                         ┆                         ┆            │
│ Áo được chia làm 3 phần với 3 van độc lập, phân cách bằng các    ┆ bật với chất liệu bền đẹp, an toàn.                              ┆                         ┆                         ┆            │
│ đường hàn, giúp bố mẹ dễ dàng và nhanh chóng bơm từng phần, có   ┆ **Chất liệu bền đẹp, an toàn**           Áo phao bơi Z802007-T   ┆                         ┆                         ┆            │
│ thể sử dụng bơm hơi bằng tay tiện lợi. Hai lần khóa cài và van   ┆ được làm từ chất liệu cao cấp, đảm bảo đạt tiêu chuẩn an toàn    ┆                         ┆                         ┆            │
│ khí 1 chiều chắc chắn - Thiết kế cổ và lỗ khoác tay áo rộng rãi  ┆ với độ đàn hồi rất tốt, ít bị biến dạng cùng bề mặt mềm mại,     ┆                         ┆                         ┆            │
│ tạo sự thoải mái khi vận động. - Phần móc khóa có dây đai có thể ┆ láng mịn, bảo vệ làn da bé và không gây kích ứng cho da, giúp bé ┆                         ┆                         ┆            │
│ điều chỉnh độ dài ngắn để phù hợp với kích cỡ người trẻ. Hai móc ┆ thoải mái khi vui chơi.             **Thiết kế thông minh**      ┆                         ┆                         ┆            │
│ khóa cài bản to chắc chắn đảm bảo an toàn tuyệt đối cho trẻ khi  ┆ Áo phao bơi Z802007-T sử dụng van 1 chiều thông minh nên hơi bên ┆                         ┆                         ┆            │
│ sử dụng giúp phao không tuột khỏi người bé khi đang bơi. Màu sắc ┆ trong rất khó thoát ra ngoài. Áo được chia làm 3 phần với 3 van  ┆                         ┆                         ┆            │
│ nổi bật - Kích thước nhỏ gọn, kiểu dáng áo phao thời trang được  ┆ độc lập, phân cách bằng các đường hàn, giúp bố mẹ dễ dàng và     ┆                         ┆                         ┆            │
│ thiết kế xinh xắn với màu vàng tươi sáng, rực rỡ cùng họa tiết   ┆ nhanh chóng bơm từng phần, có thể sử dụng bơm hơi bằng tay tiện  ┆                         ┆                         ┆            │
│ ngộ nghĩnh, đầy ấn tượng cho bé thêm phần nổi bật khi đi tham    ┆ lợi.            **Hai lần khóa cài và van khí 1 chiều chắc       ┆                         ┆                         ┆            │
│ quan trên thuyền, khi tắm biển hay ở bể bơi, công viên nước... - ┆ chắn**           Thiết kế cổ và lỗ khoác tay áo rộng rãi tạo sự  ┆                         ┆                         ┆            │
│ Sản phẩm sẽ là món quà vô cùng ý nghĩa và lý thú cho những đợt   ┆ thoải mái khi vận động. Phần móc khóa có dây đai có thể điều     ┆                         ┆                         ┆            │
│ du lịch sắp tới của bé cùng cả nhà. THÔNG TIN SẢN PHẨM - Tên sản ┆ chỉnh độ dài ngắn để phù hợp với kích cỡ người trẻ. Hai móc khóa ┆                         ┆                         ┆            │
│ phẩm : Áo phao bơi Z802007-T - Thương hiệu: Mesuca - Xuất xứ:    ┆ cài bản to chắc chắn đảm bảo an toàn tuyệt đối cho trẻ khi sử    ┆                         ┆                         ┆            │
│ Trung Quốc - Chất liệu: Nhựa PVC - Kích thước :40x35x25(cm) -    ┆ dụng giúp phao không tuột khỏi người bé khi đang bơi.            ┆                         ┆                         ┆            │

**mean Contain(A|B) = 0.623**
- Trung bình 62.3% bigram trong description cũng có trong description_new.
- Khi có dữ liệu thật, description_new bao phủ phần lớn nội dung của description.

**mean Contain(B|A) = 0.324**
- Chỉ 32.4% bigram trong description_new xuất hiện trong description.
-  description_new giàu/chi tiết hơn, có nhiều cụm mới (vd. “Tên sản phẩm/Thương hiệu/Xuất xứ/Kích thước…”) mà description không có.
-  Đây là lý do precision thấp.

**mean F1 = 0.405**
- Trung bình độ khớp hai chiều chỉ ở mức vừa (hàm hòa hợp của hai contain). Bị kéo xuống bởi B|A thấp.

**median Contain(A|B) = 0.620; p90 = 0.807**
- 50% cặp có ≥62% nội dung description được bao bởi description_new; top 10% đạt ≥80.7%.
- Phân bố khá lệch: nhiều cặp khớp tốt, nhưng cũng có không ít cặp lệch mạnh (kéo mean xuống).

## Xử lý

### Kiểm tra ngoài "Không xác định" và null thì còn giá trị nào có nghĩa là missing không

In [ ]:
df = item_df

def audit_missing_col(df: pl.DataFrame, col: str) -> pl.DataFrame:
    c = pl.col(col)
    norm = (
        c.cast(pl.Utf8)
         .str.replace_all('"', '')        # bỏ ngoặc kép
         .str.replace_all('“|”', '')      # bỏ ngoặc kép unicode nếu có
         .str.to_lowercase()
         .str.strip_chars()
    )
    # các biến thể thường gặp cần rà soát
    candidates = ["không xác định", "khong xac dinh", "null", "none", "na", "n/a", ""]
    return (
        df.select([
            pl.count().alias("total"),
            c.is_null().sum().alias("null_rows"),
            (norm == "không xác định").sum().alias("khong_xac_dinh"),
            (norm == "khong xac dinh").sum().alias("khong_xac_dinh_khong_dau"),
            ((norm == "") & c.is_not_null()).sum().alias("empty_after_trim"),
            (norm.is_in(["null","none","na","n/a"]) & c.is_not_null()).sum().alias("other_placeholders"),
            # chuỗi chỉ toàn dấu ngăn cách (nếu dataset có kiểu này)
            (
              c.is_not_null() &
              (c.str.replace_all(r"[ \-\.\_/|:;]+", "").str.len_chars() == 0)
            ).sum().alias("only_separators")
        ])
        .with_columns(col_name = pl.lit(col))
        .select(["col_name","total","null_rows","khong_xac_dinh","khong_xac_dinh_khong_dau",
                 "empty_after_trim","other_placeholders","only_separators"])
    )

# Chạy audit cho 2 cột
result = pl.concat([
    audit_missing_col(df, "description_new"),
    audit_missing_col(df, "description"),
])
print(result)

# (tùy chọn) Liệt kê nhanh top 10 giá trị "nghi ngờ placeholder"
for col in ["description_new","description"]:
    c = pl.col(col).cast(pl.Utf8)
    norm = (c.str.replace_all('"','').str.replace_all('“|”','')
              .str.to_lowercase().str.strip_chars())
    suspicious = df.select([norm.alias("norm")]) \
                   .group_by("norm").len() \
                   .filter(pl.col("norm").is_in(["không xác định","khong xac dinh","null","none","na","n/a",""])) \
                   .sort("len", descending=True)
    print(f"\n{col} — placeholders (normalized):")
    print(suspicious)

C:\Users\tncn2\AppData\Local\Temp\ipykernel_6912\533517684.py:16: DeprecationWarning: `pl.count()` is deprecated. Please use `pl.len()` instead.
(Deprecated in version 0.20.5)
  pl.count().alias("total"),

shape: (2, 8)
┌─────────────┬───────┬───────────┬────────────┬────────────┬────────────┬────────────┬────────────┐
│ col_name    ┆ total ┆ null_rows ┆ khong_xac_ ┆ khong_xac_ ┆ empty_afte ┆ other_plac ┆ only_separ │
│ ---         ┆ ---   ┆ ---       ┆ dinh       ┆ dinh_khong ┆ r_trim     ┆ eholders   ┆ ators      │
│ str         ┆ u32   ┆ u32       ┆ ---        ┆ _dau       ┆ ---        ┆ ---        ┆ ---        │
│             ┆       ┆           ┆ u32        ┆ ---        ┆ u32        ┆ u32        ┆ u32        │
│             ┆       ┆           ┆            ┆ u32        ┆            ┆            ┆            │
╞═════════════╪═══════╪═══════════╪════════════╪════════════╪════════════╪════════════╪════════════╡
│ description ┆ 27332 ┆ 5015      ┆ 12815      ┆ 0          ┆ 0          ┆ 0          ┆ 0          │
│ _new        ┆       ┆           ┆            ┆            ┆            ┆            ┆            │
│ description ┆ 27332 ┆ 0         ┆ 18629      ┆ 0          ┆ 0          ┆ 0          ┆ 0          │
└─────────────┴───────┴───────────┴────────────┴────────────┴────────────┴────────────┴────────────┘

description_new — placeholders (normalized):
shape: (1, 2)
┌────────────────┬───────┐
│ norm           ┆ len   │
│ ---            ┆ ---   │
│ str            ┆ u32   │
╞════════════════╪═══════╡
│ không xác định ┆ 12815 │
└────────────────┴───────┘

description — placeholders (normalized):
shape: (1, 2)
┌────────────────┬───────┐
│ norm           ┆ len   │
│ ---            ┆ ---   │
│ str            ┆ u32   │
╞════════════════╪═══════╡
│ không xác định ┆ 18629 │
└────────────────┴───────┘

### Gộp 2 cột description và description_new

- Sau khi đã xác định các giá trị thiếu chỉ gồm null hoặc "Không xác định" thì chỉ cần kiểm tra missing(x) = is_null(x) OR lower(strip(x)) == "Không xác định" 
- Để nhận diện thiếu, tránh copy nhầm "Không xác định"

**Logic gộp**
1. Nếu des_new không missing => lấy des_new
2. Nếu des_new missing nhưng des không missing => lấy des 
3. Nếu cả hai missing => Để NULL
4. Thêm cột description_source = new / old_as_fill / missing để audit

In [15]:
df = item_df

# 1) Định nghĩa điều kiện thiếu (tối giản)
def is_missing(col: str) -> pl.Expr:
    c = pl.col(col)
    return c.is_null() | (
        c.cast(pl.Utf8).str.to_lowercase().str.strip_chars() == "không xác định"
    )

new_miss = is_missing("description_new")
old_miss = is_missing("description")

# 2) Gộp và đánh dấu nguồn
df = df.with_columns([
    pl.when(~new_miss).then(pl.col("description_new"))
      .when(~old_miss).then(pl.col("description"))
      .otherwise(None)
      .alias("description_merged"),

    pl.when(~new_miss).then(pl.lit("new"))
     .when(~old_miss).then(pl.lit("old_as_fill"))
     .otherwise(pl.lit("missing"))
     .alias("description_source")
])

# 3) Báo cáo: filled_from_old & still_missing (+ %)
report = (
    df.select(
        pl.count().alias("total"),
        (pl.col("description_source") == "old_as_fill").sum().alias("filled_from_old"),
        (pl.col("description_source") == "missing").sum().alias("still_missing"),
        (pl.col("description_source") == "new").sum().alias("from_new")
    )
    .with_columns(
        filled_from_old_pct = (pl.col("filled_from_old") / pl.col("total") * 100).round(2),
        still_missing_pct   = (pl.col("still_missing")   / pl.col("total") * 100).round(2),
    )
)

print(">>> Merge report")
print(report)

# 4) (Tuỳ chọn) xem nhanh vài dòng được lấp từ description cũ
print("\n>>> Sample rows (old_as_fill):")
print(
    df.filter(pl.col("description_source") == "old_as_fill")
      .select(["description_new", "description", "description_merged"])
      .head(5)
)

# Gán lại vào item_df nếu bạn muốn tiếp tục dùng ở các cell sau
item_df = df

>>> Merge report
shape: (1, 6)
┌───────┬─────────────────┬───────────────┬──────────┬─────────────────────┬───────────────────┐
│ total ┆ filled_from_old ┆ still_missing ┆ from_new ┆ filled_from_old_pct ┆ still_missing_pct │
│ ---   ┆ ---             ┆ ---           ┆ ---      ┆ ---                 ┆ ---               │
│ u32   ┆ u32             ┆ u32           ┆ u32      ┆ f64                 ┆ f64               │
╞═══════╪═════════════════╪═══════════════╪══════════╪═════════════════════╪═══════════════════╡
│ 27332 ┆ 2395            ┆ 15435         ┆ 9502     ┆ 8.76                ┆ 56.47             │
└───────┴─────────────────┴───────────────┴──────────┴─────────────────────┴───────────────────┘

>>> Sample rows (old_as_fill):
shape: (5, 3)
┌─────────────────┬─────────────────────────────────┬─────────────────────────────────┐
│ description_new ┆ description                     ┆ description_merged              │
│ ---             ┆ ---                             ┆ ---                             │
│ str             ┆ str                             ┆ str                             │
╞═════════════════╪═════════════════════════════════╪═════════════════════════════════╡
│ Không xác định  ┆ ﻿﻿Tã dán Merries size S 82 miế…   ┆ ﻿﻿Tã dán Merries size S 82 miế…   │
│ Không xác định  ┆ ﻿﻿﻿Bỉm tã quần Merries size M …    ┆ ﻿﻿﻿Bỉm tã quần Merries size M …    │
│ Không xác định  ┆ Áo thun bé trai tay ngắn CF B0… ┆ Áo thun bé trai tay ngắn CF B0… │
│ Không xác định  ┆ ﻿﻿﻿Dòng sản phẩm tã quần Huggi…    ┆ ﻿﻿﻿Dòng sản phẩm tã quần Huggi…    │
│ Không xác định  ┆ Chân váy kaki bé gái CF G04801… ┆ Chân váy kaki bé gái CF G04801… │
└─────────────────┴─────────────────────────────────┴─────────────────────────────────┘

C:\Users\tncn2\AppData\Local\Temp\ipykernel_4608\922089957.py:29: DeprecationWarning: `pl.count()` is deprecated. Please use `pl.len()` instead.
(Deprecated in version 0.20.5)
  pl.count().alias("total"),

In [16]:
item_df.head()

shape: (5, 37)
┌───────┬────────────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ p_id  ┆ item_id    ┆ price      ┆ category_l ┆ … ┆ descripti ┆ age_bucke ┆ descripti ┆ descripti │
│ ---   ┆ ---        ┆ ---        ┆ 1_id       ┆   ┆ on_new    ┆ t_primary ┆ on_merged ┆ on_source │
│ i32   ┆ str        ┆ decimal[38 ┆ ---        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│       ┆            ┆ ,4]        ┆ i32        ┆   ┆ str       ┆ str       ┆ str       ┆ str       │
╞═══════╪════════════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 17065 ┆ 0502020000 ┆ 99000.0000 ┆ 1          ┆ … ┆ Chi tiết  ┆ null      ┆ Chi tiết  ┆ new       │
│       ┆ 004        ┆            ┆            ┆   ┆ sản phẩm  ┆           ┆ sản phẩm  ┆           │
│       ┆            ┆            ┆            ┆   ┆ …         ┆           ┆ …         ┆           │
│ 72370 ┆ 0010290040 ┆ 69000.0000 ┆ 3292       ┆ … ┆ Không xác ┆ 2-4Y      ┆ null      ┆ missing   │
│       ┆ 150        ┆            ┆            ┆   ┆ định      ┆           ┆           ┆           │
│ 31154 ┆ 0008010000 ┆ 45000.0000 ┆ 351        ┆ … ┆ Chi tiết  ┆ null      ┆ Chi tiết  ┆ new       │
│       ┆ 015        ┆            ┆            ┆   ┆ sản phẩm  ┆           ┆ sản phẩm  ┆           │
│       ┆            ┆            ┆            ┆   ┆ …         ┆           ┆ …         ┆           │
│ 46123 ┆ 0020010000 ┆ 401000.000 ┆ 2222       ┆ … ┆ Không xác ┆ null      ┆ ﻿﻿Tã dán    ┆ old_as_fi │
│       ┆ 094        ┆ 0          ┆            ┆   ┆ định      ┆           ┆ Merries   ┆ ll        │
│       ┆            ┆            ┆            ┆   ┆           ┆           ┆ size S 82 ┆           │
│       ┆            ┆            ┆            ┆   ┆           ┆           ┆ miế…      ┆           │
│ 46127 ┆ 0020010000 ┆ 401000.000 ┆ 2222       ┆ … ┆ Không xác ┆ null      ┆ ﻿﻿﻿Bỉm tã    ┆ old_as_fi │
│       ┆ 098        ┆ 0          ┆            ┆   ┆ định      ┆           ┆ quần      ┆ ll        │
│       ┆            ┆            ┆            ┆   ┆           ┆           ┆ Merries   ┆           │
│       ┆            ┆            ┆            ┆   ┆           ┆           ┆ size M …  ┆           │
└───────┴────────────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

- description_source là nguồn gốc cho giá trị trong description_merged. Nó cho biết giá trị hợp nhất lấy từ đâu:
    - new: lấy từ description_new
    - old_as_fill: lấy từ description vì description_new thiếu
    -  missing: cả hai đều thiếu ⇒ description_merged = NULL
- description_source là metadata cho pipeline, không nhất thiết đưa vào mô hình chính (tránh rủi ro nhiễu/bias). Dùng nó để lọc/giám sát và đánh giá là chính.

# size và age_group

## Kiểm tra

In [9]:
size_uniques = df.select(pl.col("size").unique()).to_series().to_list()
age_uniques = df.select(pl.col("age_group").unique()).to_series().to_list()

print("=== SIZE UNIQUE VALUES ===")
for val in size_uniques:
    print(val)

print("\n=== AGE_GROUP UNIQUE VALUES ===")
for val in age_uniques:
    print(val)

=== SIZE UNIQUE VALUES ===
S
11
24
22
L (9-14kg) - 72 miếng
4-5T
0 tháng
28*36cm
3-6M
SS
XXL (>15kg) 54 miếng
18 tháng
Từ 2 tuổi
1-2 tuổi
19
3-4Y
L
24-36 tháng
14
3 tháng
1T
1Y
0-36 tháng
16
Không xác định
4-14 tháng
1
M(7-12kg) - 76 miếng
Sơ sinh
2-3T
12-18M
0-1Y
2
26
23
Từ 7 tháng
4-5Y
L(9-14kg) - 68 miếng
6T
0-3M
7-8Y
15
XXL ( >15kg) - 48+6 miếng
XL
9M
12 tháng
B85
18-24M
5T
25x28cm
24 tháng
13
XXL(15-25kg) - 26 miếng
12-24M
12
2Y
110
5-6Y
3T
9
9 tháng
4Y
24*28cm
7-8 tuổi
25
6-9M
XXL
4T
90*140cm
2T
60*100cm
6 tháng
9-12M
10
1-2Y
17
4-6 tháng
NB
B75
3
S (4-8kg) - 80 miếng
2-3Y
34
1-3 tháng
0-6M
20
0-3 tuổi
M
36
21
M(6-11kg) - 64 miếng

=== AGE_GROUP UNIQUE VALUES ===
Từ 10M
6M-10M
18M-24M
3M-18M
0-2M
6M-12Y
1Y-6Y
9M-36M
1Y-4Y
0-3M
3M-24M
Từ 10Y
Từ 19Y
12M-4Y
Trên 2Y
3Y-5Y
2Y-6Y
0-5M
Từ 13Y
9M-15M
1M-3M
6M-36M
12M-18M
Trên 1Y
3Y-4Y
18M-36M
Từ 4M
1Y-12Y
0-18M
["Từ 0M", "Từ 3M", "Từ 6M"]
0-12M
Từ 5Y
9M-6Y
["Từ 3M", "Từ 6M", "Từ 1Y"]
10Y-12Y
1Y-2Y
1Y-11Y
Từ 8M
1Y-3Y
Từ 5M
0-1M
9M-12M
6M-5Y
0-10M
Từ 12Y
2Y-10Y
Từ 9M
Từ 19M
5Y-6Y
Từ 3Y
9Y-10Y
9M-24M
["Từ 3M", "Từ 6M", "Từ 9M", "Từ 1Y"]
7Y-14Y
["Từ 3M", "Từ 6M"]
Từ 2M
8Y-14Y
Từ 7Y
Trên 3Y
0-12Y
Từ 3M
Từ 4Y
0-24M
1Y-10Y
6M-6Y
Từ 2Y
3Y-10Y
3M-6M
2Y-3Y
0-6Y
Từ 6Y
0-4Y
Từ 18M
0-5Y
1Y-9Y
0-6M
6M-15M
4M-4Y
Mẹ
7Y-10Y
2M-15M
9M-20M
Trên 6M
6M-24M
1M-12M
9M-4Y
["Từ 3M", "Từ 6M", "Từ 9M"]
4M-6M
6M-18M
["Từ 6M", "Từ 9M", "Từ 1Y"]
Từ 1Y
4Y-5Y
13M-24M
1M-15M
6M-12M
["Từ 0M", "Từ 3M"]
Từ 1M
18M-4Y
0-36M
1Y-16Y
Không xác định
3M-12M
Từ 7M
2M-6M
3Y-12Y
Từ 0M
Từ 6M
7Y-8Y
0-9M
3Y-6Y
6M-9M
11Y-12Y

- đo mức liên quan: Cramér’s V, NMI, Theil’s U hai chiều
- đo độ phủ/gộp: “mode-coverage” size→age_group và ngược lại

In [16]:
# 1) Chuẩn hoá NULL
NULLISH = {"", "không xác định", "khong xac dinh", "unknown", "null", "none", "nan", "na", "n/a"}

def _clean_null(x):
    if x is None:
        return None
    s = str(x).strip().lower()
    return None if s in NULLISH else s

df = item_df.with_columns([
    pl.col("size").map_elements(_clean_null, return_dtype=pl.Utf8).alias("size_c"),
    pl.col("age_group").map_elements(_clean_null, return_dtype=pl.Utf8).alias("age_c"),
])

total = df.height

# 2) Đếm 4 trường hợp (ép kiểu Int64 ngay tại đây để tránh UInt32)
counts_raw = df.select([
    ( (pl.col("size_c").is_not_null() & pl.col("age_c").is_not_null())
        .cast(pl.Int64).sum() ).alias("both_present"),
    ( (pl.col("size_c").is_not_null() & pl.col("age_c").is_null())
        .cast(pl.Int64).sum() ).alias("only_size"),
    ( (pl.col("size_c").is_null() & pl.col("age_c").is_not_null())
        .cast(pl.Int64).sum() ).alias("only_age_group"),
    ( (pl.col("size_c").is_null() & pl.col("age_c").is_null())
        .cast(pl.Int64).sum() ).alias("neither_present"),
])

# Dạng bảng dài + tính tỷ lệ
counts = (
    counts_raw
    .melt(variable_name="Trường hợp", value_name="Số dòng")
    .with_columns([
        pl.col("Số dòng").cast(pl.Int64),  # đảm bảo Int64
        (pl.col("Số dòng").cast(pl.Float64) / pl.lit(float(total)) * 100)
            .round(2)
            .alias("Tỷ lệ (%)"),
    ])
)

# 3) Thêm dòng Tổng (schema khớp: Utf8, Int64, Float64)
summary = pl.concat([
    counts,
    pl.DataFrame({
        "Trường hợp": pl.Series(["Tổng"], dtype=pl.Utf8),
        "Số dòng":    pl.Series([int(total)], dtype=pl.Int64),
        "Tỷ lệ (%)":  pl.Series([100.0], dtype=pl.Float64),
    }),
], how="vertical")

print("› Độ phủ hai cột: size vs age_group\n")
print(summary)

# 4) In vài số tóm tắt để đọc nhanh
both_present = counts_raw.select(pl.col("both_present")).item()
only_size    = counts_raw.select(pl.col("only_size")).item()
only_age     = counts_raw.select(pl.col("only_age_group")).item()
neither      = counts_raw.select(pl.col("neither_present")).item()

have_size = both_present + only_size
have_age  = both_present + only_age

print(
    f"\n• Hàng có size: {have_size:,}  → Thiếu size ≈ {total - have_size:,}"
    f"\n• Hàng có age_group: {have_age:,}  → Thiếu age_group ≈ {total - have_age:,}"
    f"\n• Hàng có ÍT NHẤT MỘT cột: {total - neither:,} ({(total - neither)/total:.2%})"
)

› Độ phủ hai cột: size vs age_group

shape: (5, 3)
┌─────────────────┬─────────┬───────────┐
│ Trường hợp      ┆ Số dòng ┆ Tỷ lệ (%) │
│ ---             ┆ ---     ┆ ---       │
│ str             ┆ i64     ┆ f64       │
╞═════════════════╪═════════╪═══════════╡
│ both_present    ┆ 1109    ┆ 4.06      │
│ only_size       ┆ 1115    ┆ 4.08      │
│ only_age_group  ┆ 10411   ┆ 38.09     │
│ neither_present ┆ 14697   ┆ 53.77     │
│ Tổng            ┆ 27332   ┆ 100.0     │
└─────────────────┴─────────┴───────────┘

• Hàng có size: 2,224  → Thiếu size ≈ 25,108
• Hàng có age_group: 11,520  → Thiếu age_group ≈ 15,812
• Hàng có ÍT NHẤT MỘT cột: 12,635 (46.23%)

C:\Users\tncn2\AppData\Local\Temp\ipykernel_22020\1385061828.py:32: DeprecationWarning: `DataFrame.melt` is deprecated; use `DataFrame.unpivot` instead, with `index` instead of `id_vars` and `on` instead of `value_vars`
  .melt(variable_name="Trường hợp", value_name="Số dòng")

In [14]:
# ============================================================
# RELATION & COVERAGE between item_df["size"] and ["age_group"]
# ============================================================
import polars as pl
import math, re

# -------------------------------
# 0) Chuẩn hoá giá trị null/unknown
# -------------------------------
NULLISH = {"", "không xác định", "khong xac dinh", "unknown", "null", "none", "nan", "na", "n/a"}

def _clean_cat(x):
    if x is None:
        return None
    s = str(x).strip()
    return None if s.lower() in NULLISH else s

df2 = item_df.with_columns([
    pl.col("size").map_elements(_clean_cat, return_dtype=pl.Utf8).alias("size_c"),
    pl.col("age_group").map_elements(_clean_cat, return_dtype=pl.Utf8).alias("age_c"),
])

pair = df2.select("size_c", "age_c").drop_nulls()
N = pair.height
print(f"[INFO] Rows used (both non-null): {N}")
if N == 0:
    raise ValueError("Không đủ dữ liệu hợp lệ để tính các chỉ số (N == 0).")

# -------------------------------
# 1) Contingency table
# -------------------------------
ct = pair.group_by(["size_c", "age_c"]).len().rename({"len": "n"})
row_tot = ct.group_by("size_c").agg(pl.col("n").sum().alias("row_total"))
col_tot = ct.group_by("age_c").agg(pl.col("n").sum().alias("col_total"))

expected_expr = (pl.col("row_total") * pl.col("col_total") / pl.lit(N))
ct2 = (
    ct.join(row_tot, on="size_c")
      .join(col_tot, on="age_c")
      .with_columns([
          ((pl.col("n") - expected_expr) ** 2 / expected_expr).alias("chi2_term"),
          (pl.col("n") / pl.lit(N)).alias("p_xy"),
      ])
)

# -------------------------------
# 2) Cramér’s V (bias-corrected)
# -------------------------------
chi2 = ct2.select(pl.col("chi2_term").sum()).item()
r, c = row_tot.height, col_tot.height
cramers_v = 0.0
if r >= 2 and c >= 2:
    phi2 = chi2 / N
    phi2corr = max(0.0, phi2 - ((c - 1) * (r - 1)) / (N - 1))
    rcorr = r - 1 - (r - 1) ** 2 / (N - 1)
    ccorr = c - 1 - (c - 1) ** 2 / (N - 1)
    denom = max(1.0, min(rcorr, ccorr))
    cramers_v = math.sqrt(phi2corr / denom) if denom > 0 else 0.0

# -------------------------------
# 3) Mutual Information, NMI, Theil’s U
# -------------------------------
row_probs = row_tot.with_columns((pl.col("row_total") / pl.lit(N)).alias("p_x"))
col_probs = col_tot.with_columns((pl.col("col_total") / pl.lit(N)).alias("p_y"))

ct3 = (
    ct2.join(row_probs.select(["size_c", "p_x"]), on="size_c")
       .join(col_probs.select(["age_c", "p_y"]), on="age_c")
       .with_columns(
           pl.when(pl.col("p_xy") > 0)
             .then(pl.col("p_xy") * (pl.col("p_xy") / (pl.col("p_x") * pl.col("p_y"))).log())
             .otherwise(0.0)
             .alias("mi_term")
       )
)

mi = ct3.select(pl.col("mi_term").sum()).item()
Hx = -row_probs.select((pl.col("p_x") * pl.col("p_x").log()).sum()).item()  # entropy(size)
Hy = -col_probs.select((pl.col("p_y") * pl.col("p_y").log()).sum()).item()  # entropy(age_group)

nmi = mi / math.sqrt(Hx * Hy) if Hx > 0 and Hy > 0 else 0.0
U_age_given_size = mi / Hy if Hy > 0 else 0.0    # Theil's U(Y|X)
U_size_given_age = mi / Hx if Hx > 0 else 0.0    # Theil's U(X|Y)

# -------------------------------
# 4) Mode-coverage hai chiều (per-group mode)
#    Dùng rank over group để lấy phần tử n lớn nhất per group (ổn định)
# -------------------------------
# size -> age_group
top_by_size = (
    ct.with_columns(pl.col("n").rank("dense", descending=True).over("size_c").alias("rk"))
      .filter(pl.col("rk") == 1)
      .select(["size_c", "age_c", "n"])
      .join(row_tot, on="size_c")
      .with_columns((pl.col("n") / pl.col("row_total")).alias("share_in_size"))
      .sort("share_in_size", descending=True)
)
acc_size_to_age = top_by_size.select(pl.col("n").sum() / pl.lit(N)).item()

# age_group -> size
top_by_age = (
    ct.with_columns(pl.col("n").rank("dense", descending=True).over("age_c").alias("rk"))
      .filter(pl.col("rk") == 1)
      .select(["age_c", "size_c", "n"])
      .join(col_tot, on="age_c")
      .with_columns((pl.col("n") / pl.col("col_total")).alias("share_in_age"))
      .sort("share_in_age", descending=True)
)
acc_age_to_size = top_by_age.select(pl.col("n").sum() / pl.lit(N)).item()

# -------------------------------
# 5) Metrics table (ép dtype rõ ràng để tránh lỗi int/float)
# -------------------------------
metrics = pl.DataFrame({
    "metric": pl.Series(
        "metric",
        [
            "N",
            "Cramers_V",
            "NMI",
            "Theils_U(age|size)",
            "Theils_U(size|age)",
            "ModeCoverage(size→age)",
            "ModeCoverage(age→size)",
        ],
        dtype=pl.Utf8,
    ),
    "value": pl.Series(
        "value",
        [
            float(N),
            float(cramers_v),
            float(nmi),
            float(U_age_given_size),
            float(U_size_given_age),
            float(acc_size_to_age),
            float(acc_age_to_size),
        ],
        dtype=pl.Float64,
    ),
})

print("\n===== METRICS =====")
print(metrics)

print("\n===== TOP MAP: size → age_group (per-size mode) =====")
print(top_by_size.head(30))   # đổi head(None) nếu muốn in tất cả

print("\n===== TOP MAP: age_group → size (per-age mode) =====")
print(top_by_age.head(30))    # đổi head(None) nếu muốn in tất cả

# -------------------------------
# 6) (Optional) So khớp token tuổi giữa 2 cột
# -------------------------------
DO_TOKEN_MATCH = True

def _age_token(s: str | None):
    if s is None:
        return None
    s = s.lower().strip()
    s = (
        s.replace("tháng", "m").replace("thang", "m")
         .replace("tuổi", "y").replace("tuoi", "y")
         .replace("–", "-").replace("—", "-").replace("−", "-")
         .replace(" ", "")
    )
    # range month/year
    if re.fullmatch(r"\d+-\d+m", s): return s     # ví dụ: 6-9m
    if re.fullmatch(r"\d+-\d+y", s): return s     # ví dụ: 1-3y
    # single month/year
    if re.fullmatch(r"\d+m", s): return s         # ví dụ: 9m
    if re.fullmatch(r"\d+y", s): return s         # ví dụ: 2y
    # prefixes
    if s.startswith("từ") or s.startswith("tu"):
        return "tu" + re.sub(r"[^\dy]", "", s.replace("từ", "tu"))
    if s.startswith("trên") or s.startswith("tren"):
        return "tren" + re.sub(r"[^\dy]", "", s.replace("trên", "tren"))
    return None

if DO_TOKEN_MATCH:
    df_tok = df2.with_columns([
        pl.col("size_c").map_elements(_age_token, return_dtype=pl.Utf8).alias("size_token"),
        pl.col("age_c").map_elements(_age_token, return_dtype=pl.Utf8).alias("age_token"),
    ])
    both = df_tok.filter(pl.col("size_token").is_not_null() & pl.col("age_token").is_not_null())
    exact_match_rate = both.select(
        (pl.col("size_token") == pl.col("age_token")).cast(pl.Float64).mean().alias("rate")
    ).item()
    print(f"\n[OPTIONAL] Exact-match rate of normalized age tokens: {exact_match_rate:.3f} "
          f"(on {both.height} tokenized rows)")

[INFO] Rows used (both non-null): 1109

===== METRICS =====
shape: (7, 2)
┌────────────────────────┬──────────┐
│ metric                 ┆ value    │
│ ---                    ┆ ---      │
│ str                    ┆ f64      │
╞════════════════════════╪══════════╡
│ N                      ┆ 1109.0   │
│ Cramers_V              ┆ 0.642075 │
│ NMI                    ┆ 0.691014 │
│ Theils_U(age|size)     ┆ 0.67411  │
│ Theils_U(size|age)     ┆ 0.708341 │
│ ModeCoverage(size→age) ┆ 0.645627 │
│ ModeCoverage(age→size) ┆ 0.713255 │
└────────────────────────┴──────────┘

===== TOP MAP: size → age_group (per-size mode) =====
shape: (30, 5)
┌──────────┬─────────────────────────────┬─────┬───────────┬───────────────┐
│ size_c   ┆ age_c                       ┆ n   ┆ row_total ┆ share_in_size │
│ ---      ┆ ---                         ┆ --- ┆ ---       ┆ ---           │
│ str      ┆ str                         ┆ u32 ┆ u32       ┆ f64           │
╞══════════╪═════════════════════════════╪═════╪═══════════╪═══════════════╡
│ L        ┆ Mẹ                          ┆ 5   ┆ 5         ┆ 1.0           │
│ 5-6Y     ┆ Từ 6Y                       ┆ 4   ┆ 4         ┆ 1.0           │
│ 9 tháng  ┆ Từ 9M                       ┆ 7   ┆ 7         ┆ 1.0           │
│ 12-24M   ┆ 1Y-3Y                       ┆ 7   ┆ 7         ┆ 1.0           │
│ 12 tháng ┆ 6M-24M                      ┆ 1   ┆ 1         ┆ 1.0           │
│ …        ┆ …                           ┆ …   ┆ …         ┆ …             │
│ 3-6M     ┆ ["Từ 6M", "Từ 9M", "Từ 1Y"] ┆ 32  ┆ 51        ┆ 0.627451      │
│ 1-2Y     ┆ Từ 2Y                       ┆ 12  ┆ 20        ┆ 0.6           │
│ 6 tháng  ┆ ["Từ 6M", "Từ 9M", "Từ 1Y"] ┆ 14  ┆ 24        ┆ 0.583333      │
│ 9        ┆ 6M-12M                      ┆ 5   ┆ 9         ┆ 0.555556      │
│ 12-18M   ┆ 1Y-2Y                       ┆ 13  ┆ 24        ┆ 0.541667      │
└──────────┴─────────────────────────────┴─────┴───────────┴───────────────┘

===== TOP MAP: age_group → size (per-age mode) =====
shape: (30, 5)
┌─────────────────────────────────┬─────────┬─────┬───────────┬──────────────┐
│ age_c                           ┆ size_c  ┆ n   ┆ col_total ┆ share_in_age │
│ ---                             ┆ ---     ┆ --- ┆ ---       ┆ ---          │
│ str                             ┆ str     ┆ u32 ┆ u32       ┆ f64          │
╞═════════════════════════════════╪═════════╪═════╪═══════════╪══════════════╡
│ 9M-12M                          ┆ 6-9M    ┆ 1   ┆ 1         ┆ 1.0          │
│ Từ 4Y                           ┆ 4Y      ┆ 2   ┆ 2         ┆ 1.0          │
│ 3M-12M                          ┆ 3-6M    ┆ 1   ┆ 1         ┆ 1.0          │
│ 18M-36M                         ┆ 18-24M  ┆ 3   ┆ 3         ┆ 1.0          │
│ ["Từ 0M", "Từ 3M", "Từ 6M"]     ┆ NB      ┆ 4   ┆ 4         ┆ 1.0          │
│ …                               ┆ …       ┆ …   ┆ …         ┆ …            │
│ 9M-24M                          ┆ 6-9M    ┆ 28  ┆ 33        ┆ 0.848485     │
│ ["Từ 3M", "Từ 6M", "Từ 9M", "T… ┆ 3 tháng ┆ 16  ┆ 19        ┆ 0.842105     │
│ 9M-15M                          ┆ 14      ┆ 4   ┆ 5         ┆ 0.8          │
│ 6M-36M                          ┆ 6-9M    ┆ 46  ┆ 58        ┆ 0.793103     │
│ Từ 9M                           ┆ 6-9M    ┆ 22  ┆ 29        ┆ 0.758621     │
└─────────────────────────────────┴─────────┴─────┴───────────┴──────────────┘

[OPTIONAL] Exact-match rate of normalized age tokens: 0.003 (on 324 tokenized rows)

In [17]:
# Giá trị coi như NULL
NULLISH = {"", "không xác định", "khong xac dinh", "unknown", "null", "none", "nan", "na", "n/a"}
def _clean(x):
    if x is None: return None
    s = str(x).strip()
    return None if s.lower() in NULLISH else s

# Chuẩn hoá & group theo category_l1
by_cat = (
    item_df.with_columns([
        pl.col("size").map_elements(_clean, return_dtype=pl.Utf8).alias("size_c"),
        pl.col("age_group").map_elements(_clean, return_dtype=pl.Utf8).alias("age_c"),
    ])
    .group_by("category_l1")
    .agg([
        pl.len().alias("rows"),
        pl.col("size_c").is_not_null().sum().alias("rows_with_size"),
        pl.col("age_c").is_not_null().sum().alias("rows_with_age"),
        pl.col("size_c").filter(pl.col("size_c").is_not_null()).n_unique().alias("n_size_unique"),
        pl.col("age_c").filter(pl.col("age_c").is_not_null()).n_unique().alias("n_age_unique"),
        # Danh sách unique (có thể rất dài)
        pl.col("size_c").filter(pl.col("size_c").is_not_null()).unique().sort().alias("size_unique"),
        pl.col("age_c").filter(pl.col("age_c").is_not_null()).unique().sort().alias("age_group_unique"),
    ])
    .sort("rows", descending=True)
)

print(by_cat)

shape: (15, 8)
┌────────────┬───────┬────────────┬────────────┬────────────┬────────────┬────────────┬────────────┐
│ category_l ┆ rows  ┆ rows_with_ ┆ rows_with_ ┆ n_size_uni ┆ n_age_uniq ┆ size_uniqu ┆ age_group_ │
│ 1          ┆ ---   ┆ size       ┆ age        ┆ que        ┆ ue         ┆ e          ┆ unique     │
│ ---        ┆ u32   ┆ ---        ┆ ---        ┆ ---        ┆ ---        ┆ ---        ┆ ---        │
│ str        ┆       ┆ u32        ┆ u32        ┆ u32        ┆ u32        ┆ list[str]  ┆ list[str]  │
╞════════════╪═══════╪════════════╪════════════╪════════════╪════════════╪════════════╪════════════╡
│ Thời trang ┆ 15042 ┆ 1825       ┆ 8984       ┆ 47         ┆ 55         ┆ ["0        ┆ ["0-12M",  │
│            ┆       ┆            ┆            ┆            ┆            ┆ tháng",    ┆ "0-24M", … │
│            ┆       ┆            ┆            ┆            ┆            ┆ "0-1Y", …  ┆ "["Từ 6M"… │
│            ┆       ┆            ┆            ┆            ┆            ┆ "XL"]      ┆            │
│ Phụ kiện   ┆ 3147  ┆ 356        ┆ 561        ┆ 20         ┆ 27         ┆ ["1-2      ┆ ["0-12M",  │
│            ┆       ┆            ┆            ┆            ┆            ┆ tuổi",     ┆ "0-24M", … │
│            ┆       ┆            ┆            ┆            ┆            ┆ "10", …    ┆ "Từ 6Y"]   │
│            ┆       ┆            ┆            ┆            ┆            ┆ "9"]       ┆            │
│ Đồ chơi &  ┆ 2955  ┆ 5          ┆ 679        ┆ 3          ┆ 18         ┆ ["12",     ┆ ["0-36M",  │
│ Sách       ┆       ┆            ┆            ┆            ┆            ┆ "16", "Từ  ┆ "0-3M", …  │
│            ┆       ┆            ┆            ┆            ┆            ┆ 2 tuổi"]   ┆ "Từ 9M"]   │
│ Babycare   ┆ 1994  ┆ 25         ┆ 327        ┆ 13         ┆ 40         ┆ ["0-3      ┆ ["0-12Y",  │
│            ┆       ┆            ┆            ┆            ┆            ┆ tuổi",     ┆ "0-18M", … │
│            ┆       ┆            ┆            ┆            ┆            ┆ "0-36      ┆ "Từ 9M"]   │
│            ┆       ┆            ┆            ┆            ┆            ┆ tháng", …  ┆            │
│            ┆       ┆            ┆            ┆            ┆            ┆ "…         ┆            │
│ Thực phẩm  ┆ 981   ┆ 0          ┆ 345        ┆ 0          ┆ 23         ┆ []         ┆ ["10Y-12Y" │
│ cho bé     ┆       ┆            ┆            ┆            ┆            ┆            ┆ ,          │
│            ┆       ┆            ┆            ┆            ┆            ┆            ┆ "13M-24M", │
│            ┆       ┆            ┆            ┆            ┆            ┆            ┆ … "Từ 9…   │
│ …          ┆ …     ┆ …          ┆ …          ┆ …          ┆ …          ┆ …          ┆ …          │
│ Hóa mỹ     ┆ 346   ┆ 0          ┆ 89         ┆ 0          ┆ 13         ┆ []         ┆ ["0-24M",  │
│ phẩm cho   ┆       ┆            ┆            ┆            ┆            ┆            ┆ "0-36M", … │
│ bé         ┆       ┆            ┆            ┆            ┆            ┆            ┆ "Từ 6M"]   │
│ TPCN       ┆ 270   ┆ 0          ┆ 23         ┆ 0          ┆ 18         ┆ []         ┆ ["0-12M",  │
│            ┆       ┆            ┆            ┆            ┆            ┆            ┆ "0-36M", … │
│            ┆       ┆            ┆            ┆            ┆            ┆            ┆ "Từ 7M"]   │
│ Sữa nước   ┆ 166   ┆ 0          ┆ 91         ┆ 0          ┆ 5          ┆ []         ┆ ["1Y-10Y", │
│            ┆       ┆            ┆            ┆            ┆            ┆            ┆ "Từ 1Y", … │
│            ┆       ┆            ┆            ┆            ┆            ┆            ┆ "Từ 6M"]   │
│ Vệ sinh    ┆ 132   ┆ 0          ┆ 1          ┆ 0          ┆ 1          ┆ []         ┆ ["Từ 0M"]  │
│ Gói Hội    ┆ 7     ┆ 0          ┆ 0          ┆ 0          ┆ 0          ┆ []         ┆ []         │
│ Viên       ┆       ┆            ┆            ┆            ┆            ┆            ┆            │
└────────────┴───────┴────────────┴────────────┴────────────┴────────────┴────────────┴────────────┘

In [24]:
# Lấy danh sách category
cats = (item_df.select(pl.col("category_l1").unique())
                .to_series().to_list())

for cat in cats:
    sub = item_df.filter(pl.col("category_l1") == cat).with_columns([
        pl.col("size").map_elements(_clean, return_dtype=pl.Utf8).alias("size_c"),
        pl.col("age_group").map_elements(_clean, return_dtype=pl.Utf8).alias("age_c"),
    ])

    size_vals = [v for v in sub.select("size_c").to_series().to_list() if v is not None]
    age_vals  = [v for v in sub.select("age_c").to_series().to_list()  if v is not None]

    size_u = sorted(set(size_vals))
    age_u  = sorted(set(age_vals))

    print(f"\n=== category_l1 = {cat} ===")
    # print(f"Unique size ({len(size_u)}):")
    # for v in size_u:
    #     print(" -", v)

    print(f"Unique age_group ({len(age_u)}):")
    for v in age_u:
        print(" -", v)

=== category_l1 = Thực phẩm cho gia đình ===
Unique age_group (6):
 - Mẹ
 - Từ 1Y
 - Từ 2Y
 - Từ 3Y
 - Từ 4Y
 - Từ 6M

=== category_l1 = Textile ===
Unique age_group (12):
 - 0-12M
 - 0-36M
 - 0-5Y
 - 1M-12M
 - 1M-15M
 - 1Y-2Y
 - 1Y-3Y
 - 2Y-6Y
 - Từ 0M
 - Từ 1Y
 - Từ 2M
 - Từ 3M

=== category_l1 = Vệ sinh ===
Unique age_group (1):
 - Từ 0M

=== category_l1 = Thời trang ===
Unique age_group (55):
 - 0-12M
 - 0-24M
 - 0-3M
 - 0-6M
 - 0-9M
 - 11Y-12Y
 - 12M-18M
 - 12M-4Y
 - 18M-24M
 - 18M-36M
 - 18M-4Y
 - 1Y-2Y
 - 1Y-3Y
 - 1Y-4Y
 - 1Y-6Y
 - 2Y-3Y
 - 2Y-6Y
 - 3M-12M
 - 3M-24M
 - 3M-6M
 - 3Y-4Y
 - 4Y-5Y
 - 5Y-6Y
 - 6M-12M
 - 6M-24M
 - 6M-36M
 - 6M-5Y
 - 6M-6Y
 - 6M-9M
 - 7Y-8Y
 - 9M-12M
 - 9M-24M
 - 9M-36M
 - 9M-4Y
 - 9M-6Y
 - 9Y-10Y
 - Mẹ
 - Từ 0M
 - Từ 18M
 - Từ 1Y
 - Từ 2Y
 - Từ 3M
 - Từ 3Y
 - Từ 4Y
 - Từ 5Y
 - Từ 6M
 - Từ 6Y
 - Từ 9M
 - ["Từ 0M", "Từ 3M", "Từ 6M"]
 - ["Từ 0M", "Từ 3M"]
 - ["Từ 3M", "Từ 6M", "Từ 1Y"]
 - ["Từ 3M", "Từ 6M", "Từ 9M", "Từ 1Y"]
 - ["Từ 3M", "Từ 6M", "Từ 9M"]
 - ["Từ 3M", "Từ 6M"]
 - ["Từ 6M", "Từ 9M", "Từ 1Y"]

=== category_l1 = Babycare ===
Unique age_group (40):
 - 0-12Y
 - 0-18M
 - 0-1M
 - 0-24M
 - 0-2M
 - 0-36M
 - 0-3M
 - 0-4Y
 - 0-5M
 - 0-6M
 - 0-6Y
 - 1M-3M
 - 1Y-3Y
 - 2M-15M
 - 2M-6M
 - 3M-18M
 - 3M-24M
 - 3M-6M
 - 3Y-5Y
 - 4M-6M
 - 6M-12M
 - 6M-18M
 - 6M-24M
 - 6M-36M
 - 6M-9M
 - Mẹ
 - Từ 0M
 - Từ 18M
 - Từ 1M
 - Từ 1Y
 - Từ 2M
 - Từ 2Y
 - Từ 3M
 - Từ 3Y
 - Từ 4M
 - Từ 4Y
 - Từ 6M
 - Từ 7M
 - Từ 8M
 - Từ 9M

=== category_l1 = TPCN ===
Unique age_group (18):
 - 0-12M
 - 0-36M
 - 0-4Y
 - 1Y-11Y
 - 1Y-12Y
 - 1Y-3Y
 - 1Y-9Y
 - 3Y-12Y
 - 4M-4Y
 - 6M-12M
 - 6M-12Y
 - Từ 0M
 - Từ 13Y
 - Từ 19Y
 - Từ 1Y
 - Từ 4M
 - Từ 6M
 - Từ 7M

=== category_l1 = Phụ kiện ===
Unique age_group (27):
 - 0-12M
 - 0-24M
 - 12M-18M
 - 1M-12M
 - 1M-3M
 - 1Y-2Y
 - 1Y-3Y
 - 1Y-6Y
 - 2Y-3Y
 - 2Y-6Y
 - 3Y-4Y
 - 3Y-6Y
 - 4Y-5Y
 - 5Y-6Y
 - 6M-10M
 - 6M-12M
 - 6M-15M
 - 6M-18M
 - 6M-24M
 - 9M-15M
 - 9M-20M
 - Từ 0M
 - Từ 2Y
 - Từ 3Y
 - Từ 4Y
 - Từ 5Y
 - Từ 6Y

=== category_l1 = Sữa nước ===
Unique age_group (5):
 - 1Y-10Y
 - Từ 1Y
 - Từ 2Y
 - Từ 3Y
 - Từ 6M

=== category_l1 = Sữa ===
Unique age_group (27):
 - 0-12M
 - 0-36M
 - 0-6M
 - 12M-18M
 - 1Y-10Y
 - 1Y-12Y
 - 1Y-2Y
 - 1Y-3Y
 - 1Y-6Y
 - 1Y-9Y
 - 2Y-10Y
 - 2Y-6Y
 - 3Y-10Y
 - 3Y-12Y
 - 3Y-6Y
 - 6M-12M
 - 6M-24M
 - 6M-36M
 - 9M-36M
 - Mẹ
 - Trên 2Y
 - Trên 3Y
 - Từ 18M
 - Từ 1Y
 - Từ 2Y
 - Từ 3Y
 - Từ 6M

=== category_l1 = Tã ===
Unique age_group (3):
 - 0-10M
 - Từ 1M
 - Từ 6M

=== category_l1 = Hóa mỹ phẩm gia đình ===
Unique age_group (5):
 - 3Y-5Y
 - Mẹ
 - Từ 12Y
 - Từ 3Y
 - Từ 6Y

=== category_l1 = Đồ chơi & Sách ===
Unique age_group (18):
 - 0-36M
 - 0-3M
 - 1Y-3Y
 - 2Y-6Y
 - 4Y-5Y
 - Từ 0M
 - Từ 10M
 - Từ 18M
 - Từ 19M
 - Từ 1Y
 - Từ 2Y
 - Từ 3M
 - Từ 3Y
 - Từ 5Y
 - Từ 6M
 - Từ 6Y
 - Từ 8M
 - Từ 9M

=== category_l1 = Hóa mỹ phẩm cho bé ===
Unique age_group (13):
 - 0-24M
 - 0-36M
 - 0-4Y
 - 0-6M
 - 0-6Y
 - 2Y-6Y
 - Trên 1Y
 - Từ 0M
 - Từ 1Y
 - Từ 2Y
 - Từ 3M
 - Từ 3Y
 - Từ 6M

=== category_l1 = Thực phẩm cho bé ===
Unique age_group (23):
 - 10Y-12Y
 - 13M-24M
 - 1Y-16Y
 - 3Y-12Y
 - 6M-12M
 - 6M-36M
 - 7Y-10Y
 - 7Y-14Y
 - 8Y-14Y
 - Trên 6M
 - Từ 10Y
 - Từ 18M
 - Từ 1Y
 - Từ 2Y
 - Từ 3Y
 - Từ 4M
 - Từ 5M
 - Từ 5Y
 - Từ 6M
 - Từ 7M
 - Từ 7Y
 - Từ 8M
 - Từ 9M

=== category_l1 = Gói Hội Viên ===
Unique age_group (0):

In [19]:
import polars as pl
import pandas as pd

# Hàm clean (nếu chưa có)
def _clean(x):
    if x is None:
        return None
    x = str(x).strip()
    if x.lower() in ["", "nan", "none", "không xác định"]:
        return None
    return x

# Lấy danh sách category
cats = (item_df.select(pl.col("category_l1").unique())
                .to_series().to_list())

results = []  # danh sách để lưu tất cả kết quả

for cat in cats:
    sub = item_df.filter(pl.col("category_l1") == cat).with_columns([
        pl.col("size").map_elements(_clean, return_dtype=pl.Utf8).alias("size_c"),
        pl.col("age_group").map_elements(_clean, return_dtype=pl.Utf8).alias("age_c"),
    ])

    size_vals = [v for v in sub.select("size_c").to_series().to_list() if v is not None]
    age_vals  = [v for v in sub.select("age_c").to_series().to_list()  if v is not None]

    size_u = sorted(set(size_vals))
    age_u  = sorted(set(age_vals))

    # Lưu kết quả từng dòng
    results.append({
        "category_l1": cat,
        "unique_size_count": len(size_u),
        "unique_age_group_count": len(age_u),
        "unique_size_values": ", ".join(size_u),
        "unique_age_group_values": ", ".join(age_u)
    })

# Chuyển sang DataFrame và lưu CSV
results_df = pd.DataFrame(results)
results_df.to_csv("unique_size_age_by_category.csv", index=False, encoding="utf-8-sig")

print("✅ Đã lưu kết quả vào file unique_size_age_by_category.csv")

✅ Đã lưu kết quả vào file unique_size_age_by_category.csv

In [5]:
# Hàm clean (nếu chưa có)
def _clean(x):
    if x is None:
        return None
    x = str(x).strip()
    if x.lower() in ["", "nan", "none", "không xác định"]:
        return None
    return x

In [22]:
# Lấy danh sách category
cats = (item_df.select(pl.col("category_l2").unique())
                .to_series().to_list())

for cat in cats:
    sub = item_df.filter(pl.col("category_l2") == cat).with_columns([
        pl.col("size").map_elements(_clean, return_dtype=pl.Utf8).alias("size_c"),
        pl.col("age_group").map_elements(_clean, return_dtype=pl.Utf8).alias("age_c"),
    ])

    size_vals = [v for v in sub.select("size_c").to_series().to_list() if v is not None]
    age_vals  = [v for v in sub.select("age_c").to_series().to_list()  if v is not None]

    size_u = sorted(set(size_vals))
    age_u  = sorted(set(age_vals))

    print(f"\n=== category_l2 = {cat} ===")
    # print(f"Unique size ({len(size_u)}):")
    # for v in size_u:
    #     print(" -", v)

    print(f"Unique age_group ({len(age_u)}):")
    for v in age_u:
        print(" -", v)

=== category_l2 = Huggies ===
Unique age_group (0):

=== category_l2 = TP từ sữa (bảo quản lạnh) ===
Unique age_group (4):
 - 13M-24M
 - 6M-12M
 - Từ 3Y
 - Từ 6M

=== category_l2 = TPCN cho gia đình ===
Unique age_group (0):

=== category_l2 = Tã mẫu thử ===
Unique age_group (0):

=== category_l2 = Alphagen ===
Unique age_group (0):

=== category_l2 = Thiết bị điện gia dụng ===
Unique age_group (1):
 - Mẹ

=== category_l2 = Bình sữa, phụ kiện ===
Unique age_group (23):
 - 0-1M
 - 0-2M
 - 0-3M
 - 0-5M
 - 0-6M
 - 1M-3M
 - 2M-6M
 - 3M-18M
 - 3M-24M
 - 3M-6M
 - 4M-6M
 - 6M-12M
 - 6M-18M
 - 6M-9M
 - Từ 0M
 - Từ 1M
 - Từ 2M
 - Từ 3M
 - Từ 4M
 - Từ 6M
 - Từ 7M
 - Từ 8M
 - Từ 9M

=== category_l2 = Anlene ===
Unique age_group (0):

=== category_l2 = Trái cây ===
Unique age_group (0):

=== category_l2 = Caryn ===
Unique age_group (0):

=== category_l2 = Khăn em bé ===
Unique age_group (2):
 - 1Y-3Y
 - Từ 0M

=== category_l2 = TP từ sữa (bảo quản thường) ===
Unique age_group (3):
 - Từ 2Y
 - Từ 6M
 - Từ 8M

=== category_l2 = SP mùa vụ ===
Unique age_group (0):

=== category_l2 = Pampers ===
Unique age_group (0):

=== category_l2 = Purelac ===
Unique age_group (0):

=== category_l2 = Kẹo ===
Unique age_group (1):
 - Từ 4Y

=== category_l2 = Bubs ===
Unique age_group (4):
 - 0-6M
 - 1Y-3Y
 - 3Y-12Y
 - 6M-12M

=== category_l2 = Vinamilk ===
Unique age_group (9):
 - 0-12M
 - 0-6M
 - 1Y-2Y
 - 2Y-10Y
 - 2Y-6Y
 - 6M-12M
 - Từ 1Y
 - Từ 2Y
 - Từ 3Y

=== category_l2 = Giặt xả cho bé ===
Unique age_group (2):
 - 0-24M
 - Từ 0M

=== category_l2 = Cháo ăn dặm ===
Unique age_group (1):
 - Từ 7M

=== category_l2 = Vệ sinh cho bé ===
Unique age_group (11):
 - 0-36M
 - 0-4Y
 - 0-6M
 - 0-6Y
 - 2Y-6Y
 - Trên 1Y
 - Từ 0M
 - Từ 1Y
 - Từ 2Y
 - Từ 3Y
 - Từ 6M

=== category_l2 = Molfix ===
Unique age_group (1):
 - Từ 1M

=== category_l2 = Ildong ===
Unique age_group (1):
 - 1Y-9Y

=== category_l2 = Đồ dùng cho mẹ ===
Unique age_group (1):
 - Mẹ

=== category_l2 = Khăn gia đình ===
Unique age_group (0):

=== category_l2 = Mì & Đồ khô ăn liền ===
Unique age_group (8):
 - Mẹ
 - Từ 1Y
 - Từ 4M
 - Từ 5M
 - Từ 6M
 - Từ 7M
 - Từ 8M
 - Từ 9M

=== category_l2 = Đồ uống ===
Unique age_group (5):
 - 1Y-16Y
 - Từ 1Y
 - Từ 3Y
 - Từ 5M
 - Từ 9M

=== category_l2 = Sữa có vị ===
Unique age_group (4):
 - Từ 1Y
 - Từ 2Y
 - Từ 3Y
 - Từ 6M

=== category_l2 = Whoopee ===
Unique age_group (0):

=== category_l2 = Merries ===
Unique age_group (2):
 - 0-10M
 - Từ 6M

=== category_l2 = Enfa ===
Unique age_group (9):
 - 0-12M
 - 0-6M
 - 1Y-2Y
 - 1Y-3Y
 - 1Y-6Y
 - 2Y-6Y
 - 3Y-6Y
 - 6M-12M
 - Từ 1Y

=== category_l2 = Thức ăn nghiền cho bé ===
Unique age_group (4):
 - Từ 4M
 - Từ 5M
 - Từ 6M
 - Từ 8M

=== category_l2 = Meiji ===
Unique age_group (3):
 - 0-12M
 - 1Y-3Y
 - 3Y-10Y

=== category_l2 = TPCN cho bé ===
Unique age_group (16):
 - 0-12M
 - 0-36M
 - 0-4Y
 - 1Y-11Y
 - 1Y-12Y
 - 1Y-3Y
 - 1Y-9Y
 - 3Y-12Y
 - 4M-4Y
 - 6M-12M
 - 6M-12Y
 - Từ 0M
 - Từ 1Y
 - Từ 4M
 - Từ 6M
 - Từ 7M

=== category_l2 = Thời trang bé trai ===
Unique age_group (27):
 - 0-12M
 - 0-3M
 - 12M-18M
 - 18M-24M
 - 1Y-2Y
 - 1Y-4Y
 - 2Y-3Y
 - 3M-6M
 - 3Y-4Y
 - 4Y-5Y
 - 5Y-6Y
 - 6M-24M
 - 6M-36M
 - 6M-5Y
 - 6M-6Y
 - 6M-9M
 - 9M-12M
 - 9M-36M
 - 9M-4Y
 - 9M-6Y
 - Từ 1Y
 - Từ 2Y
 - Từ 3Y
 - Từ 4Y
 - Từ 5Y
 - Từ 6Y
 - Từ 9M

=== category_l2 = Sách & VPP ===
Unique age_group (4):
 - 0-36M
 - 4Y-5Y
 - Từ 0M
 - Từ 3Y

=== category_l2 = Chăn ga gối gia đình ===
Unique age_group (0):

=== category_l2 = TPCN cho mẹ ===
Unique age_group (2):
 - Từ 13Y
 - Từ 19Y

=== category_l2 = Gối ===
Unique age_group (9):
 - 0-5Y
 - 1M-12M
 - 1M-15M
 - 1Y-2Y
 - 1Y-3Y
 - 2Y-6Y
 - Từ 1Y
 - Từ 2M
 - Từ 3M

=== category_l2 = 1Y+ ===
Unique age_group (12):
 - 1Y-3Y
 - 2Y-6Y
 - Từ 10M
 - Từ 18M
 - Từ 1Y
 - Từ 2Y
 - Từ 3Y
 - Từ 5Y
 - Từ 6M
 - Từ 6Y
 - Từ 8M
 - Từ 9M

=== category_l2 = Abbott ===
Unique age_group (8):
 - 0-12M
 - 0-6M
 - 1Y-10Y
 - 1Y-2Y
 - 2Y-6Y
 - 3Y-6Y
 - 6M-12M
 - Từ 2Y

=== category_l2 = Chăm sóc tóc ===
Unique age_group (1):
 - Mẹ

=== category_l2 = Bellamy ===
Unique age_group (5):
 - 0-6M
 - 1Y-3Y
 - 6M-12M
 - Mẹ
 - Từ 3Y

=== category_l2 = Sữa đặc trị pha sẵn ===
Unique age_group (3):
 - 1Y-10Y
 - Từ 1Y
 - Từ 2Y

=== category_l2 = Gói Hội Viên BẦU ===
Unique age_group (0):

=== category_l2 = Sữa bột pha sẵn ===
Unique age_group (4):
 - Từ 1Y
 - Từ 2Y
 - Từ 3Y
 - Từ 6M

=== category_l2 = Chăm sóc răng miệng ===
Unique age_group (3):
 - 3Y-5Y
 - Từ 12Y
 - Từ 6Y

=== category_l2 = Maeil ===
Unique age_group (1):
 - 1Y-10Y

=== category_l2 = Đồ dùng bé ngủ ngon ===
Unique age_group (4):
 - 0-12M
 - 0-36M
 - 1Y-3Y
 - Từ 0M

=== category_l2 = Anmum ===
Unique age_group (1):
 - Mẹ

=== category_l2 = Snack ===
Unique age_group (0):

=== category_l2 = A2 milk company ===
Unique age_group (0):

=== category_l2 = Bánh ===
Unique age_group (1):
 - Từ 2Y

=== category_l2 = Aptamil ===
Unique age_group (5):
 - 0-12M
 - 0-6M
 - 1Y-2Y
 - 6M-36M
 - Từ 2Y

=== category_l2 = Genki ===
Unique age_group (0):

=== category_l2 = Thời trang đông ===
Unique age_group (16):
 - 0-12M
 - 0-24M
 - 0-9M
 - 12M-18M
 - 18M-24M
 - 1Y-2Y
 - 1Y-4Y
 - 2Y-3Y
 - 3M-6M
 - 6M-12M
 - 6M-36M
 - 6M-9M
 - 9M-12M
 - Từ 2Y
 - Từ 3Y
 - Từ 4Y

=== category_l2 = Đồ dùng ăn uống ===
Unique age_group (9):
 - Từ 18M
 - Từ 1Y
 - Từ 2Y
 - Từ 3M
 - Từ 3Y
 - Từ 4M
 - Từ 6M
 - Từ 8M
 - Từ 9M

=== category_l2 = Humana ===
Unique age_group (4):
 - 0-6M
 - 1Y-9Y
 - 6M-24M
 - Từ 2Y

=== category_l2 = Thời trang bé gái ===
Unique age_group (27):
 - 0-12M
 - 0-3M
 - 0-9M
 - 12M-18M
 - 18M-24M
 - 1Y-4Y
 - 2Y-3Y
 - 2Y-6Y
 - 3M-6M
 - 3Y-4Y
 - 4Y-5Y
 - 5Y-6Y
 - 6M-24M
 - 6M-36M
 - 6M-5Y
 - 6M-6Y
 - 6M-9M
 - 9M-12M
 - 9M-4Y
 - 9M-6Y
 - Từ 18M
 - Từ 1Y
 - Từ 2Y
 - Từ 3Y
 - Từ 4Y
 - Từ 5Y
 - Từ 6Y

=== category_l2 = Glico ===
Unique age_group (4):
 - 0-12M
 - 1Y-3Y
 - 9M-36M
 - Từ 3Y

=== category_l2 = Kabrita ===
Unique age_group (3):
 - 0-12M
 - 1Y-2Y
 - Từ 2Y

=== category_l2 = Aptamil Úc ===
Unique age_group (4):
 - 6M-12M
 - Từ 1Y
 - Từ 3Y
 - Từ 6M

=== category_l2 = Khẩu trang ===
Unique age_group (0):

=== category_l2 = Meiji Nội địa ===
Unique age_group (2):
 - 0-12M
 - 1Y-3Y

=== category_l2 = Bobby ===
Unique age_group (0):

=== category_l2 = Chăn ===
Unique age_group (2):
 - 1Y-3Y
 - Từ 0M

=== category_l2 = Đồ dùng vệ sinh ===
Unique age_group (10):
 - 0-24M
 - 0-36M
 - 3Y-5Y
 - Từ 0M
 - Từ 1Y
 - Từ 2Y
 - Từ 3Y
 - Từ 4Y
 - Từ 6M
 - Từ 8M

=== category_l2 = Nước rửa bình sữa ===
Unique age_group (2):
 - 0-36M
 - Từ 0M

=== category_l2 = Wakodo ===
Unique age_group (3):
 - 0-12M
 - 1Y-3Y
 - Từ 3Y

=== category_l2 = Moony ===
Unique age_group (0):

=== category_l2 = Whito ===
Unique age_group (0):

=== category_l2 = Băng vệ sinh ===
Unique age_group (0):

=== category_l2 = Nón ===
Unique age_group (5):
 - 0-12M
 - 1M-12M
 - 1M-3M
 - 1Y-3Y
 - 3Y-6Y

=== category_l2 = Blackmores ===
Unique age_group (3):
 - 0-6M
 - 6M-12M
 - Từ 1Y

=== category_l2 = Kế hoạch gia đình ===
Unique age_group (0):

=== category_l2 = Bột lắc sữa ===
Unique age_group (1):
 - Từ 6M

=== category_l2 = Giày dép 1-3Y ===
Unique age_group (2):
 - 0-12M
 - 1Y-3Y

=== category_l2 = Sữa cho mẹ ===
Unique age_group (0):

=== category_l2 = Nestle ===
Unique age_group (11):
 - 0-12M
 - 0-36M
 - 0-6M
 - 12M-18M
 - 1Y-10Y
 - 1Y-12Y
 - 1Y-2Y
 - 2Y-6Y
 - 6M-12M
 - 6M-24M
 - Từ 18M

=== category_l2 = Vitadairy ===
Unique age_group (5):
 - 0-12M
 - 1Y-10Y
 - 1Y-2Y
 - Mẹ
 - Từ 2Y

=== category_l2 = Appekidz ===
Unique age_group (0):

=== category_l2 = Confidence ===
Unique age_group (0):

=== category_l2 = Sweety ===
Unique age_group (0):

=== category_l2 = Sức khỏe gia đình ===
Unique age_group (0):

=== category_l2 = Giặt xả gia đình ===
Unique age_group (0):

=== category_l2 = Mứt & Bơ phết ===
Unique age_group (0):

=== category_l2 = Chăm sóc da ===
Unique age_group (3):
 - Từ 12Y
 - Từ 3Y
 - Từ 6Y

=== category_l2 = Phụ kiện khác ===
Unique age_group (2):
 - 1Y-6Y
 - Từ 2Y

=== category_l2 = Kid Essential ===
Unique age_group (1):
 - 1Y-10Y

=== category_l2 = Bông tẩy trang ===
Unique age_group (0):

=== category_l2 = Goon ===
Unique age_group (0):

=== category_l2 = Dad and Me ===
Unique age_group (0):

=== category_l2 = Chăm sóc cơ thể ===
Unique age_group (1):
 - Mẹ

=== category_l2 = Dầu sức khỏe ===
Unique age_group (1):
 - Từ 0M

=== category_l2 = Dầu ăn & Gia vị ===
Unique age_group (6):
 - Từ 1Y
 - Từ 3Y
 - Từ 5M
 - Từ 6M
 - Từ 8M
 - Từ 9M

=== category_l2 = Bột ăn dặm ===
Unique age_group (5):
 - 6M-36M
 - Trên 6M
 - Từ 4M
 - Từ 6M
 - Từ 7M

=== category_l2 = Bông gạc ===
Unique age_group (0):

=== category_l2 = Bánh & Kẹo cho bé ===
Unique age_group (11):
 - 10Y-12Y
 - 3Y-12Y
 - 7Y-10Y
 - 7Y-14Y
 - 8Y-14Y
 - Từ 10Y
 - Từ 18M
 - Từ 2Y
 - Từ 3Y
 - Từ 5Y
 - Từ 7Y

=== category_l2 = Modal kháng khuẩn ===
Unique age_group (14):
 - 0-12M
 - 0-24M
 - 0-3M
 - 0-9M
 - 12M-18M
 - 18M-24M
 - 1Y-2Y
 - 3M-24M
 - 3M-6M
 - 6M-9M
 - 9M-12M
 - 9M-24M
 - Từ 0M
 - Từ 9M

=== category_l2 = Giấy ===
Unique age_group (0):

=== category_l2 = Quần áo & Phụ kiện sơ sinh ===
Unique age_group (20):
 - 0-12M
 - 0-3M
 - 0-6M
 - 0-9M
 - 12M-4Y
 - 18M-24M
 - 18M-36M
 - 18M-4Y
 - 1Y-3Y
 - 2Y-3Y
 - 2Y-6Y
 - 3M-12M
 - 3M-6M
 - 3Y-4Y
 - 4Y-5Y
 - 5Y-6Y
 - 6M-12M
 - 6M-9M
 - 9M-12M
 - Từ 0M

=== category_l2 = Thơm không gian ===
Unique age_group (0):

=== category_l2 = Trà & Cà phê ===
Unique age_group (0):

=== category_l2 = Thực phẩm đông lạnh ===
Unique age_group (0):

=== category_l2 = Giày tập đi ===
Unique age_group (11):
 - 0-12M
 - 0-24M
 - 12M-18M
 - 1Y-3Y
 - 6M-10M
 - 6M-12M
 - 6M-15M
 - 6M-18M
 - 9M-15M
 - 9M-20M
 - Từ 0M

=== category_l2 = Khăn ướt ===
Unique age_group (1):
 - Từ 0M

=== category_l2 = Đồ dùng ra ngoài ===
Unique age_group (10):
 - 0-12Y
 - 0-18M
 - 0-36M
 - 0-4Y
 - 0-6Y
 - 1Y-3Y
 - 6M-36M
 - Từ 0M
 - Từ 2Y
 - Từ 6M

=== category_l2 = Chăm sóc sức khỏe bé ===
Unique age_group (3):
 - 0-6Y
 - Từ 0M
 - Từ 3M

=== category_l2 = Khăn khô ===
Unique age_group (0):

=== category_l2 = Animo ===
Unique age_group (0):

=== category_l2 = Sữa chua uống ===
Unique age_group (2):
 - Từ 1Y
 - Từ 2Y

=== category_l2 = 0-1Y ===
Unique age_group (11):
 - 0-3M
 - Từ 0M
 - Từ 10M
 - Từ 18M
 - Từ 19M
 - Từ 1Y
 - Từ 2Y
 - Từ 3M
 - Từ 3Y
 - Từ 6M
 - Từ 9M

=== category_l2 = Morinaga ===
Unique age_group (4):
 - 0-6M
 - 6M-36M
 - Mẹ
 - Trên 3Y

=== category_l2 = Cơ cấu hàng cũ ===
Unique age_group (45):
 - 0-12M
 - 0-24M
 - 0-3M
 - 0-6M
 - 0-9M
 - 11Y-12Y
 - 12M-18M
 - 18M-24M
 - 1Y-2Y
 - 1Y-3Y
 - 1Y-6Y
 - 2Y-3Y
 - 2Y-6Y
 - 3M-6M
 - 3Y-4Y
 - 4Y-5Y
 - 5Y-6Y
 - 6M-12M
 - 6M-24M
 - 6M-36M
 - 6M-9M
 - 7Y-8Y
 - 9M-12M
 - 9M-24M
 - 9M-36M
 - 9Y-10Y
 - Mẹ
 - Từ 0M
 - Từ 18M
 - Từ 1Y
 - Từ 2Y
 - Từ 3M
 - Từ 3Y
 - Từ 4Y
 - Từ 5Y
 - Từ 6M
 - Từ 6Y
 - Từ 9M
 - ["Từ 0M", "Từ 3M", "Từ 6M"]
 - ["Từ 0M", "Từ 3M"]
 - ["Từ 3M", "Từ 6M", "Từ 1Y"]
 - ["Từ 3M", "Từ 6M", "Từ 9M", "Từ 1Y"]
 - ["Từ 3M", "Từ 6M", "Từ 9M"]
 - ["Từ 3M", "Từ 6M"]
 - ["Từ 6M", "Từ 9M", "Từ 1Y"]

=== category_l2 = Nutifood ===
Unique age_group (7):
 - 0-12M
 - 0-6M
 - 1Y-2Y
 - 6M-12M
 - Trên 2Y
 - Từ 1Y
 - Từ 2Y

=== category_l2 = Gói Hội Viên Mass ===
Unique age_group (0):

=== category_l2 = Snack ăn dặm ===
Unique age_group (5):
 - Từ 1Y
 - Từ 6M
 - Từ 7M
 - Từ 8M
 - Từ 9M

=== category_l2 = Bé ngủ ===
Unique age_group (6):
 - 0-36M
 - 0-4Y
 - 0-6M
 - 2M-15M
 - 6M-24M
 - Từ 0M

=== category_l2 = Cơ cấu hàng tồn ===
Unique age_group (0):

=== category_l2 = FCV ===
Unique age_group (7):
 - 0-12M
 - 0-6M
 - 1Y-2Y
 - 1Y-3Y
 - 2Y-6Y
 - 3Y-6Y
 - 6M-12M

=== category_l2 = Takato ===
Unique age_group (0):

=== category_l2 = Sữa hạt ===
Unique age_group (0):

=== category_l2 = XO ===
Unique age_group (2):
 - 1Y-3Y
 - Mẹ

=== category_l2 = Chăm sóc da bé ===
Unique age_group (1):
 - Từ 0M

=== category_l2 = Cho mẹ ===
Unique age_group (1):
 - Mẹ

=== category_l2 = TP bảo quản lạnh ===
Unique age_group (0):

=== category_l2 = Sữa tươi tiệt trùng ===
Unique age_group (1):
 - Từ 1Y

=== category_l2 = Chăm sóc gia đình ===
Unique age_group (1):
 - Từ 3Y

=== category_l2 = Hipp ===
Unique age_group (4):
 - 0-6M
 - 1Y-3Y
 - 6M-12M
 - Từ 3Y

=== category_l2 = Nutricare ===
Unique age_group (6):
 - 0-12M
 - 0-6M
 - 1Y-10Y
 - 1Y-3Y
 - 2Y-10Y
 - 6M-12M

=== category_l2 = Chăm sóc mẹ trước & sau sinh ===
Unique age_group (0):

=== category_l2 = Elprairie ===
Unique age_group (0):

=== category_l2 = Vệ sinh dụng cụ & bề mặt ===
Unique age_group (0):

=== category_l2 = Rascal ===
Unique age_group (0):

In [7]:
import polars as pl

# 1) Quy về NULL các giá trị "Không xác định" và tương đương
NULLISH = {
    "", " ", "   ",
    "không xác định", "khong xac dinh",
    "unknown", "null", "none", "nan", "na", "n/a"
}
def _to_null(x):
    if x is None:
        return None
    s = str(x).strip().lower()
    return None if s in NULLISH else s

df = item_df.with_columns([
    pl.col("size").map_elements(_to_null, return_dtype=pl.Utf8).alias("size_c"),
    pl.col("age_group").map_elements(_to_null, return_dtype=pl.Utf8).alias("age_c"),
])

# 2) Đếm theo category_l1
by_cat = (
    df.group_by("category_l1")
      .agg([
          pl.len().alias("rows"),
          pl.col("size_c").is_null().cast(pl.Int64).sum().alias("size_unknown"),
          pl.col("age_c").is_null().cast(pl.Int64).sum().alias("age_unknown"),
          (pl.col("size_c").is_null() & pl.col("age_c").is_null()).cast(pl.Int64).sum().alias("both_unknown"),
          pl.col("size_c").is_not_null().cast(pl.Int64).sum().alias("size_present"),
          pl.col("age_c").is_not_null().cast(pl.Int64).sum().alias("age_present"),
          (pl.col("size_c").is_not_null() | pl.col("age_c").is_not_null()).cast(pl.Int64).sum().alias("at_least_one_present"),
      ])
      .with_columns([
          (pl.col("size_unknown")/pl.col("rows")*100).round(2).alias("%size_unknown"),
          (pl.col("age_unknown")/pl.col("rows")*100).round(2).alias("%age_unknown"),
          (pl.col("both_unknown")/pl.col("rows")*100).round(2).alias("%both_unknown"),
          (pl.col("at_least_one_present")/pl.col("rows")*100).round(2).alias("%at_least_one_present"),
      ])
      .sort("rows", descending=True)
)

# 3) Thêm dòng tổng toàn bộ
total_row = (
    df.select([
        pl.len().alias("rows"),
        pl.col("size_c").is_null().cast(pl.Int64).sum().alias("size_unknown"),
        pl.col("age_c").is_null().cast(pl.Int64).sum().alias("age_unknown"),
        (pl.col("size_c").is_null() & pl.col("age_c").is_null()).cast(pl.Int64).sum().alias("both_unknown"),
        pl.col("size_c").is_not_null().cast(pl.Int64).sum().alias("size_present"),
        pl.col("age_c").is_not_null().cast(pl.Int64).sum().alias("age_present"),
        (pl.col("size_c").is_not_null() | pl.col("age_c").is_not_null()).cast(pl.Int64).sum().alias("at_least_one_present"),
    ])
    .with_columns([
        (pl.col("size_unknown")/pl.col("rows")*100).round(2).alias("%size_unknown"),
        (pl.col("age_unknown")/pl.col("rows")*100).round(2).alias("%age_unknown"),
        (pl.col("both_unknown")/pl.col("rows")*100).round(2).alias("%both_unknown"),
        (pl.col("at_least_one_present")/pl.col("rows")*100).round(2).alias("%at_least_one_present"),
    ])
    .with_columns(pl.lit("TOTAL").alias("category_l1"))
)

cols = ["category_l1","rows","size_unknown","age_unknown","both_unknown",
        "size_present","age_present","at_least_one_present",
        "%size_unknown","%age_unknown","%both_unknown","%at_least_one_present"]

summary = pl.concat([
    by_cat.select(cols),
    total_row.select(cols)
], how="vertical")

print(summary)

shape: (16, 12)
┌────────────┬───────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ category_l ┆ rows  ┆ size_unkno ┆ age_unknow ┆ … ┆ %size_unk ┆ %age_unkn ┆ %both_unk ┆ %at_least │
│ 1          ┆ ---   ┆ wn         ┆ n          ┆   ┆ nown      ┆ own       ┆ nown      ┆ _one_pres │
│ ---        ┆ u32   ┆ ---        ┆ ---        ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ent       │
│ str        ┆       ┆ i64        ┆ i64        ┆   ┆ f64       ┆ f64       ┆ f64       ┆ ---       │
│            ┆       ┆            ┆            ┆   ┆           ┆           ┆           ┆ f64       │
╞════════════╪═══════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ Thời trang ┆ 15042 ┆ 13217      ┆ 6058       ┆ … ┆ 87.87     ┆ 40.27     ┆ 34.66     ┆ 65.34     │
│ Phụ kiện   ┆ 3147  ┆ 2791       ┆ 2586       ┆ … ┆ 88.69     ┆ 82.17     ┆ 74.93     ┆ 25.07     │
│ Đồ chơi &  ┆ 2955  ┆ 2950       ┆ 2276       ┆ … ┆ 99.83     ┆ 77.02     ┆ 76.85     ┆ 23.15     │
│ Sách       ┆       ┆            ┆            ┆   ┆           ┆           ┆           ┆           │
│ Babycare   ┆ 1994  ┆ 1969       ┆ 1667       ┆ … ┆ 98.75     ┆ 83.6      ┆ 82.4      ┆ 17.6      │
│ Thực phẩm  ┆ 981   ┆ 981        ┆ 636        ┆ … ┆ 100.0     ┆ 64.83     ┆ 64.83     ┆ 35.17     │
│ cho bé     ┆       ┆            ┆            ┆   ┆           ┆           ┆           ┆           │
│ …          ┆ …     ┆ …          ┆ …          ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ TPCN       ┆ 270   ┆ 270        ┆ 247        ┆ … ┆ 100.0     ┆ 91.48     ┆ 91.48     ┆ 8.52      │
│ Sữa nước   ┆ 166   ┆ 166        ┆ 75         ┆ … ┆ 100.0     ┆ 45.18     ┆ 45.18     ┆ 54.82     │
│ Vệ sinh    ┆ 132   ┆ 132        ┆ 131        ┆ … ┆ 100.0     ┆ 99.24     ┆ 99.24     ┆ 0.76      │
│ Gói Hội    ┆ 7     ┆ 7          ┆ 7          ┆ … ┆ 100.0     ┆ 100.0     ┆ 100.0     ┆ 0.0       │
│ Viên       ┆       ┆            ┆            ┆   ┆           ┆           ┆           ┆           │
│ TOTAL      ┆ 27332 ┆ 25108      ┆ 15812      ┆ … ┆ 91.86     ┆ 57.85     ┆ 53.77     ┆ 46.23     │
└────────────┴───────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

## Xử lý

- Bucket hoá age_group → age_month_lo/hi/mid và age_bucket ∈ {0–6M, 6–12M, 1–2Y, 2–4Y, >4Y}.
- Nhận dạng size “giống tuổi” (age-like) và gắn nhãn size_type ∈ {age, letter, kg_range, cm_dim, numeric_code, other}.
- Nếu size_type='age' → đổi về tháng: size_age_month_lo/hi/mid.
- Thêm cờ: is_age_missing, is_size_missing, size_is_age/letter/kg/cm/numeric/other.
- Cell này chỉ chuẩn hoá, chưa điền chéo giữa size và age_group.

In [25]:
import polars as pl
import re, json

# ── Chuẩn hoá chuỗi để parse ──────────────────────────────────────────────
def _norm_age(s: str) -> str:
    s = s.lower().strip()
    s = (s.replace("tháng","m").replace("thang","m")
           .replace("tuổi","y").replace("tuoi","y")
           .replace("từ","tu").replace("trên","tren")
           .replace("–","-").replace("—","-").replace("−","-")
           .replace(" ", ""))
    # toddler 'T' -> 'y' (2T = 2y)
    s = re.sub(r"(?<=\d)t\b", "y", s)
    # gom newborn
    s = (s.replace("sơsinh","nb")
           .replace("sosinh","nb")
           .replace("newborn","nb"))
    return s

# ── Parse về (lo, hi) theo THÁNG; cover cả "0-5Y", "0-4Y", ... ────────────
def _parse_to_months(val: str | None):
    if val is None:
        return (None, None)

    raw = str(val).strip()

    # list-string JSON: ["Từ 0M","Từ 3M",...]
    if raw.lstrip().startswith("["):
        try:
            items = json.loads(raw)
            lows, highs = [], []
            for it in items:
                lo, hi = _parse_to_months(it)
                if lo is not None: lows.append(lo)
                if hi is not None: highs.append(hi)
            if lows or highs:
                return (min(lows) if lows else None, max(highs) if highs else None)
        except Exception:
            pass  # rơi xuống parse thường

    s = _norm_age(raw)

    # giữ nguyên "Mẹ"
    if s in {"me","mẹ"}:
        return ("Mẹ", "Mẹ")  # dùng sentinel để lát nữa trả về "Mẹ"

    # newborn
    if s == "nb":
        return (0, 3)

    # 1) RANGE với đơn vị tuỳ chọn ở MỖI VẾ
    #    - bắt được: 0-5y, 6m-12m, 12m-4y, 1y-3y, v.v...
    m = re.fullmatch(r"(\d+)(m|y)?-(\d+)(m|y)?", s)
    if m:
        a, u1, b, u2 = m.groups()
        if u1 is None and u2 is None:
            pass  # không đoán bừa nếu cả hai đều thiếu
        else:
            # nếu thiếu đơn vị ở 1 vế, kế thừa từ vế còn lại
            if u1 is None: u1 = u2
            if u2 is None: u2 = u1
            a = int(a) * (1 if u1 == "m" else 12)
            b = int(b) * (1 if u2 == "m" else 12)
            if a > b: a, b = b, a
            return (a, b)

    # 2) SINGLE: 9m, 2y
    m = re.fullmatch(r"(\d+)(m|y)", s)
    if m:
        a, u = m.groups()
        a = int(a) * (1 if u == "m" else 12)
        return (a, a)

    # 3) THRESHOLD: tu6m, tren2y
    m = re.fullmatch(r"(tu|tren)(\d+)(m|y)", s)
    if m:
        v = int(m.group(2)) * (1 if m.group(3) == "m" else 12)
        return (v, None)

    return (None, None)

# ── Map (lo,hi) -> primary bucket ─────────────────────────────────────────
def _bucket_from_months(lo, hi):
    if lo == "Mẹ" and hi == "Mẹ":
        return "Mẹ"
    if lo is None and hi is None:
        return None
    mid = lo if (hi is None or isinstance(lo, str)) else (lo + hi) / 2.0
    if isinstance(mid, str):  # đề phòng "Mẹ"
        return "Mẹ"
    if mid < 6:   return "0-6M"
    if mid < 12:  return "6-12M"
    if mid < 24:  return "1-2Y"
    if mid < 48:  return "2-4Y"
    return ">4Y"

def age_to_primary_bucket(val):
    lo, hi = _parse_to_months(val)
    return _bucket_from_months(lo, hi)

# ── Tạo cột bucket ────────────────────────────────────────────────────────
item_df = item_df.with_columns(
    pl.col("age_group").map_elements(age_to_primary_bucket, return_dtype=pl.Utf8).alias("age_bucket_primary")
)

# (tuỳ chọn) xem phân bố
print(item_df.select(pl.col("age_bucket_primary").value_counts()))

shape: (7, 1)
┌────────────────────┐
│ age_bucket_primary │
│ ---                │
│ struct[2]          │
╞════════════════════╡
│ {"1-2Y",2163}      │
│ {"Mẹ",150}         │
│ {null,15812}       │
│ {"6-12M",3073}     │
│ {">4Y",1746}       │
│ {"2-4Y",2753}      │
│ {"0-6M",1635}      │
└────────────────────┘

In [37]:
import polars as pl
import re, json
from functools import lru_cache

# =========================
# 0) Tham số
# =========================
USE_LLM = False           # Bật True nếu bạn đã điền call_llm_api bên dưới
LLM_THRESHOLD = 0.90      # Ngưỡng tin cậy tối thiểu để chấp nhận kết quả LLM
MAX_MONTHS = 216          # Giới hạn biên (18 năm), điều chỉnh nếu cần

# =========================
# 1) Chuẩn hoá/bucket hoá AGE (tái dùng cho size dạng tuổi)
# =========================
def _norm_age(s: str) -> str:
    s = s.lower().strip()
    s = (s.replace("tháng","m").replace("thang","m")
           .replace("tuổi","y").replace("tuoi","y")
           .replace("từ","tu").replace("trên","tren")
           .replace("–","-").replace("—","-").replace("−","-")
           .replace(" ", ""))
    # toddler 'T' -> 'y' (2T=2y)
    s = re.sub(r"(?<=\d)t\b", "y", s)
    # newborn
    s = (s.replace("sơsinh","nb")
           .replace("sosinh","nb")
           .replace("newborn","nb"))
    return s

def parse_age_text_to_months(val: str | None):
    """Parse chuỗi tuổi (size dạng tuổi HOẶC age_group) → (lo_m, hi_m).
       Cover: range trộn đơn vị + thiếu đơn vị 1 vế, single, threshold, list-string JSON, NB.
    """
    if val is None:
        return (None, None)

    raw = str(val).strip()

    # list-string JSON: ["Từ 0M","Từ 3M",...]
    if raw.lstrip().startswith("["):
        try:
            items = json.loads(raw)
            lows, highs = [], []
            for it in items:
                lo, hi = parse_age_text_to_months(it)
                if lo is not None: lows.append(lo)
                if hi is not None: highs.append(hi)
            if lows or highs:
                return (min(lows) if lows else None, max(highs) if highs else None)
        except Exception:
            pass  # rơi xuống parse thường

    s = _norm_age(raw)

    # giữ "mẹ": không phải tuổi
    if s in {"me","mẹ"}:
        return (None, None)

    # newborn
    if s == "nb":
        return (0, 3)

    # RANGE với đơn vị tuỳ chọn ở hai vế (0-5y, 6m-12m, 12m-4y, 1y-3y, ...)
    m = re.fullmatch(r"(\d+)(m|y)?-(\d+)(m|y)?", s)
    if m:
        a, u1, b, u2 = m.groups()
        if u1 is None and u2 is None:
            pass  # không đoán khi cả hai thiếu
        else:
            if u1 is None: u1 = u2
            if u2 is None: u2 = u1
            a = int(a) * (1 if u1 == "m" else 12)
            b = int(b) * (1 if u2 == "m" else 12)
            if a > b: a, b = b, a
            return (a, b)

    # SINGLE: 9m, 2y
    m = re.fullmatch(r"(\d+)(m|y)", s)
    if m:
        a, u = m.groups()
        a = int(a) * (1 if u == "m" else 12)
        return (a, a)

    # THRESHOLD: tu6m, tren2y
    m = re.fullmatch(r"(tu|tren)(\d+)(m|y)", s)
    if m:
        v = int(m.group(2)) * (1 if m.group(3) == "m" else 12)
        return (v, None)

    return (None, None)

def primary_bucket_from_months(lo: int | None, hi: int | None) -> str | None:
    """Mid-based primary bucket (biên 6/12/24/48 dùng '<' để rơi sang bucket cao hơn)."""
    if lo is None and hi is None:
        return None
    mid = lo if hi is None else (lo + hi) / 2.0
    if mid < 6:   return "0-6M"
    if mid < 12:  return "6-12M"
    if mid < 24:  return "1-2Y"
    if mid < 48:  return "2-4Y"
    return ">4Y"

# =========================
# 2) RULES: nhận diện size dạng tuổi
# =========================
AGE_KEYWORDS = None  # không dùng keyword; rely hoàn toàn vào regex tuổi bên trên

def size_rules_extract_months(size_val: str | None):
    """Nếu size là tuổi -> (lo_m, hi_m), else (None, None)."""
    if size_val is None:
        return (None, None)
    lo, hi = parse_age_text_to_months(size_val)
    # validate biên
    if lo is None and hi is None:
        return (None, None)
    # chặn các case vô lý
    l = lo if lo is not None else 0
    h = hi if hi is not None else MAX_MONTHS
    if l < 0 or h < 0 or h > MAX_MONTHS or (hi is not None and lo is not None and lo > hi):
        return (None, None)
    return (lo, hi)

# =========================
# 3) (TÙY CHỌN) LLM/API extraction
# =========================
def call_llm_api(size_text: str) -> dict | None:
    """
    >>> TRÁI TIM LOGIC Ở ĐÂY <<<
    Trả về dict như: {"type":"age","lo_m":6,"hi_m":12,"confidence":0.93}
    hoặc None nếu không chắc.

    Bạn có thể:
    - Dùng OpenAI: gpt-4o-mini / structured JSON
    - Dùng local Ollama: llama3/qwen; prompt yêu cầu JSON thuần
    - Dùng bất kỳ endpoint nào bạn có

    Ở đây mình để khung trống (return None).
    """
    return None  # <-- điền code gọi LLM của bạn ở đây

def size_llm_extract_months(size_val: str | None, threshold: float = LLM_THRESHOLD):
    if not size_val:
        return (None, None, None)  # lo, hi, conf
    resp = call_llm_api(str(size_val))
    if not resp:
        return (None, None, None)
    try:
        if resp.get("type") != "age":
            return (None, None, resp.get("confidence"))
        lo = resp.get("lo_m"); hi = resp.get("hi_m"); conf = float(resp.get("confidence", 0))
        # validate
        if conf < threshold: 
            return (None, None, conf)
        if lo is None and hi is None:
            return (None, None, conf)
        l = 0 if lo is None else int(lo)
        h = MAX_MONTHS if hi is None else int(hi)
        if l < 0 or h < 0 or h > MAX_MONTHS or (lo is not None and hi is not None and lo > hi):
            return (None, None, conf)
        return (lo, hi, conf)
    except Exception:
        return (None, None, None)

# =========================
# 4) Áp dụng trên các giá trị size UNIQUE (cache + join lại)
# =========================
# Lấy unique size (bạn có thể thay "size" bằng cột bạn dùng)
size_unique = (
    item_df.select(pl.col("size").cast(pl.Utf8))
           .unique()
           .drop_nulls()
)

# Tạo mapping qua rules trước
size_map_rows = []
for s in size_unique.get_column("size").to_list():
    lo, hi = size_rules_extract_months(s)
    source = None
    conf = None
    if lo is not None or hi is not None:
        source = "size_rule"
    elif USE_LLM:
        lo, hi, conf = size_llm_extract_months(s, threshold=LLM_THRESHOLD)
        if lo is not None or hi is not None:
            source = "size_llm"
    # bucket
    bucket = primary_bucket_from_months(lo, hi) if (lo is not None or hi is not None) else None
    size_map_rows.append( (s, lo, hi, bucket, source, conf) )

size_map = pl.DataFrame(size_map_rows, schema={
    "size": pl.Utf8,
    "size_lo_m": pl.Int64,
    "size_hi_m": pl.Int64,
    "size_age_bucket": pl.Utf8,
    "age_fill_source": pl.Utf8,
    "age_llm_conf": pl.Float64,
})

# Join mapping vào item_df
df_with_size_age = (
    item_df.join(size_map, on="size", how="left")
)

# Điền bổ sung vào age_bucket_primary nếu đang null
df_filled = df_with_size_age.with_columns(
    pl.when(pl.col("age_bucket_primary").is_null() & pl.col("size_age_bucket").is_not_null())
      .then(pl.col("size_age_bucket"))
      .otherwise(pl.col("age_bucket_primary"))
      .alias("age_bucket_primary_filled")
)

# Báo cáo nhanh coverage tăng thêm bao nhiêu
coverage_before = df_with_size_age.select(pl.col("age_bucket_primary").is_not_null().sum()).item()
coverage_after  = df_filled.select(pl.col("age_bucket_primary_filled").is_not_null().sum()).item()
total_rows      = df_filled.height
print({
    "total_rows": total_rows,
    "coverage_before": coverage_before,
    "coverage_after": coverage_after,
    "delta": coverage_after - coverage_before
})

{'total_rows': 27332, 'coverage_before': 11520, 'coverage_after': 12359, 'delta': 839}

C:\Users\tncn2\AppData\Local\Temp\ipykernel_4608\3834834473.py:190: DataOrientationWarning: Row orientation inferred during DataFrame construction. Explicitly specify the orientation by passing `orient="row"` to silence this warning.
  size_map = pl.DataFrame(size_map_rows, schema={

In [38]:
item_df = df_filled

In [27]:
import polars as pl

def show(df: pl.DataFrame, title: str, n: int = 20):
    print(f"\n=== {title} (show up to {n}) ===")
    cols = [c for c in [
        "category_l1", "product_id", "sku", "title",
        "size", "age_group",
        "size_lo_m", "size_hi_m", "size_age_bucket",
        "age_bucket_primary", "age_bucket_primary_filled",
        "age_fill_source", "age_llm_conf"
    ] if c in df.columns]
    print(df.select(cols).sample(n=min(n, df.height), seed=42) if df.height else "— No rows —")

# 1) Các dòng đã được FILL từ size
filled_rows = df_filled.filter(
    pl.col("age_bucket_primary").is_null() &
    pl.col("age_bucket_primary_filled").is_not_null()
)
show(filled_rows, "ĐÃ ĐIỀN bucket từ size", n=20)

# 2) Bất đồng giữa age_group bucket và size bucket (để kiểm tra)
disagree = df_filled.filter(
    pl.col("age_bucket_primary").is_not_null() &
    pl.col("size_age_bucket").is_not_null() &
    (pl.col("age_bucket_primary") != pl.col("size_age_bucket"))
)
show(disagree, "KHÁC NHAU giữa bucket từ age_group vs size (chỉ xem)", n=20)

# 3) Cả hai đều thiếu
both_missing = df_filled.filter(
    pl.col("age_bucket_primary").is_null() &
    pl.col("size_age_bucket").is_null()
)
show(both_missing, "CẢ HAI THIẾU (không có bucket)", n=20)

# 4) "Mẹ" giữ nguyên
adult_kept = df_filled.filter(pl.col("age_bucket_primary") == "Mẹ")
show(adult_kept, '"Mẹ" được giữ nguyên', n=10)

# 5) Đếm nhanh
print("\n=== COUNTS ===")
counts = pl.DataFrame({
    "metric": [
        "total_rows",
        "filled_from_size",
        "have_any_bucket_after_fill",
        "both_missing",
        "disagree_age_vs_size"
    ],
    "value": [
        df_filled.height,
        filled_rows.height,
        df_filled.filter(pl.col("age_bucket_primary_filled").is_not_null()).height,
        both_missing.height,
        disagree.height
    ]
})
print(counts)

=== ĐÃ ĐIỀN bucket từ size (show up to 20) ===
shape: (20, 10)
┌────────────┬─────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ category_l ┆ size    ┆ age_group ┆ size_lo_m ┆ … ┆ age_bucke ┆ age_bucke ┆ age_fill_ ┆ age_llm_c │
│ 1          ┆ ---     ┆ ---       ┆ ---       ┆   ┆ t_primary ┆ t_primary ┆ source    ┆ onf       │
│ ---        ┆ str     ┆ str       ┆ i64       ┆   ┆ ---       ┆ _filled   ┆ ---       ┆ ---       │
│ str        ┆         ┆           ┆           ┆   ┆ str       ┆ ---       ┆ str       ┆ f64       │
│            ┆         ┆           ┆           ┆   ┆           ┆ str       ┆           ┆           │
╞════════════╪═════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ Thời trang ┆ 2-3Y    ┆ Không xác ┆ 24        ┆ … ┆ null      ┆ 2-4Y      ┆ size_rule ┆ null      │
│            ┆         ┆ định      ┆           ┆   ┆           ┆           ┆           ┆           │
│ Thời trang ┆ 9 tháng ┆ Không xác ┆ 9         ┆ … ┆ null      ┆ 6-12M     ┆ size_rule ┆ null      │
│            ┆         ┆ định      ┆           ┆   ┆           ┆           ┆           ┆           │
│ Thời trang ┆ 1Y      ┆ Không xác ┆ 12        ┆ … ┆ null      ┆ 1-2Y      ┆ size_rule ┆ null      │
│            ┆         ┆ định      ┆           ┆   ┆           ┆           ┆           ┆           │
│ Thời trang ┆ 2Y      ┆ Không xác ┆ 24        ┆ … ┆ null      ┆ 2-4Y      ┆ size_rule ┆ null      │
│            ┆         ┆ định      ┆           ┆   ┆           ┆           ┆           ┆           │
│ Thời trang ┆ 1Y      ┆ Không xác ┆ 12        ┆ … ┆ null      ┆ 1-2Y      ┆ size_rule ┆ null      │
│            ┆         ┆ định      ┆           ┆   ┆           ┆           ┆           ┆           │
│ …          ┆ …       ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ Thời trang ┆ 1-2Y    ┆ Không xác ┆ 12        ┆ … ┆ null      ┆ 1-2Y      ┆ size_rule ┆ null      │
│            ┆         ┆ định      ┆           ┆   ┆           ┆           ┆           ┆           │
│ Thời trang ┆ 1-2Y    ┆ Không xác ┆ 12        ┆ … ┆ null      ┆ 1-2Y      ┆ size_rule ┆ null      │
│            ┆         ┆ định      ┆           ┆   ┆           ┆           ┆           ┆           │
│ Thời trang ┆ 1-2Y    ┆ Không xác ┆ 12        ┆ … ┆ null      ┆ 1-2Y      ┆ size_rule ┆ null      │
│            ┆         ┆ định      ┆           ┆   ┆           ┆           ┆           ┆           │
│ Thời trang ┆ 1Y      ┆ Không xác ┆ 12        ┆ … ┆ null      ┆ 1-2Y      ┆ size_rule ┆ null      │
│            ┆         ┆ định      ┆           ┆   ┆           ┆           ┆           ┆           │
│ Thời trang ┆ NB      ┆ Không xác ┆ 0         ┆ … ┆ null      ┆ 0-6M      ┆ size_rule ┆ null      │
│            ┆         ┆ định      ┆           ┆   ┆           ┆           ┆           ┆           │
└────────────┴─────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

=== KHÁC NHAU giữa bucket từ age_group vs size (chỉ xem) (show up to 20) ===
shape: (20, 10)
┌────────────┬──────┬────────────┬───────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ category_l ┆ size ┆ age_group  ┆ size_lo_m ┆ … ┆ age_bucket ┆ age_bucket ┆ age_fill_ ┆ age_llm_c │
│ 1          ┆ ---  ┆ ---        ┆ ---       ┆   ┆ _primary   ┆ _primary_f ┆ source    ┆ onf       │
│ ---        ┆ str  ┆ str        ┆ i64       ┆   ┆ ---        ┆ illed      ┆ ---       ┆ ---       │
│ str        ┆      ┆            ┆           ┆   ┆ str        ┆ ---        ┆ str       ┆ f64       │
│            ┆      ┆            ┆           ┆   ┆            ┆ str        ┆           ┆           │
╞════════════╪══════╪════════════╪═══════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ Thời trang ┆ 0-3M ┆ 0-12M      ┆ 0         ┆ … ┆ 6-12M      ┆ 6-12M      ┆ size_rule ┆ null      │
│ Thời trang ┆ 6-9M ┆ 6M-36M     ┆ 6         ┆ … ┆ 1-2Y       ┆ 1-2Y       ┆ size_rule ┆ null      │
│ Thời trang ┆ 1Y   ┆ 1Y-4Y      ┆ 12        ┆ … ┆ 2-4Y       ┆ 2-4Y       ┆ size_rule ┆ null      │
│ Thời trang ┆ 6-9M ┆ 6M-36M     ┆ 6         ┆ … ┆ 1-2Y       ┆ 1-2Y       ┆ size_rule ┆ null      │
│ Thời trang ┆ 9M   ┆ 9M-6Y      ┆ 9         ┆ … ┆ 2-4Y       ┆ 2-4Y       ┆ size_rule ┆ null      │
│ …          ┆ …    ┆ …          ┆ …         ┆ … ┆ …          ┆ …          ┆ …         ┆ …         │
│ Thời trang ┆ 9M   ┆ 9M-6Y      ┆ 9         ┆ … ┆ 2-4Y       ┆ 2-4Y       ┆ size_rule ┆ null      │
│ Thời trang ┆ 0-3M ┆ 0-12M      ┆ 0         ┆ … ┆ 6-12M      ┆ 6-12M      ┆ size_rule ┆ null      │
│ Thời trang ┆ 6-9M ┆ ["Từ 3M",  ┆ 6         ┆ … ┆ 0-6M       ┆ 0-6M       ┆ size_rule ┆ null      │
│            ┆      ┆ "Từ 6M",   ┆           ┆   ┆            ┆            ┆           ┆           │
│            ┆      ┆ "Từ 9M"]   ┆           ┆   ┆            ┆            ┆           ┆           │
│ Thời trang ┆ 0-3M ┆ 0-12M      ┆ 0         ┆ … ┆ 6-12M      ┆ 6-12M      ┆ size_rule ┆ null      │
│ Thời trang ┆ 6-9M ┆ Từ 3M      ┆ 6         ┆ … ┆ 0-6M       ┆ 0-6M       ┆ size_rule ┆ null      │
└────────────┴──────┴────────────┴───────────┴───┴────────────┴────────────┴───────────┴───────────┘

=== CẢ HAI THIẾU (không có bucket) (show up to 20) ===
shape: (20, 10)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ category_ ┆ size      ┆ age_group ┆ size_lo_m ┆ … ┆ age_bucke ┆ age_bucke ┆ age_fill_ ┆ age_llm_ │
│ l1        ┆ ---       ┆ ---       ┆ ---       ┆   ┆ t_primary ┆ t_primary ┆ source    ┆ conf     │
│ ---       ┆ str       ┆ str       ┆ i64       ┆   ┆ ---       ┆ _filled   ┆ ---       ┆ ---      │
│ str       ┆           ┆           ┆           ┆   ┆ str       ┆ ---       ┆ str       ┆ f64      │
│           ┆           ┆           ┆           ┆   ┆           ┆ str       ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ Phụ kiện  ┆ Không xác ┆ Không xác ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆ định      ┆ định      ┆           ┆   ┆           ┆           ┆           ┆          │
│ Phụ kiện  ┆ Không xác ┆ Không xác ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆ định      ┆ định      ┆           ┆   ┆           ┆           ┆           ┆          │
│ Phụ kiện  ┆ Không xác ┆ Không xác ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆ định      ┆ định      ┆           ┆   ┆           ┆           ┆           ┆          │
│ Đồ chơi & ┆ Không xác ┆ Không xác ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ Sách      ┆ định      ┆ định      ┆           ┆   ┆           ┆           ┆           ┆          │
│ Babycare  ┆ Không xác ┆ Không xác ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆ định      ┆ định      ┆           ┆   ┆           ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ Babycare  ┆ Không xác ┆ Không xác ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆ định      ┆ định      ┆           ┆   ┆           ┆           ┆           ┆          │
│ Phụ kiện  ┆ Không xác ┆ Không xác ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆ định      ┆ định      ┆           ┆   ┆           ┆           ┆           ┆          │
│ Phụ kiện  ┆ Không xác ┆ Không xác ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│           ┆ định      ┆ định      ┆           ┆   ┆           ┆           ┆           ┆          │
│ Hóa mỹ    ┆ Không xác ┆ Không xác ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ phẩm cho  ┆ định      ┆ định      ┆           ┆   ┆           ┆           ┆           ┆          │
│ bé        ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Thực phẩm ┆ Không xác ┆ Không xác ┆ null      ┆ … ┆ null      ┆ null      ┆ null      ┆ null     │
│ cho gia   ┆ định      ┆ định      ┆           ┆   ┆           ┆           ┆           ┆          │
│ đình      ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

=== "Mẹ" được giữ nguyên (show up to 10) ===
shape: (10, 10)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ category_ ┆ size      ┆ age_group ┆ size_lo_m ┆ … ┆ age_bucke ┆ age_bucke ┆ age_fill_ ┆ age_llm_ │
│ l1        ┆ ---       ┆ ---       ┆ ---       ┆   ┆ t_primary ┆ t_primary ┆ source    ┆ conf     │
│ ---       ┆ str       ┆ str       ┆ i64       ┆   ┆ ---       ┆ _filled   ┆ ---       ┆ ---      │
│ str       ┆           ┆           ┆           ┆   ┆ str       ┆ ---       ┆ str       ┆ f64      │
│           ┆           ┆           ┆           ┆   ┆           ┆ str       ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ Thời      ┆ Không xác ┆ Mẹ        ┆ null      ┆ … ┆ Mẹ        ┆ Mẹ        ┆ null      ┆ null     │
│ trang     ┆ định      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Thời      ┆ L         ┆ Mẹ        ┆ null      ┆ … ┆ Mẹ        ┆ Mẹ        ┆ null      ┆ null     │
│ trang     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Sữa       ┆ Không xác ┆ Mẹ        ┆ null      ┆ … ┆ Mẹ        ┆ Mẹ        ┆ null      ┆ null     │
│           ┆ định      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Babycare  ┆ Không xác ┆ Mẹ        ┆ null      ┆ … ┆ Mẹ        ┆ Mẹ        ┆ null      ┆ null     │
│           ┆ định      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Thời      ┆ Không xác ┆ Mẹ        ┆ null      ┆ … ┆ Mẹ        ┆ Mẹ        ┆ null      ┆ null     │
│ trang     ┆ định      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Thời      ┆ Không xác ┆ Mẹ        ┆ null      ┆ … ┆ Mẹ        ┆ Mẹ        ┆ null      ┆ null     │
│ trang     ┆ định      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Thời      ┆ Không xác ┆ Mẹ        ┆ null      ┆ … ┆ Mẹ        ┆ Mẹ        ┆ null      ┆ null     │
│ trang     ┆ định      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Thời      ┆ S         ┆ Mẹ        ┆ null      ┆ … ┆ Mẹ        ┆ Mẹ        ┆ null      ┆ null     │
│ trang     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Thời      ┆ Không xác ┆ Mẹ        ┆ null      ┆ … ┆ Mẹ        ┆ Mẹ        ┆ null      ┆ null     │
│ trang     ┆ định      ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
│ Thời      ┆ S         ┆ Mẹ        ┆ null      ┆ … ┆ Mẹ        ┆ Mẹ        ┆ null      ┆ null     │
│ trang     ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

=== COUNTS ===
shape: (5, 2)
┌────────────────────────────┬───────┐
│ metric                     ┆ value │
│ ---                        ┆ ---   │
│ str                        ┆ i64   │
╞════════════════════════════╪═══════╡
│ total_rows                 ┆ 27332 │
│ filled_from_size           ┆ 839   │
│ have_any_bucket_after_fill ┆ 12359 │
│ both_missing               ┆ 14973 │
│ disagree_age_vs_size       ┆ 745   │
└────────────────────────────┴───────┘

In [39]:
# === Cell: Trích tuổi từ description_merged và điền bổ sung (đÃ FIX "0-6M") ===
import polars as pl

df = item_df  # dùng DF hiện tại

# -- helper: map mid(tháng) -> nhãn bucket (dùng pl.lit cho LITERAL) --
def bucket_from_mid_expr(mid: pl.Expr) -> pl.Expr:
    return (
        pl.when(mid.is_null()).then(pl.lit(None))
         .when(mid < 6).then(pl.lit("0-6M"))
         .when(mid < 12).then(pl.lit("6-12M"))
         .when(mid < 24).then(pl.lit("1-2Y"))
         .when(mid < 48).then(pl.lit("2-4Y"))
         .otherwise(pl.lit(">4Y"))
    )

# (an toàn) nếu có cột bucket cũ dùng en-dash, đưa về ASCII hyphen
if "age_bucket_primary_filled" in df.columns:
    df = df.with_columns(
        pl.col("age_bucket_primary_filled").cast(pl.Utf8)
          .str.replace_all("–|—", "-")
          .alias("age_bucket_primary_filled")
    )

# nếu chưa có cột primary, tạo từ age_month_mid (nếu có), else để None
if "age_bucket_primary_filled" not in df.columns:
    df = df.with_columns(
        bucket_from_mid_expr(pl.col("age_month_mid")).alias("age_bucket_primary_filled")
        if "age_month_mid" in df.columns else pl.lit(None).alias("age_bucket_primary_filled")
    )

# 1) chuẩn hoá mô tả để parse (không đổi giá trị gốc)
df = df.with_columns(
    pl.col("description_merged").cast(pl.Utf8)
      .str.to_lowercase()
      .str.replace_all('"', '').str.replace_all('“|”', '')
      .str.replace_all(r"\s+", " ").str.strip_chars()
      .alias("_desc_norm")
)

# 2) trích tuổi (tháng) từ mô tả
d_range_m_lo = pl.col("_desc_norm").str.extract(r'(\d{1,2})\s*[-–—]\s*(\d{1,2})\s*(?:m|mo|tháng)\b', 1).cast(pl.Int64)
d_range_m_hi = pl.col("_desc_norm").str.extract(r'(\d{1,2})\s*[-–—]\s*(\d{1,2})\s*(?:m|mo|tháng)\b', 2).cast(pl.Int64)
d_range_y_lo = pl.col("_desc_norm").str.extract(r'(\d{1,2})\s*[-–—]\s*(\d{1,2})\s*(?:y|yr|years|tuổi|năm)\b', 1).cast(pl.Int64) * 12
d_range_y_hi = pl.col("_desc_norm").str.extract(r'(\d{1,2})\s*[-–—]\s*(\d{1,2})\s*(?:y|yr|years|tuổi|năm)\b', 2).cast(pl.Int64) * 12
d_lb_m       = pl.col("_desc_norm").str.extract(r'(?:từ|>=|trên)\s*(\d{1,2})\s*(?:m|mo|tháng)\b', 1).cast(pl.Int64)
d_lb_y       = pl.col("_desc_norm").str.extract(r'(?:từ|>=|trên)\s*(\d{1,2})\s*(?:y|yr|years|tuổi|năm)\b', 1).cast(pl.Int64) * 12
d_single_m   = pl.col("_desc_norm").str.extract(r'\b(\d{1,2})\s*(?:m|mo|tháng)\b', 1).cast(pl.Int64)
d_single_y   = pl.col("_desc_norm").str.extract(r'\b(\d{1,2})\s*(?:y|yr|years|tuổi|năm)\b', 1).cast(pl.Int64) * 12
d_nb_lo      = pl.when(pl.col("_desc_norm").str.contains(r'\b(nb|newborn|sơ sinh)\b')).then(pl.lit(0)).otherwise(None)
d_nb_hi      = pl.when(pl.col("_desc_norm").str.contains(r'\b(nb|newborn|sơ sinh)\b')).then(pl.lit(3)).otherwise(None)

df = df.with_columns([
    pl.coalesce([d_range_m_lo, d_range_y_lo, d_nb_lo, d_lb_m, d_lb_y, d_single_m, d_single_y]).alias("desc_age_month_lo"),
    pl.coalesce([d_range_m_hi, d_range_y_hi, d_nb_hi]).alias("desc_age_month_hi"),
]).with_columns([
    pl.when(pl.col("desc_age_month_lo").is_not_null() & pl.col("desc_age_month_hi").is_not_null())
      .then((pl.col("desc_age_month_lo") + pl.col("desc_age_month_hi")) / 2)
      .when(pl.col("desc_age_month_lo").is_not_null())
      .then(pl.col("desc_age_month_lo").cast(pl.Float64))
      .otherwise(None)
      .alias("desc_age_month_mid"),
])

# 3) bucket mô tả theo chuẩn ASCII (dùng pl.lit trong bucket_from_mid_expr)
df = df.with_columns(
    bucket_from_mid_expr(pl.col("desc_age_month_mid")).alias("desc_age_bucket")
)

# 4) confidence đơn giản
df = df.with_columns(
    pl.when(pl.col("desc_age_month_lo").is_not_null() & pl.col("desc_age_month_hi").is_not_null()).then(pl.lit(0.95))
     .when(pl.col("desc_age_month_lo").is_not_null() & pl.col("desc_age_month_hi").is_null()).then(pl.lit(0.85))
     .otherwise(pl.lit(None))
     .alias("desc_age_confidence")
)

# 5) điền bổ sung vào tuổi chính (coalesce ưu tiên primary)
df = df.with_columns([
    pl.when(pl.col("age_bucket_primary_filled").is_not_null())
      .then(pl.col("age_bucket_primary_filled"))
      .when(pl.col("desc_age_bucket").is_not_null())
      .then(pl.col("desc_age_bucket"))
      .otherwise(pl.lit(None))
      .alias("age_bucket_enriched"),
    pl.when(pl.col("age_bucket_primary_filled").is_not_null()).then(pl.lit("primary"))
     .when(pl.col("desc_age_bucket").is_not_null()).then(pl.lit("from_description"))
     .otherwise(pl.lit("missing"))
     .alias("age_source_enriched")
])

# 6) báo cáo
report = (
    df.select([
        pl.count().alias("total"),
        pl.col("age_bucket_primary_filled").is_not_null().sum().alias("present_primary"),
        pl.col("age_bucket_enriched").is_not_null().sum().alias("present_enriched"),
        (pl.col("age_source_enriched") == "from_description").sum().alias("filled_from_description"),
    ])
    .with_columns(
        primary_pct   = (pl.col("present_primary")   / pl.col("total") * 100).round(2),
        enriched_pct  = (pl.col("present_enriched")  / pl.col("total") * 100).round(2),
        added_by_desc = (pl.col("filled_from_description") / pl.col("total") * 100).round(2),
    )
)
print(">>> Age coverage (before/after + added by description)")
print(report)

# vài dòng mẫu điền từ mô tả
print("\n>>> Sample rows filled from description:")
print(
    df.filter(pl.col("age_source_enriched") == "from_description")
      .select(["desc_age_bucket","desc_age_confidence","description_merged"])
      .head(5)
)

# lưu lại
item_df = df

>>> Age coverage (before/after + added by description)
shape: (1, 7)
┌───────┬───────────────┬───────────────┬──────────────┬─────────────┬──────────────┬──────────────┐
│ total ┆ present_prima ┆ present_enric ┆ filled_from_ ┆ primary_pct ┆ enriched_pct ┆ added_by_des │
│ ---   ┆ ry            ┆ hed           ┆ description  ┆ ---         ┆ ---          ┆ c            │
│ u32   ┆ ---           ┆ ---           ┆ ---          ┆ f64         ┆ f64          ┆ ---          │
│       ┆ u32           ┆ u32           ┆ u32          ┆             ┆              ┆ f64          │
╞═══════╪═══════════════╪═══════════════╪══════════════╪═════════════╪══════════════╪══════════════╡
│ 27332 ┆ 12359         ┆ 17150         ┆ 4791         ┆ 45.22       ┆ 62.75        ┆ 17.53        │
└───────┴───────────────┴───────────────┴──────────────┴─────────────┴──────────────┴──────────────┘

>>> Sample rows filled from description:
shape: (5, 3)
┌─────────────────┬─────────────────────┬─────────────────────────────────┐
│ desc_age_bucket ┆ desc_age_confidence ┆ description_merged              │
│ ---             ┆ ---                 ┆ ---                             │
│ str             ┆ f64                 ┆ str                             │
╞═════════════════╪═════════════════════╪═════════════════════════════════╡
│ 0-6M            ┆ 0.95                ┆ Chi tiết sản phẩm             … │
│ 1-2Y            ┆ 0.95                ┆ Chi tiết sản phẩm             … │
│ 0-6M            ┆ 0.95                ┆ Chi tiết sản phẩm             … │
│ 1-2Y            ┆ 0.95                ┆ Chi tiết sản phẩm             … │
│ 1-2Y            ┆ 0.85                ┆ Chi tiết sản phẩm             … │
└─────────────────┴─────────────────────┴─────────────────────────────────┘

C:\Users\tncn2\AppData\Local\Temp\ipykernel_4608\2188144062.py:95: DeprecationWarning: `pl.count()` is deprecated. Please use `pl.len()` instead.
(Deprecated in version 0.20.5)
  pl.count().alias("total"),

In [40]:
item_df.head(5)

shape: (5, 56)
┌───────┬────────────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ p_id  ┆ item_id    ┆ price      ┆ category_l ┆ … ┆ desc_age_ ┆ desc_age_ ┆ age_bucke ┆ age_sourc │
│ ---   ┆ ---        ┆ ---        ┆ 1_id       ┆   ┆ bucket    ┆ confidenc ┆ t_enriche ┆ e_enriche │
│ i32   ┆ str        ┆ decimal[38 ┆ ---        ┆   ┆ ---       ┆ e         ┆ d         ┆ d         │
│       ┆            ┆ ,4]        ┆ i32        ┆   ┆ str       ┆ ---       ┆ ---       ┆ ---       │
│       ┆            ┆            ┆            ┆   ┆           ┆ f64       ┆ str       ┆ str       │
╞═══════╪════════════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 17065 ┆ 0502020000 ┆ 99000.0000 ┆ 1          ┆ … ┆ 0-6M      ┆ 0.95      ┆ 0-6M      ┆ from_desc │
│       ┆ 004        ┆            ┆            ┆   ┆           ┆           ┆           ┆ ription   │
│ 72370 ┆ 0010290040 ┆ 69000.0000 ┆ 3292       ┆ … ┆ null      ┆ null      ┆ 2-4Y      ┆ primary   │
│       ┆ 150        ┆            ┆            ┆   ┆           ┆           ┆           ┆           │
│ 31154 ┆ 0008010000 ┆ 45000.0000 ┆ 351        ┆ … ┆ null      ┆ null      ┆ null      ┆ missing   │
│       ┆ 015        ┆            ┆            ┆   ┆           ┆           ┆           ┆           │
│ 46123 ┆ 0020010000 ┆ 401000.000 ┆ 2222       ┆ … ┆ null      ┆ null      ┆ null      ┆ missing   │
│       ┆ 094        ┆ 0          ┆            ┆   ┆           ┆           ┆           ┆           │
│ 46127 ┆ 0020010000 ┆ 401000.000 ┆ 2222       ┆ … ┆ null      ┆ null      ┆ null      ┆ missing   │
│       ┆ 098        ┆ 0          ┆            ┆   ┆           ┆           ┆           ┆           │
└───────┴────────────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

Bắt các mẫu cân nặng: 4-8 kg, 4 – 8kg, từ 4 đến 8 kg, và cân nặng đơn 8 kg.

Quy đổi về kg_mid (trung điểm) rồi map sang bucket tuổi:
0–5.5 → 0-6M, 5.5–7.5 → 3-6M, 7.5–9.5 → 6-9M, 9.5–11.5 → 9-12M, 11.5–14 → 1-2Y, 14–20 → 2-4Y, >20 → >4Y.

confidence: 0.70 cho khoảng kg, 0.55 cho đơn lẻ kg (thấp hơn tuổi trích trực tiếp).

Điền vào cột mới age_bucket_final (ưu tiên age_bucket_enriched → cân nặng).

In [42]:
import polars as pl

df = item_df

# 0) Chuẩn hoá mô tả (nếu chưa có _desc_norm từ trước)
if "_desc_norm" not in df.columns:
    df = df.with_columns(
        pl.col("description_merged").cast(pl.Utf8)
          .str.to_lowercase()
          .str.replace_all('"', '').str.replace_all('“|”', '')
          .str.replace_all(r"\s+", " ").str.strip_chars()
          .alias("_desc_norm")
    )

# 1) Trích cân nặng (kg)
#   - Hyphen/ndashes: "4-8kg" hoặc "4 - 8 kg"
kg_r_lo = pl.col("_desc_norm").str.extract(r'(\d+(?:[.,]\d+)?)\s*[-–—]\s*(\d+(?:[.,]\d+)?)\s*kg\b', 1)
kg_r_hi = pl.col("_desc_norm").str.extract(r'(\d+(?:[.,]\d+)?)\s*[-–—]\s*(\d+(?:[.,]\d+)?)\s*kg\b', 2)

#   - "từ ... đến ... kg"
kg_tu_lo = pl.col("_desc_norm").str.extract(r'(?:từ)\s*(\d+(?:[.,]\d+)?)\s*(?:kg)?\s*(?:đến|to|-|–|—)\s*(\d+(?:[.,]\d+)?)\s*kg\b', 1)
kg_tu_hi = pl.col("_desc_norm").str.extract(r'(?:từ)\s*(\d+(?:[.,]\d+)?)\s*(?:kg)?\s*(?:đến|to|-|–|—)\s*(\d+(?:[.,]\d+)?)\s*kg\b', 2)

#   - Cân nặng đơn: "8 kg"
kg_single = pl.col("_desc_norm").str.extract(r'\b(\d+(?:[.,]\d+)?)\s*kg\b', 1)

def to_float(expr: pl.Expr) -> pl.Expr:
    return expr.str.replace_all(",", ".").cast(pl.Float64)

df = df.with_columns([
    pl.coalesce([to_float(kg_r_lo), to_float(kg_tu_lo)]).alias("kg_lo"),
    pl.coalesce([to_float(kg_r_hi), to_float(kg_tu_hi)]).alias("kg_hi"),
    to_float(kg_single).alias("kg_single"),
])

# Nếu có khoảng thì dùng khoảng; nếu không thì dùng đơn lẻ
df = df.with_columns([
    pl.when(pl.col("kg_lo").is_not_null() & pl.col("kg_hi").is_not_null())
      .then((pl.col("kg_lo") + pl.col("kg_hi")) / 2)
      .when(pl.col("kg_lo").is_not_null() & pl.col("kg_hi").is_null())
      .then(pl.col("kg_lo"))
      .when(pl.col("kg_lo").is_null() & pl.col("kg_hi").is_null() & pl.col("kg_single").is_not_null())
      .then(pl.col("kg_single"))
      .otherwise(None)
      .alias("kg_mid")
])

# 2) Map kg_mid -> age bucket theo heuristic
def bucket_from_kg_expr(kg_mid: pl.Expr) -> pl.Expr:
    return (
        pl.when(kg_mid.is_null()).then(pl.lit(None))
         .when(kg_mid < 5.5).then(pl.lit("0-6M"))
         .when(kg_mid < 7.5).then(pl.lit("3-6M"))   # chỉ dùng nội bộ; sẽ map tiếp sang lưới 5-bucket
         .when(kg_mid < 9.5).then(pl.lit("6-9M"))
         .when(kg_mid < 11.5).then(pl.lit("9-12M"))
         .when(kg_mid < 14).then(pl.lit("1-2Y"))
         .when(kg_mid < 20).then(pl.lit("2-4Y"))
         .otherwise(pl.lit(">4Y"))
    )

df = df.with_columns(
    bucket_from_kg_expr(pl.col("kg_mid")).alias("weight_age_bucket_raw")
)

# (Tuỳ chọn) gom về lưới bucket chính 5 mức của bạn
def normalize_to_primary(bucket_col: pl.Expr) -> pl.Expr:
    return (
        pl.when(bucket_col.is_null()).then(pl.lit(None))
         .when(bucket_col == "0-6M").then(pl.lit("0-6M"))
         .when((bucket_col == "3-6M") | (bucket_col == "6-9M")).then(pl.lit("6-12M"))
         .when(bucket_col == "9-12M").then(pl.lit("6-12M"))
         .when(bucket_col == "1-2Y").then(pl.lit("1-2Y"))
         .when(bucket_col == "2-4Y").then(pl.lit("2-4Y"))
         .otherwise(pl.lit(">4Y"))
    )

df = df.with_columns(
    normalize_to_primary(pl.col("weight_age_bucket_raw")).alias("weight_age_bucket")
)

# 3) Confidence & source (range > single)
df = df.with_columns(
    pl.when(pl.col("kg_lo").is_not_null() & pl.col("kg_hi").is_not_null()).then(pl.lit(0.70))
     .when(pl.col("kg_mid").is_not_null()).then(pl.lit(0.55))
     .otherwise(pl.lit(None)).alias("weight_age_confidence"),
).with_columns(
    pl.when(pl.col("kg_lo").is_not_null() & pl.col("kg_hi").is_not_null()).then(pl.lit("weight_range"))
     .when(pl.col("kg_mid").is_not_null()).then(pl.lit("weight_single"))
     .otherwise(pl.lit(None)).alias("weight_age_source")
)

# 4) Điền bổ sung vào tuổi (sau bước enrich từ description)
df = df.with_columns([
    pl.when(pl.col("age_bucket_enriched").is_not_null())
      .then(pl.col("age_bucket_enriched"))
      .when(pl.col("weight_age_bucket").is_not_null())
      .then(pl.col("weight_age_bucket"))
      .otherwise(pl.lit(None))
      .alias("age_bucket_final"),
    pl.when(pl.col("age_bucket_enriched").is_not_null()).then(pl.lit("enriched"))
     .when(pl.col("weight_age_bucket").is_not_null()).then(pl.lit("from_weight"))
     .otherwise(pl.lit("missing"))
     .alias("age_source_final")
])

# 5) Báo cáo uplift từ cân nặng
report_w = (
    df.select([
        pl.len().alias("total"),
        pl.col("age_bucket_enriched").is_not_null().sum().alias("present_before"),
        pl.col("age_bucket_final").is_not_null().sum().alias("present_after"),
        (pl.col("age_source_final") == "from_weight").sum().alias("filled_from_weight"),
    ])
    .with_columns(
        before_pct = (pl.col("present_before") / pl.col("total") * 100).round(2),
        after_pct  = (pl.col("present_after")  / pl.col("total") * 100).round(2),
        added_pct  = (pl.col("filled_from_weight") / pl.col("total") * 100).round(2),
    )
)
print(">>> Weight-based enrichment report")
print(report_w)

print("\n>>> Sample rows filled from weight:")
print(
    df.filter(pl.col("age_source_final") == "from_weight")
      .select(["kg_lo","kg_hi","kg_mid","weight_age_bucket","weight_age_confidence","_desc_norm"])
      .head(5)
)

# Lưu lại
item_df = df

>>> Weight-based enrichment report
shape: (1, 7)
┌───────┬────────────────┬───────────────┬────────────────────┬────────────┬───────────┬───────────┐
│ total ┆ present_before ┆ present_after ┆ filled_from_weight ┆ before_pct ┆ after_pct ┆ added_pct │
│ ---   ┆ ---            ┆ ---           ┆ ---                ┆ ---        ┆ ---       ┆ ---       │
│ u32   ┆ u32            ┆ u32           ┆ u32                ┆ f64        ┆ f64       ┆ f64       │
╞═══════╪════════════════╪═══════════════╪════════════════════╪════════════╪═══════════╪═══════════╡
│ 27332 ┆ 17150          ┆ 18384         ┆ 1234               ┆ 62.75      ┆ 67.26     ┆ 4.51      │
└───────┴────────────────┴───────────────┴────────────────────┴────────────┴───────────┴───────────┘

>>> Sample rows filled from weight:
shape: (5, 6)
┌───────┬───────┬────────┬───────────────────┬───────────────────────┬─────────────────────────────┐
│ kg_lo ┆ kg_hi ┆ kg_mid ┆ weight_age_bucket ┆ weight_age_confidence ┆ _desc_norm                  │
│ ---   ┆ ---   ┆ ---    ┆ ---               ┆ ---                   ┆ ---                         │
│ f64   ┆ f64   ┆ f64    ┆ str               ┆ f64                   ┆ str                         │
╞═══════╪═══════╪════════╪═══════════════════╪═══════════════════════╪═════════════════════════════╡
│ 4.0   ┆ 8.0   ┆ 6.0    ┆ 6-12M             ┆ 0.7                   ┆ ﻿﻿tã dán merries size s 82    │
│       ┆       ┆        ┆                   ┆                       ┆ miế…                        │
│ 6.0   ┆ 11.0  ┆ 8.5    ┆ 6-12M             ┆ 0.7                   ┆ ﻿﻿﻿bỉm tã quần merries size m  │
│       ┆       ┆        ┆                   ┆                       ┆ …                           │
│ null  ┆ null  ┆ 3.5    ┆ 0-6M              ┆ 0.55                  ┆ chi tiết sản phẩm tên sản   │
│       ┆       ┆        ┆                   ┆                       ┆ phẩm…                       │
│ 15.0  ┆ 28.0  ┆ 21.5   ┆ >4Y               ┆ 0.7                   ┆ ﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿tã quần merries size…       │
│ 9.0   ┆ 14.0  ┆ 11.5   ┆ 1-2Y              ┆ 0.7                   ┆ ﻿﻿tã dán merries size l 54    │
│       ┆       ┆        ┆                   ┆                       ┆ miế…                        │
└───────┴───────┴────────┴───────────────────┴───────────────────────┴─────────────────────────────┘

In [43]:
import polars as pl

df = item_df

# Preview mô tả gọn để nhìn nhanh (cắt 160 ký tự, gom khoảng trắng)
df = df.with_columns(
    pl.col("description_merged").cast(pl.Utf8)
      .str.replace_all(r"\s+", " ")
      .str.slice(0, 160)
      .alias("desc_preview")
)

print("=== Mẫu ĐƯỢC ĐIỀN từ DESCRIPTION ===")
print(
    df.filter(pl.col("age_source_enriched") == "from_description")
      .select([
          "item_id","category_l1","brand","size","age_bucket_primary_filled",
          "desc_age_bucket","desc_age_confidence","desc_preview"
      ])
      .head(10)
)

print("\n=== Mẫu ĐƯỢC ĐIỀN từ WEIGHT ===")
print(
    df.filter(pl.col("age_source_final") == "from_weight")
      .select([
          "item_id","category_l1","brand","size","kg_lo","kg_hi","kg_mid",
          "weight_age_bucket","weight_age_confidence","desc_preview"
      ])
      .head(10)
)

print("\n=== Mẫu CÓ CẢ primary & description NHƯNG KHÁC NHAU (để so sánh) ===")
print(
    df.filter(
        pl.col("age_bucket_primary_filled").is_not_null() &
        pl.col("desc_age_bucket").is_not_null() &
        (pl.col("age_bucket_primary_filled") != pl.col("desc_age_bucket"))
    )
    .select([
        "item_id","category_l1","brand","size",
        "age_bucket_primary_filled","desc_age_bucket","desc_age_confidence",
        "desc_preview"
    ])
    .head(10)
)

print("\n=== Mẫu VẪN THIẾU SAU TẤT CẢ (age_bucket_final is NULL) ===")
print(
    df.filter(pl.col("age_bucket_final").is_null())
      .select([
          "item_id","category_l1","brand","size","age_group",
          "age_bucket_primary_filled","desc_age_bucket","weight_age_bucket","desc_preview"
      ])
      .head(10)
)

=== Mẫu ĐƯỢC ĐIỀN từ DESCRIPTION ===
shape: (10, 8)
┌────────────┬────────────┬────────────┬───────────┬───────────┬───────────┬───────────┬───────────┐
│ item_id    ┆ category_l ┆ brand      ┆ size      ┆ age_bucke ┆ desc_age_ ┆ desc_age_ ┆ desc_prev │
│ ---        ┆ 1          ┆ ---        ┆ ---       ┆ t_primary ┆ bucket    ┆ confidenc ┆ iew       │
│ str        ┆ ---        ┆ str        ┆ str       ┆ _filled   ┆ ---       ┆ e         ┆ ---       │
│            ┆ str        ┆            ┆           ┆ ---       ┆ str       ┆ ---       ┆ str       │
│            ┆            ┆            ┆           ┆ str       ┆           ┆ f64       ┆           │
╞════════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 0502020000 ┆ Babycare   ┆ Dr.Brown's ┆ Không xác ┆ null      ┆ 0-6M      ┆ 0.95      ┆ Chi tiết  │
│ 004        ┆            ┆            ┆ định      ┆           ┆           ┆           ┆ sản phẩm  │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ Tên sản   │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ phẩm…     │
│ 0008180000 ┆ Đồ chơi &  ┆ Quà tặng   ┆ Không xác ┆ null      ┆ 1-2Y      ┆ 0.95      ┆ Chi tiết  │
│ 017        ┆ Sách       ┆ không bán  ┆ định      ┆           ┆           ┆           ┆ sản phẩm  │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ Tên sản   │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ phẩm…     │
│ 0020010000 ┆ Tã         ┆ Moony      ┆ Không xác ┆ null      ┆ 0-6M      ┆ 0.95      ┆ Chi tiết  │
│ 151        ┆            ┆            ┆ định      ┆           ┆           ┆           ┆ sản phẩm  │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ Tên sản   │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ phẩm…     │
│ 0008170000 ┆ Đồ chơi &  ┆ Winnie     ┆ Không xác ┆ null      ┆ 1-2Y      ┆ 0.95      ┆ Chi tiết  │
│ 021        ┆ Sách       ┆ Care (Thái ┆ định      ┆           ┆           ┆           ┆ sản phẩm  │
│            ┆            ┆ Lan)       ┆           ┆           ┆           ┆           ┆ Tên sản   │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ phẩm…     │
│ 0007080000 ┆ Babycare   ┆ Misa (Việt ┆ Không xác ┆ null      ┆ 1-2Y      ┆ 0.85      ┆ Chi tiết  │
│ 368        ┆            ┆ Nam)       ┆ định      ┆           ┆           ┆           ┆ sản phẩm  │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ Tên sản   │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ phẩm…     │
│ 0007051040 ┆ Babycare   ┆ Autoru     ┆ Không xác ┆ null      ┆ 0-6M      ┆ 0.95      ┆ Chi tiết  │
│ 005        ┆            ┆            ┆ định      ┆           ┆           ┆           ┆ sản phẩm  │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ Tên sản   │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ phẩm…     │
│ 0014570000 ┆ Phụ kiện   ┆ Không xác  ┆ Không xác ┆ null      ┆ 0-6M      ┆ 0.95      ┆ Chi tiết  │
│ 020        ┆            ┆ định       ┆ định      ┆           ┆           ┆           ┆ sản phẩm  │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ Tên sản   │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ phẩm…     │
│ 0020020000 ┆ Thực phẩm  ┆ Sài Gòn    ┆ Không xác ┆ null      ┆ 6-12M     ┆ 0.85      ┆ Cháo tươi │
│ 204        ┆ cho bé     ┆ Food       ┆ định      ┆           ┆           ┆           ┆ baby cá   │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ hồi cải … │
│ 0007010000 ┆ Babycare   ┆ Pigeon     ┆ Không xác ┆ null      ┆ 6-12M     ┆ 0.85      ┆ Chi tiết  │
│ 281        ┆            ┆            ┆ định      ┆           ┆           ┆           ┆ sản phẩm  │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ Tên sản   │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ phẩm…     │
│ 3827000000 ┆ Textile    ┆ Animo      ┆ Không xác ┆ null      ┆ 0-6M      ┆ 0.95      ┆ Chi tiết  │
│ 003        ┆            ┆            ┆ định      ┆           ┆           ┆           ┆ sản phẩm  │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ Tên sản   │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ phẩm…     │
└────────────┴────────────┴────────────┴───────────┴───────────┴───────────┴───────────┴───────────┘

=== Mẫu ĐƯỢC ĐIỀN từ WEIGHT ===
shape: (10, 10)
┌──────────┬──────────┬──────────┬──────────┬───────┬───────┬────────┬─────────┬─────────┬─────────┐
│ item_id  ┆ category ┆ brand    ┆ size     ┆ kg_lo ┆ kg_hi ┆ kg_mid ┆ weight_ ┆ weight_ ┆ desc_pr │
│ ---      ┆ _l1      ┆ ---      ┆ ---      ┆ ---   ┆ ---   ┆ ---    ┆ age_buc ┆ age_con ┆ eview   │
│ str      ┆ ---      ┆ str      ┆ str      ┆ f64   ┆ f64   ┆ f64    ┆ ket     ┆ fidence ┆ ---     │
│          ┆ str      ┆          ┆          ┆       ┆       ┆        ┆ ---     ┆ ---     ┆ str     │
│          ┆          ┆          ┆          ┆       ┆       ┆        ┆ str     ┆ f64     ┆         │
╞══════════╪══════════╪══════════╪══════════╪═══════╪═══════╪════════╪═════════╪═════════╪═════════╡
│ 00200100 ┆ Tã       ┆ Merries  ┆ Không    ┆ 4.0   ┆ 8.0   ┆ 6.0    ┆ 6-12M   ┆ 0.7     ┆ ﻿﻿Tã dán  │
│ 00094    ┆          ┆ Nhật     ┆ xác định ┆       ┆       ┆        ┆         ┆         ┆ Merries │
│          ┆          ┆          ┆          ┆       ┆       ┆        ┆         ┆         ┆ size S  │
│          ┆          ┆          ┆          ┆       ┆       ┆        ┆         ┆         ┆ 82 miế… │
│ 00200100 ┆ Tã       ┆ Merries  ┆ Không    ┆ 6.0   ┆ 11.0  ┆ 8.5    ┆ 6-12M   ┆ 0.7     ┆ ﻿﻿﻿Bỉm tã  │
│ 00098    ┆          ┆ Nhật     ┆ xác định ┆       ┆       ┆        ┆         ┆         ┆ quần    │
│          ┆          ┆          ┆          ┆       ┆       ┆        ┆         ┆         ┆ Merries │
│          ┆          ┆          ┆          ┆       ┆       ┆        ┆         ┆         ┆ size M  │
│          ┆          ┆          ┆          ┆       ┆       ┆        ┆         ┆         ┆ …       │
│ 00070400 ┆ Babycare ┆ Carrot   ┆ Không    ┆ null  ┆ null  ┆ 3.5    ┆ 0-6M    ┆ 0.55    ┆ Chi     │
│ 40001    ┆          ┆          ┆ xác định ┆       ┆       ┆        ┆         ┆         ┆ tiết    │
│          ┆          ┆          ┆          ┆       ┆       ┆        ┆         ┆         ┆ sản     │
│          ┆          ┆          ┆          ┆       ┆       ┆        ┆         ┆         ┆ phẩm    │
│          ┆          ┆          ┆          ┆       ┆       ┆        ┆         ┆         ┆ Tên sản │
│          ┆          ┆          ┆          ┆       ┆       ┆        ┆         ┆         ┆ phẩm…   │
│ 00200100 ┆ Tã       ┆ Merries  ┆ Không    ┆ 15.0  ┆ 28.0  ┆ 21.5   ┆ >4Y     ┆ 0.7     ┆ ﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿Tã quần │
│ 00396    ┆          ┆ Nhật     ┆ xác định ┆       ┆       ┆        ┆         ┆         ┆ Merries │
│          ┆          ┆          ┆          ┆       ┆       ┆        ┆         ┆         ┆ size…   │
│ 00200100 ┆ Tã       ┆ Merries  ┆ Không    ┆ 9.0   ┆ 14.0  ┆ 11.5   ┆ 1-2Y    ┆ 0.7     ┆ ﻿﻿Tã dán  │
│ 00096    ┆          ┆ Nhật     ┆ xác định ┆       ┆       ┆        ┆         ┆         ┆ Merries │
│          ┆          ┆          ┆          ┆       ┆       ┆        ┆         ┆         ┆ size L  │
│          ┆          ┆          ┆          ┆       ┆       ┆        ┆         ┆         ┆ 54 miế… │
│ 00200100 ┆ Tã       ┆ Merries  ┆ Không    ┆ 12.0  ┆ 20.0  ┆ 16.0   ┆ 2-4Y    ┆ 0.7     ┆ ﻿﻿﻿Tã dán  │
│ 00097    ┆          ┆ Nhật     ┆ xác định ┆       ┆       ┆        ┆         ┆         ┆ Merries │
│          ┆          ┆          ┆          ┆       ┆       ┆        ┆         ┆         ┆ size XL │
│          ┆          ┆          ┆          ┆       ┆       ┆        ┆         ┆         ┆ 44 m…   │
│ 20740000 ┆ Đồ chơi  ┆ Mesuca   ┆ Không    ┆ 9.0   ┆ 14.0  ┆ 11.5   ┆ 1-2Y    ┆ 0.7     ┆ Chi     │
│ 00004    ┆ & Sách   ┆          ┆ xác định ┆       ┆       ┆        ┆         ┆         ┆ tiết    │
│          ┆          ┆          ┆          ┆       ┆       ┆        ┆         ┆         ┆ sản     │
│          ┆          ┆          ┆          ┆       ┆       ┆        ┆         ┆         ┆ phẩm    │
│          ┆          ┆          ┆          ┆       ┆       ┆        ┆         ┆         ┆ Tên sản │
│          ┆          ┆          ┆          ┆       ┆       ┆        ┆         ┆         ┆ phẩm…   │
│ 00081700 ┆ Đồ chơi  ┆ Winnie   ┆ Không    ┆ 9.0   ┆ 14.0  ┆ 11.5   ┆ 1-2Y    ┆ 0.7     ┆ Chi     │
│ 00052    ┆ & Sách   ┆ (Đài     ┆ xác định ┆       ┆       ┆        ┆         ┆         ┆ tiết    │
│          ┆          ┆ Loan)    ┆          ┆       ┆       ┆        ┆         ┆         ┆ sản     │
│          ┆          ┆          ┆          ┆       ┆       ┆        ┆         ┆         ┆ phẩm    │
│          ┆          ┆          ┆          ┆       ┆       ┆        ┆         ┆         ┆ Tên sản │
│          ┆          ┆          ┆          ┆       ┆       ┆        ┆         ┆         ┆ phẩm…   │
│ 00145200 ┆ Phụ kiện ┆ Con Cưng ┆ Không    ┆ 9.0   ┆ 14.0  ┆ 11.5   ┆ 1-2Y    ┆ 0.7     ┆ Chi     │
│ 40110    ┆          ┆          ┆ xác định ┆       ┆       ┆        ┆         ┆         ┆ tiết    │
│          ┆          ┆          ┆          ┆       ┆       ┆        ┆         ┆         ┆ sản     │
│          ┆          ┆          ┆          ┆       ┆       ┆        ┆         ┆         ┆ phẩm    │
│          ┆          ┆          ┆          ┆       ┆       ┆        ┆         ┆         ┆ Tên sản │
│          ┆          ┆          ┆          ┆       ┆       ┆        ┆         ┆         ┆ phẩm…   │
│ 00060400 ┆ Babycare ┆ Nanny    ┆ Không    ┆ 9.0   ┆ 14.0  ┆ 11.5   ┆ 1-2Y    ┆ 0.7     ┆ Chi     │
│ 00099    ┆          ┆          ┆ xác định ┆       ┆       ┆        ┆         ┆         ┆ tiết    │
│          ┆          ┆          ┆          ┆       ┆       ┆        ┆         ┆         ┆ sản     │
│          ┆          ┆          ┆          ┆       ┆       ┆        ┆         ┆         ┆ phẩm    │
│          ┆          ┆          ┆          ┆       ┆       ┆        ┆         ┆         ┆ Tên sản │
│          ┆          ┆          ┆          ┆       ┆       ┆        ┆         ┆         ┆ phẩm…   │
└──────────┴──────────┴──────────┴──────────┴───────┴───────┴────────┴─────────┴─────────┴─────────┘

=== Mẫu CÓ CẢ primary & description NHƯNG KHÁC NHAU (để so sánh) ===
shape: (10, 8)
┌────────────┬────────────┬────────────┬───────────┬───────────┬───────────┬───────────┬───────────┐
│ item_id    ┆ category_l ┆ brand      ┆ size      ┆ age_bucke ┆ desc_age_ ┆ desc_age_ ┆ desc_prev │
│ ---        ┆ 1          ┆ ---        ┆ ---       ┆ t_primary ┆ bucket    ┆ confidenc ┆ iew       │
│ str        ┆ ---        ┆ str        ┆ str       ┆ _filled   ┆ ---       ┆ e         ┆ ---       │
│            ┆ str        ┆            ┆           ┆ ---       ┆ str       ┆ ---       ┆ str       │
│            ┆            ┆            ┆           ┆ str       ┆           ┆ f64       ┆           │
╞════════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 1735000000 ┆ Hóa mỹ     ┆ Splat      ┆ Không xác ┆ 1-2Y      ┆ 0-6M      ┆ 0.95      ┆ Chi tiết  │
│ 008        ┆ phẩm cho   ┆            ┆ định      ┆           ┆           ┆           ┆ sản phẩm  │
│            ┆ bé         ┆            ┆           ┆           ┆           ┆           ┆ Tên sản   │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ phẩm…     │
│ 3951000000 ┆ Thời trang ┆ Animo      ┆ 6-9M      ┆ 2-4Y      ┆ 6-12M     ┆ 0.85      ┆ Chi tiết  │
│ 115        ┆            ┆            ┆           ┆           ┆           ┆           ┆ sản       │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ phẩmTên   │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ sản       │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ phẩm:…    │
│ 6053000000 ┆ Phụ kiện   ┆ Animo      ┆ 12        ┆ 6-12M     ┆ 1-2Y      ┆ 0.85      ┆ Chi tiết  │
│ 053        ┆            ┆            ┆           ┆           ┆           ┆           ┆ sản       │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ phẩmTên   │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ sản       │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ phẩm:…    │
│ 3953000000 ┆ Thời trang ┆ Animo      ┆ 1Y        ┆ 1-2Y      ┆ >4Y       ┆ 0.85      ┆ Chi tiết  │
│ 671        ┆            ┆            ┆           ┆           ┆           ┆           ┆ sản       │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ phẩmTên   │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ sản       │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ phẩm:…    │
│ 6034000000 ┆ Thời trang ┆ Animo      ┆ 1Y        ┆ 2-4Y      ┆ >4Y       ┆ 0.85      ┆ Chi tiết  │
│ 042        ┆            ┆            ┆           ┆           ┆           ┆           ┆ sản       │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ phẩmTên   │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ sản       │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ phẩm:…    │
│ 0872114830 ┆ Phụ kiện   ┆ CF         ┆ 1-2 tuổi  ┆ 1-2Y      ┆ 2-4Y      ┆ 0.95      ┆ Chi tiết  │
│ 001        ┆            ┆ (ConCung   ┆           ┆           ┆           ┆           ┆ sản phẩm  │
│            ┆            ┆ Fashion)   ┆           ┆           ┆           ┆           ┆ Tên sản   │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ phẩm…     │
│ 4018000000 ┆ Phụ kiện   ┆ Animo      ┆ Không xác ┆ 2-4Y      ┆ >4Y       ┆ 0.85      ┆ Chi tiết  │
│ 028        ┆            ┆            ┆ định      ┆           ┆           ┆           ┆ sản       │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ phẩmTên   │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ sản       │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ phẩm:…    │
│ 0903093830 ┆ Phụ kiện   ┆ CF         ┆ 1-2 tuổi  ┆ 1-2Y      ┆ 0-6M      ┆ 0.95      ┆ Chi tiết  │
│ 001        ┆            ┆ (ConCung   ┆           ┆           ┆           ┆           ┆ sản phẩm  │
│            ┆            ┆ Fashion)   ┆           ┆           ┆           ┆           ┆ Tên sản   │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ phẩm…     │
│ 0026110000 ┆ Babycare   ┆ Gluck      ┆ Không xác ┆ Mẹ        ┆ 1-2Y      ┆ 0.85      ┆ Máy hút   │
│ 001        ┆            ┆            ┆ định      ┆           ┆           ┆           ┆ sữa điện  │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ đôi Gluck │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ GP …      │
│ 0814004480 ┆ Thời trang ┆ CF         ┆ 9-12M     ┆ 6-12M     ┆ 1-2Y      ┆ 0.95      ┆ Bộ thun   │
│ 013        ┆            ┆ (ConCung   ┆           ┆           ┆           ┆           ┆ bé gái    │
│            ┆            ┆ Fashion)   ┆           ┆           ┆           ┆           ┆ ngắn CF   │
│            ┆            ┆            ┆           ┆           ┆           ┆           ┆ G129027…  │
└────────────┴────────────┴────────────┴───────────┴───────────┴───────────┴───────────┴───────────┘

=== Mẫu VẪN THIẾU SAU TẤT CẢ (age_bucket_final is NULL) ===
shape: (10, 9)
┌──────────┬──────────┬──────────┬──────────┬──────────┬──────────┬──────────┬──────────┬──────────┐
│ item_id  ┆ category ┆ brand    ┆ size     ┆ age_grou ┆ age_buck ┆ desc_age ┆ weight_a ┆ desc_pre │
│ ---      ┆ _l1      ┆ ---      ┆ ---      ┆ p        ┆ et_prima ┆ _bucket  ┆ ge_bucke ┆ view     │
│ str      ┆ ---      ┆ str      ┆ str      ┆ ---      ┆ ry_fille ┆ ---      ┆ t        ┆ ---      │
│          ┆ str      ┆          ┆          ┆ str      ┆ d        ┆ str      ┆ ---      ┆ str      │
│          ┆          ┆          ┆          ┆          ┆ ---      ┆          ┆ str      ┆          │
│          ┆          ┆          ┆          ┆          ┆ str      ┆          ┆          ┆          │
╞══════════╪══════════╪══════════╪══════════╪══════════╪══════════╪══════════╪══════════╪══════════╡
│ 00080100 ┆ Đồ chơi  ┆ Thương   ┆ Không    ┆ Không    ┆ null     ┆ null     ┆ null     ┆ Chi tiết │
│ 00015    ┆ & Sách   ┆ hiệu     ┆ xác định ┆ xác định ┆          ┆          ┆          ┆ sản phẩm │
│          ┆          ┆ khác     ┆          ┆          ┆          ┆          ┆          ┆ Tên sản  │
│          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆ phẩm…    │
│ 00200100 ┆ Tã       ┆ Huggies  ┆ Không    ┆ Không    ┆ null     ┆ null     ┆ null     ┆ ﻿﻿﻿Dòng sản │
│ 00150    ┆          ┆ Dry      ┆ xác định ┆ xác định ┆          ┆          ┆          ┆ phẩm tã  │
│          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆ quần     │
│          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆ Huggi…   │
│ 05010300 ┆ Thời     ┆ Không    ┆ Không    ┆ Không    ┆ null     ┆ null     ┆ null     ┆ null     │
│ 00126    ┆ trang    ┆ xác định ┆ xác định ┆ xác định ┆          ┆          ┆          ┆          │
│ 00090510 ┆ Textile  ┆ BabyTop  ┆ Không    ┆ Không    ┆ null     ┆ null     ┆ null     ┆ Chi tiết │
│ 40002    ┆          ┆          ┆ xác định ┆ xác định ┆          ┆          ┆          ┆ sản phẩm │
│          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆ Tên sản  │
│          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆ phẩm…    │
│ 00080200 ┆ Đồ chơi  ┆ Winfun   ┆ Không    ┆ Không    ┆ null     ┆ null     ┆ null     ┆ null     │
│ 00220    ┆ & Sách   ┆          ┆ xác định ┆ xác định ┆          ┆          ┆          ┆          │
│ 00200300 ┆ Tã       ┆ Pampers  ┆ Không    ┆ Không    ┆ null     ┆ null     ┆ null     ┆ Với Tã   │
│ 00001    ┆          ┆          ┆ xác định ┆ xác định ┆          ┆          ┆          ┆ dán      │
│          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆ Pampers  │
│          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆ Nhật Bản │
│          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆ ne…      │
│ 00150200 ┆ Đồ chơi  ┆ NXB Phụ  ┆ Không    ┆ Không    ┆ null     ┆ null     ┆ null     ┆ Chỉ cần  │
│ 00079    ┆ & Sách   ┆ Nữ       ┆ xác định ┆ xác định ┆          ┆          ┆          ┆ mỗi ngày │
│          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆ đọc một  │
│          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆ trang…   │
│ 00072400 ┆ Textile  ┆ Mollis   ┆ Không    ┆ Không    ┆ null     ┆ null     ┆ null     ┆ Chi tiết │
│ 00018    ┆          ┆          ┆ xác định ┆ xác định ┆          ┆          ┆          ┆ sản      │
│          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆ phẩmTên  │
│          ┆          ┆          ┆          ┆          ┆          ┆          ┆          ┆ sản      │

In [47]:

df = item_df
CONF = 0.70  # chỉ tính các fill từ cân nặng có confidence >= 0.70

# Hàng được điền từ cân nặng (sau tất cả bước enrich trước đó)
mask_from_weight = (
    (pl.col("age_source_final") == "from_weight")
    & (pl.col("weight_age_confidence") >= CONF)
)

# 1) Đếm theo category_l1
by_cat = (
    df.group_by("category_l1")
      .agg([
          pl.len().alias("rows"),
          mask_from_weight.sum().alias("filled_from_weight"),
          pl.col("age_bucket_final").is_not_null().sum().alias("age_present_after"),
      ])
      .with_columns([
          (pl.col("filled_from_weight") / pl.col("rows") * 100).round(2).alias("pct_from_weight"),
          (pl.col("age_present_after") / pl.col("rows") * 100).round(2).alias("pct_age_present_after"),
      ])
      .sort(["filled_from_weight", "pct_from_weight"], descending=True)
)

print("=== Filled from weight by category_l1 ===")
print(by_cat)

# 2) Tổng quan toàn bộ tập
overall = df.select([
    pl.len().alias("total_rows"),
    mask_from_weight.sum().alias("filled_from_weight"),
    (pl.col("age_source_final") == "enriched").sum().alias("filled_from_primary_or_desc"),
    pl.col("age_bucket_final").is_not_null().sum().alias("age_present_after"),
]).with_columns([
    (pl.col("filled_from_weight") / pl.col("total_rows") * 100).round(2).alias("pct_from_weight"),
    (pl.col("age_present_after") / pl.col("total_rows") * 100).round(2).alias("pct_age_present_after"),
])

print("\n=== Overall ===")
print(overall)

# 3) (Tuỳ chọn) Tìm nhóm KHÔNG PHẢI 'Tã' nhưng vẫn được điền từ cân nặng (gợi ý dương tính giả)
suspect = (
    df.filter(mask_from_weight & (pl.col("category_l1") != "Tã"))
      .group_by("category_l1")
      .agg([pl.len().alias("rows_from_weight")])
      .sort("rows_from_weight", descending=True)
)
print("\n=== Suspicious (non-'Tã') filled from weight ===")
print(suspect)

# 4) (Tuỳ chọn) Top brand trong nhóm Tã được điền từ cân nặng
by_brand_in_ta = (
    df.filter(mask_from_weight & (pl.col("category_l1") == "Tã"))
      .group_by("brand")
      .agg([pl.len().alias("rows_from_weight")])
      .sort("rows_from_weight", descending=True)
      .head(15)
)
print("\n=== Top brands (category_l1='Tã') filled from weight ===")
print(by_brand_in_ta)

=== Filled from weight by category_l1 ===
shape: (15, 6)
┌────────────────────────┬───────┬────────────────────┬───────────────────┬─────────────────┬───────────────────────┐
│ category_l1            ┆ rows  ┆ filled_from_weight ┆ age_present_after ┆ pct_from_weight ┆ pct_age_present_after │
│ ---                    ┆ ---   ┆ ---                ┆ ---               ┆ ---             ┆ ---                   │
│ str                    ┆ u32   ┆ u32                ┆ u32               ┆ f64             ┆ f64                   │
╞════════════════════════╪═══════╪════════════════════╪═══════════════════╪═════════════════╪═══════════════════════╡
│ Phụ kiện               ┆ 3147  ┆ 758                ┆ 2166              ┆ 24.09           ┆ 68.83                 │
│ Tã                     ┆ 442   ┆ 186                ┆ 331               ┆ 42.08           ┆ 74.89                 │
│ Đồ chơi & Sách         ┆ 2955  ┆ 101                ┆ 2048              ┆ 3.42            ┆ 69.31                 │
│ Babycare               ┆ 1994  ┆ 18                 ┆ 1384              ┆ 0.9             ┆ 69.41                 │
│ Textile                ┆ 555   ┆ 14                 ┆ 359               ┆ 2.52            ┆ 64.68                 │
│ Hóa mỹ phẩm gia đình   ┆ 388   ┆ 5                  ┆ 169               ┆ 1.29            ┆ 43.56                 │
│ Thực phẩm cho bé       ┆ 981   ┆ 3                  ┆ 756               ┆ 0.31            ┆ 77.06                 │
│ Vệ sinh                ┆ 132   ┆ 1                  ┆ 53                ┆ 0.76            ┆ 40.15                 │
│ Hóa mỹ phẩm cho bé     ┆ 346   ┆ 1                  ┆ 278               ┆ 0.29            ┆ 80.35                 │
│ Thực phẩm cho gia đình ┆ 470   ┆ 1                  ┆ 214               ┆ 0.21            ┆ 45.53                 │
│ Thời trang             ┆ 15042 ┆ 0                  ┆ 9886              ┆ 0.0             ┆ 65.72                 │
│ TPCN                   ┆ 270   ┆ 0                  ┆ 210               ┆ 0.0             ┆ 77.78                 │
│ Sữa                    ┆ 437   ┆ 0                  ┆ 397               ┆ 0.0             ┆ 90.85                 │
│ Sữa nước               ┆ 166   ┆ 0                  ┆ 126               ┆ 0.0             ┆ 75.9                  │
│ Gói Hội Viên           ┆ 7     ┆ 0                  ┆ 7                 ┆ 0.0             ┆ 100.0                 │
└────────────────────────┴───────┴────────────────────┴───────────────────┴─────────────────┴───────────────────────┘

=== Overall ===
shape: (1, 6)
┌────────────┬────────────────────┬─────────────────────────────┬───────────────────┬─────────────────┬───────────────────────┐
│ total_rows ┆ filled_from_weight ┆ filled_from_primary_or_desc ┆ age_present_after ┆ pct_from_weight ┆ pct_age_present_after │
│ ---        ┆ ---                ┆ ---                         ┆ ---               ┆ ---             ┆ ---                   │
│ u32        ┆ u32                ┆ u32                         ┆ u32               ┆ f64             ┆ f64                   │
╞════════════╪════════════════════╪═════════════════════════════╪═══════════════════╪═════════════════╪═══════════════════════╡
│ 27332      ┆ 1088               ┆ 17150                       ┆ 18384             ┆ 3.98            ┆ 67.26                 │
└────────────┴────────────────────┴─────────────────────────────┴───────────────────┴─────────────────┴───────────────────────┘

=== Suspicious (non-'Tã') filled from weight ===
shape: (9, 2)
┌────────────────────────┬──────────────────┐
│ category_l1            ┆ rows_from_weight │
│ ---                    ┆ ---              │
│ str                    ┆ u32              │
╞════════════════════════╪══════════════════╡
│ Phụ kiện               ┆ 758              │
│ Đồ chơi & Sách         ┆ 101              │
│ Babycare               ┆ 18               │
│ Textile                ┆ 14               │
│ Hóa mỹ phẩm gia đình   ┆ 5                │
│ Thực phẩm cho bé       ┆ 3                │
│ Thực phẩm cho gia đình ┆ 1                │
│ Hóa mỹ phẩm cho bé     ┆ 1                │
│ Vệ sinh                ┆ 1                │
└────────────────────────┴──────────────────┘

=== Top brands (category_l1='Tã') filled from weight ===
shape: (15, 2)
┌──────────────────────────────┬──────────────────┐
│ brand                        ┆ rows_from_weight │
│ ---                          ┆ ---              │
│ str                          ┆ u32              │
╞══════════════════════════════╪══════════════════╡
│ Bobby                        ┆ 27               │
│ Moony Blue                   ┆ 15               │
│ Molfix                       ┆ 14               │
│ Takato                       ┆ 13               │
│ Merries Nhật                 ┆ 12               │
│ Rascal + Friends             ┆ 10               │
│ Huggies Skincare             ┆ 8                │
│ Merries                      ┆ 7                │
│ Whito                        ┆ 7                │
│ Tã Animo                     ┆ 7                │
│ Huggies Platinum Nature Made ┆ 7                │
│ Pampers                      ┆ 7                │
│ Huggies Dry                  ┆ 5                │
│ Pampers Nhật                 ┆ 4                │
│ Huggies Thin & Soft          ┆ 4                │
└──────────────────────────────┴──────────────────┘

In [48]:
df = item_df

# chỉ lấy các dòng 'Phụ kiện' được điền từ weight
mask = (pl.col("category_l1") == "Phụ kiện") & (pl.col("age_source_final") == "from_weight")

subset = df.filter(mask)

print(f"Số dòng 'Phụ kiện' điền từ weight: {subset.height}")

# các cột muốn xem
cols_want = [
    "item_id", "brand", "size", "age_group",
    "kg_lo", "kg_hi", "kg_mid",
    "weight_age_bucket", "weight_age_confidence",
    "desc_age_bucket", "age_bucket_enriched",
    "age_bucket_final", "age_source_final",
    "description_merged",
]
cols_exist = [c for c in cols_want if c in subset.columns]

# in N dòng với mô tả đầy đủ (không bị rút gọn)
N = 15  # chỉnh nếu muốn
for i, row in enumerate(subset.select(cols_exist).to_dicts()[:N], start=1):
    print("\n" + "="*120)
    print(f"ROW #{i}")
    for k, v in row.items():
        if k == "description_merged":
            print(f"{k}:\n{v}")  # in toàn bộ mô tả
        else:
            print(f"{k}: {v}")

# (tuỳ chọn) lưu toàn bộ để kiểm tra ngoài
subset.select(cols_exist).write_csv("phu_kien_filled_from_weight.csv")
print("\n> Đã lưu: phu_kien_filled_from_weight.csv")

Số dòng 'Phụ kiện' điền từ weight: 760

========================================================================================================================
ROW #1
item_id: 0014520040110
brand: Con Cưng
size: Không xác định
age_group: Không xác định
kg_lo: 9.0
kg_hi: 14.0
kg_mid: 11.5
weight_age_bucket: 1-2Y
weight_age_confidence: 0.7
desc_age_bucket: None
age_bucket_enriched: None
age_bucket_final: 1-2Y
age_source_final: from_weight
description_merged:
Chi tiết sản phẩm                     Tên sản phẩm: Bỉm tã quần Moony size L 44 miếng         Loại sản phẩm: Tã quần         Đối tượng sử dụng: Bé từ 9-14kg         Thương hiệu: Moony         Nguồn gốc: Đến từ Nhật Bản                        Bỉm tã quần Moony size L 44 miếng là tã quần dành cho bé từ 9-14kg của thương hiệu Moony đến từ Nhật Bản. Sản phẩm với khả năng thấm hút vượt trội và giúp bé luôn khô thoáng.                              Bỉm tã quần Moony + Khả năng thấm hút siêu tốc + Giúp bé khô thoáng cả ngày                 Bỉm tã quần Moony sở hữu khả năng thấm hút siêu tốc giúp bé luôn khô ráo và thoải mái. Thiết kế thông minh cùng chất liệu mềm mại mang lại sự dễ chịu cho làn da nhạy cảm của bé.               Bỉm tã quần Moony + Thiết kế thoáng khí + Giúp bé tự do vận động                 Với thiết kế thoáng khí, bỉm tã Moony cho phép không khí lưu thông dễ dàng, giúp bé luôn cảm thấy thoải mái và tự do vận động mà không bị gò bó.               Hướng dẫn chọn size               Size L dành cho bé có cân nặng từ 9-14kg.                        Hướng dẫn sử dụng               Mở bao bì và lấy ra tã.         Đặt tã vào dưới bé, sao cho phần lưng tã ở mức ngang với lưng của bé.         Kéo hai bên tã lên và dán sao cho vừa vặn nhưng không chặt quá.         Kiểm tra lại độ vừa vặn và điều chỉnh nếu cần thiết.                        Hướng dẫn bảo quản               Bảo quản ở nơi khô ráo, thoáng mát.         Tránh ánh sáng trực tiếp và độ ẩm cao.         Không để sản phẩm tiếp xúc với hóa chất mạnh hoặc các chất tẩy rửa.                        Lưu ý               Không sử dụng sản phẩm nếu bao bì bị vỡ.         Kiểm tra thường xuyên để đảm bảo tã không bị tràn.         Nên thay tã cho bé thường xuyên để giữ gìn sức khỏe làn da.                        Thành phần               Vải không dệt         Polymer hút ẩm         Keo dán an toàn         Bột giấy         Chất chống dị ứng         Chất tạo hương tự nhiên         Chất làm mềm         Chất tạo màu an toàn         Chất chống thấm         Nước

========================================================================================================================
ROW #2
item_id: 4002000000007
brand: Animo
size: Không xác định
age_group: Không xác định
kg_lo: 9.0
kg_hi: 14.0
kg_mid: 11.5
weight_age_bucket: 1-2Y
weight_age_confidence: 0.7
desc_age_bucket: None
age_bucket_enriched: None
age_bucket_final: 1-2Y
age_source_final: from_weight
description_merged:
Chi tiết sản phẩm                     Tên sản phẩm: Bỉm tã quần Moony size L 44 miếng         Loại sản phẩm: Tã quần         Đối tượng sử dụng: Bé 9-14kg         Thương hiệu & nguồn gốc: của thương hiệu Moony đến từ Nhật Bản         Điểm nổi bật: Thiết kế thông minh, thấm hút vượt trội                        Bỉm tã quần Moony size L 44 miếng là tã quần dành cho bé 9-14kg của thương hiệu Moony đến từ Nhật Bản. Thiết kế thông minh, thấm hút vượt trội.                        Bỉm tã quần Moony + công nghệ thấm hút nhanh + giúp da bé luôn khô thoáng            Bỉm tã quần Moony tích hợp công nghệ thấm hút nhanh, giúp cho da bé luôn khô thoáng, không bị hăm tã ngay cả khi bé hoạt động cả ngày.            Bỉm tã quần Moony + lớp bông mềm mại + mang lại cảm giác thoải mái cho bé            Lớp bông mềm mại bên trong bỉm tã giúp cho làn da nhạy cảm của bé không bị tổn thương, mang lại cảm giác thoải mái cho bé khi vận động.               Hướng dẫn chọn size               Size S: Dành cho bé từ 4-8kg         Size M: Dành cho bé từ 7-12kg         Size L: Dành cho bé từ 9-14kg         Size XL: Dành cho bé từ 12-18kg                        Hướng dẫn sử dụng               Rửa tay sạch sẽ trước khi thay tã cho bé.         Tháo tã cũ và dùng khăn giấy lau sạch vùng da của bé.         Đặt bỉm tã mới lên dưới bé, đảm bảo đúng vị trí và thun bỉm không bị gập.         Kéo hai bên bỉm lên và dán chắc chắn vào cơ thể bé.         Kiểm tra độ ôm khít và vứt bỉm đã qua sử dụng vào thùng rác.                        Hướng dẫn bảo quản               Bảo quản bỉm nơi khô ráo, thoáng mát.         Không để sản phẩm tiếp xúc với ánh nắng mặt trời hoặc nơi có độ ẩm cao.         Đậy nắp kín sau khi sử dụng để tránh bụi bẩn.                     Lưu ý               Sử dụng sản phẩm ngay sau khi mở bao bì.         Không sử dụng sản phẩm nếu bao bì đã bị rách hoặc niêm phong đã bị hỏng.         Tránh xa tầm tay trẻ em để đảm bảo an toàn.                     Thành phần               Vải không dệt         Bông tự nhiên         Polymer siêu thấm hút         Chất tạo mùi         Chất kháng khuẩn         Nước         PVC         Chất bảo quản

========================================================================================================================
ROW #3
item_id: 4002000000013
brand: Animo
size: Không xác định
age_group: Không xác định
kg_lo: 9.0
kg_hi: 14.0
kg_mid: 11.5
weight_age_bucket: 1-2Y
weight_age_confidence: 0.7
desc_age_bucket: None
age_bucket_enriched: None
age_bucket_final: 1-2Y
age_source_final: from_weight
description_merged:
Chi tiết sản phẩm                     Tên sản phẩm: Bỉm tã quần Moony size L 44 miếng         Hướng dẫn sử dụng: Dùng cho bé từ 9 - 14kg, thích hợp sử dụng ban ngày và ban đêm.         Chất liệu: Cotton và hạt hút ẩm, an toàn cho làn da bé.         Xuất xứ: Nhật Bản.                        Bỉm tã quần Moony size L 44 miếng là bỉm tã quần dành cho bé 9-14kg của thương hiệu Moony đến từ Nhật Bản. Sản phẩm nổi bật với khả năng chống tràn vượt trội và độ mềm mại hoàn hảo cho làn da nhạy cảm của bé.                        Độ thấm hút vượt trội           Bỉm tã quần Moony được thiết kế với công nghệ thấm hút nhanh chóng, giúp giữ cho làn da bé luôn khô ráo, thoáng mát trong thời gian dài.            Chất liệu tự nhiên, an toàn           Sản phẩm được làm từ chất liệu cotton mềm mại, không chứa hóa chất độc hại, an toàn tuyệt đối cho làn da nhạy cảm của bé.            Kiểu dáng thông minh           Thiết kế vừa vặn giúp bỉm tã ôm sát cơ thể bé mà không gây khó chịu, cho bé tự do vận động mà không lo bị hằn.                  Hướng dẫn chọn size               Size S: Dành cho bé dưới 4kg         Size M: Dành cho bé từ 4-9kg         Size L: Dành cho bé từ 9-14kg         Size XL: Dành cho bé từ 14-25kg                     Hướng dẫn sử dụng               Lựa chọn kích thước phù hợp với cân nặng của bé.         Mở băng dán, kéo bỉm ra và cho bé nằm xuống.         Đặt bỉm giữa hai chân bé, kéo lên cao ở hai bên hông.         Hạ băng dán xuống để cố định bỉm.         Kiểm tra độ vừa vặn, không quá chặt hay quá lỏng.                     Hướng dẫn bảo quản               Bảo quản nơi khô ráo, thoáng mát.         Tránh ánh nắng trực tiếp để giữ cho bỉm không bị biến chất.         Không để sản phẩm gần các hóa chất tẩy rửa mạnh.                     Lưu ý               Không nên sử dụng bỉm quá lâu để đảm bảo sức khỏe cho bé.         Thay bỉm cho bé ngay khi biết bé đã đi vệ sinh.         Kiểm tra thường xuyên để phát hiện rò rỉ.                     Thành phần               Chất liệu cotton         Hạt hút ẩm         Chất mền mại         Chất kháng khuẩn

========================================================================================================================
ROW #4
item_id: 0014530040111
brand: Con Cưng
size: Không xác định
age_group: Không xác định
kg_lo: 9.0
kg_hi: 14.0
kg_mid: 11.5
weight_age_bucket: 1-2Y
weight_age_confidence: 0.7
desc_age_bucket: None
age_bucket_enriched: None
age_bucket_final: 1-2Y
age_source_final: from_weight
description_merged:
Chi tiết sản phẩm                     Tên sản phẩm: Bỉm tã quần Moony size L 44 miếng         Loại sản phẩm: tã quần         Đối tượng sử dụng: bé 9-14kg         Thương hiệu: Moony         Nguồn gốc: đến từ Nhật Bản         Điểm nổi bật: Thiết kế thông minh mang lại cảm giác thoải mái cho bé                      Bỉm tã quần Moony size L 44 miếng là tã quần dành cho bé 9-14kg của thương hiệu Moony đến từ Nhật Bản. Thiết kế thông minh mang lại cảm giác thoải mái cho bé.                           Bỉm tã quần Moony + Chất liệu thân thiện + Giúp bảo vệ làn da nhạy cảm                 Bỉm tã quần Moony được làm từ chất liệu mềm mại, không chứa hóa chất độc hại, bảo vệ an toàn cho làn da nhạy cảm của bé.               Bỉm tã quần Moony + Thiết kế 3D siêu thấm + Giữ cho bé luôn khô thoáng           Với thiết kế 3D, bỉm tã quần Moony siêu thấm hút, giữ cho làn da của bé luôn khô thoáng suốt cả ngày dài.            Bỉm tã quần Moony + Khả năng co giãn linh hoạt + Không gây khó chịu cho bé           Với công nghệ co giãn tốt, bỉm không chỉ ôm trọn mà còn tạo cảm giác thoải mái tối đa, không gây khó chịu cho bé trong mọi hoạt động.            Hướng dẫn chọn size               Size S cho bé dưới 6kg         Size M cho bé từ 6-9kg         Size L cho bé từ 9-14kg         Size XL cho bé từ 14-25kg                  Hướng dẫn sử dụng               Tháo bỉm ra khỏi bao bì.         Đặt bỉm dưới mông bé, đảm bảo phần kéo co giãn ở phần lưng.         Gắn bỉm vào các vị trí được chỉ định sao cho chắc chắn.         Kiểm tra độ vừa vặn và giữ cho bé luôn thoải mái.                  Hướng dẫn bảo quản               Bảo quản nơi khô ráo, tránh ẩm ướt.         Để xa tầm tay trẻ em.         Nguyên bao bì nên không bị rách, tránh mất chất lượng sản phẩm.                  Lưu ý               Kiểm tra hạn sử dụng trước khi dùng.         Không sử dụng với trẻ em bị dị ứng chất liệu.                  Thành phần               Chất liệu cotton         Chất liệu polyester         Chất liệu thun         Kem chống hăm         Chất liệu dệt xốp         Phân tử hút ẩm         Hương liệu tự nhiên         Chất chống tĩnh điện         Chất liệu chống tràn         Chất làm mềm

========================================================================================================================
ROW #5
item_id: 4014000000013
brand: Animo
size: Không xác định
age_group: Không xác định
kg_lo: 9.0
kg_hi: 14.0
kg_mid: 11.5
weight_age_bucket: 1-2Y
weight_age_confidence: 0.7
desc_age_bucket: None
age_bucket_enriched: None
age_bucket_final: 1-2Y
age_source_final: from_weight
description_merged:
Chi tiết sản phẩm                     Tên sản phẩm: Bỉm tã quần Moony size L 44 miếng         Loại sản phẩm: Tã quần         Đối tượng sử dụng: bé 9-14kg         Thương hiệu: của thương hiệu Moony đến từ Nhật Bản         Điểm nổi bật: Siêu thấm hút nhanh chóng, giúp bé khô thoáng suốt đêm                        Bỉm tã quần Moony size L 44 miếng là tã quần dành cho bé 9-14kg của thương hiệu Moony đến từ Nhật Bản. Siêu thấm hút nhanh chóng, giúp bé khô thoáng suốt đêm.                        Bỉm tã quần Moony size L + Siêu thấm hút + Giúp bé khô thoáng suốt đêm           Với khả năng thấm hút vượt trội, Bỉm tã quần Moony giúp giữ cho làn da bé luôn khô ráo và thoải mái, đặc biệt là trong những giấc ngủ dài ban đêm.            Bỉm tã quần Moony size L + Thiết kế ôm sát + Đem lại cảm giác thoải mái cho bé           Thiết kế ôm sát và dễ dàng điều chỉnh mang đến sự thoải mái tối đa cho bé, giúp bé dễ dàng vận động mà không lo tràn.               Hướng dẫn chọn size      Đối với Bỉm tã quần Moony, size L phù hợp với những bé có cân nặng từ 9-14kg. Ba mẹ nên kiểm tra cân nặng của bé để chọn được size phù hợp nhất.               Hướng dẫn sử dụng               Mở bỉm ra và đặt vào vùng mông của bé.         Kéo phần tã lên và điều chỉnh cho vừa vặn, đảm bảo không bị xô lệch.         Kiểm tra xem có chỗ nào bị bó sát không để đảm bảo thoải mái cho bé.         Khi tã ướt, thay tã cho bé ngay để bảo vệ làn da.                     Hướng dẫn bảo quản               Bảo quản ở nơi khô ráo, sạch sẽ.         Tránh ánh nắng trực tiếp và nhiệt độ cao.         Đóng kín bao bì sau khi mở để tránh bụi bẩn.                     Lưu ý               Không tái sử dụng bỉm sau khi đã sử dụng.         Kiểm tra hạn sử dụng trước khi dùng.         Không để bỉm tiếp xúc với hóa chất độc hại.                     Thành phần               Pulppaper         Polymer siêu thấm         Tampon hoc dai         Chất chống thấm nước         Chất liệu vải không dệt         Chất tạo độ mềm mịn         Sodium Polyacrylate         Chất làm mềm         Chất bảo quản         Dye

========================================================================================================================
ROW #6
item_id: 0014520130022
brand: Con Cưng
size: Không xác định
age_group: Không xác định
kg_lo: 9.0
kg_hi: 14.0
kg_mid: 11.5
weight_age_bucket: 1-2Y
weight_age_confidence: 0.7
desc_age_bucket: None
age_bucket_enriched: None
age_bucket_final: 1-2Y
age_source_final: from_weight
description_merged:
Chi tiết sản phẩm                     Tên sản phẩm: Bỉm tã quần Moony size L 44 miếng         Loại sản phẩm: Bỉm tã quần         Đối tượng sử dụng: bé 9-14kg         Thương hiệu: Moony, đến từ Nhật Bản         Điểm nổi bật: Thiết kế thông minh, thấm hút tốt, giữ cho bé khô thoáng                        Bỉm tã quần Moony size L 44 miếng là bỉm tã quần dành cho bé 9-14kg của thương hiệu Moony, đến từ Nhật Bản. Với thiết kế thông minh, sản phẩm mang lại khả năng thấm hút tốt, giữ cho bé luôn khô thoáng.                              Bỉm tã quần Moony - Thiết kế siêu mỏng - Giúp bé thoải mái trong mỗi chuyển động                  Bỉm tã quần Moony với thiết kế siêu mỏng, giúp bé thoải mái trong mọi hoạt động mà không lo bị cộm cấn.            Bỉm tã quần Moony - Khả năng thấm hút mạnh mẽ - Giữ cho bé khô ráo suốt đêm                  Với khả năng thấm hút mạnh mẽ, bỉm tã quần Moony giúp giữ cho bé khô ráo suốt đêm, mang đến giấc ngủ ngon và thoải mái.               Hướng dẫn chọn size      Để chọn size phù hợp cho bé, bố mẹ nên cân nhắc trọng lượng thực tế của bé. Dưới đây là bảng size tham khảo:               Tã size S: cho bé dưới 4kg         Tã size M: cho bé từ 4-9kg         Tã size L: cho bé từ 9-14kg         Tã size XL: cho bé từ 14-20kg                     Hướng dẫn sử dụng               Chọn size phù hợp với cân nặng của bé.         Mở bung phần dán bên ngoài của bỉm.         Đặt bỉm vào vị trí dưới mông của bé.         Kéo hai bên bỉm lên, dán chặt lại.         Kiểm tra độ vừa vặn và thoải mái cho bé.                     Hướng dẫn bảo quản               Bảo quản nơi khô ráo, thoáng mát.         Tránh ánh nắng mặt trời trực tiếp.         Không để sản phẩm tiếp xúc với hóa chất.                     Lưu ý               Chọn size bỉm đúng với trọng lượng của bé để tránh tình trạng bị hở hoặc chật.         Không sử dụng sản phẩm đã hết hạn sử dụng.         Thường xuyên kiểm tra tình trạng bỉm sau khi sử dụng để đảm bảo an toàn cho bé.                     Thành phần               Polymer thấm hút         Không chứa latex         Chất liệu mềm mại         Chất tạo gel         Chất khử mùi         Hương liệu tự nhiên         Bảo vệ da         Chất chống thấm         Chất kết dính an toàn         Chất đàn hồi

========================================================================================================================
ROW #7
item_id: 0014521040067
brand: CF (ConCung Fashion)
size: Không xác định
age_group: Không xác định
kg_lo: 9.0
kg_hi: 14.0
kg_mid: 11.5
weight_age_bucket: 1-2Y
weight_age_confidence: 0.7
desc_age_bucket: None
age_bucket_enriched: None
age_bucket_final: 1-2Y
age_source_final: from_weight
description_merged:
Chi tiết sản phẩm                     Tên sản phẩm: Bỉm tã quần Moony size L 44 miếng         Loại sản phẩm: tã quần         Đối tượng sử dụng: bé 9-14kg         Thương hiệu: Moony         Nguồn gốc: đến từ Nhật Bản         Điểm nổi bật: Thiết kế thông minh giúp bé thoải mái và dễ chịu.                        **Bỉm tã quần Moony size L 44 miếng** là tã quần dành cho bé 9-14kg của thương hiệu Moony đến từ Nhật Bản. Thiết kế thông minh giúp bé thoải mái và dễ chịu.                              Chất liệu mềm mại, an toàn cho làn da                 Chất liệu bỉm tã quần Moony được làm từ sợi cotton tự nhiên, giúp bảo vệ làn da nhạy cảm của bé. Đảm bảo không gây kích ứng da, cho bé thoải mái suốt cả ngày.               Thiết kế ôm sát, chống tràn hiệu quả                 Với thiết kế ôm sát và khả năng chống tràn tối ưu, bỉm tã quần Moony giúp bé hoạt động tự do mà không lo bị ướt, tạo cảm giác an toàn cho cả mẹ và bé.               Thông thoáng và hút ẩm tốt                 Hệ thống thông thoáng của bỉm giúp khí ẩm thoát ra dễ dàng, giữ cho làn da của bé luôn khô thoáng và dễ chịu.               Hướng dẫn chọn size               Size L dành cho bé nặng từ 9-14kg.         Chọn đúng size để đảm bảo sự thoải mái và hiệu quả khi sử dụng.                     Hướng dẫn sử dụng               Đặt bỉm dưới mông bé.         Kéo bỉm lên và điều chỉnh cho ôm vừa vặn.         Đảm bảo phần lưng bỉm ở trên mông bé để tránh bị tràn.         Khi thay bỉm, gói lại và vứt bỏ đúng cách.                     Hướng dẫn bảo quản               Để sản phẩm ở nơi khô ráo, thoáng mát.         Tránh ánh nắng trực tiếp và nơi ẩm ướt.         Đóng kín bao bì sau khi sử dụng để đảm bảo độ an toàn.                     Lưu ý               Không sử dụng bỉm khi sản phẩm đã hết hạn.         Kiểm tra bỉm trước khi sử dụng để đảm bảo không bị hư hỏng.                     Thành phần               Sợi cotton tự nhiên         Polymers hút ẩm         Chất chống dị ứng         Màu thực phẩm an toàn

========================================================================================================================
ROW #8
item_id: 7206000000004
brand: Animo
size: Không xác định
age_group: Không xác định
kg_lo: 9.0
kg_hi: 14.0
kg_mid: 11.5
weight_age_bucket: 1-2Y
weight_age_confidence: 0.7
desc_age_bucket: None
age_bucket_enriched: None
age_bucket_final: 1-2Y
age_source_final: from_weight
description_merged:

In [50]:
item_df.head(5)

shape: (5, 66)
┌───────┬───────────────┬───────────────┬────────────────┬────────────────┬───┬───────────────────┬───────────────────────┬───────────────────┬──────────────────┬──────────────────┐
│ p_id  ┆ item_id       ┆ price         ┆ category_l1_id ┆ category_l1    ┆ … ┆ weight_age_bucket ┆ weight_age_confidence ┆ weight_age_source ┆ age_bucket_final ┆ age_source_final │
│ ---   ┆ ---           ┆ ---           ┆ ---            ┆ ---            ┆   ┆ ---               ┆ ---                   ┆ ---               ┆ ---              ┆ ---              │
│ i32   ┆ str           ┆ decimal[38,4] ┆ i32            ┆ str            ┆   ┆ str               ┆ f64                   ┆ str               ┆ str              ┆ str              │
╞═══════╪═══════════════╪═══════════════╪════════════════╪════════════════╪═══╪═══════════════════╪═══════════════════════╪═══════════════════╪══════════════════╪══════════════════╡
│ 17065 ┆ 0502020000004 ┆ 99000.0000    ┆ 1              ┆ Babycare       ┆ … ┆ null              ┆ null                  ┆ null              ┆ 0-6M             ┆ enriched         │
│ 72370 ┆ 0010290040150 ┆ 69000.0000    ┆ 3292           ┆ Thời trang     ┆ … ┆ null              ┆ null                  ┆ null              ┆ 2-4Y             ┆ enriched         │
│ 31154 ┆ 0008010000015 ┆ 45000.0000    ┆ 351            ┆ Đồ chơi & Sách ┆ … ┆ null              ┆ null                  ┆ null              ┆ null             ┆ missing          │
│ 46123 ┆ 0020010000094 ┆ 401000.0000   ┆ 2222           ┆ Tã             ┆ … ┆ 6-12M             ┆ 0.7                   ┆ weight_range      ┆ 6-12M            ┆ from_weight      │
│ 46127 ┆ 0020010000098 ┆ 401000.0000   ┆ 2222           ┆ Tã             ┆ … ┆ 6-12M             ┆ 0.7                   ┆ weight_range      ┆ 6-12M            ┆ from_weight      │
└───────┴───────────────┴───────────────┴────────────────┴────────────────┴───┴───────────────────┴───────────────────────┴───────────────────┴──────────────────┴──────────────────┘

## Xóa các cột trung gian để cho bước xử lý tiếp theo

In [51]:
# Xoá tất cả cột trong danh sách trừ "description_merged" và "age_bucket_final"
cols = [
    "age_bucket_primary","description_merged","description_source",
    "size_lo_m","size_hi_m","size_age_bucket","age_fill_source","age_llm_conf",
    "age_bucket_primary_filled","size_lo_m_right","size_hi_m_right","size_age_bucket_right",
    "age_fill_source_right","age_llm_conf_right","_desc_norm","desc_age_month_lo",
    "desc_age_month_hi","desc_age_month_mid","desc_age_bucket","desc_age_confidence",
    "age_bucket_enriched","age_source_enriched","kg_lo","kg_hi","kg_single","kg_mid",
    "weight_age_bucket_raw","weight_age_bucket","weight_age_confidence","weight_age_source",
    "age_bucket_final","age_source_final"
]

keep = {"description_merged", "age_bucket_final"}
drop_cols = [c for c in cols if c not in keep and c in item_df.columns]

item_df_clean = item_df.drop(drop_cols)

print(f"Dropped {len(drop_cols)} cols. Remaining cols: {len(item_df_clean.columns)}")

Dropped 30 cols. Remaining cols: 36

In [52]:
from pathlib import Path

df = item_df_clean  # dùng DF đã dọn ở cell trước

# 1) Backup 2 cột gốc (nếu tồn tại)
backup_cols = [c for c in ["description", "description_new"] if c in df.columns]
if backup_cols:
    out_path = Path("backup_descriptions.parquet")
    df.select(["item_id"] + backup_cols if "item_id" in df.columns else backup_cols).write_parquet(out_path.as_posix())
    print(f"Đã backup {backup_cols} -> {out_path}")

# 2) Xoá khỏi DF làm việc
drop_cols = [c for c in ["description", "description_new"] if c in df.columns]
item_df_clean = df.drop(drop_cols)

print(f"Đã xoá {drop_cols}. Số cột còn lại: {len(item_df_clean.columns)}")

Đã backup ['description', 'description_new'] -> backup_descriptions.parquet
Đã xoá ['description', 'description_new']. Số cột còn lại: 34

- nháp

In [20]:
import polars as pl
import re, json

# ---------- Helpers: normalize & parse with debug ----------
NULLISH = {"", " ", "  ", "không xác định", "khong xac dinh", "unknown", "null", "none", "nan", "na", "n/a"}

def _norm_age(s: str) -> str:
    s = s.lower().strip()
    s = (s.replace("tháng","m").replace("thang","m")
           .replace("tuổi","y").replace("tuoi","y")
           .replace("từ","tu").replace("trên","tren")
           .replace("–","-").replace("—","-").replace("−","-")
           .replace(" ", ""))
    # gom newborn
    s = (s.replace("sơsinh","nb")
           .replace("sosinh","nb")
           .replace("newborn","nb"))
    # toddler 'T' => year
    s = re.sub(r"(?<=\d)t\b", "y", s)
    return s

def _parse_age_to_months_debug(val: str | None):
    """
    Trả dict: {lo, hi, norm, reason}
    reason ∈ {nullish, adult, newborn, range, single, threshold, tokens_scan, list_scan, unparsed}
    """
    if val is None:
        return {"lo": None, "hi": None, "norm": None, "reason": "nullish"}

    raw = str(val).strip()
    if raw.lower() in NULLISH or raw == "":
        return {"lo": None, "hi": None, "norm": None, "reason": "nullish"}

    # adult product
    if raw.lower() in {"mẹ", "me"}:
        return {"lo": None, "hi": None, "norm": _norm_age(raw), "reason": "adult"}

    # list-string JSON: ["Từ 0M","Từ 3M",...]
    if raw.lstrip().startswith("["):
        try:
            items = json.loads(raw)
            lows, highs = [], []
            for it in items:
                r = _parse_age_to_months_debug(it)
                if r["lo"] is not None:
                    lows.append(r["lo"])
                if r["hi"] is not None:
                    highs.append(r["hi"])
            if lows or highs:
                lo = min(lows) if lows else None
                hi = max(highs) if highs else None
                return {"lo": lo, "hi": hi, "norm": _norm_age(raw), "reason": "list_scan"}
            else:
                return {"lo": None, "hi": None, "norm": _norm_age(raw), "reason": "list_scan"}
        except Exception:
            # sẽ rơi xuống dưới và quét token
            pass

    s = _norm_age(raw)

    # newborn
    if s == "nb":
        return {"lo": 0, "hi": 3, "norm": s, "reason": "newborn"}

    # 1) range với đơn vị ở hai đầu (cho phép trộn m/y)
    m = re.fullmatch(r"(\d+)(m|y)-(\d+)(m|y)", s)
    if m:
        a, u1, b, u2 = m.groups()
        a = int(a) * (1 if u1 == "m" else 12)
        b = int(b) * (1 if u2 == "m" else 12)
        if a > b: a, b = b, a
        return {"lo": a, "hi": b, "norm": s, "reason": "range"}

    # 2) single
    m = re.fullmatch(r"(\d+)(m|y)", s)
    if m:
        a, u = m.groups()
        a = int(a) * (1 if u == "m" else 12)
        return {"lo": a, "hi": a, "norm": s, "reason": "single"}

    # 3) threshold 'tu'/'tren'
    m = re.fullmatch(r"(tu|tren)(\d+)(m|y)", s)
    if m:
        v = int(m.group(2)) * (1 if m.group(3) == "m" else 12)
        return {"lo": v, "hi": None, "norm": s, "reason": "threshold"}

    # 4) quét token tự do trong chuỗi (fallback)
    toks = re.findall(r"(\d+)(m|y)", s)
    if toks:
        vals = [int(n) * (1 if u == "m" else 12) for (n, u) in toks]
        lo = min(vals) if vals else None
        hi = max(vals) if len(vals) > 1 else (vals[0] if vals else None)
        return {"lo": lo, "hi": hi, "norm": s, "reason": "tokens_scan"}

    # không parse được
    return {"lo": None, "hi": None, "norm": s, "reason": "unparsed"}

# ---------- Build debug table ----------
dbg = (
    item_df
    .select([
        pl.col("category_l1"),
        pl.col("age_group"),
        pl.col("age_group").map_elements(
            _parse_age_to_months_debug,
            return_dtype=pl.Struct([
                pl.Field("lo", pl.Int64),
                pl.Field("hi", pl.Int64),
                pl.Field("norm", pl.Utf8),
                pl.Field("reason", pl.Utf8),
            ])
        ).alias("p")
    ])
    .with_columns([
        pl.col("p").struct.field("lo").alias("age_lo_m"),
        pl.col("p").struct.field("hi").alias("age_hi_m"),
        pl.col("p").struct.field("norm").alias("age_norm"),
        pl.col("p").struct.field("reason").alias("parse_reason"),
    ])
    .with_columns(
        (pl.col("age_lo_m").is_null() & pl.col("age_hi_m").is_null()).alias("parse_fail")
    )
)

# ---------- 1) Tỷ lệ fail tổng quan ----------
summary = dbg.select([
    pl.len().alias("rows"),
    pl.col("parse_fail").cast(pl.Int64).sum().alias("fail_rows"),
    (pl.col("parse_fail").cast(pl.Int64).mean()*100).round(2).alias("fail_rate_%"),
    pl.col("parse_reason").filter(pl.col("parse_fail")).value_counts().alias("fail_by_reason")
])
print(summary)

# ---------- 2) TOP 20 giá trị không parse (overall) ----------
top20_fail = (
    dbg.filter(pl.col("parse_fail"))
       .group_by(["age_group","age_norm","parse_reason"])
       .agg(pl.len().alias("n"),
            pl.col("category_l1").value_counts().alias("cats"))
       .sort("n", descending=True)
       .head(20)
)
print("\nTOP 20 age_group không parse:")
print(top20_fail)

# ---------- 3) TOP 10 theo từng category_l1 ----------
top10_per_cat = (
    dbg.filter(pl.col("parse_fail"))
       .group_by(["category_l1","age_group","age_norm","parse_reason"])
       .agg(pl.len().alias("n"))
       .sort(["category_l1","n"], descending=[False, True])
       .group_by("category_l1").head(10)
)
print("\nTOP 10 không parse theo category_l1:")
print(top10_per_cat)

shape: (2, 4)
┌───────┬───────────┬─────────────┬───────────────────┐
│ rows  ┆ fail_rows ┆ fail_rate_% ┆ fail_by_reason    │
│ ---   ┆ ---       ┆ ---         ┆ ---               │
│ u32   ┆ i64       ┆ f64         ┆ struct[2]         │
╞═══════╪═══════════╪═════════════╪═══════════════════╡
│ 27332 ┆ 15962     ┆ 58.4        ┆ {"nullish",15812} │
│ 27332 ┆ 15962     ┆ 58.4        ┆ {"adult",150}     │
└───────┴───────────┴─────────────┴───────────────────┘

TOP 20 age_group không parse:
shape: (2, 5)
┌────────────────┬──────────┬──────────────┬───────┬─────────────────────────────────┐
│ age_group      ┆ age_norm ┆ parse_reason ┆ n     ┆ cats                            │
│ ---            ┆ ---      ┆ ---          ┆ ---   ┆ ---                             │
│ str            ┆ str      ┆ str          ┆ u32   ┆ list[struct[2]]                 │
╞════════════════╪══════════╪══════════════╪═══════╪═════════════════════════════════╡
│ Không xác định ┆ null     ┆ nullish      ┆ 15812 ┆ [{"Gói Hội Viên",7}, {"Textile… │
│ Mẹ             ┆ mẹ       ┆ adult        ┆ 150   ┆ [{"Sữa",7}, {"Thời trang",103}… │
└────────────────┴──────────┴──────────────┴───────┴─────────────────────────────────┘

TOP 10 không parse theo category_l1:
shape: (20, 5)
┌────────────────────────┬────────────────┬──────────┬──────────────┬──────┐
│ category_l1            ┆ age_group      ┆ age_norm ┆ parse_reason ┆ n    │
│ ---                    ┆ ---            ┆ ---      ┆ ---          ┆ ---  │
│ str                    ┆ str            ┆ str      ┆ str          ┆ u32  │
╞════════════════════════╪════════════════╪══════════╪══════════════╪══════╡
│ Babycare               ┆ Không xác định ┆ null     ┆ nullish      ┆ 1667 │
│ Babycare               ┆ Mẹ             ┆ mẹ       ┆ adult        ┆ 37   │
│ Gói Hội Viên           ┆ Không xác định ┆ null     ┆ nullish      ┆ 7    │
│ Hóa mỹ phẩm cho bé     ┆ Không xác định ┆ null     ┆ nullish      ┆ 257  │
│ Hóa mỹ phẩm gia đình   ┆ Không xác định ┆ null     ┆ nullish      ┆ 379  │
│ …                      ┆ …              ┆ …        ┆ …            ┆ …    │
│ Thực phẩm cho gia đình ┆ Không xác định ┆ null     ┆ nullish      ┆ 455  │
│ Thực phẩm cho gia đình ┆ Mẹ             ┆ mẹ       ┆ adult        ┆ 1    │
│ Tã                     ┆ Không xác định ┆ null     ┆ nullish      ┆ 433  │
│ Vệ sinh                ┆ Không xác định ┆ null     ┆ nullish      ┆ 131  │
│ Đồ chơi & Sách         ┆ Không xác định ┆ null     ┆ nullish      ┆ 2276 │
└────────────────────────┴────────────────┴──────────┴──────────────┴──────┘

In [ ]:
item_df.columns

In [44]:
item_df.head(10)

shape: (10, 66)
┌─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┬─────┐
│ p_i ┆ ite ┆ pri ┆ cat ┆ cat ┆ cat ┆ cat ┆ cat ┆ cat ┆ cat ┆ cat ┆ des ┆ bra ┆ man ┆ cre ┆ is_ ┆ cre ┆ upd ┆ syn ┆ las ┆ syn ┆ ima ┆ gen ┆ age ┆ ite ┆ gp  ┆ wei ┆ col ┆ siz ┆ ori ┆ vol ┆ mat ┆ sal ┆ des ┆ age ┆ des ┆ des ┆ siz ┆ siz ┆ siz ┆ age ┆ age ┆ age ┆ siz ┆ siz ┆ siz ┆ age ┆ age ┆ _de ┆ des ┆ des ┆ des ┆ des ┆ des ┆ age ┆ age ┆ kg_ ┆ kg_ ┆ kg_ ┆ kg_ ┆ wei ┆ wei ┆ wei ┆ wei ┆ age ┆ age │
│ d   ┆ m_i ┆ ce  ┆ ego ┆ ego ┆ ego ┆ ego ┆ ego ┆ ego ┆ ego ┆ ego ┆ cri ┆ nd  ┆ ufa ┆ ati ┆ del ┆ ate ┆ ate ┆ c_s ┆ t_s ┆ c_e ┆ ge_ ┆ der ┆ _gr ┆ m_t ┆ --- ┆ ght ┆ or  ┆ e   ┆ gin ┆ ume ┆ eri ┆ e_s ┆ cri ┆ _bu ┆ cri ┆ cri ┆ e_l ┆ e_h ┆ e_a ┆ _fi ┆ _ll ┆ _bu ┆ e_l ┆ e_h ┆ e_a ┆ _fi ┆ _ll ┆ sc_ ┆ c_a ┆ c_a ┆ c_a ┆ c_a ┆ c_a ┆ _bu ┆ _so ┆ lo  ┆ hi  ┆ sin ┆ mid ┆ ght ┆ ght ┆ ght ┆ ght ┆ _bu ┆ _so │
│ --- ┆ d   ┆ --- ┆ ry_ ┆ ry_ ┆ ry_ ┆ ry_ ┆ ry_ ┆ ry_ ┆ ry_ ┆ ry  ┆ pti ┆ --- ┆ ctu ┆ on_ ┆ ete ┆ d_d ┆ d_d ┆ tat ┆ ync ┆ rro ┆ url ┆ _ta ┆ oup ┆ ype ┆ dec ┆ --- ┆ --- ┆ --- ┆ --- ┆ --- ┆ al  ┆ tat ┆ pti ┆ cke ┆ pti ┆ pti ┆ o_m ┆ i_m ┆ ge_ ┆ ll_ ┆ m_c ┆ cke ┆ o_m ┆ i_m ┆ ge_ ┆ ll_ ┆ m_c ┆ nor ┆ ge_ ┆ ge_ ┆ ge_ ┆ ge_ ┆ ge_ ┆ cke ┆ urc ┆ --- ┆ --- ┆ gle ┆ --- ┆ _ag ┆ _ag ┆ _ag ┆ _ag ┆ cke ┆ urc │
│ i32 ┆ --- ┆ dec ┆ l1_ ┆ l1  ┆ l2_ ┆ l2  ┆ l3_ ┆ l3  ┆ id  ┆ --- ┆ on  ┆ str ┆ rer ┆ tim ┆ d   ┆ ate ┆ ate ┆ us_ ┆ _da ┆ r_m ┆ --- ┆ rge ┆ --- ┆ --- ┆ ima ┆ f32 ┆ str ┆ str ┆ str ┆ str ┆ --- ┆ us  ┆ on_ ┆ t_p ┆ on_ ┆ on_ ┆ --- ┆ --- ┆ buc ┆ sou ┆ onf ┆ t_p ┆ _ri ┆ _ri ┆ buc ┆ sou ┆ onf ┆ m   ┆ mon ┆ mon ┆ mon ┆ buc ┆ con ┆ t_e ┆ e_e ┆ f64 ┆ f64 ┆ --- ┆ f64 ┆ e_b ┆ e_b ┆ e_c ┆ e_s ┆ t_f ┆ e_f │
│     ┆ str ┆ ima ┆ id  ┆ --- ┆ id  ┆ --- ┆ id  ┆ --- ┆ --- ┆ str ┆ --- ┆     ┆ --- ┆ est ┆ --- ┆ --- ┆ --- ┆ id  ┆ te  ┆ ess ┆ str ┆ t   ┆ str ┆ str ┆ l[3 ┆     ┆     ┆     ┆     ┆     ┆ str ┆ --- ┆ new ┆ rim ┆ mer ┆ sou ┆ i64 ┆ i64 ┆ ket ┆ rce ┆ --- ┆ rim ┆ ght ┆ ght ┆ ket ┆ rce ┆ _ri ┆ --- ┆ th_ ┆ th_ ┆ th_ ┆ ket ┆ fid ┆ nri ┆ nri ┆     ┆     ┆ f64 ┆     ┆ uck ┆ uck ┆ onf ┆ our ┆ ina ┆ ina │
│     ┆     ┆ l[3 ┆ --- ┆ str ┆ --- ┆ str ┆ --- ┆ str ┆ i32 ┆     ┆ str ┆     ┆ str ┆ amp ┆ boo ┆ dat ┆ dat ┆ --- ┆ --- ┆ age ┆     ┆ --- ┆     ┆     ┆ 8,4 ┆     ┆     ┆     ┆     ┆     ┆     ┆ i32 ┆ --- ┆ ary ┆ ged ┆ rce ┆     ┆     ┆ --- ┆ --- ┆ f64 ┆ ary ┆ --- ┆ --- ┆ _ri ┆ _ri ┆ ght ┆ str ┆ lo  ┆ hi  ┆ mid ┆ --- ┆ enc ┆ che ┆ che ┆     ┆     ┆     ┆     ┆ et_ ┆ et  ┆ ide ┆ ce  ┆ l   ┆ l   │
│     ┆     ┆ 8,4 ┆ i32 ┆     ┆ i32 ┆     ┆ i32 ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆ l   ┆ eti ┆ eti ┆ i32 ┆ dat ┆ --- ┆     ┆ str ┆     ┆     ┆ ]   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ --- ┆ --- ┆ --- ┆     ┆     ┆ str ┆ str ┆     ┆ _fi ┆ i64 ┆ i64 ┆ ght ┆ ght ┆ --- ┆     ┆ --- ┆ --- ┆ --- ┆ str ┆ e   ┆ d   ┆ d   ┆     ┆     ┆     ┆     ┆ raw ┆ --- ┆ nce ┆ --- ┆ --- ┆ --- │
│     ┆     ┆ ]   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i64 ┆     ┆ me[ ┆ me[ ┆     ┆ eti ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆ lle ┆     ┆     ┆ --- ┆ --- ┆ f64 ┆     ┆ i64 ┆ i64 ┆ f64 ┆     ┆ --- ┆ --- ┆ --- ┆     ┆     ┆     ┆     ┆ --- ┆ str ┆ --- ┆ str ┆ str ┆ str │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ μs] ┆ μs] ┆     ┆ me[ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ d   ┆     ┆     ┆ str ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆ f64 ┆ str ┆ str ┆     ┆     ┆     ┆     ┆ str ┆     ┆ f64 ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ μs] ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ --- ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ str ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
╞═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╪═════╡
│ 170 ┆ 050 ┆ 990 ┆ 1   ┆ Bab ┆ 35  ┆ Bìn ┆ 705 ┆ Núm ┆ 705 ┆ Núm ┆ Khô ┆ Dr. ┆ Khô ┆ 133 ┆ fal ┆ 201 ┆ 202 ┆ 2   ┆ 202 ┆ nul ┆ Khô ┆ Khô ┆ Khô ┆ Khô ┆ 368 ┆ nul ┆ Khô ┆ Khô ┆ Khô ┆ Khô ┆ Khô ┆ 0   ┆ Chi ┆ nul ┆ Chi ┆ new ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ chi ┆ 1   ┆ 2   ┆ 1.5 ┆ 0-6 ┆ 0.9 ┆ 0-6 ┆ fro ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ 0-6 ┆ enr │
│ 65  ┆ 202 ┆ 00. ┆     ┆ yca ┆     ┆ h   ┆ 0   ┆ ty  ┆ 8   ┆ ty  ┆ ng  ┆ Bro ┆ ng  ┆ 353 ┆ se  ┆ 2-0 ┆ 5-0 ┆     ┆ 5-0 ┆ l   ┆ ng  ┆ ng  ┆ ng  ┆ ng  ┆ 28. ┆ l   ┆ ng  ┆ ng  ┆ ng  ┆ ng  ┆ ng  ┆     ┆ tiế ┆ l   ┆ tiế ┆     ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ tiế ┆     ┆     ┆     ┆ M   ┆ 5   ┆ M   ┆ m_d ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ M   ┆ ich │
│     ┆ 000 ┆ 000 ┆     ┆ re  ┆     ┆ sữa ┆     ┆     ┆     ┆ Dr  ┆ xác ┆ wn' ┆ xác ┆ 154 ┆     ┆ 4-0 ┆ 8-1 ┆     ┆ 7-1 ┆     ┆ xác ┆ xác ┆ xác ┆ xác ┆ 000 ┆     ┆ xác ┆ xác ┆ xác ┆ xác ┆ xác ┆     ┆ t   ┆     ┆ t   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ t   ┆     ┆     ┆     ┆     ┆     ┆     ┆ esc ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ed  │
│     ┆ 000 ┆ 0   ┆     ┆     ┆     ┆ ,   ┆     ┆     ┆     ┆ Bro ┆ địn ┆ s   ┆ địn ┆ 4   ┆     ┆ 4   ┆ 8   ┆     ┆ 8   ┆     ┆ địn ┆ địn ┆ địn ┆ địn ┆ 0   ┆     ┆ địn ┆ địn ┆ địn ┆ địn ┆ địn ┆     ┆ sản ┆     ┆ sản ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sản ┆     ┆     ┆     ┆     ┆     ┆     ┆ rip ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ 4   ┆     ┆     ┆     ┆     ┆ phụ ┆     ┆     ┆     ┆ wn  ┆ h   ┆     ┆ h   ┆     ┆     ┆ 09: ┆ 09: ┆     ┆ 17: ┆     ┆ h   ┆ h   ┆ h   ┆ h   ┆     ┆     ┆ h   ┆ h   ┆ h   ┆ h   ┆ h   ┆     ┆ phẩ ┆     ┆ phẩ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ phẩ ┆     ┆     ┆     ┆     ┆     ┆     ┆ tio ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ kiệ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 25: ┆ 59: ┆     ┆ 59: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ m   ┆     ┆ m   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ m   ┆     ┆     ┆     ┆     ┆     ┆     ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆ n   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 44. ┆ 19. ┆     ┆ 29. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ …   ┆     ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tên ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 240 ┆ 847 ┆     ┆ 898 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sản ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 256 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ phẩ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ m…  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 723 ┆ 001 ┆ 690 ┆ 329 ┆ Thờ ┆ 395 ┆ Cơ  ┆ 700 ┆ Thờ ┆ 698 ┆ Bộ  ┆ Khô ┆ Con ┆ Khô ┆ 150 ┆ fal ┆ 201 ┆ 202 ┆ nul ┆ nul ┆ nul ┆ Khô ┆ Bé  ┆ Từ  ┆ Bộ  ┆ 0.0 ┆ nul ┆ Khô ┆ Khô ┆ Khô ┆ Khô ┆ Khô ┆ 0   ┆ Khô ┆ 2-4 ┆ nul ┆ mis ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ 2-4 ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ 2-4 ┆ pri ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ 2-4 ┆ enr │
│ 70  ┆ 029 ┆ 00. ┆ 2   ┆ i   ┆ 8   ┆ cấu ┆ 7   ┆ i   ┆ 7   ┆ quầ ┆ ng  ┆ Cưn ┆ ng  ┆ 304 ┆ se  ┆ 7-0 ┆ 5-0 ┆ l   ┆ l   ┆ l   ┆ ng  ┆ Gái ┆ 3Y  ┆ quầ ┆ 000 ┆ l   ┆ ng  ┆ ng  ┆ ng  ┆ ng  ┆ ng  ┆     ┆ ng  ┆ Y   ┆ l   ┆ sin ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ Y   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ Y   ┆ mar ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ Y   ┆ ich │
│     ┆ 004 ┆ 000 ┆     ┆ tra ┆     ┆ hàn ┆     ┆ tra ┆     ┆ n   ┆ xác ┆ g   ┆ xác ┆ 625 ┆     ┆ 8-1 ┆ 9-1 ┆     ┆     ┆     ┆ xác ┆     ┆     ┆ n   ┆     ┆     ┆ xác ┆ xác ┆ xác ┆ xác ┆ xác ┆     ┆ xác ┆     ┆     ┆ g   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ y   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ed  │
│     ┆ 015 ┆ 0   ┆     ┆ ng  ┆     ┆ g   ┆     ┆ ng  ┆     ┆ áo  ┆ địn ┆     ┆ địn ┆ 0   ┆     ┆ 8   ┆ 8   ┆     ┆     ┆     ┆ địn ┆     ┆     ┆ áo  ┆     ┆     ┆ địn ┆ địn ┆ địn ┆ địn ┆ địn ┆     ┆ địn ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ 0   ┆     ┆     ┆     ┆     ┆ cũ  ┆     ┆ bé  ┆     ┆ bé  ┆ h   ┆     ┆ h   ┆     ┆     ┆ 08: ┆ 16: ┆     ┆     ┆     ┆ h   ┆     ┆     ┆     ┆     ┆     ┆ h   ┆ h   ┆ h   ┆ h   ┆ h   ┆     ┆ h   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tra ┆     ┆ gái ┆     ┆     ┆     ┆     ┆     ┆ 50: ┆ 05: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ i,  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 50. ┆ 42. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ bé  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 713 ┆ 360 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ gái ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ cũ  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 311 ┆ 000 ┆ 450 ┆ 351 ┆ Đồ  ┆ 203 ┆ 0-1 ┆ 211 ┆ Gặm ┆ 212 ┆ Gặm ┆ -   ┆ Thư ┆ Khô ┆ 135 ┆ fal ┆ 201 ┆ 202 ┆ 2   ┆ 202 ┆ nul ┆ Khô ┆ Khô ┆ Khô ┆ Khô ┆ 144 ┆ nul ┆ Khô ┆ Khô ┆ Khô ┆ Khô ┆ Khô ┆ 0   ┆ Chi ┆ nul ┆ Chi ┆ new ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ chi ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ mis ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ mis │
│ 54  ┆ 801 ┆ 00. ┆     ┆ chơ ┆ 3   ┆ Y   ┆ 8   ┆ nướ ┆ 1   ┆ nướ ┆ Chấ ┆ ơng ┆ ng  ┆ 850 ┆ se  ┆ 3-0 ┆ 5-0 ┆     ┆ 5-0 ┆ l   ┆ ng  ┆ ng  ┆ ng  ┆ ng  ┆ 90. ┆ l   ┆ ng  ┆ ng  ┆ ng  ┆ ng  ┆ ng  ┆     ┆ tiế ┆ l   ┆ tiế ┆     ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ tiế ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ sin ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ sin │
│     ┆ 000 ┆ 000 ┆     ┆ i & ┆     ┆     ┆     ┆ u   ┆     ┆ u   ┆ t   ┆ hiệ ┆ xác ┆ 158 ┆     ┆ 1-1 ┆ 9-2 ┆     ┆ 7-1 ┆     ┆ xác ┆ xác ┆ xác ┆ xác ┆ 000 ┆     ┆ xác ┆ xác ┆ xác ┆ xác ┆ xác ┆     ┆ t   ┆     ┆ t   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ t   ┆     ┆     ┆     ┆     ┆     ┆     ┆ g   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ g   │
│     ┆ 001 ┆ 0   ┆     ┆ Sác ┆     ┆     ┆     ┆     ┆     ┆ khá ┆ liệ ┆ u   ┆ địn ┆ 4   ┆     ┆ 8   ┆ 7   ┆     ┆ 8   ┆     ┆ địn ┆ địn ┆ địn ┆ địn ┆ 0   ┆     ┆ địn ┆ địn ┆ địn ┆ địn ┆ địn ┆     ┆ sản ┆     ┆ sản ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sản ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆ 5   ┆     ┆     ┆ h   ┆     ┆     ┆     ┆     ┆     ┆ c   ┆ u:  ┆ khá ┆ h   ┆     ┆     ┆ 09: ┆ 00: ┆     ┆ 17: ┆     ┆ h   ┆ h   ┆ h   ┆ h   ┆     ┆     ┆ h   ┆ h   ┆ h   ┆ h   ┆ h   ┆     ┆ phẩ ┆     ┆ phẩ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ phẩ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Sản ┆ c   ┆     ┆     ┆     ┆ 33: ┆ 05: ┆     ┆ 59: ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ m   ┆     ┆ m   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ m   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ phẩ ┆     ┆     ┆     ┆     ┆ 04. ┆ 36. ┆     ┆ 29. ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ …   ┆     ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ tên ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ m   ┆     ┆     ┆     ┆     ┆ 260 ┆ 233 ┆     ┆ 898 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ sản ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ đượ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ 256 ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ phẩ ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ c   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ m…  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ làm ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ …   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │
│ 461 ┆ 002 ┆ 401 ┆ 222 ┆ Tã  ┆ 227 ┆ Mer ┆ 227 ┆ Mer ┆ 227 ┆ Mer ┆ ﻿﻿Tã  ┆ Mer ┆ Khô ┆ 140 ┆ fal ┆ 201 ┆ 202 ┆ 2   ┆ 202 ┆ nul ┆ Khô ┆ Khô ┆ Khô ┆ Khô ┆ 597 ┆ nul ┆ Khô ┆ Khô ┆ Nhậ ┆ Khô ┆ Giấ ┆ 0   ┆ Khô ┆ nul ┆ ﻿﻿Tã  ┆ old ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ ﻿﻿tã  ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ nul ┆ mis ┆ 4.0 ┆ 8.0 ┆ 8.0 ┆ 6.0 ┆ 3-6 ┆ 6-1 ┆ 0.7 ┆ wei ┆ 6-1 ┆ fro │
│ 23  ┆ 001 ┆ 000 ┆ 2   ┆     ┆ 2   ┆ rie ┆ 5   ┆ rie ┆ 6   ┆ rie ┆ dán ┆ rie ┆ ng  ┆ 006 ┆ se  ┆ 4-0 ┆ 5-0 ┆     ┆ 5-0 ┆ l   ┆ ng  ┆ ng  ┆ ng  ┆ ng  ┆ 49. ┆ l   ┆ ng  ┆ ng  ┆ t   ┆ ng  ┆ y,  ┆     ┆ ng  ┆ l   ┆ dán ┆ _as ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ dán ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ l   ┆ sin ┆     ┆     ┆     ┆     ┆ M   ┆ 2M  ┆     ┆ ght ┆ 2M  ┆ m_w │
│     ┆ 000 ┆ .00 ┆     ┆     ┆     ┆ s   ┆     ┆ s   ┆     ┆ s_S ┆ Mer ┆ s   ┆ xác ┆ 203 ┆     ┆ 5-1 ┆ 9-2 ┆     ┆ 7-1 ┆     ┆ xác ┆ xác ┆ xác ┆ xác ┆ 000 ┆     ┆ xác ┆ xác ┆ Bản ┆ xác ┆ bột ┆     ┆ xác ┆     ┆ Mer ┆ _fi ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ mer ┆     ┆     ┆     ┆     ┆     ┆     ┆ g   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ _ra ┆     ┆ eig │
│     ┆ 009 ┆ 00  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ ơ   ┆ rie ┆ Nhậ ┆ địn ┆ 9   ┆     ┆ 4   ┆ 7   ┆     ┆ 8   ┆     ┆ địn ┆ địn ┆ địn ┆ địn ┆ 0   ┆     ┆ địn ┆ địn ┆ ,   ┆ địn ┆ giấ ┆     ┆ địn ┆     ┆ rie ┆ ll  ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ rie ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ nge ┆     ┆ ht  │
│     ┆ 4   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ Sin ┆ s   ┆ t   ┆ h   ┆     ┆     ┆ 10: ┆ 00: ┆     ┆ 17: ┆     ┆ h   ┆ h   ┆ h   ┆ h   ┆     ┆     ┆ h   ┆ h   ┆ Nhậ ┆ h   ┆ y,  ┆     ┆ h   ┆     ┆ s   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆ s   ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     ┆     │

In [45]:
pl.Config.set_tbl_rows(50)             # số dòng tối đa hiển thị
pl.Config.set_tbl_cols(10)             # số cột tối đa hiển thị
pl.Config.set_tbl_width_chars(200)     # tổng chiều rộng bảng ký tự
pl.Config.set_fmt_str_lengths(2000)     # độ dài chuỗi tối đa hiển thị (quan trọng nhất!)

item_df.select(["description_merged", "age_bucket_final"]).head(10)

shape: (10, 2)
┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┬──────────────────┐
│ description_merged                                                                                                                                                                ┆ age_bucket_final │
│ ---                                                                                                                                                                               ┆ ---              │
│ str                                                                                                                                                                               ┆ str              │
╞═══════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════════╪══════════════════╡
│ Chi tiết sản phẩm                     Tên sản phẩm: Hộp 2 núm ty DrBrown's Options Plus cổ rộng Y cut (Trên 9 tháng)         Loại sản phẩm: Núm ty         Đối tượng sử dụng: Trẻ ┆ 0-6M             │
│ trên 9 tháng         Thương hiệu: DrBrown's         Điểm nổi bật: Núm vú silicon siêu mềm giúp phát triển cơ hàm của bé thông qua sự cử động lưỡi tự nhiên.                       ┆                  │
│ Hộp 2 núm ty DrBrown's Options Plus cổ rộng Y cut (Trên 9 tháng) là núm ty dành cho trẻ trên 9 tháng của thương hiệu DrBrown's đến từ Mỹ. Núm vú silicon siêu mềm giúp phát triển ┆                  │
│ cơ hàm của bé thông qua sự cử động lưỡi một cách tự nhiên.                        Núm ty silicon mềm mại            Núm vú silicon siêu mềm giúp phát triển cơ hàm của bé thông   ┆                  │
│ qua sự cử động lưỡi một cách tự nhiên. Thiết kế đầu núm vừa vặn với vòm miệng bé, mang lại sự thoải mái khi sử dụng.               Thiết kế thông minh            Núm ty          ┆                  │
│ DrBrown's Options Plus được thiết kế với lỗ tiết sữa Y cut, phù hợp với nhu cầu ăn cháo đặc của bé trên 9 tháng tuổi, từ đó giúp bé có cảm giác gần gũi hơn trong từng lần bú.    ┆                  │
│ Hướng dẫn sử dụng               Rửa sạch núm ty bằng nước rửa chuyên dụng trước khi sử dụng lần đầu.         Đun sôi núm vú trong vòng 3-5 phút để tiệt trùng sau mỗi lần sử      ┆                  │
│ dụng.         Kiểm tra núm vú trước khi cho bé sử dụng, đảm bảo không có dấu hiệu rách hoặc thủng.         Không cho trẻ bú bình khi không có sự giám sát của người lớn.          ┆                  │
│ Hướng dẫn bảo quản               Bảo quản ở nhiệt độ phòng, nơi khô ráo, thoáng mát.         Tránh ánh nắng mặt trời trực tiếp.         Thay núm ty mới sau khi sử dụng từ 1 - 2  ┆                  │
│ tháng để đảm bảo vệ sinh cho trẻ.                     Lưu ý               Không rửa núm ty bằng xà phòng hoặc nước tẩy rửa.         Không tiệt trùng núm ty bằng lò vi sóng.      ┆                  │
│ Kiểm tra núm vú thường xuyên trước khi sử dụng.                     Thành phần               Silicon cao cấp         Không chứa BPA         Chất đàn hồi tốt                      ┆                  │
│ null                                                                                                                                                                              ┆ 2-4Y             │
│ Chi tiết sản phẩm                     Tên sản phẩm: Miếng Gặm Nướu Papa (CEQ004) (Cá hồng)         Chất liệu: Silicone mềm, dẻo và nước đã được chưng cất         Đối tượng sử    ┆ null             │
│ dụng: Dành cho các bé trong giai đoạn mọc răng         Thương hiệu: Papa         Xuất xứ: Thái Lan         Giá: 45.000₫                     **Miếng Gặm Nướu Papa (CEQ004) (Cá    ┆                  │
│ hồng)** là một sản phẩm giúp bé giảm đau trong giai đoạn mọc răng của thương hiệu **Papa đến từ Thái Lan**. Sản phẩm được thiết kế đặc biệt để tạo cảm giác dễ chịu cho bé khi    ┆                  │
│ nhai.                        Chất liệu an toàn: Silicone mềm, dẻo           Miếng gặm nướu được làm bằng chất liệu silicone mềm, dẻo và nước đã được chưng cất, đảm bảo an toàn   ┆                  │
│ tuyệt đối cho sức khỏe của bé.            Cảm giác dễ chịu: Bề mặt núm mát-xa           Bề mặt có các núm mát-xa nhỏ, mềm mịn, tạo cảm giác dễ chịu và thích thú khi bé sử dụng.  ┆                  │
│ Thiết kế ngộ nghĩnh: Hình động vật với tay cầm           Sản phẩm được thiết kế dạng hình các con vật đồ dùng ngộ nghĩnh, đặc biệt có tay cầm giúp bé dễ cầm nắm và chơi đùa.     ┆                  │
│ Độ đàn hồi tốt: Bền đẹp và dễ sử dụng           Miếng gặm nướu có độ đàn hồi tốt, dễ dàng uốn dẻo, bền đẹp mà không gây ảnh hưởng đến sức khỏe cho bé.            Cảm giác mát    ┆                  │
│ lạnh: Hỗ trợ giảm đau           Trước khi cho bé sử dụng, bạn có thể cho vào tủ lạnh tạo cảm giác mát lạnh, giúp bé thích thú và giảm đau nướu.               Hướng dẫn sử dụng   ┆                  │
│ Rửa sạch sản phẩm trước khi cho bé sử dụng.         Để sản phẩm trong tủ lạnh trước khi cho bé sử dụng để tạo cảm giác mát lạnh.         Giám sát bé khi sử dụng để đảm bảo an    ┆                  │
│ toàn.                     Hướng dẫn bảo quản               Bảo quản sản phẩm ở nơi khô ráo, thoáng mát.         Không sử dụng nước sôi để khử trùng sản phẩm.         Thường      ┆                  │
│ xuyên kiểm tra sản phẩm để đảm bảo không bị hư hỏng.                     Lưu ý               Sản phẩm chỉ dành cho bé trong giai đoạn mọc răng.         Khi sản phẩm có dấu hiệu  ┆                  │
│ hư hỏng, không nên cho bé sử dụng.  …                                                                                                                                             ┆                  │
│ ﻿﻿Tã dán Merries size S 82 miếng là sản phẩm dành cho bé 4-8kg đến từ thương hiệu uy tín Merries của Nhật Bản. Ra đời với công nghệ "4 siêu" - siêu mềm mại, siêu thông thoáng,     ┆ 6-12M            │
│ siêu thấm hút, siêu linh hoạt, tã dán Merries trở thành "người bạn" của hàng ngàn em bé trên toàn thế giới.﻿﻿﻿Ưu điểm nổi bật. Siêu mềm mại: được làm từ bông siêu mỏng và các hạt   ┆                  │
│ thấm hút nhanh, có bề mặt mềm mại, xốp mịn, tiếp xúc nhẹ nhàng, không gây hằn đỏ trên da bé.. Siêu thông thoáng: dựa vào công nghệ siêu thoát khí từ chất liệu màng đáy thoát khí ┆                  │
│ đặc biệt giúp bé yêu cảm thấy luôn dễ chịu, thoải mái. Cha mẹ có thể xóa tan nỗi lo nóng ẩm và hầm hơi do nước tiểu và mồ hôi cũng như kích ứng da do các tác nhân gây hại.. Siêu ┆                  │
│ thấm hút: thiết kế chống tràn khóa chặt chất lỏng đến 6-8 tiếng và không vón cục. Các hạt thấm hút kép cùng với bề mặt tiếp xúc điểm xốp mịn tạo ra những khoảng trống giúp thấm  ┆                  │
│ chất lỏng cực nhanh và không bị lan ra khắp bề mặt tã.. Siêu linh hoạt: thiết kế vừa vặn với cơ thể bé với vách chống tràn co dãn và phần eo mềm mại ôm khít, thiết kế phần đáy   ┆                  │
│ hình chữ "W" không gây cảm giác vướng víu và linh hoạt theo từng chuyển động của bé.. Vạch báo thời gian thay tã thông minh: thay đổi sang màu xanh lá đậm sẽ giúp bố mẹ dễ dàng  ┆                  │
│ nhận biết thời điểm cần thiết để thay tã cho bé.Hướng dẫn sử dụng                                                                                                                 ┆                  │
│ ﻿﻿﻿Bỉm tã quần Merries size M 58 miếng là sản phẩm dành cho bé từ 6-11kg đến từ thương hiệu uy tín Merries của Nhật Bản. ﻿﻿﻿﻿Tã quần Merries – một sản phẩm mang tính đột phá đến từ     ┆ 6-12M            │
│ Nhật Bản, khác biệt hoàn toàn so với những loại tã giấy khác trên thị trường, đặc biệt mỏng nhẹ giúp bé tung tăng chạy nhảy suốt 24h mà vẫn khô thoáng và êm dịu.Ưu điểm nổi bật﻿. ┆                  │
│ Siêu mềm mại với bề mặt tiếp xúc điểm xốp mịn và chất liệu mỏng nhẹ, không gây kích ứng lên làn da mỏng manh của bé.. Siêu thông thoáng với chất liệu màng đáy thoát khí đặc      ┆                  │
│ biệt. Các đường thun được thiết kế để không khí dễ dàng thổi qua giữa miếng tã và da. Bé sẽ luôn cảm thấy khô ráo ngay cả khi vân động nhiều.. Siêu thấm hút với lõi siêu thấm    ┆                  │
│ trung tâm độc đáo giúp thấm hút và khoá chặt một lượng lớn chất lỏng ngay lập tức. Đặc biệt tã không bị vón cục sau khi thấm hút.. Siêu linh hoạt trong chuyển động với thiết kế  ┆                  │
│ chữ “W” biến đổi linh hoạt với đáy quần thích ứng theo chuyển động của bé. Đường thun ôm vừa vặn không để lại vết hằn trên da.. Vạch báo thời gian thay tã thông minh: Thay tã    ┆                  │
│ khi vạch đổi sang màu xanh lá đậmHướng dẫn sử dụng ﻿﻿                                                                                                                               ┆                  │
│ Áo thun bé trai tay ngắn CF B078010 Xanh  là sản phẩm với chất liệu cotton mềm mại, thấm hút mồ hôi, đường may kỹ lưỡng chắc chắn sẽ giúp bé thoải mái vận động. Bên cạnh đó, sản ┆ 6-12M            │
│ phẩm có kiểu dáng cá tính cùng họa tiết đáng yêu sẽ giúp bé thêm phần thời trang. ĐẶC ĐIỂM NỔI BẬT Chất liệu cotton mềm mại Sản phẩm được may từ vải cotton mềm mại cho phép bé   ┆                  │
│ thoải mái chơi đùa, vận động mà không cảm thấy khó chịu. Bên cạnh đó, chất liệu cotton không gây kích ứng da và có khả năng thấm hút mồ hôi tốt nên Mẹ không phải lo lắng bé yêu  ┆                  │
│ bị nổi rôm, tuyệt đối an toàn khi sử dụng. Thiết kế thoải mái, đáng yêu Thiết kế thoải mái phối cùng họa tiết cá tính sẽ mang đến phong cách thoải mái và không kém phần thời     ┆                  │
│ trang cho bé của bạn. Ngoài ra, các đường nối, đường cuốn biên trên sản phẩm không bị nổi cộm gây khó chịu và ngứa da bé cho phép bé vận động dễ dàng. THÔNG TIN SẢN PHẨM Tên sản ┆                  │
│ phẩm: Áo thun bé trai tay ngắn CF B078010 Xanh Thương hiệu: CF Sản xuất tại: CÔNG TY TNHH MAY MẶC HẢI NAM , Việt Nam Chất liệu: 95% Cotton5% Spandex BẢO QUẢN SẢN PHẨM - Hạn chế  ┆                  │
│ dùng sản phẩm giặt tẩy - Không ngâm, giặt chung với sản phẩm ra màu - Không giặt trong nước nóng trên 40°C - Nên ủi/là mặt trái sản phẩm                                          ┆                  │
│ Chi tiết sản phẩm                     Tên sản phẩm: Thảm xốp hình chữ 30x30cm, 26 miếng         Chất liệu: Cao su         Kích thước: 30x30x1cm/miếng         Khối lượng tịnh:    ┆ 1-2Y             │
│ 58g/miếng         Xuất xứ: Việt Nam         Năm sản xuất: 2018         Sản xuất tại: Công Ty TNHH SX-TM THOẠI TÂN THÀNH (28/36/23 Lương Thế Vinh, P.Tân Thới Hoà, Q.Tân phú,      ┆                  │
│ TP.HCM)         Chịu trách nhiệm hàng hóa: CÔNG TY CỔ PHẦN CON CƯNG (101-103 Trần Quang Khải, P.Tân Định, Q.1, HCM)                        **Thảm xốp hình chữ 30x30cm, 26        ┆                  │
│ miếng** là thảm xốp dành cho bé từ 3 - 36 tháng tuổi của Con Cưng đến từ Việt Nam. Sản phẩm được làm từ cao su có tính đàn hồi tốt, giúp bé học chơi mà không lo bị va đập.       ┆                  │
│ Thảm xốp hình chữ - Nguyên liệu cao su, tính đàn hồi tốt           Thảm xốp hình chữ với thiết kế nhiều màu sắc, hình các chữ cái và số, giúp bé vừa học vừa chơi, tạo điều kiện  ┆                  │
│ cho sự phát triển trí tuệ và thể chất mà mẹ có thể yên tâm làm việc nhà.            Cảnh báo an toàn - Bé không nên ngậm hay cắn           Để đảm bảo an toàn cho trẻ, không nên  ┆                  │
│ cho bé ngậm, cắn hoặc đưa sản phẩm vào miệng trong quá trình vui chơi.               Hướng dẫn sử dụng               Nối các tấm xốp với nhau bằng răng nối.                      ┆                  │
│ Hướng dẫn bảo quản               Để sản phẩm ở nơi khô ráo, thoáng mát.         Tránh ánh nắng mặt trời trực tiếp.         Vệ sinh bề mặt sản phẩm bằng vải ẩm khi cần thiết.     ┆                  │
│ Lưu ý               Họa tiết và màu sắc có thể thay đổi tùy vào đợt hàng về.                     Thành phần               Cao su                                                  ┆                  │
│ ﻿﻿﻿Dòng sản phẩm tã quần Huggies Dry với tinh chất tràm trà tự nhiên sẽ mang đến cho da con cảm giác dễ chịu. Đặc biệt, sản phẩm cũng được chứng minh lâm sàng giúp ngừa hăm tã hiệu ┆ null             │
│ quả. Ưu điểm nổi bật. Tã quần Huggies Dry cải tiến mới với công nghệ lưng thun đệm mây, chống hằn da;. Bề mặt tã quần Huggies được bổ sung tinh chất tràm trà tự nhiên giúp mang  ┆                  │
│ đến cảm giác dịu da;. Khả năng thoáng khí được chứng minh lâm sàng giúp ngăn ngừa hăm tã, giữ mông bé luôn khô thoáng;. Nhờ chất liệu mềm mại, bỉm Huggies giúp nâng niu làn da   ┆                  │
│ nhạy cảm của bé.Hướng dẫn thay tã. Mặt tã như mặt quần của bé với chữ "SAU-BACK" ở mặt sau.. Chỉnh tã ôm vừa chân, tránh bị gập vào để chống tràn hiệu quả.. Khi tã bị bẩn, xé    ┆                  │
│ đường thun 2 bên hông để cởi bỏ.Hướng dẫn chọn size tã* Sản phẩm sẽ được giao hàng với bao bì ngẫu nhiên. ﻿                                                                        ┆                  │
│ null                                                                                                                                                                              ┆ null             │
│ Chi tiết sản phẩm                     Tên sản phẩm: Bỉm - Tã dán Moony newborn 90 miếng (         Thương hiệu: Unicharm         Xuất xứ thương hiệu: Nhật Bản         Kích cỡ     ┆ 0-6M             │
│ (size): Newborn,          Số miếng: 90                     Bỉm - Tã dán Moony newborn 90 miếng ( là bỉm tã dán dành cho bé sơ sinh của thương hiệu Moony đến từ Nhật Bản. Với     ┆                  │
│ viền điều hòa thông minh, sản phẩm giúp bé thoải mái mà không lo trào tã.                           Viền điều hòa thông minh giúp sản phẩm ôm vừa vặn cơ thể bé, chống trào hiệu  ┆                  │
│ quả.                 Viền điều hòa thông minh là tính năng giúp tã Moony cong ôm vừa vặn cơ thể bé, ngăn ngừa nguy cơ trào tã, mang lại sự thoải mái tốt nhất cho trẻ nhỏ.        ┆                  │
│ Màng vải lưng thun 3 vòng co giãn 360° giúp khô thoáng cả ngày dài.           Màng vải này giúp tã không bị hầm bí và hăm đỏ, cho bé thoải mái tiếp xúc với không khí, mỗi cử     ┆                  │
│ động đều dễ dàng và không bị cản trở.               Rãnh rốn Oheso bảo vệ phần rốn non nớt của bé sơ sinh.           Rãnh rốn OHESO được thiết kế riêng, giúp bảo vệ phần rốn     ┆                  │
│ nhạy cảm của trẻ, tạo cảm giác thoải mái nhất cho các bé ngay từ những ngày đầu đời.               Sợi Nano siêu mềm mịn nhẹ nhàng nâng niu làn da nhạy cảm.           Chất liệu  ┆                  │
│ sợi Nano giúp tã Moony siêu nhẹ, mang lại cảm giác mềm mại và dễ chịu cho làn da của bé yêu, giảm thiểu tình trạng kích ứng da.            Lõi bông cao cấp siêu chống trào.      ┆                  │
│ Lõi bông được thiết kế để thấm hút cực tốt, giúp sản phẩm giữ cho bé luôn khô thoáng, mà không lo bị tràn ra ngoài.            Chỉ thị ướt báo hiệu thời điểm thay tã cho bé.     ┆                  │
│ Thêm vào đó, chỉ thị ướt tiện lợi giúp mẹ nhanh chóng nhận biết khi nào cần thay tã cho bé, mang lại sự tiện lợi và chăm sóc tốt nhất.               Hướng dẫn chọn size          ┆                  │
│ Chọn đúng size tã cho bé là rất quan trọng. Với tã Moony, size Newborn (               Hướng dẫn sử dụng               Mặt sau tã có miếng dán cố định. Mở miếng tã mới và tròng  ┆                  │
│ vào chân bé, kéo CAO ngang hông.         Kéo ch…                                                                                                                                  ┆                  │
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┴──────────────────┘

In [49]:
print(f"{len(item_df.columns)} columns:")
for i, c in enumerate(item_df.columns, 1):
    print(f"{i:02d}. {c}")

66 columns:
01. p_id
02. item_id
03. price
04. category_l1_id
05. category_l1
06. category_l2_id
07. category_l2
08. category_l3_id
09. category_l3
10. category_id
11. category
12. description
13. brand
14. manufacturer
15. creation_timestamp
16. is_deleted
17. created_date
18. updated_date
19. sync_status_id
20. last_sync_date
21. sync_error_message
22. image_url
23. gender_target
24. age_group
25. item_type
26. gp
27. weight
28. color
29. size
30. origin
31. volume
32. material
33. sale_status
34. description_new
35. age_bucket_primary
36. description_merged
37. description_source
38. size_lo_m
39. size_hi_m
40. size_age_bucket
41. age_fill_source
42. age_llm_conf
43. age_bucket_primary_filled
44. size_lo_m_right
45. size_hi_m_right
46. size_age_bucket_right
47. age_fill_source_right
48. age_llm_conf_right
49. _desc_norm
50. desc_age_month_lo
51. desc_age_month_hi
52. desc_age_month_mid
53. desc_age_bucket
54. desc_age_confidence
55. age_bucket_enriched
56. age_source_enriched
57. kg_lo
58. kg_hi
59. kg_single
60. kg_mid
61. weight_age_bucket_raw
62. weight_age_bucket
63. weight_age_confidence
64. weight_age_source
65. age_bucket_final
66. age_source_final

In [ ]:
import polars as pl

df = item_df  # đổi tên nếu bạn dùng df_item
FASHION = "Thời trang"

def is_missing(col: str) -> pl.Expr:
    return pl.col(col).is_null() | (
        pl.col(col).cast(pl.Utf8).str.to_lowercase().str.strip_chars() == "không xác định"
    )

# 1) Filter category Thời trang
fashion = df.filter(pl.col("category_1") == FASHION)

size_ok = ~is_missing("size")
age_ok  = ~is_missing("age_group")

# ===== A) size -> age_group =====
both = fashion.filter(size_ok & age_ok).select(["size", "age_group"])

# Đếm cặp (size, age_group)
pair = both.group_by(["size", "age_group"]).len().rename({"len":"n"})
# Tổng theo size
size_tot = both.group_by("size").len().rename({"len":"size_n"})

# Bảng ánh xạ: với mỗi size, lấy age_group đa số + tỉ lệ
map_size_to_age = (
    pair.join(size_tot, on="size")
        .with_columns((pl.col("n") / pl.col("size_n")).alias("share"))
        .group_by("size")
        .agg([
            pl.col("age_group").sort_by("share").last().alias("best_age"),
            pl.col("share").max().alias("best_share"),
            pl.col("size_n").max().alias("support"),
        ])
        .sort("best_share", descending=True)
)

# Ngưỡng chấp nhận
TAU = 0.90
MIN_SUP = 20
good_maps = map_size_to_age.filter((pl.col("best_share") >= TAU) & (pl.col("support") >= MIN_SUP))

# Ước tính số dòng có thể điền: age_group thiếu nhưng size có, và size nằm trong good_maps
can_fill_age = (
    fashion.filter(~age_ok & size_ok)
           .join(good_maps.select(["size","best_age"]), on="size", how="inner")
)
print("size -> age_group | fillable rows:", can_fill_age.height)

# (tuỳ chọn) xem vài mapping tốt
print(good_maps.head(10))

# ===== B) age_group -> size (nếu muốn điền ngược) =====
pair2 = both.group_by(["age_group","size"]).len().rename({"len":"n"})
age_tot = both.group_by("age_group").len().rename({"len":"age_n"})

map_age_to_size = (
    pair2.join(age_tot, on="age_group")
         .with_columns((pl.col("n") / pl.col("age_n")).alias("share"))
         .group_by("age_group")
         .agg([
             pl.col("size").sort_by("share").last().alias("best_size"),
             pl.col("share").max().alias("best_share"),
             pl.col("age_n").max().alias("support"),
         ])
         .sort("best_share", descending=True)
)

good_maps_rev = map_age_to_size.filter((pl.col("best_share") >= TAU) & (pl.col("support") >= MIN_SUP))

can_fill_size = (
    fashion.filter(~size_ok & age_ok)
           .join(good_maps_rev.select(["age_group","best_size"]), on="age_group", how="inner")
)
print("age_group -> size | fillable rows:", can_fill_size.height)