In [4]:
import polars as pl
import numpy as np
from sklearn.cluster import KMeans
import pandas as pd
import os
from datetime import datetime

### **Đặc trưng:** Phân khúc loại sản phẩm (category_l1) theo mức giá: Bình dân - Trung cấp - Cao cấp

In [3]:
path_item = r"D:\003. HK1 - Năm 3\02. CS116 - Python cho Máy học\CS116-DoAn\Phase-3\preprocessing data\sale_pers.item_chunk_0.parquet"
df_item = pl.read_parquet(path_item)
print(df_item.shape)
print(df_item.head())

(27323, 11)
shape: (5, 11)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ item_id   ┆ price     ┆ category_ ┆ category_ ┆ … ┆ gender_ta ┆ descripti ┆ brand_fin ┆ age_grou │
│ ---       ┆ ---       ┆ l1        ┆ l2        ┆   ┆ rget_fina ┆ on_final  ┆ al        ┆ p_final  │
│ str       ┆ decimal[3 ┆ ---       ┆ ---       ┆   ┆ l         ┆ ---       ┆ ---       ┆ ---      │
│           ┆ 8,4]      ┆ str       ┆ str       ┆   ┆ ---       ┆ str       ┆ str       ┆ str      │
│           ┆           ┆           ┆           ┆   ┆ str       ┆           ┆           ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 050202000 ┆ 99000.000 ┆ Babycare  ┆ Bình sữa, ┆ … ┆ Không xác ┆ Chi tiết  ┆ Dr.Brown' ┆ Từ 9M    │
│ 0004      ┆ 0         ┆           ┆ phụ kiện  ┆   ┆ định      ┆ sản phẩm  ┆ s         ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ …         ┆           ┆          │
│ 001029004 ┆ 69000.000 ┆ Thời      ┆ Cơ cấu    ┆ … ┆ Bé Gái    ┆ Không xác ┆ Con Cưng  ┆ Từ 36M   │
│ 0150      ┆ 0         ┆ trang     ┆ hàng cũ   ┆   ┆           ┆ định      ┆           ┆          │
│ 000801000 ┆ 45000.000 ┆ Đồ chơi & ┆ 0-1Y      ┆ … ┆ Không xác ┆ Chi tiết  ┆ Thương    ┆ 0-12M    │
│ 0015      ┆ 0         ┆ Sách      ┆           ┆   ┆ định      ┆ sản phẩm  ┆ hiệu khác ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ …         ┆           ┆          │
│ 002001000 ┆ 401000.00 ┆ Tã        ┆ Merries   ┆ … ┆ Không xác ┆ ﻿﻿Tã dán    ┆ Merries   ┆ ["Từ     │
│ 0094      ┆ 00        ┆           ┆           ┆   ┆ định      ┆ Merries   ┆           ┆ 4M",     │
│           ┆           ┆           ┆           ┆   ┆           ┆ size S 82 ┆           ┆ "3M-6M", │
│           ┆           ┆           ┆           ┆   ┆           ┆ miế…      ┆           ┆ "12-36M" │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ]        │
│ 002001000 ┆ 401000.00 ┆ Tã        ┆ Merries   ┆ … ┆ Không xác ┆ ﻿﻿﻿Bỉm tã    ┆ Merries   ┆ 12-36M   │
│ 0098      ┆ 00        ┆           ┆           ┆   ┆ định      ┆ quần      ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ Merries   ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ size M …  ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [4]:
def cluster_price_group(prices):
    prices_reshaped = prices.to_numpy().reshape(-1, 1)

    # Gom cụm 3 cluster
    kmeans = KMeans(n_clusters=3, random_state=42)
    labels = kmeans.fit_predict(prices_reshaped)

    # Tính mean của từng cluster bằng pandas
    df_temp = pd.DataFrame({"price": prices.values, "cluster": labels})
    cluster_means = df_temp.groupby("cluster")["price"].mean()

    # Sắp xếp cluster theo giá tăng dần → 0,1,2
    sorted_clusters = cluster_means.sort_values().index.tolist()

    # Mapping cluster gốc → 0,1,2
    cluster_map = {sorted_clusters[i]: i for i in range(3)}

    # Trả về danh sách nhãn theo thứ tự index
    return [cluster_map[c] for c in labels]

In [5]:
pdf = df_item.select(["item_id", "price", "category_l1"]).to_pandas()

# Tạo cột rỗng
pdf["price_segment"] = -1

for cat, group in pdf.groupby("category_l1"):
    X = group["price"].values.reshape(-1,1)

    if len(group) < 3:
        # Không gom cụm nếu số lượng ít → gán 0 hết
        pdf.loc[group.index, "price_segment"] = 0
        continue

    # Gom cụm
    kmeans = KMeans(n_clusters=3, random_state=42, n_init="auto")
    labels = kmeans.fit_predict(X)

    # Remap theo thứ tự giá trung bình
    cluster_mean = pd.DataFrame({
        "cluster": labels,
        "price": group["price"].values
    }).groupby("cluster")["price"].mean().sort_values()

    mapping = {cluster: rank for rank, cluster in enumerate(cluster_mean.index)}

    # Gán nhãn theo index
    pdf.loc[group.index, "price_segment"] = [mapping[c] for c in labels]

In [6]:
print(pdf.groupby(["category_l1", "price_segment"]).size())

category_l1             price_segment
Babycare                0                1795
                        1                 165
                        2                  34
Gói Hội Viên            0                   3
                        1                   1
                        2                   3
Hóa mỹ phẩm cho bé      0                 168
                        1                 148
                        2                  29
Hóa mỹ phẩm gia đình    0                 178
                        1                 183
                        2                  26
Phụ kiện                0                1492
                        1                1134
                        2                 521
Sữa                     0                 159
                        1                 205
                        2                  73
Sữa nước                0                 131
                        1                  27
                        2                   8
TPCN                    0                 206
                        1                  54
                        2                  10
Textile                 0                 502
                        1                  34
                        2                  18
Thời trang              0                8792
                        1                5262
                        2                 988
Thực phẩm cho bé        0                 604
                        1                 303
                        2                  74
Thực phẩm cho gia đình  0                 393
                        1                  76
                        2                   1
Tã                      0                 154
                        1                 282
                        2                   2
Vệ sinh                 0                  45
                        1                  52
                        2                  35
Đồ chơi & Sách          0                2704
                        1                 220
                        2                  29
dtype: int64

Mapping:
- 0: Bình dân
- 1: Trung cấp
- 2: Cao cấp

In [7]:
segment_stats = (
    pdf.groupby(["category_l1", "price_segment"])["price"]
       .agg(["min", "max", "mean", "median", "count"])
       .sort_values(["category_l1", "price_segment"])
)

print("\n=== BẢNG THỐNG KÊ THEO SEGMENT ===")
print(segment_stats)

=== BẢNG THỐNG KÊ THEO SEGMENT ===
                                               min            max  \
category_l1            price_segment
Babycare               0                 1000.0000   1767273.0000
                       1              1821000.0000   6775000.0000
                       2              6950000.0000  20990000.0000
Gói Hội Viên           0                19000.0000     99000.0000
                       1               169000.0000    169000.0000
                       2               230000.0000    299000.0000
Hóa mỹ phẩm cho bé     0                20000.0000    140000.0000
                       1               145000.0000    290000.0000
                       2               295000.0000    685000.0000
Hóa mỹ phẩm gia đình   0                12000.0000    135000.0000
                       1               139000.0000    275000.0000
                       2               288000.0000    750000.0000
Phụ kiện               0                 9000.0000     79000.0000
                       1                89000.0000    165000.0000
                       2               179000.0000    345000.0000
Sữa                    0                85000.0000    435000.0000
                       1               439000.0000    735000.0000
                       2               750000.0000   1295000.0000
Sữa nước               0                14000.0000     73000.0000
                       1                76500.0000    163000.0000
                       2               195000.0000    400000.0000
TPCN                   0                32000.0000    396000.0000
                       1               410000.0000    799000.0000
                       2               880000.0000   1720000.0000
Textile                0                25000.0000    840000.0000
                       1              1099000.0000   2300000.0000
                       2              2699000.0000   6799000.0000
Thời trang             0                 9000.0000    130000.0000
                       1               135000.0000    269000.0000
                       2               279000.0000    499000.0000
Thực phẩm cho bé       0                 3000.0000     74000.0000
                       1                75000.0000    159000.0000
                       2               165000.0000    380000.0000
Thực phẩm cho gia đình 0                 2500.0000    129000.0000
                       1               135000.0000    550000.0000
                       2              1500000.0000   1500000.0000
Tã                     0                55000.0000    259000.0000
                       1               279000.0000    638000.0000
                       2              1320000.0000   1320000.0000
Vệ sinh                0                 8000.0000     36000.0000
                       1                39000.0000     66000.0000
                       2                73000.0000    180000.0000
Đồ chơi & Sách         0                 5000.0000    490000.0000
                       1               495000.0000   1690000.0000
                       2              1890000.0000   4200000.0000

                                                mean     median  count
category_l1            price_segment
Babycare               0               250702.354875   125000.0   1795
                       1              3367533.612121  2999000.0    165
                       2                  10334623.0  8819500.0     34
Gói Hội Viên           0                62333.333333    69000.0      3
                       1                    169000.0   169000.0      1
                       2                    266000.0   269000.0      3
Hóa mỹ phẩm cho bé     0                 84059.52381    89000.0    168
                       1               200935.810811   195000.0    148
                       2               386620.689655   359000.0     29
Hóa mỹ phẩm gia đình   0                79955.617978    83000.0    178
                       1               196322.404372   195000.0    183
                       2               369423.076923   312000.0     26
Phụ kiện               0                31540.214477    29000.0   1492
                       1               134518.518519   139000.0   1134
                       2               202074.856046   195000.0    521
Sữa                    0               309735.849057   319000.0    159
                       1               564409.756098   565000.0    205
                       2               927547.945205   895000.0     73
Sữa nước               0                40324.427481    39000.0    131
                       1               109259.259259   107000.0     27
                       2                    265500.0   258500.0      8
TPCN                   0               248514.563107   277000.0    206
                       1               553814.814815   517000.0     54
                       2                   1103900.0   979500.0     10
Textile                0               203725.099602   169000.0    502
                       1              1709529.411765  1700000.0     34
                       2                   3544000.0  3094000.0     18
Thời trang             0                67084.622384    49000.0   8792
                       1               194130.938807   199000.0   5262
                       2               347451.417004   349000.0    988
Thực phẩm cho bé       0                46804.635762    49000.0    604
                       1               102557.755776    95000.0    303
                       2               227067.567568   179000.0     74
Thực phẩm cho gia đình 0                47445.292621    38000.0    393
                       1               218828.947368   201500.0     76
                       2                   1500000.0  1500000.0      1
Tã                     0               171727.272727   185000.0    154
                       1               368932.624113   379000.0    282
                       2                   1320000.0  1320000.0      2
Vệ sinh                0                24644.444444    27000.0     45
                       1                48990.384615    46000.0     52
                       2                96342.857143    89000.0     35
Đồ chơi & Sách         0               144453.957101   125000.0   2704
                       1                    843450.0   790000.0    220
                       2              2912724.137931  2890000.0     29

In [8]:
df_price_seg = pl.from_pandas(pdf)

In [9]:
df_item = df_item.join(
    df_price_seg.select(["item_id", "price_segment"]),
    on="item_id",
    how="left"
)

In [10]:
print(df_item.head())
print(df_item.select("price_segment").unique())

shape: (5, 12)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ item_id   ┆ price     ┆ category_ ┆ category_ ┆ … ┆ descripti ┆ brand_fin ┆ age_group ┆ price_se │
│ ---       ┆ ---       ┆ l1        ┆ l2        ┆   ┆ on_final  ┆ al        ┆ _final    ┆ gment    │
│ str       ┆ decimal[3 ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---      │
│           ┆ 8,4]      ┆ str       ┆ str       ┆   ┆ str       ┆ str       ┆ str       ┆ i64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 050202000 ┆ 99000.000 ┆ Babycare  ┆ Bình sữa, ┆ … ┆ Chi tiết  ┆ Dr.Brown' ┆ Từ 9M     ┆ 0        │
│ 0004      ┆ 0         ┆           ┆ phụ kiện  ┆   ┆ sản phẩm  ┆ s         ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ …         ┆           ┆           ┆          │
│ 001029004 ┆ 69000.000 ┆ Thời      ┆ Cơ cấu    ┆ … ┆ Không xác ┆ Con Cưng  ┆ Từ 36M    ┆ 0        │
│ 0150      ┆ 0         ┆ trang     ┆ hàng cũ   ┆   ┆ định      ┆           ┆           ┆          │
│ 000801000 ┆ 45000.000 ┆ Đồ chơi & ┆ 0-1Y      ┆ … ┆ Chi tiết  ┆ Thương    ┆ 0-12M     ┆ 0        │
│ 0015      ┆ 0         ┆ Sách      ┆           ┆   ┆ sản phẩm  ┆ hiệu khác ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ …         ┆           ┆           ┆          │
│ 002001000 ┆ 401000.00 ┆ Tã        ┆ Merries   ┆ … ┆ ﻿﻿Tã dán    ┆ Merries   ┆ ["Từ 4M", ┆ 1        │
│ 0094      ┆ 00        ┆           ┆           ┆   ┆ Merries   ┆           ┆ "3M-6M",  ┆          │
│           ┆           ┆           ┆           ┆   ┆ size S 82 ┆           ┆ "12-36M"] ┆          │
│           ┆           ┆           ┆           ┆   ┆ miế…      ┆           ┆           ┆          │
│ 002001000 ┆ 401000.00 ┆ Tã        ┆ Merries   ┆ … ┆ ﻿﻿﻿Bỉm tã    ┆ Merries   ┆ 12-36M    ┆ 1        │
│ 0098      ┆ 00        ┆           ┆           ┆   ┆ quần      ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ Merries   ┆           ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ size M …  ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘
shape: (3, 1)
┌───────────────┐
│ price_segment │
│ ---           │
│ i64           │
╞═══════════════╡
│ 0             │
│ 1             │
│ 2             │
└───────────────┘

In [12]:
output_path = r"D:\003. HK1 - Năm 3\02. CS116 - Python cho Máy học\CS116-DoAn\Phase-3\Feature engineering\sale_pers.item_chunk_0.parquet"

df_item.write_parquet(output_path)

print(f"Đã lưu thành công vào:\n{output_path}")

Đã lưu thành công vào:
D:\003. HK1 - Năm 3\02. CS116 - Python cho Máy học\CS116-DoAn\Phase-3\Feature engineering\sale_pers.item_chunk_0.parquet

**Nhận Xét:**

**1. Các nhóm ngành có phân khúc giá rất rõ ràng và hợp lý**

Những category_l1 như Sữa, Tã, Textile, Đồ chơi & Sách, TPCN, Hóa mỹ phẩm, Babycare thể hiện phân tách giá rất mạnh:
- Cụm 0 (Bình dân): giá thấp – trung bình
- Cụm 1 (Trung cấp): giá tăng đáng kể
- Cụm 2 (Cao cấp): giá cao vượt trội và rất đặc trưng

**2. Các ngành hàng giá thấp như “Phụ kiện”, “Thực phẩm cho bé”, “Vệ sinh” không quá chênh lệch giữa 0 - 1 - 2**

=> Phân bố không quá rõ ràng để ứng dụng phân cụm

**3. Chỉ có "Tã" và "Sữa" là có phân khúc Trung cấp nhiều hơn Cao cấp**

In [305]:
#===================================

### **Đặc trưng:** Số loại sản phẩm (category_l1) trung bình cho một lần mua hàng (một ngày), và phân cụm số loại giao dịch trung bình đó, gán vào 3 nhãn "Mua ít", "Mua vừa" và "Mua nhiều".

In [43]:
path_tx_0 = r"D:\003. HK1 - Năm 3\02. CS116 - Python cho Máy học\CS116-DoAn\Phase-3\preprocessing data\sale_pers.purchase_history_daily_chunk_0.parquet"

df_tx0 = pl.read_parquet(path_tx_0)

print("Số dòng:", df_tx0.height)
print("Số cột:", df_tx0.width)
print("\nDanh sách cột:")
print(df_tx0.columns)

Số dòng: 487850
Số cột: 13

Danh sách cột:
['item_id', 'price', 'quantity', 'customer_id', 'created_date', 'channel', 'payment', 'location', 'discount', 'category_l1', 'list_price', 'category_l2', 'discount_rate']

In [44]:
df_tx0.head()

shape: (5, 13)
┌───────────┬───────────┬──────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ item_id   ┆ price     ┆ quantity ┆ customer_ ┆ … ┆ category_ ┆ list_pric ┆ category_ ┆ discount_ │
│ ---       ┆ ---       ┆ ---      ┆ id        ┆   ┆ l1        ┆ e         ┆ l2        ┆ rate      │
│ str       ┆ decimal[3 ┆ i32      ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│           ┆ 8,4]      ┆          ┆ i32       ┆   ┆ str       ┆ decimal[3 ┆ str       ┆ decimal[3 │
│           ┆           ┆          ┆           ┆   ┆           ┆ 8,4]      ┆           ┆ 8,4]      │
╞═══════════╪═══════════╪══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 711500000 ┆ 49000.000 ┆ 1        ┆ 5254214   ┆ … ┆ Thực phẩm ┆ 49000.000 ┆ Snack ăn  ┆ 0.0000    │
│ 0004      ┆ 0         ┆          ┆           ┆   ┆ cho bé    ┆ 0         ┆ dặm       ┆           │
│ 002913000 ┆ 69000.000 ┆ 1        ┆ 7573232   ┆ … ┆ Thực phẩm ┆ 74000.000 ┆ Bột ăn    ┆ 0.0676    │
│ 0030      ┆ 0         ┆          ┆           ┆   ┆ cho bé    ┆ 0         ┆ dặm       ┆           │
│ 349600000 ┆ 75000.000 ┆ 2        ┆ 8187418   ┆ … ┆ Thời      ┆ 75000.000 ┆ Quần áo & ┆ 0.0000    │
│ 0053      ┆ 0         ┆          ┆           ┆   ┆ trang     ┆ 0         ┆ Phụ kiện  ┆           │
│           ┆           ┆          ┆           ┆   ┆           ┆           ┆ sơ sinh   ┆           │
│ 270000000 ┆ 58500.000 ┆ 2        ┆ 8187418   ┆ … ┆ Vệ sinh   ┆ 65000.000 ┆ Khăn khô  ┆ 0.1000    │
│ 0002      ┆ 0         ┆          ┆           ┆   ┆           ┆ 0         ┆           ┆           │
│ 002911000 ┆ 89000.000 ┆ 1        ┆ 6931560   ┆ … ┆ Thực phẩm ┆ 99000.000 ┆ Snack ăn  ┆ 0.1010    │
│ 0036      ┆ 0         ┆          ┆           ┆   ┆ cho bé    ┆ 0         ┆ dặm       ┆           │
└───────────┴───────────┴──────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [58]:
TX_DIR = r"D:\003. HK1 - Năm 3\02. CS116 - Python cho Máy học\CS116-DoAn\Phase-3\preprocessing data"
TX_PATTERN = "sale_pers.purchase_history_daily_chunk_{}.parquet"

ITEM_PATH = r"D:\003. HK1 - Năm 3\02. CS116 - Python cho Máy học\CS116-DoAn\Phase-3\preprocessing data\sale_pers.item_chunk_0.parquet"

OUTPUT_PATH = r"D:\003. HK1 - Năm 3\02. CS116 - Python cho Máy học\CS116-DoAn\Phase-3\Feature engineering\customer_behavior_202401_202501.parquet"

In [46]:
START_DATE = datetime(2024, 1, 1)
END_DATE   = datetime(2025, 1, 31)

In [47]:
# 3. READ ITEM
df_item = pl.read_parquet(ITEM_PATH).select(
    ["item_id", "category_l1"]
)

print("Item shape:", df_item.shape)

Item shape: (27323, 2)

In [48]:
# 4. PROCESS TRANSACTION CHUNKS

customer_agg_chunks = []

for i in range(80):  # 0 → 79
    tx_path = os.path.join(TX_DIR, TX_PATTERN.format(i))
    if not os.path.exists(tx_path):
        continue

    print(f"\n=== Đang xử lý chunk {i} ===")

    tx_chunk = pl.read_parquet(
        tx_path,
        columns=["item_id", "customer_id", "created_date"]
    )

    # --- Lọc theo thời gian ---
    tx_chunk = tx_chunk.filter(
        (pl.col("created_date") >= START_DATE) &
        (pl.col("created_date") <= END_DATE)
    )

    if tx_chunk.is_empty():
        print("  -> Không có dữ liệu trong window thời gian, skip.")
        continue

    # --- Join lấy category_l1 ---
    tx_joined = tx_chunk.join(
        df_item,
        on="item_id",
        how="left"
    )

    # --- Đếm số category_l1 khác nhau mỗi ngày ---
    daily_cat_count = (
        tx_joined
        .group_by(["customer_id", "created_date"])
        .agg(
            pl.col("category_l1").n_unique().alias("unique_categories")
        )
    )

    # --- Aggregate trong chunk ---
    cust_chunk = (
        daily_cat_count
        .group_by("customer_id")
        .agg([
            pl.col("unique_categories").sum().alias("sum_unique_categories"),
            pl.len().alias("num_days")
        ])
    )

    customer_agg_chunks.append(cust_chunk)

print("\n=== Hoàn thành xử lý tất cả transaction chunks ===")

=== Đang xử lý chunk 0 ===

=== Đang xử lý chunk 1 ===

=== Đang xử lý chunk 2 ===

=== Đang xử lý chunk 3 ===

=== Đang xử lý chunk 4 ===

=== Đang xử lý chunk 5 ===

=== Đang xử lý chunk 6 ===

=== Đang xử lý chunk 7 ===

=== Đang xử lý chunk 8 ===

=== Đang xử lý chunk 9 ===

=== Đang xử lý chunk 10 ===

=== Đang xử lý chunk 11 ===

=== Đang xử lý chunk 12 ===

=== Đang xử lý chunk 13 ===

=== Đang xử lý chunk 14 ===

=== Đang xử lý chunk 15 ===

=== Đang xử lý chunk 16 ===

=== Đang xử lý chunk 17 ===

=== Đang xử lý chunk 18 ===

=== Đang xử lý chunk 19 ===

=== Đang xử lý chunk 20 ===

=== Đang xử lý chunk 21 ===

=== Đang xử lý chunk 22 ===

=== Đang xử lý chunk 23 ===

=== Đang xử lý chunk 24 ===

=== Đang xử lý chunk 25 ===

=== Đang xử lý chunk 26 ===

=== Đang xử lý chunk 27 ===

=== Đang xử lý chunk 28 ===

=== Đang xử lý chunk 29 ===

=== Đang xử lý chunk 30 ===

=== Đang xử lý chunk 31 ===

=== Đang xử lý chunk 32 ===

=== Đang xử lý chunk 33 ===

=== Đang xử lý chunk 34 ===

=== Đang xử lý chunk 35 ===

=== Đang xử lý chunk 36 ===

=== Đang xử lý chunk 37 ===

=== Đang xử lý chunk 38 ===

=== Đang xử lý chunk 39 ===

=== Đang xử lý chunk 40 ===

=== Đang xử lý chunk 41 ===

=== Đang xử lý chunk 42 ===

=== Đang xử lý chunk 43 ===

=== Đang xử lý chunk 44 ===

=== Đang xử lý chunk 45 ===

=== Đang xử lý chunk 46 ===

=== Đang xử lý chunk 47 ===

=== Đang xử lý chunk 48 ===

=== Đang xử lý chunk 49 ===

=== Đang xử lý chunk 50 ===

=== Đang xử lý chunk 51 ===

=== Đang xử lý chunk 52 ===

=== Đang xử lý chunk 53 ===

=== Đang xử lý chunk 54 ===

=== Đang xử lý chunk 55 ===

=== Đang xử lý chunk 56 ===

=== Đang xử lý chunk 57 ===

=== Đang xử lý chunk 58 ===

=== Đang xử lý chunk 59 ===

=== Đang xử lý chunk 60 ===

=== Đang xử lý chunk 61 ===

=== Đang xử lý chunk 62 ===

=== Đang xử lý chunk 63 ===

=== Đang xử lý chunk 64 ===

=== Đang xử lý chunk 65 ===

=== Đang xử lý chunk 66 ===

=== Đang xử lý chunk 67 ===

=== Đang xử lý chunk 68 ===

=== Đang xử lý chunk 69 ===

=== Đang xử lý chunk 70 ===

=== Đang xử lý chunk 71 ===

=== Đang xử lý chunk 72 ===

=== Đang xử lý chunk 73 ===

=== Đang xử lý chunk 74 ===

=== Đang xử lý chunk 75 ===

=== Đang xử lý chunk 76 ===

=== Đang xử lý chunk 77 ===

=== Đang xử lý chunk 78 ===

=== Đang xử lý chunk 79 ===

=== Hoàn thành xử lý tất cả transaction chunks ===

In [49]:
# 5. AGG FINAL PER CUSTOMER

customer_agg_all = pl.concat(customer_agg_chunks, how="vertical")

customer_final = (
    customer_agg_all
    .group_by("customer_id")
    .agg([
        pl.col("sum_unique_categories").sum().alias("total_unique_categories"),
        pl.col("num_days").sum().alias("total_days")
    ])
    .with_columns(
        (pl.col("total_unique_categories") / pl.col("total_days"))
        .alias("avg_categories_per_day")
    )
)

print("Số khách hàng:", customer_final.height)

Số khách hàng: 2569978

In [50]:
# 6. KMEANS CLUSTERING (3 SEGMENTS)
X = customer_final["avg_categories_per_day"].to_numpy().reshape(-1, 1)

kmeans = KMeans(n_clusters=3, random_state=42, n_init="auto")
labels = kmeans.fit_predict(X)

customer_final = customer_final.with_columns(
    pl.Series("buy_segment_raw", labels)
)

# --- Remap cluster theo thứ tự centroid ---
cluster_stats = (
    customer_final
    .group_by("buy_segment_raw")
    .agg(pl.col("avg_categories_per_day").mean().alias("mean_avg"))
    .sort("mean_avg")
)

mapping = {
    row["buy_segment_raw"]: idx
    for idx, row in enumerate(cluster_stats.iter_rows(named=True))
}

customer_final = customer_final.with_columns(
    pl.col("buy_segment_raw").replace(mapping).alias("buy_segment")
)

In [51]:
# Bảng tổng hợp theo segment

segment_summary = (
    customer_final
    .group_by("buy_segment")
    .agg([
        pl.count().alias("num_customers"),
        pl.col("avg_categories_per_day").min().alias("min_avg"),
        pl.col("avg_categories_per_day").median().alias("median_avg"),
        pl.col("avg_categories_per_day").mean().alias("mean_avg"),
        pl.col("avg_categories_per_day").max().alias("max_avg"),
    ])
    .sort("buy_segment")
)

print("=== SUMMARY THEO SEGMENT ===")
print(segment_summary)

=== SUMMARY THEO SEGMENT ===
shape: (3, 6)
┌─────────────┬───────────────┬──────────┬────────────┬──────────┬──────────┐
│ buy_segment ┆ num_customers ┆ min_avg  ┆ median_avg ┆ mean_avg ┆ max_avg  │
│ ---         ┆ ---           ┆ ---      ┆ ---        ┆ ---      ┆ ---      │
│ i32         ┆ u32           ┆ f64      ┆ f64        ┆ f64      ┆ f64      │
╞═════════════╪═══════════════╪══════════╪════════════╪══════════╪══════════╡
│ 0           ┆ 1663256       ┆ 1.0      ┆ 1.0        ┆ 1.069234 ┆ 1.421569 │
│ 1           ┆ 778872        ┆ 1.421687 ┆ 1.75       ┆ 1.775453 ┆ 2.495413 │
│ 2           ┆ 127850        ┆ 2.5      ┆ 3.0        ┆ 3.219877 ┆ 11.0     │
└─────────────┴───────────────┴──────────┴────────────┴──────────┴──────────┘

C:\Users\PC\AppData\Local\Temp\ipykernel_500\1147667939.py:7: DeprecationWarning: `pl.count()` is deprecated. Please use `pl.len()` instead.
(Deprecated in version 0.20.5)
  pl.count().alias("num_customers"),

In [52]:
# In mẫu khách hàng mỗi segment

for seg in [0, 1, 2]:
    print(f"\n=== SAMPLE SEGMENT {seg} ===")
    print(
        customer_final
        .filter(pl.col("buy_segment") == seg)
        .select(["customer_id", "avg_categories_per_day"])
        .sort("avg_categories_per_day")
        .head(10)
    )

=== SAMPLE SEGMENT 0 ===
shape: (10, 2)
┌─────────────┬────────────────────────┐
│ customer_id ┆ avg_categories_per_day │
│ ---         ┆ ---                    │
│ i32         ┆ f64                    │
╞═════════════╪════════════════════════╡
│ 4610623     ┆ 1.0                    │
│ 7225148     ┆ 1.0                    │
│ 8276276     ┆ 1.0                    │
│ 7905693     ┆ 1.0                    │
│ 7141629     ┆ 1.0                    │
│ 7384528     ┆ 1.0                    │
│ 8291344     ┆ 1.0                    │
│ 7407724     ┆ 1.0                    │
│ 8008067     ┆ 1.0                    │
│ 7121720     ┆ 1.0                    │
└─────────────┴────────────────────────┘

=== SAMPLE SEGMENT 1 ===
shape: (10, 2)
┌─────────────┬────────────────────────┐
│ customer_id ┆ avg_categories_per_day │
│ ---         ┆ ---                    │
│ i32         ┆ f64                    │
╞═════════════╪════════════════════════╡
│ 6374055     ┆ 1.421687               │
│ 3303190     ┆ 1.421687               │
│ 5880663     ┆ 1.421687               │
│ 3673288     ┆ 1.421687               │
│ 5722105     ┆ 1.421687               │
│ 7251317     ┆ 1.421687               │
│ 4090520     ┆ 1.421687               │
│ 1979666     ┆ 1.421687               │
│ 5688674     ┆ 1.421687               │
│ 6753992     ┆ 1.421687               │
└─────────────┴────────────────────────┘

=== SAMPLE SEGMENT 2 ===
shape: (10, 2)
┌─────────────┬────────────────────────┐
│ customer_id ┆ avg_categories_per_day │
│ ---         ┆ ---                    │
│ i32         ┆ f64                    │
╞═════════════╪════════════════════════╡
│ 7939256     ┆ 2.5                    │
│ 7958656     ┆ 2.5                    │
│ 874462      ┆ 2.5                    │
│ 7782109     ┆ 2.5                    │
│ 651621      ┆ 2.5                    │
│ 5905174     ┆ 2.5                    │
│ 8139178     ┆ 2.5                    │
│ 5561476     ┆ 2.5                    │
│ 8035083     ┆ 2.5                    │
│ 8104808     ┆ 2.5                    │
└─────────────┴────────────────────────┘

In [53]:
segment_counts = (
    customer_final
    .group_by("buy_segment")
    .agg(
        pl.count().alias("num_customers")
    )
    .sort("buy_segment")
)

print("=== SỐ LƯỢNG KHÁCH HÀNG THEO SEGMENT ===")
print(segment_counts)

=== SỐ LƯỢNG KHÁCH HÀNG THEO SEGMENT ===
shape: (3, 2)
┌─────────────┬───────────────┐
│ buy_segment ┆ num_customers │
│ ---         ┆ ---           │
│ i32         ┆ u32           │
╞═════════════╪═══════════════╡
│ 0           ┆ 1663256       │
│ 1           ┆ 778872        │
│ 2           ┆ 127850        │
└─────────────┴───────────────┘

C:\Users\PC\AppData\Local\Temp\ipykernel_500\3131816565.py:5: DeprecationWarning: `pl.count()` is deprecated. Please use `pl.len()` instead.
(Deprecated in version 0.20.5)
  pl.count().alias("num_customers")

In [54]:
customer_final

shape: (2_569_978, 6)
┌─────────────┬───────────────────┬────────────┬───────────────────┬─────────────────┬─────────────┐
│ customer_id ┆ total_unique_cate ┆ total_days ┆ avg_categories_pe ┆ buy_segment_raw ┆ buy_segment │
│ ---         ┆ gories            ┆ ---        ┆ r_day             ┆ ---             ┆ ---         │
│ i32         ┆ ---               ┆ u32        ┆ ---               ┆ i32             ┆ i32         │
│             ┆ u32               ┆            ┆ f64               ┆                 ┆             │
╞═════════════╪═══════════════════╪════════════╪═══════════════════╪═════════════════╪═════════════╡
│ 4610623     ┆ 1                 ┆ 1          ┆ 1.0               ┆ 0               ┆ 0           │
│ 7225148     ┆ 1                 ┆ 1          ┆ 1.0               ┆ 0               ┆ 0           │
│ 8276276     ┆ 1                 ┆ 1          ┆ 1.0               ┆ 0               ┆ 0           │
│ 7905693     ┆ 1                 ┆ 1          ┆ 1.0               ┆ 0               ┆ 0           │
│ 7144273     ┆ 3                 ┆ 2          ┆ 1.5               ┆ 2               ┆ 1           │
│ …           ┆ …                 ┆ …          ┆ …                 ┆ …               ┆ …           │
│ 7366664     ┆ 9                 ┆ 5          ┆ 1.8               ┆ 2               ┆ 1           │
│ 1391920     ┆ 1                 ┆ 1          ┆ 1.0               ┆ 0               ┆ 0           │
│ 4511223     ┆ 3                 ┆ 1          ┆ 3.0               ┆ 1               ┆ 2           │
│ 5822283     ┆ 81                ┆ 56         ┆ 1.446429          ┆ 2               ┆ 1           │
│ 236846      ┆ 11                ┆ 8          ┆ 1.375             ┆ 0               ┆ 0           │
└─────────────┴───────────────────┴────────────┴───────────────────┴─────────────────┴─────────────┘

In [55]:
customer_final = customer_final.drop("buy_segment_raw")

In [56]:
customer_final

shape: (2_569_978, 5)
┌─────────────┬─────────────────────────┬────────────┬────────────────────────┬─────────────┐
│ customer_id ┆ total_unique_categories ┆ total_days ┆ avg_categories_per_day ┆ buy_segment │
│ ---         ┆ ---                     ┆ ---        ┆ ---                    ┆ ---         │
│ i32         ┆ u32                     ┆ u32        ┆ f64                    ┆ i32         │
╞═════════════╪═════════════════════════╪════════════╪════════════════════════╪═════════════╡
│ 4610623     ┆ 1                       ┆ 1          ┆ 1.0                    ┆ 0           │
│ 7225148     ┆ 1                       ┆ 1          ┆ 1.0                    ┆ 0           │
│ 8276276     ┆ 1                       ┆ 1          ┆ 1.0                    ┆ 0           │
│ 7905693     ┆ 1                       ┆ 1          ┆ 1.0                    ┆ 0           │
│ 7144273     ┆ 3                       ┆ 2          ┆ 1.5                    ┆ 1           │
│ …           ┆ …                       ┆ …          ┆ …                      ┆ …           │
│ 7366664     ┆ 9                       ┆ 5          ┆ 1.8                    ┆ 1           │
│ 1391920     ┆ 1                       ┆ 1          ┆ 1.0                    ┆ 0           │
│ 4511223     ┆ 3                       ┆ 1          ┆ 3.0                    ┆ 2           │
│ 5822283     ┆ 81                      ┆ 56         ┆ 1.446429               ┆ 1           │
│ 236846      ┆ 11                      ┆ 8          ┆ 1.375                  ┆ 0           │
└─────────────┴─────────────────────────┴────────────┴────────────────────────┴─────────────┘

In [59]:
# 7. SAVE
os.makedirs(os.path.dirname(OUTPUT_PATH), exist_ok=True)
customer_final.select(
    ["customer_id", "avg_categories_per_day", "buy_segment"]
).write_parquet(OUTPUT_PATH)

print("Đã lưu file:", OUTPUT_PATH)

Đã lưu file: D:\003. HK1 - Năm 3\02. CS116 - Python cho Máy học\CS116-DoAn\Phase-3\Feature engineering\customer_behavior_202401_202501.parquet

### **Đặc trưng:** Mức độ cao cấp của khách hàng - dựa trên "Sữa", "Tã"
- Bước 1: Gom nhóm giá các mặt hàng có category_l1 = 'sữa' theo các nhãn "Bình dân", "Trung cấp" và "cao cấp".

- Bước 2: Thống kê xem khách hàng đó mua sữa thuộc nhóm nào nhiều nhất để gán nhãn cho khách hàng đó.

In [60]:
# 1. PATHS (PHASE 3)

ITEM_PATH = r"D:\003. HK1 - Năm 3\02. CS116 - Python cho Máy học\CS116-DoAn\Phase-3\Feature engineering\sale_pers.item_chunk_0.parquet"

TX_DIR = r"D:\003. HK1 - Năm 3\02. CS116 - Python cho Máy học\CS116-DoAn\Phase-3\preprocessing data"
TX_PATTERN = "sale_pers.purchase_history_daily_chunk_{}.parquet"

OUTPUT_PATH = r"D:\003. HK1 - Năm 3\02. CS116 - Python cho Máy học\CS116-DoAn\Phase-3\Feature engineering\customer_luxury_202401_202501.parquet"

In [61]:
# 2. TIME WINDOW

START_DATE = datetime(2024, 1, 1)
END_DATE   = datetime(2025, 1, 31)

In [62]:
# 3. LOAD ITEM (CHỈ GIỮ CẦN THIẾT)

df_item = pl.read_parquet(
    ITEM_PATH,
    columns=["item_id", "category_l1", "price_segment"]
)

print("ITEM shape:", df_item.shape)
print(df_item.select(["category_l1", "price_segment"]).unique())

ITEM shape: (27323, 3)
shape: (45, 2)
┌────────────────────────┬───────────────┐
│ category_l1            ┆ price_segment │
│ ---                    ┆ ---           │
│ str                    ┆ i64           │
╞════════════════════════╪═══════════════╡
│ Babycare               ┆ 1             │
│ Tã                     ┆ 0             │
│ Textile                ┆ 2             │
│ Đồ chơi & Sách         ┆ 1             │
│ Textile                ┆ 1             │
│ …                      ┆ …             │
│ Thực phẩm cho gia đình ┆ 1             │
│ Hóa mỹ phẩm gia đình   ┆ 1             │
│ Thực phẩm cho bé       ┆ 1             │
│ Đồ chơi & Sách         ┆ 0             │
│ Vệ sinh                ┆ 2             │
└────────────────────────┴───────────────┘

In [63]:
# 4. PROCESS TRANSACTION CHUNKS

important_cats = ["Sữa", "Tã"]
customer_seg_chunks = []

for i in range(80):  # 0 → 79
    tx_path = os.path.join(TX_DIR, TX_PATTERN.format(i))
    if not os.path.exists(tx_path):
        continue

    print(f"\n=== Processing chunk {i} ===")

    df_tx = pl.read_parquet(
        tx_path,
        columns=["customer_id", "item_id", "created_date"]
    )

    # --- Lọc thời gian ---
    df_tx = df_tx.filter(
        (pl.col("created_date") >= START_DATE) &
        (pl.col("created_date") <= END_DATE)
    )

    if df_tx.is_empty():
        print("  -> No data in time window, skip")
        continue

    # --- Join item ---
    df_join = df_tx.join(df_item, on="item_id", how="left")

    # --- Lọc Sữa + Tã ---
    df_filtered = df_join.filter(
        pl.col("category_l1").is_in(important_cats)
    )

    if df_filtered.is_empty():
        print("  -> No Sữa / Tã in this chunk")
        continue

    # --- Count purchase theo price_segment ---
    cust_seg = (
        df_filtered
        .group_by(["customer_id", "price_segment"])
        .agg(pl.count().alias("purchase_count"))
    )

    customer_seg_chunks.append(cust_seg)

print("\n=== Done reading all chunks ===")

=== Processing chunk 0 ===

=== Processing chunk 1 ===

=== Processing chunk 2 ===

C:\Users\PC\AppData\Local\Temp\ipykernel_500\1162869475.py:44: DeprecationWarning: `pl.count()` is deprecated. Please use `pl.len()` instead.
(Deprecated in version 0.20.5)
  .agg(pl.count().alias("purchase_count"))

=== Processing chunk 3 ===

=== Processing chunk 4 ===

=== Processing chunk 5 ===

=== Processing chunk 6 ===

=== Processing chunk 7 ===

=== Processing chunk 8 ===

=== Processing chunk 9 ===

=== Processing chunk 10 ===

=== Processing chunk 11 ===

=== Processing chunk 12 ===

=== Processing chunk 13 ===

=== Processing chunk 14 ===

=== Processing chunk 15 ===

=== Processing chunk 16 ===

=== Processing chunk 17 ===

=== Processing chunk 18 ===

=== Processing chunk 19 ===

=== Processing chunk 20 ===

=== Processing chunk 21 ===

=== Processing chunk 22 ===

=== Processing chunk 23 ===

=== Processing chunk 24 ===

=== Processing chunk 25 ===

=== Processing chunk 26 ===

=== Processing chunk 27 ===

=== Processing chunk 28 ===

=== Processing chunk 29 ===

=== Processing chunk 30 ===

=== Processing chunk 31 ===

=== Processing chunk 32 ===

=== Processing chunk 33 ===

=== Processing chunk 34 ===

=== Processing chunk 35 ===

=== Processing chunk 36 ===

=== Processing chunk 37 ===

=== Processing chunk 38 ===

=== Processing chunk 39 ===

=== Processing chunk 40 ===

=== Processing chunk 41 ===

=== Processing chunk 42 ===

=== Processing chunk 43 ===

=== Processing chunk 44 ===

=== Processing chunk 45 ===

=== Processing chunk 46 ===

=== Processing chunk 47 ===

=== Processing chunk 48 ===

=== Processing chunk 49 ===

=== Processing chunk 50 ===

=== Processing chunk 51 ===

=== Processing chunk 52 ===

=== Processing chunk 53 ===

=== Processing chunk 54 ===

=== Processing chunk 55 ===

=== Processing chunk 56 ===

=== Processing chunk 57 ===

=== Processing chunk 58 ===

=== Processing chunk 59 ===

=== Processing chunk 60 ===

=== Processing chunk 61 ===

=== Processing chunk 62 ===

=== Processing chunk 63 ===

=== Processing chunk 64 ===

=== Processing chunk 65 ===

=== Processing chunk 66 ===

=== Processing chunk 67 ===

=== Processing chunk 68 ===

=== Processing chunk 69 ===

=== Processing chunk 70 ===

=== Processing chunk 71 ===

=== Processing chunk 72 ===

=== Processing chunk 73 ===

=== Processing chunk 74 ===

=== Processing chunk 75 ===

=== Processing chunk 76 ===

=== Processing chunk 77 ===

=== Processing chunk 78 ===

=== Processing chunk 79 ===

=== Done reading all chunks ===

In [64]:
# 5. AGG FINAL PER CUSTOMER

customer_seg_all = pl.concat(customer_seg_chunks, how="vertical")

customer_seg_all = (
    customer_seg_all
    .group_by(["customer_id", "price_segment"])
    .agg(pl.col("purchase_count").sum())
)

print("\n=== SAMPLE customer x price_segment ===")
print(customer_seg_all.head(10))

=== SAMPLE customer x price_segment ===
shape: (10, 3)
┌─────────────┬───────────────┬────────────────┐
│ customer_id ┆ price_segment ┆ purchase_count │
│ ---         ┆ ---           ┆ ---            │
│ i32         ┆ i64           ┆ u32            │
╞═════════════╪═══════════════╪════════════════╡
│ 6410373     ┆ 0             ┆ 3              │
│ 7402309     ┆ 1             ┆ 1              │
│ 3961256     ┆ 0             ┆ 1              │
│ 7163318     ┆ 0             ┆ 1              │
│ 2571150     ┆ 1             ┆ 1              │
│ 2507640     ┆ 1             ┆ 21             │
│ 4167887     ┆ 0             ┆ 3              │
│ 815360      ┆ 1             ┆ 6              │
│ 7712471     ┆ 1             ┆ 1              │
│ 3088089     ┆ 1             ┆ 1              │
└─────────────┴───────────────┴────────────────┘

In [65]:
# 6. PIVOT + LUXURY LEVEL

customer_pivot = (
    customer_seg_all
    .pivot(
        index="customer_id",
        columns="price_segment",
        values="purchase_count",
        aggregate_function="first"
    )
    .fill_null(0)
    .rename({
        "0": "seg_0",   # Bình dân
        "1": "seg_1",   # Trung cấp
        "2": "seg_2",   # Cao cấp
    })
)

print("\n=== PIVOT TABLE (SAMPLE) ===")
print(customer_pivot.head(10))

customer_luxury = customer_pivot.with_columns(
    pl.when((pl.col("seg_2") >= pl.col("seg_1")) & (pl.col("seg_2") >= pl.col("seg_0")))
        .then(2)
    .when((pl.col("seg_1") >= pl.col("seg_0")) & (pl.col("seg_1") >= pl.col("seg_2")))
        .then(1)
    .otherwise(0)
    .alias("luxury_level")
)

print("\n=== SAMPLE luxury_level ===")
print(customer_luxury.head(10))

C:\Users\PC\AppData\Local\Temp\ipykernel_500\4280525608.py:5: DeprecationWarning: the argument `columns` for `DataFrame.pivot` is deprecated. It was renamed to `on` in version 1.0.0.
  .pivot(

=== PIVOT TABLE (SAMPLE) ===
shape: (10, 4)
┌─────────────┬───────┬───────┬───────┐
│ customer_id ┆ seg_0 ┆ seg_1 ┆ seg_2 │
│ ---         ┆ ---   ┆ ---   ┆ ---   │
│ i32         ┆ u32   ┆ u32   ┆ u32   │
╞═════════════╪═══════╪═══════╪═══════╡
│ 6410373     ┆ 3     ┆ 2     ┆ 0     │
│ 7402309     ┆ 2     ┆ 1     ┆ 0     │
│ 3961256     ┆ 1     ┆ 0     ┆ 0     │
│ 7163318     ┆ 1     ┆ 5     ┆ 0     │
│ 2571150     ┆ 10    ┆ 1     ┆ 0     │
│ 2507640     ┆ 2     ┆ 21    ┆ 1     │
│ 4167887     ┆ 3     ┆ 9     ┆ 0     │
│ 815360      ┆ 19    ┆ 6     ┆ 0     │
│ 7712471     ┆ 0     ┆ 1     ┆ 0     │
│ 3088089     ┆ 0     ┆ 1     ┆ 0     │
└─────────────┴───────┴───────┴───────┘

=== SAMPLE luxury_level ===
shape: (10, 5)
┌─────────────┬───────┬───────┬───────┬──────────────┐
│ customer_id ┆ seg_0 ┆ seg_1 ┆ seg_2 ┆ luxury_level │
│ ---         ┆ ---   ┆ ---   ┆ ---   ┆ ---          │
│ i32         ┆ u32   ┆ u32   ┆ u32   ┆ i32          │
╞═════════════╪═══════╪═══════╪═══════╪══════════════╡
│ 6410373     ┆ 3     ┆ 2     ┆ 0     ┆ 0            │
│ 7402309     ┆ 2     ┆ 1     ┆ 0     ┆ 0            │
│ 3961256     ┆ 1     ┆ 0     ┆ 0     ┆ 0            │
│ 7163318     ┆ 1     ┆ 5     ┆ 0     ┆ 1            │
│ 2571150     ┆ 10    ┆ 1     ┆ 0     ┆ 0            │
│ 2507640     ┆ 2     ┆ 21    ┆ 1     ┆ 1            │
│ 4167887     ┆ 3     ┆ 9     ┆ 0     ┆ 1            │
│ 815360      ┆ 19    ┆ 6     ┆ 0     ┆ 0            │
│ 7712471     ┆ 0     ┆ 1     ┆ 0     ┆ 1            │
│ 3088089     ┆ 0     ┆ 1     ┆ 0     ┆ 1            │
└─────────────┴───────┴───────┴───────┴──────────────┘

In [66]:
# 7. CHECK PHÂN BỐ

level_counts = (
    customer_luxury
    .group_by("luxury_level")
    .agg(pl.count().alias("num_customers"))
    .sort("luxury_level")
)

print("\n=== SỐ LƯỢNG CUSTOMER THEO LUXURY LEVEL ===")
print(level_counts)

=== SỐ LƯỢNG CUSTOMER THEO LUXURY LEVEL ===
shape: (3, 2)
┌──────────────┬───────────────┐
│ luxury_level ┆ num_customers │
│ ---          ┆ ---           │
│ i32          ┆ u32           │
╞══════════════╪═══════════════╡
│ 0            ┆ 419556        │
│ 1            ┆ 830821        │
│ 2            ┆ 99641         │
└──────────────┴───────────────┘

C:\Users\PC\AppData\Local\Temp\ipykernel_500\2959444835.py:6: DeprecationWarning: `pl.count()` is deprecated. Please use `pl.len()` instead.
(Deprecated in version 0.20.5)
  .agg(pl.count().alias("num_customers"))

In [67]:
# 8. SAVE CLEAN FEATURE

os.makedirs(os.path.dirname(OUTPUT_PATH), exist_ok=True)

customer_luxury.select(
    ["customer_id", "luxury_level"]
).write_parquet(OUTPUT_PATH)

print("\nĐã lưu file:", OUTPUT_PATH)

Đã lưu file: D:\003. HK1 - Năm 3\02. CS116 - Python cho Máy học\CS116-DoAn\Phase-3\Feature engineering\customer_luxury_202401_202501.parquet

In [ ]:
#==================================================

### **Đặc trưng:** Tuổi hiện tại của bé
Dựa trên age_group, step_1, step_2 và mom

In [69]:
import glob
import re
from datetime import date

In [70]:
ITEM_PATH = r"D:\003. HK1 - Năm 3\02. CS116 - Python cho Máy học\CS116-DoAn\Phase-3\Feature engineering\sale_pers.item_chunk_0.parquet"
TRANS_DIR =  r"D:\003. HK1 - Năm 3\02. CS116 - Python cho Máy học\CS116-DoAn\Phase-3\preprocessing data"

OUTPUT_PATH = r"D:\003. HK1 - Năm 3\02. CS116 - Python cho Máy học\CS116-DoAn\Phase-3\Feature engineering\customer_age_features_2401_2501.parquet"

PREDICTION_DATE = date(2025, 1, 31)

STEP1_AGE_MONTHS = 3.0       # Step1 dùng cho 0–6M → trung bình ~3M
AGE_0_3M_MONTHS = 1.5        # 0–3M → trung bình ~1.5M
MOM_AGE_MONTHS = 0.0         # bạn yêu cầu = 0

In [71]:
print("Đang load ITEM...")
item = pl.read_parquet(ITEM_PATH)

item = item.select([
    "item_id", 
    "category_l1", "category_l2",
    "description_final",
    "age_group_final"
])

item = item.with_columns(
    pl.col("description_final").str.to_lowercase().alias("desc_lc")
)

Đang load ITEM...

In [72]:
# FLAG Step1 (chỉ nhận khi category_l1 = Sữa)

step1_positive = [
    "step 1", "step-1", "step1",
    "stage 1", "stage-1", "stage1",
    "cho bé 0+", "cho bé 0-6", "từ 0 tháng",
    "trẻ sơ sinh", "newborn"
]

step1_negative = [
    "bước 1:"       # chắc chắn là hướng dẫn
]


item = item.with_columns([

    # Positive: chứa 1 trong các pattern
    pl.any_horizontal([
        pl.col("desc_lc").str.contains(pat)
        for pat in step1_positive
    ]).alias("tmp_step1_pos"),

    # Negative
    pl.any_horizontal([
        pl.col("desc_lc").str.contains(pat)
        for pat in step1_negative
    ]).alias("tmp_step1_neg"),
])

item = item.with_columns([
    (
        (pl.col("category_l1") == "Sữa") &
        pl.col("tmp_step1_pos") &
        (~pl.col("tmp_step1_neg"))
    ).alias("is_step1")
]).drop(["tmp_step1_pos", "tmp_step1_neg"])

In [73]:
item.select(
    pl.col("is_step1").value_counts()
)

shape: (2, 1)
┌───────────────┐
│ is_step1      │
│ ---           │
│ struct[2]     │
╞═══════════════╡
│ {false,27261} │
│ {true,62}     │
└───────────────┘

In [74]:
# ====== FLAG is_age_0_6M (CHUẨN THEO ĐỊNH NGHĨA CUỐI) ======

item = item.with_columns(
    pl.col("age_group_final")
    .cast(pl.Utf8)
    .str.to_lowercase()
    .alias("age_lc")
)

# (A) RANGE giao [0,6]: min < 6, max <= 6
# Bắt các dạng: 0-3M, 1-5M, 2-6M, 3-6M, 4-6M, 5-6M
regex_range_0_6 = r"\b[0-5]\s*[-–]\s*[1-6]\s*m\b"

# (B) Dạng "Từ xM" với x ∈ {0,1,2,3}
regex_from_0_3 = r"\btừ\s*[0-3]\s*m\b"

item = item.with_columns(
    (
        pl.col("age_lc").str.contains(regex_range_0_6) |
        pl.col("age_lc").str.contains(regex_from_0_3)
    ).alias("is_age_0_3M")
)

In [75]:
item.select(
    pl.col("is_age_0_3M").value_counts()
)

shape: (2, 1)
┌───────────────┐
│ is_age_0_3M   │
│ ---           │
│ struct[2]     │
╞═══════════════╡
│ {false,25839} │
│ {true,1484}   │
└───────────────┘

In [76]:
#FLAG is_mom (cẩn thận ĐẦM BẦU)

mom_positive = [
    #"sữa bầu",
    #"sua bau",
    #"sữa cho mẹ",
    #"dinh dưỡng cho mẹ",
    #"dành cho mẹ",
    "mom"
]


mom_negative = [
    "đầm bầu", "váy bầu", "áo bầu"
]

item = item.with_columns([
    pl.any_horizontal([
        pl.col("desc_lc").str.contains(pat)
        for pat in mom_positive
    ]).alias("tmp_mom_pos"),

    pl.any_horizontal([
        pl.col("desc_lc").str.contains(pat)
        for pat in mom_negative
    ]).alias("tmp_mom_neg"),
])

item = item.with_columns([
    (
        (pl.col("tmp_mom_pos")) & 
        (~pl.col("tmp_mom_neg"))
    ).alias("is_mom")
]).drop(["tmp_mom_pos", "tmp_mom_neg"])

In [77]:
#ĐỌC 20 CHUNK TRANSACTION + JOIN ITEM + TÍNH NGÀY MIN/MAX

transaction_files = sorted(glob.glob(TRANS_DIR + r"\sale_pers.purchase_history_daily_chunk_*.parquet"))
print("Số file transaction:", len(transaction_files))

per_chunk_stats = []

Số file transaction: 80

In [78]:
for file in transaction_files:
    print("Đang xử lý:", file)

    trans = (
        pl.read_parquet(file)
        .select(["item_id", "customer_id", "created_date"])
        .with_columns(pl.col("created_date").cast(pl.Date))
    )

    # JOIN ITEM
    trans_j = trans.join(
        item.select(["item_id", "is_step1", "is_age_0_3M", "is_mom"]),
        on="item_id",
        how="left"
    )

    # AGG theo customer
    stats = (
        trans_j.group_by("customer_id")
        .agg([
            pl.col("created_date").filter(pl.col("is_step1")).min().alias("first_date_buy_step1"),
            pl.col("created_date").filter(pl.col("is_age_0_3M")).min().alias("first_date_buy_age_group_0_3M"),
            pl.col("created_date").filter(pl.col("is_mom")).max().alias("last_date_buy_milk4mom"),
        ])
    )

    per_chunk_stats.append(stats)

Đang xử lý: D:\003. HK1 - Năm 3\02. CS116 - Python cho Máy học\CS116-DoAn\Phase-3\preprocessing data\sale_pers.purchase_history_daily_chunk_0.parquet
Đang xử lý: D:\003. HK1 - Năm 3\02. CS116 - Python cho Máy học\CS116-DoAn\Phase-3\preprocessing data\sale_pers.purchase_history_daily_chunk_1.parquet
Đang xử lý: D:\003. HK1 - Năm 3\02. CS116 - Python cho Máy học\CS116-DoAn\Phase-3\preprocessing data\sale_pers.purchase_history_daily_chunk_10.parquet
Đang xử lý: D:\003. HK1 - Năm 3\02. CS116 - Python cho Máy học\CS116-DoAn\Phase-3\preprocessing data\sale_pers.purchase_history_daily_chunk_11.parquet
Đang xử lý: D:\003. HK1 - Năm 3\02. CS116 - Python cho Máy học\CS116-DoAn\Phase-3\preprocessing data\sale_pers.purchase_history_daily_chunk_12.parquet
Đang xử lý: D:\003. HK1 - Năm 3\02. CS116 - Python cho Máy học\CS116-DoAn\Phase-3\preprocessing data\sale_pers.purchase_history_daily_chunk_13.parquet
Đang xử lý: D:\003. HK1 - Năm 3\02. CS116 - Python cho Máy học\CS116-DoAn\Phase-3\preprocessing data\sale_pers.purchase_history_daily_chunk_14.parquet
Đang xử lý: D:\003. HK1 - Năm 3\02. CS116 - Python cho Máy học\CS116-DoAn\Phase-3\preprocessing data\sale_pers.purchase_history_daily_chunk_15.parquet
Đang xử lý: D:\003. HK1 - Năm 3\02. CS116 - Python cho Máy học\CS116-DoAn\Phase-3\preprocessing data\sale_pers.purchase_history_daily_chunk_16.parquet
Đang xử lý: D:\003. HK1 - Năm 3\02. CS116 - Python cho Máy học\CS116-DoAn\Phase-3\preprocessing data\sale_pers.purchase_history_daily_chunk_17.parquet
Đang xử lý: D:\003. HK1 - Năm 3\02. CS116 - Python cho Máy học\CS116-DoAn\Phase-3\preprocessing data\sale_pers.purchase_history_daily_chunk_18.parquet
Đang xử lý: D:\003. HK1 - Năm 3\02. CS116 - Python cho Máy học\CS116-DoAn\Phase-3\preprocessing data\sale_pers.purchase_history_daily_chunk_19.parquet
Đang xử lý: D:\003. HK1 - Năm 3\02. CS116 - Python cho Máy học\CS116-DoAn\Phase-3\preprocessing data\sale_pers.purchase_history_daily_chunk_2.parquet
Đang xử lý: D:\003. HK1 - Năm 3\02. CS116 - Python cho Máy học\CS116-DoAn\Phase-3\preprocessing data\sale_pers.purchase_history_daily_chunk_20.parquet
Đang xử lý: D:\003. HK1 - Năm 3\02. CS116 - Python cho Máy học\CS116-DoAn\Phase-3\preprocessing data\sale_pers.purchase_history_daily_chunk_21.parquet
Đang xử lý: D:\003. HK1 - Năm 3\02. CS116 - Python cho Máy học\CS116-DoAn\Phase-3\preprocessing data\sale_pers.purchase_history_daily_chunk_22.parquet
Đang xử lý: D:\003. HK1 - Năm 3\02. CS116 - Python cho Máy học\CS116-DoAn\Phase-3\preprocessing data\sale_pers.purchase_history_daily_chunk_23.parquet
Đang xử lý: D:\003. HK1 - Năm 3\02. CS116 - Python cho Máy học\CS116-DoAn\Phase-3\preprocessing data\sale_pers.purchase_history_daily_chunk_24.parquet
Đang xử lý: D:\003. HK1 - Năm 3\02. CS116 - Python cho Máy học\CS116-DoAn\Phase-3\preprocessing data\sale_pers.purchase_history_daily_chunk_25.parquet
Đang xử lý: D:\003. HK1 - Năm 3\02. CS116 - Python cho Máy học\CS116-DoAn\Phase-3\preprocessing data\sale_pers.purchase_history_daily_chunk_26.parquet
Đang xử lý: D:\003. HK1 - Năm 3\02. CS116 - Python cho Máy học\CS116-DoAn\Phase-3\preprocessing data\sale_pers.purchase_history_daily_chunk_27.parquet
Đang xử lý: D:\003. HK1 - Năm 3\02. CS116 - Python cho Máy học\CS116-DoAn\Phase-3\preprocessing data\sale_pers.purchase_history_daily_chunk_28.parquet
Đang xử lý: D:\003. HK1 - Năm 3\02. CS116 - Python cho Máy học\CS116-DoAn\Phase-3\preprocessing data\sale_pers.purchase_history_daily_chunk_29.parquet
Đang xử lý: D:\003. HK1 - Năm 3\02. CS116 - Python cho Máy học\CS116-DoAn\Phase-3\preprocessing data\sale_pers.purchase_history_daily_chunk_3.parquet
Đang xử lý: D:\003. HK1 - Năm 3\02. CS116 - Python cho Máy học\CS116-DoAn\Phase-3\preprocessing data\sale_pers.purchase_history_daily_chunk_30.parquet
Đang xử lý: D:\003. HK1 - Năm 3\02. CS116 - Python cho Máy học\CS116-DoAn\Phase-3\preprocessing data\sale_pers.purchase_history_daily_chunk_31.parquet
Đang xử lý: D:\003. HK1 - Năm 3\02. CS116 - Python cho Máy học\CS116-DoAn\Phase-3\preprocessing data\sale_pers.purchase_history_daily_chunk_32.parquet
Đang xử lý: D:\003. HK1 - Năm 3\02. CS116 - Python cho Máy học\CS116-DoAn\Phase-3\preprocessing data\sale_pers.purchase_history_daily_chunk_33.parquet
Đang xử lý: D:\003. HK1 - Năm 3\02. CS116 - Python cho Máy học\CS116-DoAn\Phase-3\preprocessing data\sale_pers.purchase_history_daily_chunk_34.parquet
Đang xử lý: D:\003. HK1 - Năm 3\02. CS116 - Python cho Máy học\CS116-DoAn\Phase-3\preprocessing data\sale_pers.purchase_history_daily_chunk_35.parquet
Đang xử lý: D:\003. HK1 - Năm 3\02. CS116 - Python cho Máy học\CS116-DoAn\Phase-3\preprocessing data\sale_pers.purchase_history_daily_chunk_36.parquet
Đang xử lý: D:\003. HK1 - Năm 3\02. CS116 - Python cho Máy học\CS116-DoAn\Phase-3\preprocessing data\sale_pers.purchase_history_daily_chunk_37.parquet
Đang xử lý: D:\003. HK1 - Năm 3\02. CS116 - Python cho Máy học\CS116-DoAn\Phase-3\preprocessing data\sale_pers.purchase_history_daily_chunk_38.parquet
Đang xử lý: D:\003. HK1 - Năm 3\02. CS116 - Python cho Máy học\CS116-DoAn\Phase-3\preprocessing data\sale_pers.purchase_history_daily_chunk_39.parquet
Đang xử lý: D:\003. HK1 - Năm 3\02. CS116 - Python cho Máy học\CS116-DoAn\Phase-3\preprocessing data\sale_pers.purchase_history_daily_chunk_4.parquet
Đang xử lý: D:\003. HK1 - Năm 3\02. CS116 - Python cho Máy học\CS116-DoAn\Phase-3\preprocessing data\sale_pers.purchase_history_daily_chunk_40.parquet
Đang xử lý: D:\003. HK1 - Năm 3\02. CS116 - Python cho Máy học\CS116-DoAn\Phase-3\preprocessing data\sale_pers.purchase_history_daily_chunk_41.parquet
Đang xử lý: D:\003. HK1 - Năm 3\02. CS116 - Python cho Máy học\CS116-DoAn\Phase-3\preprocessing data\sale_pers.purchase_history_daily_chunk_42.parquet
Đang xử lý: D:\003. HK1 - Năm 3\02. CS116 - Python cho Máy học\CS116-DoAn\Phase-3\preprocessing data\sale_pers.purchase_history_daily_chunk_43.parquet
Đang xử lý: D:\003. HK1 - Năm 3\02. CS116 - Python cho Máy học\CS116-DoAn\Phase-3\preprocessing data\sale_pers.purchase_history_daily_chunk_44.parquet
Đang xử lý: D:\003. HK1 - Năm 3\02. CS116 - Python cho Máy học\CS116-DoAn\Phase-3\preprocessing data\sale_pers.purchase_history_daily_chunk_45.parquet
Đang xử lý: D:\003. HK1 - Năm 3\02. CS116 - Python cho Máy học\CS116-DoAn\Phase-3\preprocessing data\sale_pers.purchase_history_daily_chunk_46.parquet
Đang xử lý: D:\003. HK1 - Năm 3\02. CS116 - Python cho Máy học\CS116-DoAn\Phase-3\preprocessing data\sale_pers.purchase_history_daily_chunk_47.parquet
Đang xử lý: D:\003. HK1 - Năm 3\02. CS116 - Python cho Máy học\CS116-DoAn\Phase-3\preprocessing data\sale_pers.purchase_history_daily_chunk_48.parquet
Đang xử lý: D:\003. HK1 - Năm 3\02. CS116 - Python cho Máy học\CS116-DoAn\Phase-3\preprocessing data\sale_pers.purchase_history_daily_chunk_49.parquet
Đang xử lý: D:\003. HK1 - Năm 3\02. CS116 - Python cho Máy học\CS116-DoAn\Phase-3\preprocessing data\sale_pers.purchase_history_daily_chunk_5.parquet
Đang xử lý: D:\003. HK1 - Năm 3\02. CS116 - Python cho Máy học\CS116-DoAn\Phase-3\preprocessing data\sale_pers.purchase_history_daily_chunk_50.parquet
Đang xử lý: D:\003. HK1 - Năm 3\02. CS116 - Python cho Máy học\CS116-DoAn\Phase-3\preprocessing data\sale_pers.purchase_history_daily_chunk_51.parquet
Đang xử lý: D:\003. HK1 - Năm 3\02. CS116 - Python cho Máy học\CS116-DoAn\Phase-3\preprocessing data\sale_pers.purchase_history_daily_chunk_52.parquet
Đang xử lý: D:\003. HK1 - Năm 3\02. CS116 - Python cho Máy học\CS116-DoAn\Phase-3\preprocessing data\sale_pers.purchase_history_daily_chunk_53.parquet
Đang xử lý: D:\003. HK1 - Năm 3\02. CS116 - Python cho Máy học\CS116-DoAn\Phase-3\preprocessing data\sale_pers.purchase_history_daily_chunk_54.parquet
Đang xử lý: D:\003. HK1 - Năm 3\02. CS116 - Python cho Máy học\CS116-DoAn\Phase-3\preprocessing data\sale_pers.purchase_history_daily_chunk_55.parquet
Đang xử lý: D:\003. HK1 - Năm 3\02. CS116 - Python cho Máy học\CS116-DoAn\Phase-3\preprocessing data\sale_pers.purchase_history_daily_chunk_56.parquet
Đang xử lý: D:\003. HK1 - Năm 3\02. CS116 - Python cho Máy học\CS116-DoAn\Phase-3\preprocessing data\sale_pers.purchase_history_daily_chunk_57.parquet
Đang xử lý: D:\003. HK1 - Năm 3\02. CS116 - Python cho Máy học\CS116-DoAn\Phase-3\preprocessing data\sale_pers.purchase_history_daily_chunk_58.parquet
Đang xử lý: D:\003. HK1 - Năm 3\02. CS116 - Python cho Máy học\CS116-DoAn\Phase-3\preprocessing data\sale_pers.purchase_history_daily_chunk_59.parquet
Đang xử lý: D:\003. HK1 - Năm 3\02. CS116 - Python cho Máy học\CS116-DoAn\Phase-3\preprocessing data\sale_pers.purchase_history_daily_chunk_6.parquet
Đang xử lý: D:\003. HK1 - Năm 3\02. CS116 - Python cho Máy học\CS116-DoAn\Phase-3\preprocessing data\sale_pers.purchase_history_daily_chunk_60.parquet
Đang xử lý: D:\003. HK1 - Năm 3\02. CS116 - Python cho Máy học\CS116-DoAn\Phase-3\preprocessing data\sale_pers.purchase_history_daily_chunk_61.parquet
Đang xử lý: D:\003. HK1 - Năm 3\02. CS116 - Python cho Máy học\CS116-DoAn\Phase-3\preprocessing data\sale_pers.purchase_history_daily_chunk_62.parquet
Đang xử lý: D:\003. HK1 - Năm 3\02. CS116 - Python cho Máy học\CS116-DoAn\Phase-3\preprocessing data\sale_pers.purchase_history_daily_chunk_63.parquet
Đang xử lý: D:\003. HK1 - Năm 3\02. CS116 - Python cho Máy học\CS116-DoAn\Phase-3\preprocessing data\sale_pers.purchase_history_daily_chunk_64.parquet
Đang xử lý: D:\003. HK1 - Năm 3\02. CS116 - Python cho Máy học\CS116-DoAn\Phase-3\preprocessing data\sale_pers.purchase_history_daily_chunk_65.parquet
Đang xử lý: D:\003. HK1 - Năm 3\02. CS116 - Python cho Máy học\CS116-DoAn\Phase-3\preprocessing data\sale_pers.purchase_history_daily_chunk_66.parquet
Đang xử lý: D:\003. HK1 - Năm 3\02. CS116 - Python cho Máy học\CS116-DoAn\Phase-3\preprocessing data\sale_pers.purchase_history_daily_chunk_67.parquet
Đang xử lý: D:\003. HK1 - Năm 3\02. CS116 - Python cho Máy học\CS116-DoAn\Phase-3\preprocessing data\sale_pers.purchase_history_daily_chunk_68.parquet
Đang xử lý: D:\003. HK1 - Năm 3\02. CS116 - Python cho Máy học\CS116-DoAn\Phase-3\preprocessing data\sale_pers.purchase_history_daily_chunk_69.parquet
Đang xử lý: D:\003. HK1 - Năm 3\02. CS116 - Python cho Máy học\CS116-DoAn\Phase-3\preprocessing data\sale_pers.purchase_history_daily_chunk_7.parquet
Đang xử lý: D:\003. HK1 - Năm 3\02. CS116 - Python cho Máy học\CS116-DoAn\Phase-3\preprocessing data\sale_pers.purchase_history_daily_chunk_70.parquet
Đang xử lý: D:\003. HK1 - Năm 3\02. CS116 - Python cho Máy học\CS116-DoAn\Phase-3\preprocessing data\sale_pers.purchase_history_daily_chunk_71.parquet
Đang xử lý: D:\003. HK1 - Năm 3\02. CS116 - Python cho Máy học\CS116-DoAn\Phase-3\preprocessing data\sale_pers.purchase_history_daily_chunk_72.parquet
Đang xử lý: D:\003. HK1 - Năm 3\02. CS116 - Python cho Máy học\CS116-DoAn\Phase-3\preprocessing data\sale_pers.purchase_history_daily_chunk_73.parquet
Đang xử lý: D:\003. HK1 - Năm 3\02. CS116 - Python cho Máy học\CS116-DoAn\Phase-3\preprocessing data\sale_pers.purchase_history_daily_chunk_74.parquet
Đang xử lý: D:\003. HK1 - Năm 3\02. CS116 - Python cho Máy học\CS116-DoAn\Phase-3\preprocessing data\sale_pers.purchase_history_daily_chunk_75.parquet
Đang xử lý: D:\003. HK1 - Năm 3\02. CS116 - Python cho Máy học\CS116-DoAn\Phase-3\preprocessing data\sale_pers.purchase_history_daily_chunk_76.parquet
Đang xử lý: D:\003. HK1 - Năm 3\02. CS116 - Python cho Máy học\CS116-DoAn\Phase-3\preprocessing data\sale_pers.purchase_history_daily_chunk_77.parquet
Đang xử lý: D:\003. HK1 - Năm 3\02. CS116 - Python cho Máy học\CS116-DoAn\Phase-3\preprocessing data\sale_pers.purchase_history_daily_chunk_78.parquet
Đang xử lý: D:\003. HK1 - Năm 3\02. CS116 - Python cho Máy học\CS116-DoAn\Phase-3\preprocessing data\sale_pers.purchase_history_daily_chunk_79.parquet
Đang xử lý: D:\003. HK1 - Năm 3\02. CS116 - Python cho Máy học\CS116-DoAn\Phase-3\preprocessing data\sale_pers.purchase_history_daily_chunk_8.parquet
Đang xử lý: D:\003. HK1 - Năm 3\02. CS116 - Python cho Máy học\CS116-DoAn\Phase-3\preprocessing data\sale_pers.purchase_history_daily_chunk_9.parquet

In [79]:
#GỘP KẾT QUẢ CHUNK + LẤY MIN/MAX CUỐI CÙNG

print("\n=== Gộp tất cả chunk lại ===")
customer_dates_all = pl.concat(per_chunk_stats, how="vertical_relaxed")
print("Shape sau gộp:", customer_dates_all.shape)


customer_dates_final = (
    customer_dates_all
    .group_by("customer_id")
    .agg([
        pl.col("first_date_buy_step1").min().alias("first_date_buy_step1"),
        pl.col("first_date_buy_age_group_0_3M").min().alias("first_date_buy_age_group_0_3M"),
        pl.col("last_date_buy_milk4mom").max().alias("last_date_buy_milk4mom"),
    ])
)

=== Gộp tất cả chunk lại ===
Shape sau gộp: (15859985, 4)

In [80]:
print("\n=== 20 dòng mẫu có thông tin tuổi ===")
sample_nonnull = customer_dates_final.filter(
    pl.col("first_date_buy_step1").is_not_null() |
    pl.col("first_date_buy_age_group_0_3M").is_not_null() |
    pl.col("last_date_buy_milk4mom").is_not_null()
).head(20)

print(sample_nonnull)

=== 20 dòng mẫu có thông tin tuổi ===
shape: (20, 4)
┌─────────────┬──────────────────────┬───────────────────────────────┬────────────────────────┐
│ customer_id ┆ first_date_buy_step1 ┆ first_date_buy_age_group_0_3M ┆ last_date_buy_milk4mom │
│ ---         ┆ ---                  ┆ ---                           ┆ ---                    │
│ i32         ┆ date                 ┆ date                          ┆ date                   │
╞═════════════╪══════════════════════╪═══════════════════════════════╪════════════════════════╡
│ 6704093     ┆ null                 ┆ 2024-02-03                    ┆ null                   │
│ 8171285     ┆ 2025-01-14           ┆ null                          ┆ null                   │
│ 2692649     ┆ null                 ┆ 2024-05-19                    ┆ null                   │
│ 2503898     ┆ null                 ┆ 2024-06-10                    ┆ null                   │
│ 6673701     ┆ null                 ┆ 2024-11-02                    ┆ 2024-11-02             │
│ …           ┆ …                    ┆ …                             ┆ …                      │
│ 7793893     ┆ null                 ┆ 2024-12-14                    ┆ null                   │
│ 7895621     ┆ null                 ┆ 2024-12-06                    ┆ null                   │
│ 3960857     ┆ null                 ┆ 2024-10-10                    ┆ null                   │
│ 7580097     ┆ null                 ┆ 2024-06-07                    ┆ null                   │
│ 6213198     ┆ null                 ┆ 2024-03-27                    ┆ null                   │
└─────────────┴──────────────────────┴───────────────────────────────┴────────────────────────┘

In [81]:
# TÍNH TUỔI HIỆN TẠI (age_by_*)
pred_date_lit = pl.lit(PREDICTION_DATE).cast(pl.Date)

customer_with_age = (
    customer_dates_final
    .with_columns([
        # Lấy số ngày từ hiệu hai ngày
        (pred_date_lit - pl.col("first_date_buy_step1")).dt.total_days().alias("days_from_step1"),
        (pred_date_lit - pl.col("first_date_buy_age_group_0_3M")).dt.total_days().alias("days_from_age_group"),
        (pred_date_lit - pl.col("last_date_buy_milk4mom")).dt.total_days().alias("days_from_milk4mom"),
    ])
    .with_columns([
        (pl.col("days_from_step1") / 30).alias("months_from_step1"),
        (pl.col("days_from_age_group") / 30).alias("months_from_age_group"),
        (pl.col("days_from_milk4mom") / 30).alias("months_from_milk4mom"),
    ])
    .with_columns([
        # FINAL AGE
        (STEP1_AGE_MONTHS + pl.col("months_from_step1")).alias("age_by_step1"),
        (AGE_0_3M_MONTHS + pl.col("months_from_age_group")).alias("age_by_age_group"),
        (MOM_AGE_MONTHS + pl.col("months_from_milk4mom")).alias("age_by_milk4mom"),
    ])
    .select([
        "customer_id",
        "first_date_buy_step1", "age_by_step1",
        "first_date_buy_age_group_0_3M", "age_by_age_group",
        "last_date_buy_milk4mom", "age_by_milk4mom",
    ])
)

In [82]:
# check

print("\n=== THỐNG KÊ NON-NULL ===")

print("Có Step1:", customer_with_age.filter(pl.col("age_by_step1").is_not_null()).height)
print("Có age_group 0–3M:", customer_with_age.filter(pl.col("age_by_age_group").is_not_null()).height)
print("Có Mom:", customer_with_age.filter(pl.col("age_by_milk4mom").is_not_null()).height)

=== THỐNG KÊ NON-NULL ===
Có Step1: 337570
Có age_group 0–3M: 949335
Có Mom: 175153

In [83]:
# check

print("\n=== Mẫu khách có cả 3 tín hiệu ===")
print(
    customer_with_age
    .filter(
        pl.col("age_by_step1").is_not_null() &
        pl.col("age_by_age_group").is_not_null() &
        pl.col("age_by_milk4mom").is_not_null()
    )
    .head(20)
)

=== Mẫu khách có cả 3 tín hiệu ===
shape: (20, 7)
┌─────────────┬──────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┐
│ customer_id ┆ first_date_b ┆ age_by_step ┆ first_date_ ┆ age_by_age_ ┆ last_date_b ┆ age_by_milk │
│ ---         ┆ uy_step1     ┆ 1           ┆ buy_age_gro ┆ group       ┆ uy_milk4mom ┆ 4mom        │
│ i32         ┆ ---          ┆ ---         ┆ up_0_3M     ┆ ---         ┆ ---         ┆ ---         │
│             ┆ date         ┆ f64         ┆ ---         ┆ f64         ┆ date        ┆ f64         │
│             ┆              ┆             ┆ date        ┆             ┆             ┆             │
╞═════════════╪══════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╡
│ 4680482     ┆ 2024-03-30   ┆ 13.233333   ┆ 2024-01-07  ┆ 14.5        ┆ 2025-01-22  ┆ 0.3         │
│ 7416647     ┆ 2024-04-26   ┆ 12.333333   ┆ 2024-04-26  ┆ 10.833333   ┆ 2024-06-28  ┆ 7.233333    │
│ 3496055     ┆ 2024-12-19   ┆ 4.433333    ┆ 2024-01-09  ┆ 14.433333   ┆ 2024-05-02  ┆ 9.133333    │
│ 7330785     ┆ 2024-05-29   ┆ 11.233333   ┆ 2024-03-24  ┆ 11.933333   ┆ 2024-05-13  ┆ 8.766667    │
│ 7843974     ┆ 2024-09-05   ┆ 7.933333    ┆ 2024-09-05  ┆ 6.433333    ┆ 2024-09-16  ┆ 4.566667    │
│ …           ┆ …            ┆ …           ┆ …           ┆ …           ┆ …           ┆ …           │
│ 3082346     ┆ 2024-09-29   ┆ 7.133333    ┆ 2024-08-13  ┆ 7.2         ┆ 2024-08-13  ┆ 5.7         │
│ 3482940     ┆ 2024-02-04   ┆ 15.066667   ┆ 2024-01-13  ┆ 14.3        ┆ 2025-01-14  ┆ 0.566667    │
│ 7964819     ┆ 2025-01-11   ┆ 3.666667    ┆ 2025-01-02  ┆ 2.466667    ┆ 2024-12-01  ┆ 2.033333    │
│ 7263034     ┆ 2024-03-13   ┆ 13.8        ┆ 2024-03-07  ┆ 12.5        ┆ 2024-10-25  ┆ 3.266667    │
│ 3489749     ┆ 2024-10-21   ┆ 6.4         ┆ 2024-08-01  ┆ 7.6         ┆ 2024-11-24  ┆ 2.266667    │
└─────────────┴──────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┘

In [84]:
print("\n=== Random 20 khách có cả 3 tín hiệu ===")
print(
    customer_with_age
    .filter(
        pl.col("age_by_step1").is_not_null() &
        pl.col("age_by_age_group").is_not_null() &
        pl.col("age_by_milk4mom").is_not_null()
    )
    .sample(n=20, with_replacement=False)
)

=== Random 20 khách có cả 3 tín hiệu ===
shape: (20, 7)
┌─────────────┬──────────────┬─────────────┬─────────────┬─────────────┬─────────────┬─────────────┐
│ customer_id ┆ first_date_b ┆ age_by_step ┆ first_date_ ┆ age_by_age_ ┆ last_date_b ┆ age_by_milk │
│ ---         ┆ uy_step1     ┆ 1           ┆ buy_age_gro ┆ group       ┆ uy_milk4mom ┆ 4mom        │
│ i32         ┆ ---          ┆ ---         ┆ up_0_3M     ┆ ---         ┆ ---         ┆ ---         │
│             ┆ date         ┆ f64         ┆ ---         ┆ f64         ┆ date        ┆ f64         │
│             ┆              ┆             ┆ date        ┆             ┆             ┆             │
╞═════════════╪══════════════╪═════════════╪═════════════╪═════════════╪═════════════╪═════════════╡
│ 6202351     ┆ 2024-05-04   ┆ 12.066667   ┆ 2024-01-14  ┆ 14.266667   ┆ 2024-04-30  ┆ 9.2         │
│ 6699420     ┆ 2024-01-26   ┆ 15.366667   ┆ 2024-04-07  ┆ 11.466667   ┆ 2024-02-05  ┆ 12.033333   │
│ 3782696     ┆ 2024-01-09   ┆ 15.933333   ┆ 2024-01-09  ┆ 14.433333   ┆ 2024-04-17  ┆ 9.633333    │
│ 6648906     ┆ 2024-08-19   ┆ 8.5         ┆ 2024-01-14  ┆ 14.266667   ┆ 2025-01-06  ┆ 0.833333    │
│ 1809037     ┆ 2025-01-27   ┆ 3.133333    ┆ 2024-06-20  ┆ 9.0         ┆ 2024-06-20  ┆ 7.5         │
│ …           ┆ …            ┆ …           ┆ …           ┆ …           ┆ …           ┆ …           │
│ 2819255     ┆ 2024-01-26   ┆ 15.366667   ┆ 2024-03-27  ┆ 11.833333   ┆ 2024-03-27  ┆ 10.333333   │
│ 7862841     ┆ 2024-10-11   ┆ 6.733333    ┆ 2024-11-18  ┆ 3.966667    ┆ 2024-09-11  ┆ 4.733333    │
│ 397887      ┆ 2024-09-10   ┆ 7.766667    ┆ 2024-07-31  ┆ 7.633333    ┆ 2024-12-30  ┆ 1.066667    │
│ 6703946     ┆ 2024-01-25   ┆ 15.4        ┆ 2024-01-09  ┆ 14.433333   ┆ 2024-01-09  ┆ 12.933333   │
│ 3712457     ┆ 2024-02-06   ┆ 15.0        ┆ 2024-01-04  ┆ 14.6        ┆ 2024-07-20  ┆ 6.5         │
└─────────────┴──────────────┴─────────────┴─────────────┴─────────────┴─────────────┴─────────────┘

 **age_by_milk4mom không tốt lắm nên không dùng nó để tạo cột tuổi trung bình cuối cùng.**

In [85]:
total_customers = customer_with_age.select(
    pl.col("customer_id").n_unique()
).item()

print("Tổng số customer:", total_customers)

Tổng số customer: 2569978

In [86]:
customers_with_baby_signal = (
    customer_with_age
    .filter(
        pl.col("age_by_step1").is_not_null() |
        pl.col("age_by_age_group").is_not_null()
    )
    .select(pl.col("customer_id").n_unique())
    .item()
)

print("Customer có ít nhất 1 tín hiệu em bé:", customers_with_baby_signal)

Customer có ít nhất 1 tín hiệu em bé: 1015961

Chỉ xét có cả 2:
- <=3 tháng  : 222,030  (~87.4%)
- 3–6 tháng : 22,130   (~8.7%)
- >6 tháng  : 9,980    (~3.9%)

In [87]:
# tìm ra những khách hàng có cả age_by_step1 và age_by_age_group, tính độ lệch

print(
    customer_with_age
    .filter(
        pl.col("age_by_step1").is_not_null() &
        pl.col("age_by_age_group").is_not_null()
    )
    .select(
        (pl.col("age_by_step1") - pl.col("age_by_age_group")).abs().alias("diff")
    )
    .describe()
)

shape: (9, 2)
┌────────────┬──────────┐
│ statistic  ┆ diff     │
│ ---        ┆ ---      │
│ str        ┆ f64      │
╞════════════╪══════════╡
│ count      ┆ 270944.0 │
│ null_count ┆ 0.0      │
│ mean       ┆ 1.94253  │
│ std        ┆ 1.725645 │
│ min        ┆ 0.0      │
│ 25%        ┆ 1.466667 │
│ 50%        ┆ 1.5      │
│ 75%        ┆ 1.6      │
│ max        ┆ 14.6     │
└────────────┴──────────┘

- Trung bình thì lệch tầm 1.7 tháng (mean = 1.67 (tháng))
- Có outlier khá mạnh (max = 10.67 tháng)

In [88]:
# Các khách hàng có độ lệch lớn nhất
large_diff = (
    customer_with_age
    .filter(
        pl.col("age_by_step1").is_not_null() &
        pl.col("age_by_age_group").is_not_null()
    )
    .with_columns(
        (pl.col("age_by_step1") - pl.col("age_by_age_group"))
        .abs()
        .alias("diff")
    )
    .sort("diff", descending=True)
)

print("\n=== TOP 20 khách hàng có độ lệch tuổi lớn nhất ===")
print(
    large_diff.select([
        "customer_id",
        "first_date_buy_step1",
        "age_by_step1",
        "first_date_buy_age_group_0_3M",
        "age_by_age_group",
        "diff"
    ]).head(20)
)

=== TOP 20 khách hàng có độ lệch tuổi lớn nhất ===
shape: (20, 6)
┌─────────────┬───────────────────┬──────────────┬──────────────────┬──────────────────┬───────────┐
│ customer_id ┆ first_date_buy_st ┆ age_by_step1 ┆ first_date_buy_a ┆ age_by_age_group ┆ diff      │
│ ---         ┆ ep1               ┆ ---          ┆ ge_group_0_3M    ┆ ---              ┆ ---       │
│ i32         ┆ ---               ┆ f64          ┆ ---              ┆ f64              ┆ f64       │
│             ┆ date              ┆              ┆ date             ┆                  ┆           │
╞═════════════╪═══════════════════╪══════════════╪══════════════════╪══════════════════╪═══════════╡
│ 6714164     ┆ 2024-01-03        ┆ 16.133333    ┆ 2025-01-30       ┆ 1.533333         ┆ 14.6      │
│ 3823697     ┆ 2024-01-04        ┆ 16.1         ┆ 2025-01-30       ┆ 1.533333         ┆ 14.566667 │
│ 647928      ┆ 2024-01-02        ┆ 16.166667    ┆ 2025-01-28       ┆ 1.6              ┆ 14.566667 │
│ 6373792     ┆ 2024-01-01        ┆ 16.2         ┆ 2025-01-26       ┆ 1.666667         ┆ 14.533333 │
│ 6186027     ┆ 2024-01-01        ┆ 16.2         ┆ 2025-01-26       ┆ 1.666667         ┆ 14.533333 │
│ …           ┆ …                 ┆ …            ┆ …                ┆ …                ┆ …         │
│ 5030957     ┆ 2024-01-06        ┆ 16.033333    ┆ 2025-01-27       ┆ 1.633333         ┆ 14.4      │
│ 5886347     ┆ 2024-01-06        ┆ 16.033333    ┆ 2025-01-27       ┆ 1.633333         ┆ 14.4      │
│ 6414206     ┆ 2024-01-02        ┆ 16.166667    ┆ 2025-01-23       ┆ 1.766667         ┆ 14.4      │
│ 4221471     ┆ 2024-01-05        ┆ 16.066667    ┆ 2025-01-25       ┆ 1.7              ┆ 14.366667 │
│ 683179      ┆ 2024-01-05        ┆ 16.066667    ┆ 2025-01-25       ┆ 1.7              ┆ 14.366667 │
└─────────────┴───────────────────┴──────────────┴──────────────────┴──────────────────┴───────────┘

In [89]:
# Đếm số khách hàng có độ lệch > 6 tháng
num_diff_gt_10 = (
    large_diff
    .filter(pl.col("diff") > 5)
    .select(pl.count())
    .item()
)

print(f"\n=== Số khách hàng có |age_by_step1 - age_by_age_group| > 5 tháng ===")
print(num_diff_gt_10)

=== Số khách hàng có |age_by_step1 - age_by_age_group| > 5 tháng ===
17661

C:\Users\PC\AppData\Local\Temp\ipykernel_500\578139962.py:5: DeprecationWarning: `pl.count()` is deprecated. Please use `pl.len()` instead.
(Deprecated in version 0.20.5)
  .select(pl.count())

In [90]:
customer_with_age = customer_with_age.with_columns([
    # Tính độ lệch nếu có đủ 2 tín hiệu
    pl.when(
        pl.col("age_by_step1").is_not_null() &
        pl.col("age_by_age_group").is_not_null()
    )
    .then((pl.col("age_by_step1") - pl.col("age_by_age_group")).abs())
    .otherwise(None)
    .alias("age_diff")
])

customer_with_age = customer_with_age.with_columns([
    pl.when(
        # chỉ có step1
        pl.col("age_by_step1").is_not_null() &
        pl.col("age_by_age_group").is_null()
    ).then(pl.col("age_by_step1"))

    .when(
        # chỉ có age_group
        pl.col("age_by_step1").is_null() &
        pl.col("age_by_age_group").is_not_null()
    ).then(pl.col("age_by_age_group"))

    .when(
        # lệch <= 3 tháng → trung bình
        pl.col("age_diff") <= 3
    ).then(
        (pl.col("age_by_step1") + pl.col("age_by_age_group")) / 2
    )

    .when(
        # 3 < lệch <= 6 → ưu tiên step1
        (pl.col("age_diff") > 3) & (pl.col("age_diff") <= 5)
    ).then(pl.col("age_by_step1"))

    .otherwise(None)   # lệch > 6 → loại
    .alias("age_final")
])

In [92]:
customer_with_age.head(10)

shape: (10, 9)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬──────────┬───────────┐
│ customer_ ┆ first_dat ┆ age_by_st ┆ first_dat ┆ … ┆ last_date ┆ age_by_mi ┆ age_diff ┆ age_final │
│ id        ┆ e_buy_ste ┆ ep1       ┆ e_buy_age ┆   ┆ _buy_milk ┆ lk4mom    ┆ ---      ┆ ---       │
│ ---       ┆ p1        ┆ ---       ┆ _group_0_ ┆   ┆ 4mom      ┆ ---       ┆ f64      ┆ f64       │
│ i32       ┆ ---       ┆ f64       ┆ 3M        ┆   ┆ ---       ┆ f64       ┆          ┆           │
│           ┆ date      ┆           ┆ ---       ┆   ┆ date      ┆           ┆          ┆           │
│           ┆           ┆           ┆ date      ┆   ┆           ┆           ┆          ┆           │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪══════════╪═══════════╡
│ 4748251   ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null     ┆ null      │
│ 6704093   ┆ null      ┆ null      ┆ 2024-02-0 ┆ … ┆ null      ┆ null      ┆ null     ┆ 13.6      │
│           ┆           ┆           ┆ 3         ┆   ┆           ┆           ┆          ┆           │
│ 8092223   ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null     ┆ null      │
│ 7105333   ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null     ┆ null      │
│ 2979082   ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null     ┆ null      │
│ 4045004   ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null     ┆ null      │
│ 8171285   ┆ 2025-01-1 ┆ 3.566667  ┆ null      ┆ … ┆ null      ┆ null      ┆ null     ┆ 3.566667  │
│           ┆ 4         ┆           ┆           ┆   ┆           ┆           ┆          ┆           │
│ 7577480   ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null     ┆ null      │
│ 7582327   ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null     ┆ null      │
│ 2692649   ┆ null      ┆ null      ┆ 2024-05-1 ┆ … ┆ null      ┆ null      ┆ null     ┆ 10.066667 │
│           ┆           ┆           ┆ 9         ┆   ┆           ┆           ┆          ┆           │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴──────────┴───────────┘

In [93]:
diff_bucket_stats = (
    customer_with_age
    .filter(
        pl.col("age_by_step1").is_not_null() &
        pl.col("age_by_age_group").is_not_null()
    )
    .with_columns(
        pl.when(pl.col("age_diff") <= 3)
          .then(pl.lit("<=3"))
        .when((pl.col("age_diff") > 3) & (pl.col("age_diff") <= 5))
          .then(pl.lit("3-6"))
        .otherwise(pl.lit(">5"))
        .alias("diff_bucket")
    )
    .group_by("diff_bucket")
    .agg(pl.count().alias("num_customers"))
    .sort("diff_bucket")
)

print("=== Phân bố độ lệch tuổi ===")
print(diff_bucket_stats)

=== Phân bố độ lệch tuổi ===
shape: (3, 2)
┌─────────────┬───────────────┐
│ diff_bucket ┆ num_customers │
│ ---         ┆ ---           │
│ str         ┆ u32           │
╞═════════════╪═══════════════╡
│ 3-6         ┆ 18497         │
│ <=3         ┆ 234786        │
│ >5          ┆ 17661         │
└─────────────┴───────────────┘

C:\Users\PC\AppData\Local\Temp\ipykernel_500\3055082791.py:16: DeprecationWarning: `pl.count()` is deprecated. Please use `pl.len()` instead.
(Deprecated in version 0.20.5)
  .agg(pl.count().alias("num_customers"))

In [94]:
customer_with_age

shape: (2_569_978, 9)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬──────────┬───────────┐
│ customer_ ┆ first_dat ┆ age_by_st ┆ first_dat ┆ … ┆ last_date ┆ age_by_mi ┆ age_diff ┆ age_final │
│ id        ┆ e_buy_ste ┆ ep1       ┆ e_buy_age ┆   ┆ _buy_milk ┆ lk4mom    ┆ ---      ┆ ---       │
│ ---       ┆ p1        ┆ ---       ┆ _group_0_ ┆   ┆ 4mom      ┆ ---       ┆ f64      ┆ f64       │
│ i32       ┆ ---       ┆ f64       ┆ 3M        ┆   ┆ ---       ┆ f64       ┆          ┆           │
│           ┆ date      ┆           ┆ ---       ┆   ┆ date      ┆           ┆          ┆           │
│           ┆           ┆           ┆ date      ┆   ┆           ┆           ┆          ┆           │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪══════════╪═══════════╡
│ 4748251   ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null     ┆ null      │
│ 6704093   ┆ null      ┆ null      ┆ 2024-02-0 ┆ … ┆ null      ┆ null      ┆ null     ┆ 13.6      │
│           ┆           ┆           ┆ 3         ┆   ┆           ┆           ┆          ┆           │
│ 8092223   ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null     ┆ null      │
│ 7105333   ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null     ┆ null      │
│ 2979082   ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null     ┆ null      │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …        ┆ …         │
│ 6878538   ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null     ┆ null      │
│ 7844605   ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null     ┆ null      │
│ 114947    ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null     ┆ null      │
│ 3504400   ┆ null      ┆ null      ┆ null      ┆ … ┆ null      ┆ null      ┆ null     ┆ null      │
│ 6131245   ┆ 2024-05-0 ┆ 12.0      ┆ 2024-05-0 ┆ … ┆ null      ┆ null      ┆ 1.5      ┆ 11.25     │
│           ┆ 6         ┆           ┆ 6         ┆   ┆           ┆           ┆          ┆           │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴──────────┴───────────┘

In [95]:
customer_with_age.write_parquet(OUTPUT_PATH)
print("Đã lưu:", OUTPUT_PATH)

Đã lưu: D:\003. HK1 - Năm 3\02. CS116 - Python cho Máy học\CS116-DoAn\Phase-3\Feature engineering\customer_age_features_2401_2501.parquet

### **Đặc trưng:** Có mua đa dạng brand không. 
Cũng chỉ xét "Sữa", "Tã"

In [ ]:
path_item = r"D:\003. HK1 - Năm 3\02. CS116 - Python cho Máy học\CS116-DoAn\Phase-2\Feature engineering\sale_pers.item_chunk_0.parquet"
df_item = pl.read_parquet(path_item)

print(df_item.columns)

['item_id', 'price', 'category_l1', 'category_l2', 'category_l3', 'category', 'item_type', 'gender_target_final', 'description_final', 'brand_final', 'age_group_final', 'price_segment']

In [ ]:
# df_trans: transaction (đã load từng chunk rồi concat hoặc xử lý chunk-wise)
# df_item: item đã có category_l1, brand_final

df = (
    df_trans
    .select(["item_id", "customer_id"])
    .join(
        df_item.select(["item_id", "category_l1", "brand_final"]),
        on="item_id",
        how="left"
    )
    .filter(
        pl.col("category_l1").is_in(["Sữa", "Tã"]) &
        pl.col("brand_final").is_not_null()
    )
)

brand_agg = (
    df
    .group_by(["customer_id", "category_l1"])
    .agg([
        pl.count().alias("num_transactions"),
        pl.col("brand_final").n_unique().alias("num_unique_brands"),
    ])
    .with_columns(
        (pl.col("num_unique_brands") / pl.col("num_transactions"))
        .alias("brand_diversity_ratio")
    )
)

C:\Users\PC\AppData\Local\Temp\ipykernel_12820\2008330972.py:22: DeprecationWarning: `pl.count()` is deprecated. Please use `pl.len()` instead.
(Deprecated in version 0.20.5)
  pl.count().alias("num_transactions"),

In [ ]:
def cluster_brand_diversity(pdf):
    X = pdf[["brand_diversity_ratio"]].to_numpy()

    kmeans = KMeans(n_clusters=3, random_state=42, n_init="auto")
    labels = kmeans.fit_predict(X)

    pdf["cluster_raw"] = labels

    # Sắp cluster theo mean ratio
    means = (
        pdf.groupby("cluster_raw")["brand_diversity_ratio"]
        .mean()
        .sort_values()
    )

    mapping = {cluster: i for i, cluster in enumerate(means.index)}
    pdf["brand_segment"] = pdf["cluster_raw"].map(mapping)

    return pdf.drop(columns=["cluster_raw"])

In [ ]:
# Tách theo category_l1
milk_pdf = brand_agg.filter(pl.col("category_l1") == "Sữa").to_pandas()
diaper_pdf = brand_agg.filter(pl.col("category_l1") == "Tã").to_pandas()

milk_clustered = cluster_brand_diversity(milk_pdf)
diaper_clustered = cluster_brand_diversity(diaper_pdf)

brand_segment_df = pl.concat([
    pl.from_pandas(milk_clustered),
    pl.from_pandas(diaper_clustered)
])

In [ ]:
print(
    brand_segment_df
    .group_by(["category_l1", "brand_segment"])
    .agg(pl.count().alias("num_customers"))
    .sort(["category_l1", "brand_segment"])
)

shape: (6, 3)
┌─────────────┬───────────────┬───────────────┐
│ category_l1 ┆ brand_segment ┆ num_customers │
│ ---         ┆ ---           ┆ ---           │
│ str         ┆ i64           ┆ u32           │
╞═════════════╪═══════════════╪═══════════════╡
│ Sữa         ┆ 0             ┆ 227926        │
│ Sữa         ┆ 1             ┆ 233241        │
│ Sữa         ┆ 2             ┆ 435776        │
│ Tã          ┆ 0             ┆ 227775        │
│ Tã          ┆ 1             ┆ 163506        │
│ Tã          ┆ 2             ┆ 375697        │
└─────────────┴───────────────┴───────────────┘

C:\Users\PC\AppData\Local\Temp\ipykernel_12820\3827601304.py:4: DeprecationWarning: `pl.count()` is deprecated. Please use `pl.len()` instead.
(Deprecated in version 0.20.5)
  .agg(pl.count().alias("num_customers"))

In [ ]:
print(
    brand_segment_df
    .group_by(["category_l1", "brand_segment"])
    .agg([
        pl.col("brand_diversity_ratio").min().alias("min"),
        pl.col("brand_diversity_ratio").mean().alias("mean"),
        pl.col("brand_diversity_ratio").median().alias("median"),
        pl.col("brand_diversity_ratio").max().alias("max"),
    ])
    .sort(["category_l1", "brand_segment"])
)

shape: (6, 6)
┌─────────────┬───────────────┬──────────┬──────────┬──────────┬──────────┐
│ category_l1 ┆ brand_segment ┆ min      ┆ mean     ┆ median   ┆ max      │
│ ---         ┆ ---           ┆ ---      ┆ ---      ┆ ---      ┆ ---      │
│ str         ┆ i64           ┆ f64      ┆ f64      ┆ f64      ┆ f64      │
╞═════════════╪═══════════════╪══════════╪══════════╪══════════╪══════════╡
│ Sữa         ┆ 0             ┆ 0.003984 ┆ 0.164849 ┆ 0.166667 ┆ 0.315789 │
│ Sữa         ┆ 1             ┆ 0.318182 ┆ 0.470452 ┆ 0.5      ┆ 0.727273 │
│ Sữa         ┆ 2             ┆ 0.733333 ┆ 0.995604 ┆ 1.0      ┆ 1.0      │
│ Tã          ┆ 0             ┆ 0.004184 ┆ 0.209033 ┆ 0.2      ┆ 0.363636 │
│ Tã          ┆ 1             ┆ 0.368421 ┆ 0.524987 ┆ 0.5      ┆ 0.75     │
│ Tã          ┆ 2             ┆ 0.777778 ┆ 0.999263 ┆ 1.0      ┆ 1.0      │
└─────────────┴───────────────┴──────────┴──────────┴──────────┴──────────┘

In [ ]:
for seg in [0, 1, 2]:
    print(f"\n=== Random khách segment {seg} ===")
    print(
        brand_segment_df
        .filter(pl.col("brand_segment") == seg)
        .sample(n=10, seed=42)
        .select([
            "customer_id",
            "category_l1",
            "num_transactions",
            "num_unique_brands",
            "brand_diversity_ratio"
        ])
    )

=== Random khách segment 0 ===
shape: (10, 5)
┌─────────────┬─────────────┬──────────────────┬───────────────────┬───────────────────────┐
│ customer_id ┆ category_l1 ┆ num_transactions ┆ num_unique_brands ┆ brand_diversity_ratio │
│ ---         ┆ ---         ┆ ---              ┆ ---               ┆ ---                   │
│ i32         ┆ str         ┆ u32              ┆ u32               ┆ f64                   │
╞═════════════╪═════════════╪══════════════════╪═══════════════════╪═══════════════════════╡
│ 1570091     ┆ Tã          ┆ 7                ┆ 2                 ┆ 0.285714              │
│ 5730926     ┆ Sữa         ┆ 10               ┆ 2                 ┆ 0.2                   │
│ 3801854     ┆ Tã          ┆ 11               ┆ 4                 ┆ 0.363636              │
│ 6102929     ┆ Tã          ┆ 8                ┆ 1                 ┆ 0.125                 │
│ 6497599     ┆ Tã          ┆ 6                ┆ 2                 ┆ 0.333333              │
│ 3072179     ┆ Tã          ┆ 8                ┆ 1                 ┆ 0.125                 │
│ 1858374     ┆ Sữa         ┆ 14               ┆ 2                 ┆ 0.142857              │
│ 7677381     ┆ Tã          ┆ 3                ┆ 1                 ┆ 0.333333              │
│ 829952      ┆ Sữa         ┆ 5                ┆ 1                 ┆ 0.2                   │
│ 4385527     ┆ Tã          ┆ 3                ┆ 1                 ┆ 0.333333              │
└─────────────┴─────────────┴──────────────────┴───────────────────┴───────────────────────┘

=== Random khách segment 1 ===
shape: (10, 5)
┌─────────────┬─────────────┬──────────────────┬───────────────────┬───────────────────────┐
│ customer_id ┆ category_l1 ┆ num_transactions ┆ num_unique_brands ┆ brand_diversity_ratio │
│ ---         ┆ ---         ┆ ---              ┆ ---               ┆ ---                   │
│ i32         ┆ str         ┆ u32              ┆ u32               ┆ f64                   │
╞═════════════╪═════════════╪══════════════════╪═══════════════════╪═══════════════════════╡
│ 6656657     ┆ Tã          ┆ 2                ┆ 1                 ┆ 0.5                   │
│ 5930571     ┆ Sữa         ┆ 3                ┆ 2                 ┆ 0.666667              │
│ 4507666     ┆ Tã          ┆ 2                ┆ 1                 ┆ 0.5                   │
│ 7298075     ┆ Tã          ┆ 2                ┆ 1                 ┆ 0.5                   │
│ 8025913     ┆ Tã          ┆ 2                ┆ 1                 ┆ 0.5                   │
│ 7722969     ┆ Tã          ┆ 4                ┆ 2                 ┆ 0.5                   │
│ 6657963     ┆ Sữa         ┆ 2                ┆ 1                 ┆ 0.5                   │
│ 958644      ┆ Tã          ┆ 3                ┆ 2                 ┆ 0.666667              │
│ 7287100     ┆ Sữa         ┆ 2                ┆ 1                 ┆ 0.5                   │
│ 7293097     ┆ Tã          ┆ 2                ┆ 1                 ┆ 0.5                   │
└─────────────┴─────────────┴──────────────────┴───────────────────┴───────────────────────┘

=== Random khách segment 2 ===
shape: (10, 5)
┌─────────────┬─────────────┬──────────────────┬───────────────────┬───────────────────────┐
│ customer_id ┆ category_l1 ┆ num_transactions ┆ num_unique_brands ┆ brand_diversity_ratio │
│ ---         ┆ ---         ┆ ---              ┆ ---               ┆ ---                   │
│ i32         ┆ str         ┆ u32              ┆ u32               ┆ f64                   │
╞═════════════╪═════════════╪══════════════════╪═══════════════════╪═══════════════════════╡
│ 7275541     ┆ Tã          ┆ 1                ┆ 1                 ┆ 1.0                   │
│ 4148731     ┆ Sữa         ┆ 1                ┆ 1                 ┆ 1.0                   │
│ 5990812     ┆ Tã          ┆ 1                ┆ 1                 ┆ 1.0                   │
│ 6528634     ┆ Tã          ┆ 1                ┆ 1                 ┆ 1.0                   │
│ 1381878     ┆ Tã          ┆ 1                ┆ 1                 ┆ 1.0                   │
│ 5936656     ┆ Tã          ┆ 1                ┆ 1                 ┆ 1.0                   │
│ 7902257     ┆ Sữa         ┆ 2                ┆ 2                 ┆ 1.0                   │
│ 7027158     ┆ Tã          ┆ 1                ┆ 1                 ┆ 1.0                   │
│ 2473414     ┆ Sữa         ┆ 4                ┆ 3                 ┆ 0.75                  │
│ 6654772     ┆ Tã          ┆ 1                ┆ 1                 ┆ 1.0                   │
└─────────────┴─────────────┴──────────────────┴───────────────────┴───────────────────────┘

In [ ]:

# Đường dẫn output
OUTPUT_DIR = r"D:\003. HK1 - Năm 3\02. CS116 - Python cho Máy học\CS116-DoAn\Phase-2\Feature engineering"
OUTPUT_PATH = os.path.join(OUTPUT_DIR, "brand_segment.parquet")

# Đảm bảo thư mục tồn tại
os.makedirs(OUTPUT_DIR, exist_ok=True)

# Chỉ giữ các cột cần thiết và lưu
(
    brand_segment_df
    .select(["category_l1", "brand_segment"])
    .write_parquet(OUTPUT_PATH)
)

print("✅ Đã lưu brand_segment thành công tại:")
print(OUTPUT_PATH)

✅ Đã lưu brand_segment thành công tại:
D:\003. HK1 - Năm 3\02. CS116 - Python cho Máy học\CS116-DoAn\Phase-2\Feature engineering\brand_segment.parquet

### **Đặc trưng về hành vi mua hàng:** Xét hành vi mua hàng dựa trên độ tuổi của bé
Lấy độ đa dạng trong category_1, lấy top K sản phẩm tại mỗi loại để xem người dùng có bé trong độ tuổi đó thì thường mua những sản phẩm nào

### **Đặc trưng về hành vi mua hàng:** Thống kê những sản phẩm hay mua chung và số lần mua chung: item 1 | item 2 | #cooc (Cũng xét theo ngày)

In [2]:
from itertools import permutations

In [5]:
TX_DIR = r"D:\003. HK1 - Năm 3\02. CS116 - Python cho Máy học\CS116-DoAn\Phase-3\preprocessing data"
TX_PATTERN = "sale_pers.purchase_history_daily_chunk_{}.parquet"

TMP_DIR = r"D:\tmp_item_cooc_chunks"
OUTPUT_PATH = r"D:\003. HK1 - Năm 3\02. CS116 - Python cho Máy học\CS116-DoAn\Phase-3\Feature engineering\item_co_items_202401_202501.parquet"

os.makedirs(TMP_DIR, exist_ok=True)

In [6]:
# TIME WINDOW
START_DATE = datetime(2024, 1, 1)
END_DATE   = datetime(2025, 1, 31)

# PARAMETERS
MAX_BASKET_SIZE = 10    # bắt buộc để sống
MIN_COOC = 600

In [7]:
def generate_pairs(items):
    """
    items: list[item_id], đã unique
    return: list[(a, b)] có hướng
    """
    if len(items) < 2 or len(items) > MAX_BASKET_SIZE:
        return []
    return list(permutations(items, 2))

In [8]:
for i in range(80):  # chunk_0 → chunk_79
    tx_path = os.path.join(TX_DIR, TX_PATTERN.format(i))
    if not os.path.exists(tx_path):
        continue

    print(f"\n=== Processing chunk {i} ===")

    # --- Read minimal columns + filter time ---
    tx = (
        pl.read_parquet(
            tx_path,
            columns=["customer_id", "item_id", "created_date"]
        )
        .filter(
            (pl.col("created_date") >= START_DATE) &
            (pl.col("created_date") <= END_DATE)
        )
    )

    if tx.is_empty():
        print("  -> No data after time filter")
        continue

    print("  Transactions:", tx.height)

    # --- Basket theo (customer, day) ---
    baskets = (
        tx
        .group_by(["customer_id", "created_date"])
        .agg(pl.col("item_id").unique().alias("items"))
        .filter(
            (pl.col("items").list.len() >= 2) &
            (pl.col("items").list.len() <= MAX_BASKET_SIZE)
        )
    )

    print("  Valid baskets:", baskets.height)

    if baskets.is_empty():
        print("  -> No valid baskets")
        continue

    # --- Generate item pairs ---
    pairs = (
        baskets
        .with_columns(
            pl.col("items")
            .map_elements(
                generate_pairs,
                return_dtype=pl.List(pl.List(pl.Utf8))
            )
            .alias("pairs")
        )
        .explode("pairs")
        .with_columns([
            pl.col("pairs").list.get(0).alias("item_id_a"),
            pl.col("pairs").list.get(1).alias("item_id_b"),
        ])
        .select(["item_id_a", "item_id_b"])
    )

    print("  Raw pairs:", pairs.height)

    if pairs.is_empty():
        print("  -> No pairs generated")
        continue

    # --- Count co-occurrence in this chunk ---
    pair_count = (
        pairs
        .group_by(["item_id_a", "item_id_b"])
        .agg(pl.len().alias("cooc_count"))
    )

    print("  Unique pairs in chunk:", pair_count.height)

    # --- WRITE TO DISK (CỰC KỲ QUAN TRỌNG) ---
    out_chunk = os.path.join(TMP_DIR, f"pair_chunk_{i}.parquet")
    pair_count.write_parquet(out_chunk)

    print("  Saved:", out_chunk)

=== Processing chunk 0 ===
  Transactions: 487850
  Valid baskets: 103124
  Raw pairs: 1054186
  Unique pairs in chunk: 620584
  Saved: D:\tmp_item_cooc_chunks\pair_chunk_0.parquet

=== Processing chunk 1 ===
  Transactions: 487850
  Valid baskets: 102046
  Raw pairs: 1005342
  Unique pairs in chunk: 580896
  Saved: D:\tmp_item_cooc_chunks\pair_chunk_1.parquet

=== Processing chunk 2 ===
  Transactions: 487850
  Valid baskets: 100691
  Raw pairs: 1071660
  Unique pairs in chunk: 606284
  Saved: D:\tmp_item_cooc_chunks\pair_chunk_2.parquet

=== Processing chunk 3 ===
  Transactions: 487850
  Valid baskets: 100834
  Raw pairs: 1029268
  Unique pairs in chunk: 591808
  Saved: D:\tmp_item_cooc_chunks\pair_chunk_3.parquet

=== Processing chunk 4 ===
  Transactions: 487850
  Valid baskets: 102312
  Raw pairs: 1128566
  Unique pairs in chunk: 611706
  Saved: D:\tmp_item_cooc_chunks\pair_chunk_4.parquet

=== Processing chunk 5 ===
  Transactions: 487850
  Valid baskets: 99331
  Raw pairs: 1081890
  Unique pairs in chunk: 610582
  Saved: D:\tmp_item_cooc_chunks\pair_chunk_5.parquet

=== Processing chunk 6 ===
  Transactions: 487850
  Valid baskets: 102698
  Raw pairs: 1149784
  Unique pairs in chunk: 666848
  Saved: D:\tmp_item_cooc_chunks\pair_chunk_6.parquet

=== Processing chunk 7 ===
  Transactions: 487850
  Valid baskets: 102441
  Raw pairs: 1098932
  Unique pairs in chunk: 629810
  Saved: D:\tmp_item_cooc_chunks\pair_chunk_7.parquet

=== Processing chunk 8 ===
  Transactions: 487850
  Valid baskets: 104548
  Raw pairs: 1011332
  Unique pairs in chunk: 616662
  Saved: D:\tmp_item_cooc_chunks\pair_chunk_8.parquet

=== Processing chunk 9 ===
  Transactions: 487850
  Valid baskets: 102928
  Raw pairs: 1004212
  Unique pairs in chunk: 600352
  Saved: D:\tmp_item_cooc_chunks\pair_chunk_9.parquet

=== Processing chunk 10 ===
  Transactions: 487850
  Valid baskets: 101741
  Raw pairs: 1141728
  Unique pairs in chunk: 640736
  Saved: D:\tmp_item_cooc_chunks\pair_chunk_10.parquet

=== Processing chunk 11 ===
  Transactions: 487850
  Valid baskets: 101828
  Raw pairs: 1172282
  Unique pairs in chunk: 643088
  Saved: D:\tmp_item_cooc_chunks\pair_chunk_11.parquet

=== Processing chunk 12 ===
  Transactions: 487850
  Valid baskets: 98281
  Raw pairs: 964762
  Unique pairs in chunk: 563264
  Saved: D:\tmp_item_cooc_chunks\pair_chunk_12.parquet

=== Processing chunk 13 ===
  Transactions: 487850
  Valid baskets: 83325
  Raw pairs: 600408
  Unique pairs in chunk: 367566
  Saved: D:\tmp_item_cooc_chunks\pair_chunk_13.parquet

=== Processing chunk 14 ===
  Transactions: 487850
  Valid baskets: 80773
  Raw pairs: 574624
  Unique pairs in chunk: 391956
  Saved: D:\tmp_item_cooc_chunks\pair_chunk_14.parquet

=== Processing chunk 15 ===
  Transactions: 487850
  Valid baskets: 102066
  Raw pairs: 1069696
  Unique pairs in chunk: 598236
  Saved: D:\tmp_item_cooc_chunks\pair_chunk_15.parquet

=== Processing chunk 16 ===
  Transactions: 487850
  Valid baskets: 103328
  Raw pairs: 1115126
  Unique pairs in chunk: 619310
  Saved: D:\tmp_item_cooc_chunks\pair_chunk_16.parquet

=== Processing chunk 17 ===
  Transactions: 487850
  Valid baskets: 98373
  Raw pairs: 1054880
  Unique pairs in chunk: 603396
  Saved: D:\tmp_item_cooc_chunks\pair_chunk_17.parquet

=== Processing chunk 18 ===
  Transactions: 487850
  Valid baskets: 101696
  Raw pairs: 1067476
  Unique pairs in chunk: 594280
  Saved: D:\tmp_item_cooc_chunks\pair_chunk_18.parquet

=== Processing chunk 19 ===
  Transactions: 487850
  Valid baskets: 103112
  Raw pairs: 1076638
  Unique pairs in chunk: 590138
  Saved: D:\tmp_item_cooc_chunks\pair_chunk_19.parquet

=== Processing chunk 20 ===
  Transactions: 487850
  Valid baskets: 100179
  Raw pairs: 1066644
  Unique pairs in chunk: 588642
  Saved: D:\tmp_item_cooc_chunks\pair_chunk_20.parquet

=== Processing chunk 21 ===
  Transactions: 487850
  Valid baskets: 100779
  Raw pairs: 1109584
  Unique pairs in chunk: 611994
  Saved: D:\tmp_item_cooc_chunks\pair_chunk_21.parquet

=== Processing chunk 22 ===
  Transactions: 487850
  Valid baskets: 100652
  Raw pairs: 1016670
  Unique pairs in chunk: 574992
  Saved: D:\tmp_item_cooc_chunks\pair_chunk_22.parquet

=== Processing chunk 23 ===
  Transactions: 487850
  Valid baskets: 100524
  Raw pairs: 943092
  Unique pairs in chunk: 536456
  Saved: D:\tmp_item_cooc_chunks\pair_chunk_23.parquet

=== Processing chunk 24 ===
  Transactions: 487850
  Valid baskets: 96826
  Raw pairs: 887286
  Unique pairs in chunk: 526212
  Saved: D:\tmp_item_cooc_chunks\pair_chunk_24.parquet

=== Processing chunk 25 ===
  Transactions: 487850
  Valid baskets: 100240
  Raw pairs: 969270
  Unique pairs in chunk: 539210
  Saved: D:\tmp_item_cooc_chunks\pair_chunk_25.parquet

=== Processing chunk 26 ===
  Transactions: 487850
  Valid baskets: 101402
  Raw pairs: 1032662
  Unique pairs in chunk: 575888
  Saved: D:\tmp_item_cooc_chunks\pair_chunk_26.parquet

=== Processing chunk 27 ===
  Transactions: 487850
  Valid baskets: 102206
  Raw pairs: 1064462
  Unique pairs in chunk: 588680
  Saved: D:\tmp_item_cooc_chunks\pair_chunk_27.parquet

=== Processing chunk 28 ===
  Transactions: 487850
  Valid baskets: 102589
  Raw pairs: 1116096
  Unique pairs in chunk: 615086
  Saved: D:\tmp_item_cooc_chunks\pair_chunk_28.parquet

=== Processing chunk 29 ===
  Transactions: 487850
  Valid baskets: 100046
  Raw pairs: 1075928
  Unique pairs in chunk: 596980
  Saved: D:\tmp_item_cooc_chunks\pair_chunk_29.parquet

=== Processing chunk 30 ===
  Transactions: 487850
  Valid baskets: 100940
  Raw pairs: 1096274
  Unique pairs in chunk: 595330
  Saved: D:\tmp_item_cooc_chunks\pair_chunk_30.parquet

=== Processing chunk 31 ===
  Transactions: 487850
  Valid baskets: 99975
  Raw pairs: 1132698
  Unique pairs in chunk: 607976
  Saved: D:\tmp_item_cooc_chunks\pair_chunk_31.parquet

=== Processing chunk 32 ===
  Transactions: 487850
  Valid baskets: 95473
  Raw pairs: 971462
  Unique pairs in chunk: 547582
  Saved: D:\tmp_item_cooc_chunks\pair_chunk_32.parquet

=== Processing chunk 33 ===
  Transactions: 487850
  Valid baskets: 79324
  Raw pairs: 579460
  Unique pairs in chunk: 385670
  Saved: D:\tmp_item_cooc_chunks\pair_chunk_33.parquet

=== Processing chunk 34 ===
  Transactions: 487850
  Valid baskets: 98874
  Raw pairs: 819804
  Unique pairs in chunk: 469170
  Saved: D:\tmp_item_cooc_chunks\pair_chunk_34.parquet

=== Processing chunk 35 ===
  Transactions: 487850
  Valid baskets: 101590
  Raw pairs: 994914
  Unique pairs in chunk: 568416
  Saved: D:\tmp_item_cooc_chunks\pair_chunk_35.parquet

=== Processing chunk 36 ===
  Transactions: 487850
  Valid baskets: 99139
  Raw pairs: 848960
  Unique pairs in chunk: 530392
  Saved: D:\tmp_item_cooc_chunks\pair_chunk_36.parquet

=== Processing chunk 37 ===
  Transactions: 487850
  Valid baskets: 101088
  Raw pairs: 861894
  Unique pairs in chunk: 478922
  Saved: D:\tmp_item_cooc_chunks\pair_chunk_37.parquet

=== Processing chunk 38 ===
  Transactions: 487850
  Valid baskets: 102204
  Raw pairs: 822040
  Unique pairs in chunk: 461656
  Saved: D:\tmp_item_cooc_chunks\pair_chunk_38.parquet

=== Processing chunk 39 ===
  Transactions: 487850
  Valid baskets: 99923
  Raw pairs: 819810
  Unique pairs in chunk: 475618
  Saved: D:\tmp_item_cooc_chunks\pair_chunk_39.parquet

=== Processing chunk 40 ===
  Transactions: 487850
  Valid baskets: 102463
  Raw pairs: 1052604
  Unique pairs in chunk: 576196
  Saved: D:\tmp_item_cooc_chunks\pair_chunk_40.parquet

=== Processing chunk 41 ===
  Transactions: 487850
  Valid baskets: 103533
  Raw pairs: 1047264
  Unique pairs in chunk: 640626
  Saved: D:\tmp_item_cooc_chunks\pair_chunk_41.parquet

=== Processing chunk 42 ===
  Transactions: 487850
  Valid baskets: 100815
  Raw pairs: 985082
  Unique pairs in chunk: 553494
  Saved: D:\tmp_item_cooc_chunks\pair_chunk_42.parquet

=== Processing chunk 43 ===
  Transactions: 487850
  Valid baskets: 104115
  Raw pairs: 982074
  Unique pairs in chunk: 551044
  Saved: D:\tmp_item_cooc_chunks\pair_chunk_43.parquet

=== Processing chunk 44 ===
  Transactions: 487850
  Valid baskets: 104403
  Raw pairs: 953972
  Unique pairs in chunk: 570810
  Saved: D:\tmp_item_cooc_chunks\pair_chunk_44.parquet

=== Processing chunk 45 ===
  Transactions: 487850
  Valid baskets: 104540
  Raw pairs: 1029368
  Unique pairs in chunk: 570786
  Saved: D:\tmp_item_cooc_chunks\pair_chunk_45.parquet

=== Processing chunk 46 ===
  Transactions: 487850
  Valid baskets: 100147
  Raw pairs: 1020078
  Unique pairs in chunk: 573918
  Saved: D:\tmp_item_cooc_chunks\pair_chunk_46.parquet

=== Processing chunk 47 ===
  Transactions: 487850
  Valid baskets: 100638
  Raw pairs: 990186
  Unique pairs in chunk: 573684
  Saved: D:\tmp_item_cooc_chunks\pair_chunk_47.parquet

=== Processing chunk 48 ===
  Transactions: 487850
  Valid baskets: 101208
  Raw pairs: 983018
  Unique pairs in chunk: 612952
  Saved: D:\tmp_item_cooc_chunks\pair_chunk_48.parquet

=== Processing chunk 49 ===
  Transactions: 487850
  Valid baskets: 100657
  Raw pairs: 930654
  Unique pairs in chunk: 549998
  Saved: D:\tmp_item_cooc_chunks\pair_chunk_49.parquet

=== Processing chunk 50 ===
  Transactions: 487850
  Valid baskets: 102901
  Raw pairs: 1002824
  Unique pairs in chunk: 552388
  Saved: D:\tmp_item_cooc_chunks\pair_chunk_50.parquet

=== Processing chunk 51 ===
  Transactions: 487850
  Valid baskets: 103390
  Raw pairs: 1071832
  Unique pairs in chunk: 588958
  Saved: D:\tmp_item_cooc_chunks\pair_chunk_51.parquet

=== Processing chunk 52 ===
  Transactions: 487850
  Valid baskets: 103811
  Raw pairs: 1009382
  Unique pairs in chunk: 600040
  Saved: D:\tmp_item_cooc_chunks\pair_chunk_52.parquet

=== Processing chunk 53 ===
  Transactions: 487850
  Valid baskets: 104518
  Raw pairs: 897974
  Unique pairs in chunk: 572416
  Saved: D:\tmp_item_cooc_chunks\pair_chunk_53.parquet

=== Processing chunk 54 ===
  Transactions: 487850
  Valid baskets: 100351
  Raw pairs: 861234
  Unique pairs in chunk: 504542
  Saved: D:\tmp_item_cooc_chunks\pair_chunk_54.parquet

=== Processing chunk 55 ===
  Transactions: 487850
  Valid baskets: 104180
  Raw pairs: 1004034
  Unique pairs in chunk: 561134
  Saved: D:\tmp_item_cooc_chunks\pair_chunk_55.parquet

=== Processing chunk 56 ===
  Transactions: 487850
  Valid baskets: 102254
  Raw pairs: 904642
  Unique pairs in chunk: 576452
  Saved: D:\tmp_item_cooc_chunks\pair_chunk_56.parquet

=== Processing chunk 57 ===
  Transactions: 487850
  Valid baskets: 100094
  Raw pairs: 940884
  Unique pairs in chunk: 563470
  Saved: D:\tmp_item_cooc_chunks\pair_chunk_57.parquet

=== Processing chunk 58 ===
  Transactions: 487850
  Valid baskets: 102373
  Raw pairs: 815916
  Unique pairs in chunk: 514164
  Saved: D:\tmp_item_cooc_chunks\pair_chunk_58.parquet

=== Processing chunk 59 ===
  Transactions: 487850
  Valid baskets: 100415
  Raw pairs: 864310
  Unique pairs in chunk: 576332
  Saved: D:\tmp_item_cooc_chunks\pair_chunk_59.parquet

=== Processing chunk 60 ===
  Transactions: 487850
  Valid baskets: 101184
  Raw pairs: 879406
  Unique pairs in chunk: 506314
  Saved: D:\tmp_item_cooc_chunks\pair_chunk_60.parquet

=== Processing chunk 61 ===
  Transactions: 487850
  Valid baskets: 96480
  Raw pairs: 928840
  Unique pairs in chunk: 534210
  Saved: D:\tmp_item_cooc_chunks\pair_chunk_61.parquet

=== Processing chunk 62 ===
  Transactions: 487850
  Valid baskets: 101766
  Raw pairs: 839138
  Unique pairs in chunk: 501730
  Saved: D:\tmp_item_cooc_chunks\pair_chunk_62.parquet

=== Processing chunk 63 ===
  Transactions: 487850
  Valid baskets: 101371
  Raw pairs: 951894
  Unique pairs in chunk: 566364
  Saved: D:\tmp_item_cooc_chunks\pair_chunk_63.parquet

=== Processing chunk 64 ===
  Transactions: 487850
  Valid baskets: 102634
  Raw pairs: 877338
  Unique pairs in chunk: 530216
  Saved: D:\tmp_item_cooc_chunks\pair_chunk_64.parquet

=== Processing chunk 65 ===
  Transactions: 487850
  Valid baskets: 102312
  Raw pairs: 913370
  Unique pairs in chunk: 544734
  Saved: D:\tmp_item_cooc_chunks\pair_chunk_65.parquet

=== Processing chunk 66 ===
  Transactions: 487850
  Valid baskets: 101618
  Raw pairs: 911712
  Unique pairs in chunk: 518796
  Saved: D:\tmp_item_cooc_chunks\pair_chunk_66.parquet

=== Processing chunk 67 ===
  Transactions: 487850
  Valid baskets: 104438
  Raw pairs: 944324
  Unique pairs in chunk: 541652
  Saved: D:\tmp_item_cooc_chunks\pair_chunk_67.parquet

=== Processing chunk 68 ===
  Transactions: 487850
  Valid baskets: 101201
  Raw pairs: 846712
  Unique pairs in chunk: 537034
  Saved: D:\tmp_item_cooc_chunks\pair_chunk_68.parquet

=== Processing chunk 69 ===
  Transactions: 487850
  Valid baskets: 101360
  Raw pairs: 930780
  Unique pairs in chunk: 548388
  Saved: D:\tmp_item_cooc_chunks\pair_chunk_69.parquet

=== Processing chunk 70 ===
  Transactions: 487850
  Valid baskets: 102050
  Raw pairs: 998682
  Unique pairs in chunk: 581634
  Saved: D:\tmp_item_cooc_chunks\pair_chunk_70.parquet

=== Processing chunk 71 ===
  Transactions: 487850
  Valid baskets: 97264
  Raw pairs: 802320
  Unique pairs in chunk: 494300
  Saved: D:\tmp_item_cooc_chunks\pair_chunk_71.parquet

=== Processing chunk 72 ===
  Transactions: 487850
  Valid baskets: 102809
  Raw pairs: 948722
  Unique pairs in chunk: 547076
  Saved: D:\tmp_item_cooc_chunks\pair_chunk_72.parquet

=== Processing chunk 73 ===
  Transactions: 487850
  Valid baskets: 98183
  Raw pairs: 1074374
  Unique pairs in chunk: 637106
  Saved: D:\tmp_item_cooc_chunks\pair_chunk_73.parquet

=== Processing chunk 74 ===
  Transactions: 487850
  Valid baskets: 101117
  Raw pairs: 1084654
  Unique pairs in chunk: 564796
  Saved: D:\tmp_item_cooc_chunks\pair_chunk_74.parquet

=== Processing chunk 75 ===
  Transactions: 487850
  Valid baskets: 100755
  Raw pairs: 1128360
  Unique pairs in chunk: 610562
  Saved: D:\tmp_item_cooc_chunks\pair_chunk_75.parquet

=== Processing chunk 76 ===
  Transactions: 487850
  Valid baskets: 99666
  Raw pairs: 1117688
  Unique pairs in chunk: 596508
  Saved: D:\tmp_item_cooc_chunks\pair_chunk_76.parquet

=== Processing chunk 77 ===
  Transactions: 487850
  Valid baskets: 100183
  Raw pairs: 1136376
  Unique pairs in chunk: 661156
  Saved: D:\tmp_item_cooc_chunks\pair_chunk_77.parquet

=== Processing chunk 78 ===
  Transactions: 487850
  Valid baskets: 97326
  Raw pairs: 1252874
  Unique pairs in chunk: 667858
  Saved: D:\tmp_item_cooc_chunks\pair_chunk_78.parquet

=== Processing chunk 79 ===
  Transactions: 487927
  Valid baskets: 88284
  Raw pairs: 833162
  Unique pairs in chunk: 477066
  Saved: D:\tmp_item_cooc_chunks\pair_chunk_79.parquet

In [9]:
print("\n=== PHASE 3: Aggregating all chunk files ===")

pair_files = [
    os.path.join(TMP_DIR, f)
    for f in os.listdir(TMP_DIR)
    if f.endswith(".parquet")
]

print("Num tmp files:", len(pair_files))

pair_all = pl.concat(
    [pl.read_parquet(f) for f in pair_files],
    how="vertical"
)

print("Total rows before final agg:", pair_all.height)

pair_strong = (
    pair_all
    .group_by(["item_id_a", "item_id_b"])
    .agg(pl.col("cooc_count").sum())
    .filter(pl.col("cooc_count") >= MIN_COOC)
    .sort("cooc_count", descending=True)
)

print("Strong pairs (>=600):", pair_strong.height)
print(pair_strong.head(10))

=== PHASE 3: Aggregating all chunk files ===
Num tmp files: 80
Total rows before final agg: 45173278
Strong pairs (>=600): 8024
shape: (10, 3)
┌───────────────┬───────────────┬────────────┐
│ item_id_a     ┆ item_id_b     ┆ cooc_count │
│ ---           ┆ ---           ┆ ---        │
│ str           ┆ str           ┆ u32        │
╞═══════════════╪═══════════════╪════════════╡
│ 2803000000013 ┆ 2803000000011 ┆ 57191      │
│ 2803000000011 ┆ 2803000000013 ┆ 57191      │
│ 2803000000012 ┆ 2803000000013 ┆ 39380      │
│ 2803000000013 ┆ 2803000000012 ┆ 39380      │
│ 2803000000012 ┆ 2803000000011 ┆ 38668      │
│ 2803000000011 ┆ 2803000000012 ┆ 38668      │
│ 2803000000010 ┆ 2803000000012 ┆ 29799      │
│ 2803000000012 ┆ 2803000000010 ┆ 29799      │
│ 2803000000013 ┆ 2803000000010 ┆ 23959      │
│ 2803000000010 ┆ 2803000000013 ┆ 23959      │
└───────────────┴───────────────┴────────────┘

In [ ]:
# ========== check ==================

In [16]:
ITEM_PATH = r"D:\003. HK1 - Năm 3\02. CS116 - Python cho Máy học\CS116-DoAn\Phase-3\Feature engineering\sale_pers.item_chunk_0.parquet"

item_meta = pl.read_parquet(
    ITEM_PATH,
    columns=[
        "item_id",
        "category_l1",
        "category",     # nếu cột này tồn tại
        "brand_final"
    ]
)

print("Item meta shape:", item_meta.shape)
print(item_meta.head())

Item meta shape: (27323, 4)
shape: (5, 4)
┌───────────────┬────────────────┬───────────────────┬──────────────────┐
│ item_id       ┆ category_l1    ┆ category          ┆ brand_final      │
│ ---           ┆ ---            ┆ ---               ┆ ---              │
│ str           ┆ str            ┆ str               ┆ str              │
╞═══════════════╪════════════════╪═══════════════════╪══════════════════╡
│ 0502020000004 ┆ Babycare       ┆ Núm ty Dr Brown   ┆ Dr.Brown's       │
│ 0010290040150 ┆ Thời trang     ┆ Bộ quần áo bé gái ┆ Con Cưng         │
│ 0008010000015 ┆ Đồ chơi & Sách ┆ Gặm nướu khác     ┆ Thương hiệu khác │
│ 0020010000094 ┆ Tã             ┆ Merries_Sơ Sinh   ┆ Merries          │
│ 0020010000098 ┆ Tã             ┆ Merries_Tã Quần   ┆ Merries          │
└───────────────┴────────────────┴───────────────────┴──────────────────┘

In [18]:
pair_with_a = pair_strong.join(
    item_meta.rename({
        "item_id": "item_id_a",
        "category_l1": "a_category_l1",
        "category": "a_category",
        "brand_final": "a_brand",
    }),
    on="item_id_a",
    how="left"
)

In [19]:
pair_with_ab = pair_with_a.join(
    item_meta.rename({
        "item_id": "item_id_b",
        "category_l1": "b_category_l1",
        "category": "b_category",
        "brand_final": "b_brand",
    }),
    on="item_id_b",
    how="left"
)

In [20]:
pair_with_ab.select([
    "item_id_a",
    "a_category_l1", "a_category", "a_brand",
    "item_id_b",
    "b_category_l1", "b_category", "b_brand",
    "cooc_count"
]).head(20)

shape: (20, 9)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ item_id_a ┆ a_categor ┆ a_categor ┆ a_brand   ┆ … ┆ b_categor ┆ b_categor ┆ b_brand   ┆ cooc_cou │
│ ---       ┆ y_l1      ┆ y         ┆ ---       ┆   ┆ y_l1      ┆ y         ┆ ---       ┆ nt       │
│ str       ┆ ---       ┆ ---       ┆ str       ┆   ┆ ---       ┆ ---       ┆ str       ┆ ---      │
│           ┆ str       ┆ str       ┆           ┆   ┆ str       ┆ str       ┆           ┆ u32      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 280300000 ┆ Thực phẩm ┆ Hoff      ┆ HOFF      ┆ … ┆ Thực phẩm ┆ Hoff      ┆ HOFF      ┆ 57191    │
│ 0013      ┆ cho bé    ┆           ┆           ┆   ┆ cho bé    ┆           ┆           ┆          │
│ 280300000 ┆ Thực phẩm ┆ Hoff      ┆ HOFF      ┆ … ┆ Thực phẩm ┆ Hoff      ┆ HOFF      ┆ 57191    │
│ 0011      ┆ cho bé    ┆           ┆           ┆   ┆ cho bé    ┆           ┆           ┆          │
│ 280300000 ┆ Thực phẩm ┆ Hoff      ┆ HOFF      ┆ … ┆ Thực phẩm ┆ Hoff      ┆ HOFF      ┆ 39380    │
│ 0012      ┆ cho bé    ┆           ┆           ┆   ┆ cho bé    ┆           ┆           ┆          │
│ 280300000 ┆ Thực phẩm ┆ Hoff      ┆ HOFF      ┆ … ┆ Thực phẩm ┆ Hoff      ┆ HOFF      ┆ 39380    │
│ 0013      ┆ cho bé    ┆           ┆           ┆   ┆ cho bé    ┆           ┆           ┆          │
│ 280300000 ┆ Thực phẩm ┆ Hoff      ┆ HOFF      ┆ … ┆ Thực phẩm ┆ Hoff      ┆ HOFF      ┆ 38668    │
│ 0012      ┆ cho bé    ┆           ┆           ┆   ┆ cho bé    ┆           ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 002913000 ┆ Thực phẩm ┆ Vinamilk  ┆ Ridielac  ┆ … ┆ Thực phẩm ┆ Vinamilk  ┆ Ridielac  ┆ 20526    │
│ 0030      ┆ cho bé    ┆           ┆ Gold      ┆   ┆ cho bé    ┆           ┆ Gold      ┆          │
│ 002925001 ┆ Thực phẩm ┆ Ivenet    ┆ Ivenet    ┆ … ┆ Thực phẩm ┆ Ivenet    ┆ Ivenet    ┆ 20362    │
│ 0002      ┆ cho bé    ┆           ┆           ┆   ┆ cho bé    ┆           ┆           ┆          │
│ 002925001 ┆ Thực phẩm ┆ Ivenet    ┆ Ivenet    ┆ … ┆ Thực phẩm ┆ Ivenet    ┆ Ivenet    ┆ 20362    │
│ 0001      ┆ cho bé    ┆           ┆           ┆   ┆ cho bé    ┆           ┆           ┆          │
│ 137100000 ┆ Thực phẩm ┆ Cây Thị   ┆ Cây Thị   ┆ … ┆ Thực phẩm ┆ Cây Thị   ┆ Cây Thị   ┆ 20268    │
│ 0002      ┆ cho bé    ┆           ┆           ┆   ┆ cho bé    ┆           ┆           ┆          │
│ 137100000 ┆ Thực phẩm ┆ Cây Thị   ┆ Cây Thị   ┆ … ┆ Thực phẩm ┆ Cây Thị   ┆ Cây Thị   ┆ 20268    │
│ 0001      ┆ cho bé    ┆           ┆           ┆   ┆ cho bé    ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [25]:
pair_with_ab.select([
    "item_id_a",
    "a_category_l1", "a_brand",
    "item_id_b",
    "b_category_l1", "b_brand",
    "cooc_count"
]).sample(n=10, shuffle=True)

shape: (10, 7)
┌──────────────┬──────────────┬─────────────┬─────────────┬─────────────┬─────────────┬────────────┐
│ item_id_a    ┆ a_category_l ┆ a_brand     ┆ item_id_b   ┆ b_category_ ┆ b_brand     ┆ cooc_count │
│ ---          ┆ 1            ┆ ---         ┆ ---         ┆ l1          ┆ ---         ┆ ---        │
│ str          ┆ ---          ┆ str         ┆ str         ┆ ---         ┆ str         ┆ u32        │
│              ┆ str          ┆             ┆             ┆ str         ┆             ┆            │
╞══════════════╪══════════════╪═════════════╪═════════════╪═════════════╪═════════════╪════════════╡
│ 000715000014 ┆ Vệ sinh      ┆ BeeVn       ┆ 46030240000 ┆ Hóa mỹ phẩm ┆ Animo       ┆ 743        │
│ 3            ┆              ┆             ┆ 01          ┆ cho bé      ┆             ┆            │
│ 676800000000 ┆ Tã           ┆ Takato      ┆ 59500000000 ┆ Babycare    ┆ Dr Papie    ┆ 924        │
│ 3            ┆              ┆             ┆ 01          ┆             ┆             ┆            │
│ 439600000000 ┆ Thực phẩm    ┆ Grinny      ┆ 71150000000 ┆ Thực phẩm   ┆ Grinny      ┆ 2541       │
│ 3            ┆ cho bé       ┆             ┆ 05          ┆ cho bé      ┆             ┆            │
│ 669700000000 ┆ Sữa nước     ┆ GrowPLUS+   ┆ 20240000000 ┆ Sữa nước    ┆ PediaSure   ┆ 611        │
│ 4            ┆              ┆             ┆ 11          ┆             ┆             ┆            │
│ 002002000017 ┆ Thực phẩm    ┆ Sài Gòn     ┆ 00200200002 ┆ Thực phẩm   ┆ Sài Gòn     ┆ 700        │
│ 3            ┆ cho bé       ┆ Food        ┆ 02          ┆ cho bé      ┆ Food        ┆            │
│ 260900000000 ┆ Thực phẩm    ┆ Playmore    ┆ 27070000000 ┆ Thực phẩm   ┆ Chupa chups ┆ 1156       │
│ 2            ┆ cho bé       ┆             ┆ 01          ┆ cho bé      ┆             ┆            │
│ 002925001002 ┆ Thực phẩm    ┆ Ivenet      ┆ 00292500100 ┆ Thực phẩm   ┆ Ivenet      ┆ 1528       │
│ 4            ┆ cho bé       ┆             ┆ 25          ┆ cho bé      ┆             ┆            │
│ 002002000010 ┆ Thực phẩm    ┆ Beanstalk   ┆ 00200200001 ┆ Thực phẩm   ┆ Beanstalk   ┆ 1688       │
│ 4            ┆ cho bé       ┆             ┆ 05          ┆ cho bé      ┆             ┆            │
│ 388000000000 ┆ Thực phẩm    ┆ HOFF        ┆ 55030000000 ┆ Thực phẩm   ┆ Bebedang    ┆ 686        │
│ 2            ┆ cho bé       ┆             ┆ 04          ┆ cho bé      ┆             ┆            │
│ 280300000001 ┆ Thực phẩm    ┆ HOFF        ┆ 22650000000 ┆ Tã          ┆ Huggies     ┆ 659        │
│ 1            ┆ cho bé       ┆             ┆ 25          ┆             ┆             ┆            │
└──────────────┴──────────────┴─────────────┴─────────────┴─────────────┴─────────────┴────────────┘

In [ ]:
# ============== done check =====================

In [10]:
final_output = (
    pair_strong
    .sort(["item_id_a", "cooc_count"], descending=[False, True])
    .group_by("item_id_a")
    .agg(
        pl.col("item_id_b").alias("co_items")
    )
    .sort("item_id_a")
)

print("\n=== FINAL OUTPUT SAMPLE ===")
print(final_output.head(10))
print("Num item a:", final_output.height)

=== FINAL OUTPUT SAMPLE ===
shape: (10, 2)
┌───────────────┬─────────────────────────────────┐
│ item_id_a     ┆ co_items                        │
│ ---           ┆ ---                             │
│ str           ┆ list[str]                       │
╞═══════════════╪═════════════════════════════════╡
│ 0000280000138 ┆ ["0009200000049"]               │
│ 0006020000278 ┆ ["0020010000210"]               │
│ 0006020000279 ┆ ["0020010000210"]               │
│ 0006020000281 ┆ ["0020010000210"]               │
│ 0006040000270 ┆ ["0006040000273"]               │
│ 0006040000273 ┆ ["0006040000270"]               │
│ 0006040000318 ┆ ["0007010000887"]               │
│ 0006040000478 ┆ ["0055000000002"]               │
│ 0006040000479 ┆ ["0055000000002", "00420000000… │
│ 0007010000290 ┆ ["4603024000001", "63820000000… │
└───────────────┴─────────────────────────────────┘
Num item a: 773

In [11]:
preview = final_output.with_columns(
    pl.col("co_items").list.join(",").alias("co_items_str")
)

print(preview.head(10))

shape: (10, 3)
┌───────────────┬─────────────────────────────────┬─────────────────────────────┐
│ item_id_a     ┆ co_items                        ┆ co_items_str                │
│ ---           ┆ ---                             ┆ ---                         │
│ str           ┆ list[str]                       ┆ str                         │
╞═══════════════╪═════════════════════════════════╪═════════════════════════════╡
│ 0000280000138 ┆ ["0009200000049"]               ┆ 0009200000049               │
│ 0006020000278 ┆ ["0020010000210"]               ┆ 0020010000210               │
│ 0006020000279 ┆ ["0020010000210"]               ┆ 0020010000210               │
│ 0006020000281 ┆ ["0020010000210"]               ┆ 0020010000210               │
│ 0006040000270 ┆ ["0006040000273"]               ┆ 0006040000273               │
│ 0006040000273 ┆ ["0006040000270"]               ┆ 0006040000270               │
│ 0006040000318 ┆ ["0007010000887"]               ┆ 0007010000887               │
│ 0006040000478 ┆ ["0055000000002"]               ┆ 0055000000002               │
│ 0006040000479 ┆ ["0055000000002", "00420000000… ┆ 0055000000002,0042000000003 │
│ 0007010000290 ┆ ["4603024000001", "63820000000… ┆ 4603024000001,6382000000004 │
└───────────────┴─────────────────────────────────┴─────────────────────────────┘

In [27]:
preview.sample(n=10, shuffle=True)

shape: (10, 3)
┌───────────────┬─────────────────────────────────┬─────────────────────────────────┐
│ item_id_a     ┆ co_items                        ┆ co_items_str                    │
│ ---           ┆ ---                             ┆ ---                             │
│ str           ┆ list[str]                       ┆ str                             │
╞═══════════════╪═════════════════════════════════╪═════════════════════════════════╡
│ 4051000000002 ┆ ["1512000000004", "40480000000… ┆ 1512000000004,4048000000008     │
│ 3773000000003 ┆ ["1512000000004", "46900000000… ┆ 1512000000004,4690000000001     │
│ 5506000000002 ┆ ["5506000000003", "55060000000… ┆ 5506000000003,5506000000004,55… │
│ 2610000000008 ┆ ["2610000000004"]               ┆ 2610000000004                   │
│ 2609000000001 ┆ ["2609000000002", "27070000000… ┆ 2609000000002,2707000000001,71… │
│ 0029250010001 ┆ ["0029250010003", "00292500100… ┆ 0029250010003,0029250010002,28… │
│ 0055000000002 ┆ ["0042000000005", "00060400004… ┆ 0042000000005,0006040000479,00… │
│ 1438000000002 ┆ ["1438000000001"]               ┆ 1438000000001                   │
│ 5503000000002 ┆ ["5503000000003", "55030000000… ┆ 5503000000003,5503000000004,55… │
│ 5420000000003 ┆ ["1371000000003", "13710000000… ┆ 1371000000003,1371000000006,13… │
└───────────────┴─────────────────────────────────┴─────────────────────────────────┘

In [28]:
final_output

shape: (773, 2)
┌───────────────┬─────────────────────────────────┐
│ item_id_a     ┆ co_items                        │
│ ---           ┆ ---                             │
│ str           ┆ list[str]                       │
╞═══════════════╪═════════════════════════════════╡
│ 0000280000138 ┆ ["0009200000049"]               │
│ 0006020000278 ┆ ["0020010000210"]               │
│ 0006020000279 ┆ ["0020010000210"]               │
│ 0006020000281 ┆ ["0020010000210"]               │
│ 0006040000270 ┆ ["0006040000273"]               │
│ …             ┆ …                               │
│ 7228000000016 ┆ ["7228000000015", "72280000000… │
│ 7228000000017 ┆ ["7228000000023", "19520000000… │
│ 7228000000018 ┆ ["0068000000159", "72280000000… │
│ 7228000000023 ┆ ["7228000000017", "72280000000… │
│ 7228000000024 ┆ ["7228000000018"]               │
└───────────────┴─────────────────────────────────┘

In [29]:
os.makedirs(os.path.dirname(OUTPUT_PATH), exist_ok=True)
final_output.write_parquet(OUTPUT_PATH)

print("\nSaved final output to:")
print(OUTPUT_PATH)

Saved final output to:
D:\003. HK1 - Năm 3\02. CS116 - Python cho Máy học\CS116-DoAn\Phase-3\Feature engineering\item_co_items_202401_202501.parquet

### Discount user: Người dùng đó có mua hàng discount hay k. Tính dựa trên số lần mua trong tháng
Cũng có thể sẽ là gom cụm: mua ít, mua vừa, mua nhiều

### Đếm số lượng mặt hàng được bán ra (Mặt hàng được bán ra càng nhiều thì khả năng người ta mua hàng sẽ càng cao ) 
(Hệ số phổ biến của sản phẩm)

chuẩn hóa theo từng category_l1, và chỉ giữ TOP 10 item phổ biến nhất trong mỗi category_l1.

In [1]:

# =========================
# 1) TÍNH total_sold THEO item_id (gộp 20 chunk)
# =========================
TRANS_PATH = r"D:\003. HK1 - Năm 3\02. CS116 - Python cho Máy học\CS116-DoAn\Phase-2\preprocessing data"
trans_files = sorted(glob.glob(f"{TRANS_PATH}\\sale_pers.purchase_history_daily_chunk_*.parquet"))

item_sales = []

for file in trans_files:
    print("Processing:", file)

    df = (
        pl.read_parquet(file)
        .select(["item_id", "quantity"])
        .group_by("item_id")
        .agg(pl.col("quantity").sum().alias("total_sold"))
    )
    item_sales.append(df)

item_sales_all = (
    pl.concat(item_sales, how="vertical_relaxed")
    .group_by("item_id")
    .agg(pl.col("total_sold").sum().alias("total_sold"))
)

print("item_sales_all shape:", item_sales_all.shape)

# =========================
# 2) JOIN LẤY category_l1
# =========================
# df_item: item dataframe của bạn (đã load sẵn) phải có ["item_id","category_l1"]
item_basic = df_item.select(["item_id", "category_l1"])

item_sales_cat = (
    item_sales_all
    .join(item_basic, on="item_id", how="left")
    .filter(pl.col("category_l1").is_not_null())
)

print("item_sales_cat shape:", item_sales_cat.shape)

# =========================
# 3) TOP 10 item_id THEO MỖI category_l1
# =========================
top10_by_cat = (
    item_sales_cat
    .sort(["category_l1", "total_sold"], descending=[False, True])
    .group_by("category_l1")
    .head(10)
    .sort(["category_l1", "total_sold"], descending=[False, True])
)

print("\n✅ Top 10 item phổ biến nhất theo từng category_l1 (mẫu):")
print(top10_by_cat.head(30))

# =========================
# 4) CHECK: in ra 1 category bất kỳ để bạn nhìn rõ 10 item_id
# =========================
sample_cat = top10_by_cat.select("category_l1").unique().head(1).item()
print(f"\n=== CHECK TOP 10 của category_l1 = {sample_cat} ===")
print(
    top10_by_cat
    .filter(pl.col("category_l1") == sample_cat)
    .select(["category_l1", "item_id", "total_sold"])
)

NameError: name 'glob' is not defined

In [ ]:
top10_by_cat.head(50)

shape: (50, 3)
┌─────────────┬───────────────┬────────────┐
│ category_l1 ┆ item_id       ┆ total_sold │
│ ---         ┆ ---           ┆ ---        │
│ str         ┆ str           ┆ i32        │
╞═════════════╪═══════════════╪════════════╡
│ Babycare    ┆ 5950000000001 ┆ 203388     │
│ Babycare    ┆ 0203000000004 ┆ 128333     │
│ Babycare    ┆ 0007150000144 ┆ 123655     │
│ Babycare    ┆ 0007150000031 ┆ 80181      │
│ Babycare    ┆ 6498000000005 ┆ 60252      │
│ …           ┆ …             ┆ …          │
│ Sữa         ┆ 2483000000004 ┆ 115008     │
│ Sữa         ┆ 4355000000001 ┆ 99082      │
│ Sữa         ┆ 6488000000001 ┆ 97755      │
│ Sữa         ┆ 4327000000001 ┆ 90539      │
│ Sữa         ┆ 0020010000305 ┆ 90178      │
└─────────────┴───────────────┴────────────┘

In [ ]:
# =========================
# SAVE top10_by_cat
# =========================

OUTPUT_DIR = r"D:\003. HK1 - Năm 3\02. CS116 - Python cho Máy học\CS116-DoAn\Phase-2\Feature engineering"
OUTPUT_PATH = f"{OUTPUT_DIR}\\top10_by_cat.parquet"

top10_by_cat.write_parquet(OUTPUT_PATH)

print("✅ Đã lưu top10_by_cat xuống:")
print(OUTPUT_PATH)
print("Shape:", top10_by_cat.shape)

✅ Đã lưu top10_by_cat xuống:
D:\003. HK1 - Năm 3\02. CS116 - Python cho Máy học\CS116-DoAn\Phase-2\Feature engineering\top10_by_cat.parquet
Shape: (140, 3)

**Xét Đếm số lượng mặt hàng được bán ra (Mặt hàng được bán ra càng nhiều thì khả năng người ta mua hàng sẽ càng cao ) (Hệ số phổ biến của sản phẩm), chuẩn hóa theo từng category_l1, và chỉ giữ TOP 10 item phổ biến nhất trong mỗi category_l1. Nhưng đếm theo tháng**

Tức là kiểu như tháng nào người dùng sẽ thường mua sản phẩm nào. Để sau này ví dụ thầy cho dữ liệu tháng 1/2025 thì có thể dùng những sản phẩm phổ biến của tháng 11/2024 để gợi ý

In [ ]:

TRANS_PATH = r"D:\003. HK1 - Năm 3\02. CS116 - Python cho Máy học\CS116-DoAn\Phase-2\preprocessing data"
ITEM_PATH  = r"D:\003. HK1 - Năm 3\02. CS116 - Python cho Máy học\CS116-DoAn\Phase-2\Feature engineering\sale_pers.item_chunk_0.parquet"

trans_files = sorted(
    glob.glob(f"{TRANS_PATH}/sale_pers.purchase_history_daily_chunk_*.parquet")
)

item = (
    pl.read_parquet(ITEM_PATH)
    .select(["item_id", "category_l1"])
)

In [ ]:
monthly_sales_chunks = []

for file in trans_files:
    print("Processing:", os.path.basename(file))

    df = (
        pl.read_parquet(file)
        .select(["item_id", "quantity", "created_date"])
        .with_columns(
            pl.col("created_date")
            .cast(pl.Date)
            .dt.strftime("%Y-%m")
            .alias("month")
        )
        .join(item, on="item_id", how="left")
        .filter(pl.col("category_l1").is_not_null())
        .group_by(["month", "category_l1", "item_id"])
        .agg(
            pl.col("quantity").sum().alias("total_sold")
        )
    )

    monthly_sales_chunks.append(df)

Processing: sale_pers.purchase_history_daily_chunk_0.parquet
Processing: sale_pers.purchase_history_daily_chunk_1.parquet
Processing: sale_pers.purchase_history_daily_chunk_10.parquet
Processing: sale_pers.purchase_history_daily_chunk_11.parquet
Processing: sale_pers.purchase_history_daily_chunk_12.parquet
Processing: sale_pers.purchase_history_daily_chunk_13.parquet
Processing: sale_pers.purchase_history_daily_chunk_14.parquet
Processing: sale_pers.purchase_history_daily_chunk_15.parquet
Processing: sale_pers.purchase_history_daily_chunk_16.parquet
Processing: sale_pers.purchase_history_daily_chunk_17.parquet
Processing: sale_pers.purchase_history_daily_chunk_18.parquet
Processing: sale_pers.purchase_history_daily_chunk_19.parquet
Processing: sale_pers.purchase_history_daily_chunk_2.parquet
Processing: sale_pers.purchase_history_daily_chunk_3.parquet
Processing: sale_pers.purchase_history_daily_chunk_4.parquet
Processing: sale_pers.purchase_history_daily_chunk_5.parquet
Processing: sale_pers.purchase_history_daily_chunk_6.parquet
Processing: sale_pers.purchase_history_daily_chunk_7.parquet
Processing: sale_pers.purchase_history_daily_chunk_8.parquet
Processing: sale_pers.purchase_history_daily_chunk_9.parquet

In [ ]:
monthly_sales_all = (
    pl.concat(monthly_sales_chunks, how="vertical_relaxed")
    .group_by(["month", "category_l1", "item_id"])
    .agg(
        pl.col("total_sold").sum().alias("total_sold")
    )
)

print("monthly_sales_all shape:", monthly_sales_all.shape)

monthly_sales_all shape: (153563, 4)

In [ ]:
top10_by_cat_month = (
    monthly_sales_all
    .with_columns(
        pl.col("total_sold")
        .rank(method="dense", descending=True)
        .over(["month", "category_l1"])
        .alias("rank")
    )
    .filter(pl.col("rank") <= 10)
    .sort(["month", "category_l1", "rank"])
)

print("top10_by_cat_month shape:", top10_by_cat_month.shape)

top10_by_cat_month shape: (1691, 5)

In [ ]:
print(
    top10_by_cat_month
    .filter(pl.col("month") == "2024-11")
    .head(50)
)

shape: (50, 5)
┌─────────┬─────────────┬───────────────┬────────────┬──────┐
│ month   ┆ category_l1 ┆ item_id       ┆ total_sold ┆ rank │
│ ---     ┆ ---         ┆ ---           ┆ ---        ┆ ---  │
│ str     ┆ str         ┆ str           ┆ i32        ┆ u32  │
╞═════════╪═════════════╪═══════════════╪════════════╪══════╡
│ 2024-11 ┆ Babycare    ┆ 5950000000001 ┆ 16759      ┆ 1    │
│ 2024-11 ┆ Babycare    ┆ 0203000000004 ┆ 10882      ┆ 2    │
│ 2024-11 ┆ Babycare    ┆ 0007150000144 ┆ 10481      ┆ 3    │
│ 2024-11 ┆ Babycare    ┆ 0007150000031 ┆ 6373       ┆ 4    │
│ 2024-11 ┆ Babycare    ┆ 6498000000005 ┆ 5682       ┆ 5    │
│ …       ┆ …           ┆ …             ┆ …          ┆ …    │
│ 2024-11 ┆ Sữa         ┆ 3774000000003 ┆ 13280      ┆ 5    │
│ 2024-11 ┆ Sữa         ┆ 4950000000001 ┆ 12142      ┆ 6    │
│ 2024-11 ┆ Sữa         ┆ 2483000000004 ┆ 9208       ┆ 7    │
│ 2024-11 ┆ Sữa         ┆ 2482000000004 ┆ 8949       ┆ 8    │
│ 2024-11 ┆ Sữa         ┆ 2578000000002 ┆ 8463       ┆ 9    │
└─────────┴─────────────┴───────────────┴────────────┴──────┘

In [ ]:
num_months = top10_by_cat_month.select("month").n_unique()

print(f"Số lượng tháng được lọc ra: {num_months}")

Số lượng tháng được lọc ra: 12

In [ ]:
check = (
    top10_by_cat_month
    .group_by(["month", "category_l1"])
    .agg(pl.count().alias("num_items"))
    .filter(pl.col("num_items") != 10)
)

print("Các group KHÔNG đủ 10 item (nếu có):")
print(check)

Các group KHÔNG đủ 10 item (nếu có):
shape: (11, 3)
┌─────────┬────────────────────────┬───────────┐
│ month   ┆ category_l1            ┆ num_items │
│ ---     ┆ ---                    ┆ ---       │
│ str     ┆ str                    ┆ u32       │
╞═════════╪════════════════════════╪═══════════╡
│ 2024-12 ┆ Thực phẩm cho bé       ┆ 11        │
│ 2024-08 ┆ Thời trang             ┆ 11        │
│ 2024-09 ┆ Tã                     ┆ 11        │
│ 2024-07 ┆ Thực phẩm cho gia đình ┆ 11        │
│ 2024-03 ┆ Thực phẩm cho gia đình ┆ 11        │
│ …       ┆ …                      ┆ …         │
│ 2024-06 ┆ Hóa mỹ phẩm gia đình   ┆ 11        │
│ 2024-11 ┆ Phụ kiện               ┆ 11        │
│ 2024-10 ┆ Tã                     ┆ 11        │
│ 2024-10 ┆ Phụ kiện               ┆ 11        │
│ 2024-01 ┆ Phụ kiện               ┆ 11        │
└─────────┴────────────────────────┴───────────┘

C:\Users\PC\AppData\Local\Temp\ipykernel_12820\1899442887.py:4: DeprecationWarning: `pl.count()` is deprecated. Please use `pl.len()` instead.
(Deprecated in version 0.20.5)
  .agg(pl.count().alias("num_items"))

In [ ]:
OUTPUT_DIR = r"D:\003. HK1 - Năm 3\02. CS116 - Python cho Máy học\CS116-DoAn\Phase-2\Feature engineering"
OUTPUT_PATH = f"{OUTPUT_DIR}\\top10_by_cat_month.parquet"

top10_by_cat_month.write_parquet(OUTPUT_PATH)

print("✅ Đã lưu top10_by_cat_month")
print("Path:", OUTPUT_PATH)

✅ Đã lưu top10_by_cat_month
Path: D:\003. HK1 - Năm 3\02. CS116 - Python cho Máy học\CS116-DoAn\Phase-2\Feature engineering\top10_by_cat_month.parquet

### Lần cuối cùng mua hàng của khách hàng

In [ ]:
# Như tạo r biến: Recency

### =========================================================================================

In [ ]:
pl.Config.set_tbl_rows(100)

polars.config.Config