In [36]:
import polars as pl
import pandas as pd
import numpy as np
import os

DATA_PATH = r"D:\003. HK1 - Năm 3\02. CS116 - Python cho Máy học\CS116-DoAn\dataset\sales_pers.item_chunk_0.parquet"

df = pl.read_parquet(DATA_PATH)
print(f"Số dòng: {df.height:,}, Số cột: {df.width}")

Số dòng: 27,332, Số cột: 34

In [37]:
print("\nCác cột ban đầu:")
print(df.columns)

Các cột ban đầu:
['p_id', 'item_id', 'price', 'category_l1_id', 'category_l1', 'category_l2_id', 'category_l2', 'category_l3_id', 'category_l3', 'category_id', 'category', 'description', 'brand', 'manufacturer', 'creation_timestamp', 'is_deleted', 'created_date', 'updated_date', 'sync_status_id', 'last_sync_date', 'sync_error_message', 'image_url', 'gender_target', 'age_group', 'item_type', 'gp', 'weight', 'color', 'size', 'origin', 'volume', 'material', 'sale_status', 'description_new']

# Task 1: Loại bỏ các cột mà nhóm nghĩ là không cần thiết.

In [38]:
# --- Danh sách cột cần loại bỏ (theo phân tích EDA & tương quan) ---
cols_to_drop = [
    # --- Metadata hệ thống (không dùng cho mô hình) ---
    "p_id",
    "is_deleted",
    "sync_status_id",
    "sync_error_message",
    "image_url",
    "last_sync_date",
    "creation_timestamp",
    "updated_date",
    "created_date",
    "sale_status",

    # --- Cột numeric hầu như vô nghĩa / chỉ có 1 giá trị ---
    "gp",
    "weight",
    "volume",

    # --- Các cột chất lượng kém / missing cực cao / không dùng ---
    "color",
    "size",
    "material",
    "origin",
    "manufacturer",

    # --- ID phân loại (trùng với tên category) ---
    "category_l1_id",
    "category_l2_id",
    "category_l3_id",
    "category_id"
]



# --- Loại bỏ các cột không cần thiết ---
df_cleaned = df.drop(cols_to_drop)

print(f"\nĐã loại bỏ {len(cols_to_drop)} cột không cần thiết.")
print(f"Số cột còn lại: {df_cleaned.width}")
print("\nDanh sách cột sau khi loại bỏ:")
print(df_cleaned.columns)

Đã loại bỏ 22 cột không cần thiết.
Số cột còn lại: 12

Danh sách cột sau khi loại bỏ:
['item_id', 'price', 'category_l1', 'category_l2', 'category_l3', 'category', 'description', 'brand', 'gender_target', 'age_group', 'item_type', 'description_new']

# Task 2: Xử lý NULL, Xử lý Outlier

## Xử lý outlier

In [39]:
# df_cleaned: dataframe sau khi đã drop các cột không cần thiết
print("Số lượng ban đầu:", df_cleaned.height)

# --- LOẠI SẢN PHẨM CÓ PRICE ≤ 1 (Outlier) ---
df_no_outlier = df_cleaned.filter(pl.col("price") > 1)

print("Số lượng sau khi loại outlier (price ≤ 1):", df_no_outlier.height)
print("Số lượng bị loại:", df_cleaned.height - df_no_outlier.height)

# Kiểm tra lại xem còn outlier hay không
print("\nKiểm tra min price sau khi xử lý:")
print(df_no_outlier.select(pl.col("price").min()))

Số lượng ban đầu: 27332
Số lượng sau khi loại outlier (price ≤ 1): 27323
Số lượng bị loại: 9

Kiểm tra min price sau khi xử lý:
shape: (1, 1)
┌───────────────┐
│ price         │
│ ---           │
│ decimal[38,4] │
╞═══════════════╡
│ 1000.0000     │
└───────────────┘

In [40]:
# Chuẩn hóa giá trị Unisex → Không xác định
df_no_outlier = df_no_outlier.with_columns(
    pl.col("gender_target").replace("Unisex", "Không xác định")
)

print("Đã chuyển toàn bộ Unisex thành 'Không xác định'.")
print(df_no_outlier["gender_target"].value_counts())

Đã chuyển toàn bộ Unisex thành 'Không xác định'.
shape: (4, 2)
┌────────────────┬───────┐
│ gender_target  ┆ count │
│ ---            ┆ ---   │
│ str            ┆ u32   │
╞════════════════╪═══════╡
│ Bé Trai        ┆ 3318  │
│ Không xác định ┆ 18035 │
│ Bé Gái         ┆ 4108  │
│ Sơ sinh        ┆ 1862  │
└────────────────┴───────┘

In [41]:
df_no_outlier.head(5)

shape: (5, 12)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ item_id   ┆ price     ┆ category_ ┆ category_ ┆ … ┆ gender_ta ┆ age_group ┆ item_type ┆ descript │
│ ---       ┆ ---       ┆ l1        ┆ l2        ┆   ┆ rget      ┆ ---       ┆ ---       ┆ ion_new  │
│ str       ┆ decimal[3 ┆ ---       ┆ ---       ┆   ┆ ---       ┆ str       ┆ str       ┆ ---      │
│           ┆ 8,4]      ┆ str       ┆ str       ┆   ┆ str       ┆           ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 050202000 ┆ 99000.000 ┆ Babycare  ┆ Bình sữa, ┆ … ┆ Không xác ┆ Không xác ┆ Không xác ┆ Chi tiết │
│ 0004      ┆ 0         ┆           ┆ phụ kiện  ┆   ┆ định      ┆ định      ┆ định      ┆ sản phẩm │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ …        │
│ 001029004 ┆ 69000.000 ┆ Thời      ┆ Cơ cấu    ┆ … ┆ Bé Gái    ┆ Từ 3Y     ┆ Bộ quần   ┆ Không    │
│ 0150      ┆ 0         ┆ trang     ┆ hàng cũ   ┆   ┆           ┆           ┆ áo        ┆ xác định │
│ 000801000 ┆ 45000.000 ┆ Đồ chơi & ┆ 0-1Y      ┆ … ┆ Không xác ┆ Không xác ┆ Không xác ┆ Chi tiết │
│ 0015      ┆ 0         ┆ Sách      ┆           ┆   ┆ định      ┆ định      ┆ định      ┆ sản phẩm │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ …        │
│ 002001000 ┆ 401000.00 ┆ Tã        ┆ Merries   ┆ … ┆ Không xác ┆ Không xác ┆ Không xác ┆ Không    │
│ 0094      ┆ 00        ┆           ┆           ┆   ┆ định      ┆ định      ┆ định      ┆ xác định │
│ 002001000 ┆ 401000.00 ┆ Tã        ┆ Merries   ┆ … ┆ Không xác ┆ Không xác ┆ Không xác ┆ Không    │
│ 0098      ┆ 00        ┆           ┆           ┆   ┆ định      ┆ định      ┆ định      ┆ xác định │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

## Xử lý null

In [15]:
pl.Config.set_tbl_rows(50)             # số dòng tối đa hiển thị


# df_final = df_no_outlier
df_final = df_no_outlier

n = df_final.height

results = []

for col in df_final.columns:
    s = df_final[col]

    # NULL
    null_count = s.null_count()

    # UNKNOWN ("Không xác định")
    if s.dtype == pl.String:
        # Đếm trực tiếp bằng Python list, không lỗi
        unknown_count = s.to_list().count("Không xác định")
    else:
        unknown_count = 0

    results.append({
        "column": col,
        "dtype": s.dtype,
        "null_count": null_count,
        "null_ratio(%)": round(null_count / n * 100, 2),
        "unknown_count": unknown_count,
        "unknown_ratio(%)": round(unknown_count / n * 100, 2)
    })

df_missing_report = pl.DataFrame(results)

print(df_missing_report)

shape: (13, 6)
┌─────────────────┬─────────────────┬────────────┬───────────────┬───────────────┬─────────────────┐
│ column          ┆ dtype           ┆ null_count ┆ null_ratio(%) ┆ unknown_count ┆ unknown_ratio(% │
│ ---             ┆ ---             ┆ ---        ┆ ---           ┆ ---           ┆ )               │
│ str             ┆ object          ┆ i64        ┆ f64           ┆ i64           ┆ ---             │
│                 ┆                 ┆            ┆               ┆               ┆ f64             │
╞═════════════════╪═════════════════╪════════════╪═══════════════╪═══════════════╪═════════════════╡
│ item_id         ┆ String          ┆ 0          ┆ 0.0           ┆ 0             ┆ 0.0             │
│ price           ┆ Decimal(precisi ┆ 0          ┆ 0.0           ┆ 0             ┆ 0.0             │
│                 ┆ on=38, scale=4) ┆            ┆               ┆               ┆                 │
│ category_l1     ┆ String          ┆ 0          ┆ 0.0           ┆ 0             ┆ 0.0             │
│ category_l2     ┆ String          ┆ 0          ┆ 0.0           ┆ 0             ┆ 0.0             │
│ category_l3     ┆ String          ┆ 0          ┆ 0.0           ┆ 0             ┆ 0.0             │
│ category        ┆ String          ┆ 0          ┆ 0.0           ┆ 0             ┆ 0.0             │
│ description     ┆ String          ┆ 0          ┆ 0.0           ┆ 18621         ┆ 68.15           │
│ brand           ┆ String          ┆ 0          ┆ 0.0           ┆ 5472          ┆ 20.03           │
│ gender_target   ┆ String          ┆ 0          ┆ 0.0           ┆ 18029         ┆ 65.98           │
│ age_group       ┆ String          ┆ 0          ┆ 0.0           ┆ 15803         ┆ 57.84           │
│ item_type       ┆ String          ┆ 0          ┆ 0.0           ┆ 9812          ┆ 35.91           │
│ sale_status     ┆ Int32           ┆ 0          ┆ 0.0           ┆ 0             ┆ 0.0             │
│ description_new ┆ String          ┆ 5006       ┆ 18.32         ┆ 12815         ┆ 46.9            │
└─────────────────┴─────────────────┴────────────┴───────────────┴───────────────┴─────────────────┘

### Xử lý gender_target

In [42]:

# Lọc các item thời trang nhưng gender_target = "Không xác định"
df_fashion_unknown = (
    df_no_outlier
        .filter(
            (pl.col("category_l1") == "Thời trang") &
            (pl.col("gender_target") == "Không xác định")
        )
)

print("Tổng số item thời trang có gender_target = 'Không xác định':", df_fashion_unknown.height)

# Lấy 20 dòng ngẫu nhiên
df_sample = df_fashion_unknown.sample(n=20, with_replacement=False)

pd.set_option('display.max_columns', None)
df_sample.head(10)

Tổng số item thời trang có gender_target = 'Không xác định': 7264

shape: (10, 12)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ item_id   ┆ price     ┆ category_ ┆ category_ ┆ … ┆ gender_ta ┆ age_group ┆ item_type ┆ descript │
│ ---       ┆ ---       ┆ l1        ┆ l2        ┆   ┆ rget      ┆ ---       ┆ ---       ┆ ion_new  │
│ str       ┆ decimal[3 ┆ ---       ┆ ---       ┆   ┆ ---       ┆ str       ┆ str       ┆ ---      │
│           ┆ 8,4]      ┆ str       ┆ str       ┆   ┆ str       ┆           ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 456400000 ┆ 189000.00 ┆ Thời      ┆ Modal     ┆ … ┆ Không xác ┆ Không xác ┆ Không xác ┆ null     │
│ 0368      ┆ 00        ┆ trang     ┆ kháng     ┆   ┆ định      ┆ định      ┆ định      ┆          │
│           ┆           ┆           ┆ khuẩn     ┆   ┆           ┆           ┆           ┆          │
│ 002417104 ┆ 49000.000 ┆ Thời      ┆ Cơ cấu    ┆ … ┆ Không xác ┆ Không xác ┆ Không xác ┆ Không    │
│ 0001      ┆ 0         ┆ trang     ┆ hàng cũ   ┆   ┆ định      ┆ định      ┆ định      ┆ xác định │
│ 353200000 ┆ 119000.00 ┆ Thời      ┆ Quần áo & ┆ … ┆ Không xác ┆ Không xác ┆ Không xác ┆ null     │
│ 0263      ┆ 00        ┆ trang     ┆ Phụ kiện  ┆   ┆ định      ┆ định      ┆ định      ┆          │
│           ┆           ┆           ┆ sơ sinh   ┆   ┆           ┆           ┆           ┆          │
│ 087810479 ┆ 69000.000 ┆ Thời      ┆ Cơ cấu    ┆ … ┆ Không xác ┆ Không xác ┆ Không xác ┆ null     │
│ 0001      ┆ 0         ┆ trang     ┆ hàng cũ   ┆   ┆ định      ┆ định      ┆ định      ┆          │
│ 332400000 ┆ 219000.00 ┆ Thời      ┆ Thời      ┆ … ┆ Không xác ┆ Không xác ┆ Không xác ┆ Không    │
│ 0405      ┆ 00        ┆ trang     ┆ trang bé  ┆   ┆ định      ┆ định      ┆ định      ┆ xác định │
│           ┆           ┆           ┆ gái       ┆   ┆           ┆           ┆           ┆          │
│ 456400000 ┆ 189000.00 ┆ Thời      ┆ Modal     ┆ … ┆ Không xác ┆ Không xác ┆ Không xác ┆ null     │
│ 0370      ┆ 00        ┆ trang     ┆ kháng     ┆   ┆ định      ┆ định      ┆ định      ┆          │
│           ┆           ┆           ┆ khuẩn     ┆   ┆           ┆           ┆           ┆          │
│ 699700000 ┆ 349000.00 ┆ Thời      ┆ Modal     ┆ … ┆ Không xác ┆ Không xác ┆ Không xác ┆ Không    │
│ 0244      ┆ 00        ┆ trang     ┆ kháng     ┆   ┆ định      ┆ định      ┆ định      ┆ xác định │
│           ┆           ┆           ┆ khuẩn     ┆   ┆           ┆           ┆           ┆          │
│ 085801949 ┆ 49000.000 ┆ Thời      ┆ Cơ cấu    ┆ … ┆ Không xác ┆ Không xác ┆ Không xác ┆ null     │
│ 0004      ┆ 0         ┆ trang     ┆ hàng cũ   ┆   ┆ định      ┆ định      ┆ định      ┆          │
│ 395300000 ┆ 129000.00 ┆ Thời      ┆ Thời      ┆ … ┆ Không xác ┆ Không xác ┆ Không xác ┆ Không    │
│ 0768      ┆ 00        ┆ trang     ┆ trang bé  ┆   ┆ định      ┆ định      ┆ định      ┆ xác định │
│           ┆           ┆           ┆ trai      ┆   ┆           ┆           ┆           ┆          │
│ 000901016 ┆ 49000.000 ┆ Thời      ┆ Cơ cấu    ┆ … ┆ Không xác ┆ Từ 6M     ┆ Áo        ┆ Không    │
│ 0415      ┆ 0         ┆ trang     ┆ hàng cũ   ┆   ┆ định      ┆           ┆           ┆ xác định │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [43]:
# Lọc sản phẩm thời trang có category chứa "đầm" hoặc "váy" và gender_target = "Không xác định"
df_dam_vay_unknown = (
    df_no_outlier
    .filter(
        (pl.col("category_l1") == "Thời trang")
        &
        (pl.col("gender_target") == "Không xác định")
        &
        (
            pl.col("category").str.contains("đầm", literal=False)
            | pl.col("category").str.contains("váy", literal=False)
        )
    )
)

# In thống kê số dòng
print("Tổng sản phẩm thỏa điều kiện:", df_dam_vay_unknown.height)

# Lấy mẫu 20 dòng
df_sample = df_dam_vay_unknown.sample(n=20, seed=42)

# Hiển thị đầy đủ cột
pd.set_option('display.max_columns', None)
df_sample.head(10)

Tổng sản phẩm thỏa điều kiện: 192

shape: (10, 12)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ item_id   ┆ price     ┆ category_ ┆ category_ ┆ … ┆ gender_ta ┆ age_group ┆ item_type ┆ descript │
│ ---       ┆ ---       ┆ l1        ┆ l2        ┆   ┆ rget      ┆ ---       ┆ ---       ┆ ion_new  │
│ str       ┆ decimal[3 ┆ ---       ┆ ---       ┆   ┆ ---       ┆ str       ┆ str       ┆ ---      │
│           ┆ 8,4]      ┆ str       ┆ str       ┆   ┆ str       ┆           ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 604500000 ┆ 349000.00 ┆ Thời      ┆ Cơ cấu    ┆ … ┆ Không xác ┆ Không xác ┆ Không xác ┆ null     │
│ 0002      ┆ 00        ┆ trang     ┆ hàng cũ   ┆   ┆ định      ┆ định      ┆ định      ┆          │
│ 109209385 ┆ 189000.00 ┆ Thời      ┆ Cơ cấu    ┆ … ┆ Không xác ┆ Mẹ        ┆ Áo bầu    ┆ Không    │
│ 0001      ┆ 00        ┆ trang     ┆ hàng cũ   ┆   ┆ định      ┆           ┆           ┆ xác định │
│ 108302285 ┆ 149000.00 ┆ Thời      ┆ Cơ cấu    ┆ … ┆ Không xác ┆ Mẹ        ┆ Quần bầu  ┆ Không    │
│ 0002      ┆ 00        ┆ trang     ┆ hàng cũ   ┆   ┆ định      ┆           ┆           ┆ xác định │
│ 088602677 ┆ 49000.000 ┆ Thời      ┆ Cơ cấu    ┆ … ┆ Không xác ┆ Không xác ┆ Không xác ┆ null     │
│ 0002      ┆ 0         ┆ trang     ┆ hàng cũ   ┆   ┆ định      ┆ định      ┆ định      ┆          │
│ 088702677 ┆ 49000.000 ┆ Thời      ┆ Cơ cấu    ┆ … ┆ Không xác ┆ Không xác ┆ Không xác ┆ null     │
│ 0004      ┆ 0         ┆ trang     ┆ hàng cũ   ┆   ┆ định      ┆ định      ┆ định      ┆          │
│ 089101979 ┆ 49000.000 ┆ Thời      ┆ Cơ cấu    ┆ … ┆ Không xác ┆ Không xác ┆ Không xác ┆ null     │
│ 0002      ┆ 0         ┆ trang     ┆ hàng cũ   ┆   ┆ định      ┆ định      ┆ định      ┆          │
│ 001219016 ┆ 49000.000 ┆ Thời      ┆ Cơ cấu    ┆ … ┆ Không xác ┆ Không xác ┆ Không xác ┆ Không    │
│ 0065      ┆ 0         ┆ trang     ┆ hàng cũ   ┆   ┆ định      ┆ định      ┆ định      ┆ xác định │
│ 108003386 ┆ 199000.00 ┆ Thời      ┆ Cơ cấu    ┆ … ┆ Không xác ┆ Không xác ┆ Không xác ┆ null     │
│ 0001      ┆ 00        ┆ trang     ┆ hàng cũ   ┆   ┆ định      ┆ định      ┆ định      ┆          │
│ 108000486 ┆ 189000.00 ┆ Thời      ┆ Cơ cấu    ┆ … ┆ Không xác ┆ Mẹ        ┆ Áo bầu    ┆ Không    │
│ 0001      ┆ 00        ┆ trang     ┆ hàng cũ   ┆   ┆ định      ┆           ┆           ┆ xác định │
│ 108100488 ┆ 199000.00 ┆ Thời      ┆ Cơ cấu    ┆ … ┆ Không xác ┆ Mẹ        ┆ Đầm bầu   ┆ Không    │
│ 0001      ┆ 00        ┆ trang     ┆ hàng cũ   ┆   ┆ định      ┆           ┆           ┆ xác định │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [46]:
# Sao chép gender_target sang cột mới
df_filled = df_no_outlier.with_columns(
    pl.col("gender_target").alias("gender_target_final")
)

# =========================
# 1) FILL SƠ SINH
# =========================

mask_sosinh = (
    (pl.col("category_l1") == "Thời trang")
    & (pl.col("gender_target_final") == "Không xác định")
    & (
        pl.col("category_l2").str.contains("sơ sinh", literal=False)
        | pl.col("category").str.contains("sơ sinh", literal=False)
        | pl.col("category").str.contains("0-3m", literal=False)
        | pl.col("category").str.contains("3-6m", literal=False)
        | pl.col("category").str.contains("0-12m", literal=False)
        | pl.col("category").str.contains("\\bnb\\b", literal=False)  # NB
        | pl.col("category").str.contains("newborn", literal=False)
    )
)

df_filled = df_filled.with_columns(
    pl.when(mask_sosinh)
      .then("Sơ sinh")
      .otherwise(pl.col("gender_target_final"))
      .alias("gender_target_final")
)

# =========================
# 2) FILL BÉ GÁI
# =========================

mask_fashion_unknown = (
    (pl.col("category_l1") == "Thời trang")
    & (pl.col("gender_target_final") == "Không xác định")
)

mask_not_maternity = (
    (~pl.col("category").str.contains("bầu", literal=False))
    & (~pl.col("category_l2").str.contains("bầu", literal=False))
    & (~pl.col("category_l3").str.contains("bầu", literal=False))
)

mask_not_ambiguous = (
    ~pl.col("category_l3").str.contains("Thời trang bé trai, bé gái cũ", literal=False)
)

mask_girl_keyword = (
    pl.col("category").str.contains("bé gái|đầm|váy|chân váy", literal=False)
    | pl.col("category_l2").str.contains("bé gái|đầm bé gái|bộ bé gái", literal=False)
    | pl.col("category_l3").str.contains("bé gái|đầm|váy", literal=False)
)

mask_fill_girl = mask_fashion_unknown & mask_not_maternity & mask_not_ambiguous & mask_girl_keyword

df_filled = df_filled.with_columns(
    pl.when(mask_fill_girl)
      .then("Bé Gái")
      .otherwise(pl.col("gender_target_final"))
      .alias("gender_target_final")
)

# =========================
# 3) FILL BÉ TRAI
# =========================

mask_boy_keyword = (
    pl.col("category").str.contains("bé trai", literal=False)
    | pl.col("category_l2").str.contains("bé trai|bộ bé trai", literal=False)
    | pl.col("category_l3").str.contains("bé trai", literal=False)
)

mask_fill_boy = mask_fashion_unknown & mask_not_ambiguous & mask_boy_keyword

df_filled = df_filled.with_columns(
    pl.when(mask_fill_boy)
      .then("Bé Trai")
      .otherwise(pl.col("gender_target_final"))
      .alias("gender_target_final")
)

ColumnNotFoundError: unable to find column "Sơ sinh"; valid columns: ["item_id", "price", "category_l1", "category_l2", "category_l3", "category", "description", "brand", "gender_target", "age_group", "item_type", "description_new", "gender_target_final"]

In [44]:

# Lọc các sản phẩm thuộc Phụ kiện và gender_target = "Không xác định"
df_phukien_unknown = (
    df_no_outlier
    .filter(
        (pl.col("category_l1") == "Phụ kiện") &
        (pl.col("gender_target") == "Không xác định")
    )
)

# Kiểm tra số lượng
print("Tổng số sản phẩm Phụ kiện có gender_target = 'Không xác định':",
      df_phukien_unknown.height)

# Lấy ngẫu nhiên 10 dòng
df_sample = df_phukien_unknown.sample(n=10, seed=42)

# In ra toàn bộ cột để bạn xem xét thật chi tiết
pd.set_option('display.max_columns', None)
df_sample.head(10)

Tổng số sản phẩm Phụ kiện có gender_target = 'Không xác định': 1666

shape: (10, 12)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ item_id   ┆ price     ┆ category_ ┆ category_ ┆ … ┆ gender_ta ┆ age_group ┆ item_type ┆ descript │
│ ---       ┆ ---       ┆ l1        ┆ l2        ┆   ┆ rget      ┆ ---       ┆ ---       ┆ ion_new  │
│ str       ┆ decimal[3 ┆ ---       ┆ ---       ┆   ┆ ---       ┆ str       ┆ str       ┆ ---      │
│           ┆ 8,4]      ┆ str       ┆ str       ┆   ┆ str       ┆           ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 605300000 ┆ 49000.000 ┆ Phụ kiện  ┆ Cơ cấu    ┆ … ┆ Không xác ┆ 1Y-3Y     ┆ Giày      ┆ Chi tiết │
│ 0007      ┆ 0         ┆           ┆ hàng cũ   ┆   ┆ định      ┆           ┆           ┆ sản phẩm │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ …        │
│ 605500000 ┆ 49000.000 ┆ Phụ kiện  ┆ Cơ cấu    ┆ … ┆ Không xác ┆ Không xác ┆ Giày      ┆ Chi tiết │
│ 0002      ┆ 0         ┆           ┆ hàng cũ   ┆   ┆ định      ┆ định      ┆           ┆ sản phẩm │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ …        │
│ 480400000 ┆ 249000.00 ┆ Phụ kiện  ┆ Phụ kiện  ┆ … ┆ Không xác ┆ Từ 2Y     ┆ Balo      ┆ Chi tiết │
│ 0016      ┆ 00        ┆           ┆ khác      ┆   ┆ định      ┆           ┆           ┆ sản phẩm │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ …        │
│ 479400000 ┆ 139000.00 ┆ Phụ kiện  ┆ Cơ cấu    ┆ … ┆ Không xác ┆ Không xác ┆ Không xác ┆ null     │
│ 0015      ┆ 00        ┆           ┆ hàng cũ   ┆   ┆ định      ┆ định      ┆ định      ┆          │
│ 481200000 ┆ 99000.000 ┆ Phụ kiện  ┆ Cơ cấu    ┆ … ┆ Không xác ┆ Không xác ┆ Không xác ┆ null     │
│ 0011      ┆ 0         ┆           ┆ hàng cũ   ┆   ┆ định      ┆ định      ┆ định      ┆          │
│ 605500000 ┆ 119000.00 ┆ Phụ kiện  ┆ Giày tập  ┆ … ┆ Không xác ┆ Không xác ┆ Không xác ┆ Chi tiết │
│ 0036      ┆ 00        ┆           ┆ đi        ┆   ┆ định      ┆ định      ┆ định      ┆ sản phẩm │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ …        │
│ 001452104 ┆ 9000.0000 ┆ Phụ kiện  ┆ Cơ cấu    ┆ … ┆ Không xác ┆ Không xác ┆ Kẹp tóc   ┆ Chi tiết │
│ 0104      ┆           ┆           ┆ hàng cũ   ┆   ┆ định      ┆ định      ┆           ┆ sản phẩm │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ …        │
│ 400300000 ┆ 229000.00 ┆ Phụ kiện  ┆ Giày tập  ┆ … ┆ Không xác ┆ 0-24M     ┆ Giày tập  ┆ Chi tiết │
│ 0014      ┆ 00        ┆           ┆ đi        ┆   ┆ định      ┆           ┆ đi        ┆ sản      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ phẩmTên  │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ sản      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ phẩm:…   │
│ 402700000 ┆ 139000.00 ┆ Phụ kiện  ┆ Nón       ┆ … ┆ Không xác ┆ 0-12M     ┆ Nón       ┆ Chi tiết │
│ 0049      ┆ 00        ┆           ┆           ┆   ┆ định      ┆           ┆           ┆ sản phẩm │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ …        │
│ 095200000 ┆ 165000.00 ┆ Phụ kiện  ┆ Giày tập  ┆ … ┆ Không xác ┆ Không xác ┆ Không xác ┆ null     │
│ 0078      ┆ 00        ┆           ┆ đi        ┆   ┆ định      ┆ định      ┆ định      ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

### Xử lý age_group

In [45]:
# Lọc các sản phẩm Thời trang nhưng age_group = "Không xác định"
df_fashion_age_unknown = (
    df_no_outlier
    .filter(
        (pl.col("category_l1") == "Thời trang") &
        (pl.col("age_group") == "Không xác định")
    )
)

# Kiểm tra số lượng
total = df_fashion_age_unknown.height
print("Tổng số sản phẩm Thời trang có age_group = 'Không xác định':", total)

# -----------------------------
# Thống kê description & description_new
# -----------------------------

count_desc_unknown = df_fashion_age_unknown.filter(pl.col("description") == "Không xác định").height
count_desc_new_unknown = df_fashion_age_unknown.filter(pl.col("description_new") == "Không xác định").height

print("\nThống kê tình trạng mô tả trong nhóm này:")
print(f"- description = 'Không xác định': {count_desc_unknown} / {total} ({count_desc_unknown/total*100:.2f}%)")
print(f"- description_new = 'Không xác định': {count_desc_new_unknown} / {total} ({count_desc_new_unknown/total*100:.2f}%)")

# -----------------------------
# Lấy ngẫu nhiên 20 dòng để quan sát
# -----------------------------
df_sample_age = df_fashion_age_unknown.sample(n=20, seed=42)

pd.set_option('display.max_columns', None)
df_sample_age.head(20)

Tổng số sản phẩm Thời trang có age_group = 'Không xác định': 6058

Thống kê tình trạng mô tả trong nhóm này:
- description = 'Không xác định': 5435 / 6058 (89.72%)
- description_new = 'Không xác định': 2593 / 6058 (42.80%)

shape: (20, 12)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ item_id   ┆ price     ┆ category_ ┆ category_ ┆ … ┆ gender_ta ┆ age_group ┆ item_type ┆ descript │
│ ---       ┆ ---       ┆ l1        ┆ l2        ┆   ┆ rget      ┆ ---       ┆ ---       ┆ ion_new  │
│ str       ┆ decimal[3 ┆ ---       ┆ ---       ┆   ┆ ---       ┆ str       ┆ str       ┆ ---      │
│           ┆ 8,4]      ┆ str       ┆ str       ┆   ┆ str       ┆           ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 352300000 ┆ 99000.000 ┆ Thời      ┆ Quần áo & ┆ … ┆ Không xác ┆ Không xác ┆ Không xác ┆ null     │
│ 0021      ┆ 0         ┆ trang     ┆ Phụ kiện  ┆   ┆ định      ┆ định      ┆ định      ┆          │
│           ┆           ┆           ┆ sơ sinh   ┆   ┆           ┆           ┆           ┆          │
│ 332001683 ┆ 69000.000 ┆ Thời      ┆ Cơ cấu    ┆ … ┆ Không xác ┆ Không xác ┆ Không xác ┆ null     │
│ 0007      ┆ 0         ┆ trang     ┆ hàng cũ   ┆   ┆ định      ┆ định      ┆ định      ┆          │
│ 093000236 ┆ 19000.000 ┆ Thời      ┆ Cơ cấu    ┆ … ┆ Sơ sinh   ┆ Không xác ┆ Tã vải    ┆ Không    │
│ 0001      ┆ 0         ┆ trang     ┆ hàng cũ   ┆   ┆           ┆ định      ┆           ┆ xác định │
│ 353300000 ┆ 119000.00 ┆ Thời      ┆ Quần áo & ┆ … ┆ Không xác ┆ Không xác ┆ Không xác ┆ null     │
│ 0241      ┆ 00        ┆ trang     ┆ Phụ kiện  ┆   ┆ định      ┆ định      ┆ định      ┆          │
│           ┆           ┆           ┆ sơ sinh   ┆   ┆           ┆           ┆           ┆          │
│ 603400000 ┆ 129000.00 ┆ Thời      ┆ Thời      ┆ … ┆ Không xác ┆ Không xác ┆ Không xác ┆ Không    │
│ 0360      ┆ 00        ┆ trang     ┆ trang bé  ┆   ┆ định      ┆ định      ┆ định      ┆ xác định │
│           ┆           ┆           ┆ gái       ┆   ┆           ┆           ┆           ┆          │
│ 395100000 ┆ 139000.00 ┆ Thời      ┆ Thời      ┆ … ┆ Không xác ┆ Không xác ┆ Không xác ┆ Không    │
│ 0444      ┆ 00        ┆ trang     ┆ trang bé  ┆   ┆ định      ┆ định      ┆ định      ┆ xác định │
│           ┆           ┆           ┆ trai      ┆   ┆           ┆           ┆           ┆          │
│ 089110405 ┆ 49000.000 ┆ Thời      ┆ Cơ cấu    ┆ … ┆ Bé Gái    ┆ Không xác ┆ Quần      ┆ Không    │
│ 0001      ┆ 0         ┆ trang     ┆ hàng cũ   ┆   ┆           ┆ định      ┆           ┆ xác định │
│ 699800000 ┆ 379000.00 ┆ Thời      ┆ Modal     ┆ … ┆ Không xác ┆ Không xác ┆ Không xác ┆ Không    │
│ 0086      ┆ 00        ┆ trang     ┆ kháng     ┆   ┆ định      ┆ định      ┆ định      ┆ xác định │
│           ┆           ┆           ┆ khuẩn     ┆   ┆           ┆           ┆           ┆          │
│ 341401683 ┆ 89000.000 ┆ Thời      ┆ Cơ cấu    ┆ … ┆ Không xác ┆ Không xác ┆ Không xác ┆ null     │
│ 0002      ┆ 0         ┆ trang     ┆ hàng cũ   ┆   ┆ định      ┆ định      ┆ định      ┆          │
│ 394900000 ┆ 215000.00 ┆ Thời      ┆ Thời      ┆ … ┆ Không xác ┆ Không xác ┆ Không xác ┆ null     │
│ 0018      ┆ 00        ┆ trang     ┆ trang bé  ┆   ┆ định      ┆ định      ┆ định      ┆          │
│           ┆           ┆           ┆ gái       ┆   ┆           ┆           ┆           ┆          │
│ 098328513 ┆ 140000.00 ┆ Thời      ┆ Cơ cấu    ┆ … ┆ Không xác ┆ Không xác ┆ Không xác ┆ null     │
│ 0001      ┆ 00        ┆ trang     ┆ hàng cũ   ┆   ┆ định      ┆ định      ┆ định      ┆          │
│ 603300000 ┆ 219000.00 ┆ Thời      ┆ Thời      ┆ … ┆ Không xác ┆ Không xác ┆ Không xác ┆ Không    │
│ 0114      ┆ 00        ┆ trang     ┆ trang bé  ┆   ┆ định      ┆ định      ┆ định      ┆ xác định │
│           ┆           ┆           ┆ gái       ┆   ┆           ┆           ┆           ┆          │
│ 098710451 ┆ 159000.00 ┆ Thời      ┆ Cơ cấu    ┆ … ┆ Sơ sinh   ┆ Không xác ┆ Bộ quần   ┆ Không    │
│ 0005      ┆ 00        ┆ trang     ┆ hàng cũ   ┆   ┆           ┆ định      ┆ áo        ┆ xác định │
│ 081210448 ┆ 49000.000 ┆ Thời      ┆ Cơ cấu    ┆ … ┆ Không xác ┆ Không xác ┆ Không xác ┆ null     │
│ 0003      ┆ 0         ┆ trang     ┆ hàng cũ   ┆   ┆ định      ┆ định      ┆ định      ┆          │
│ 699700000 ┆ 349000.00 ┆ Thời      ┆ Modal     ┆ … ┆ Không xác ┆ Không xác ┆ Không xác ┆ Không    │
│ 0154      ┆ 00        ┆ trang     ┆ kháng     ┆   ┆ định      ┆ định      ┆ định      ┆ xác định │
│           ┆           ┆           ┆ khuẩn     ┆   ┆           ┆           ┆           ┆          │
│ 395300000 ┆ 129000.00 ┆ Thời      ┆ Thời      ┆ … ┆ Không xác ┆ Không xác ┆ Không xác ┆ Không    │
│ 0765      ┆ 00        ┆ trang     ┆ trang bé  ┆   ┆ định      ┆ định      ┆ định      ┆ xác định │
│           ┆           ┆           ┆ trai      ┆   ┆           ┆           ┆           ┆          │
│ 082300448 ┆ 69000.000 ┆ Thời      ┆ Cơ cấu    ┆ … ┆ Không xác ┆ Không xác ┆ Không xác ┆ null     │
│ 0006      ┆ 0         ┆ trang     ┆ hàng cũ   ┆   ┆ định      ┆ định      ┆ định      ┆          │
│ 001120016 ┆ 59000.000 ┆ Thời      ┆ Cơ cấu    ┆ … ┆ Không xác ┆ Không xác ┆ Không xác ┆ Không    │
│ 0074      ┆ 0         ┆ trang     ┆ hàng cũ   ┆   ┆ định      ┆ định      ┆ định      ┆ xác định │
│ 699800000 ┆ 379000.00 ┆ Thời      ┆ Modal     ┆ … ┆ Không xác ┆ Không xác ┆ Không xác ┆ Không    │
│ 0058      ┆ 00        ┆ trang     ┆ kháng     ┆   ┆ định      ┆ định      ┆ định      ┆ xác định │
│           ┆           ┆           ┆ khuẩn     ┆   ┆           ┆           ┆           ┆          │
│ 353200000 ┆ 99000.000 ┆ Thời      ┆ Quần áo & ┆ … ┆ Không xác ┆ Không xác ┆ Không xác ┆ null     │
│ 0076      ┆ 0         ┆ trang     ┆ Phụ kiện  ┆   ┆ định      ┆ định      ┆ định      ┆          │
│           ┆           ┆           ┆ sơ sinh   ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

# Task 3: Phân tích tương đồng và xác định xem các thuộc tính tương tự nhau. Từ đó loại bỏ đặc trưng thừa.

# Task 4: Chuẩn hóa dữ liệu (nếu có), biến đổi dữ liệu

# Task 5: Nhóm hãy suy nghĩ xem, với bài toán dự đoán mua hàng, ta có thể tạo mới những đặc trưng nào. Sau đó tiến hành rút trích thêm các đặc trưng. Task này rất quan trọng vì ảnh hưởng hiệu quả của hệ thống.