In [119]:
import polars as pl
import pandas as pd
import numpy as np
import os

DATA_PATH = r".././dataset/sales_pers.item_chunk_0.parquet"

df = pl.read_parquet(DATA_PATH)
print(f"Số dòng: {df.height:,}, Số cột: {df.width}")

Số dòng: 27,332, Số cột: 34

In [120]:
print("\nCác cột ban đầu:")
print(df.columns)

Các cột ban đầu:
['p_id', 'item_id', 'price', 'category_l1_id', 'category_l1', 'category_l2_id', 'category_l2', 'category_l3_id', 'category_l3', 'category_id', 'category', 'description', 'brand', 'manufacturer', 'creation_timestamp', 'is_deleted', 'created_date', 'updated_date', 'sync_status_id', 'last_sync_date', 'sync_error_message', 'image_url', 'gender_target', 'age_group', 'item_type', 'gp', 'weight', 'color', 'size', 'origin', 'volume', 'material', 'sale_status', 'description_new']

# Task 1: Loại bỏ các cột mà nhóm nghĩ là không cần thiết.

In [121]:
# --- Danh sách cột cần loại bỏ (theo phân tích EDA & tương quan) ---
cols_to_drop = [
    # --- Metadata hệ thống (không dùng cho mô hình) ---
    "p_id",
    "is_deleted",
    "sync_status_id",
    "sync_error_message",
    "image_url",
    "last_sync_date",
    "creation_timestamp",
    "updated_date",
    "created_date",
    "sale_status",

    # --- Cột numeric hầu như vô nghĩa / chỉ có 1 giá trị ---
    "gp",
    "weight",
    "volume",

    # --- Các cột chất lượng kém / missing cực cao / không dùng ---
    "color",
    "size",
    "material",
    "origin",
    "manufacturer",

    # --- ID phân loại (trùng với tên category) ---
    "category_l1_id",
    "category_l2_id",
    "category_l3_id",
    "category_id"
]



# --- Loại bỏ các cột không cần thiết ---
df_cleaned = df.drop(cols_to_drop)

print(f"\nĐã loại bỏ {len(cols_to_drop)} cột không cần thiết.")
print(f"Số cột còn lại: {df_cleaned.width}")
print("\nDanh sách cột sau khi loại bỏ:")
print(df_cleaned.columns)

Đã loại bỏ 22 cột không cần thiết.
Số cột còn lại: 12

Danh sách cột sau khi loại bỏ:
['item_id', 'price', 'category_l1', 'category_l2', 'category_l3', 'category', 'description', 'brand', 'gender_target', 'age_group', 'item_type', 'description_new']

# Task 2: Xử lý NULL, Xử lý Outlier

## Xử lý outlier

In [122]:
# df_cleaned: dataframe sau khi đã drop các cột không cần thiết
print("Số lượng ban đầu:", df_cleaned.height)

# --- LOẠI SẢN PHẨM CÓ PRICE ≤ 1 (Outlier) ---
df_no_outlier = df_cleaned.filter(pl.col("price") > 1)

print("Số lượng sau khi loại outlier (price ≤ 1):", df_no_outlier.height)
print("Số lượng bị loại:", df_cleaned.height - df_no_outlier.height)

# Kiểm tra lại xem còn outlier hay không
print("\nKiểm tra min price sau khi xử lý:")
print(df_no_outlier.select(pl.col("price").min()))

Số lượng ban đầu: 27332
Số lượng sau khi loại outlier (price ≤ 1): 27323
Số lượng bị loại: 9

Kiểm tra min price sau khi xử lý:
shape: (1, 1)
┌───────────────┐
│ price         │
│ ---           │
│ decimal[38,4] │
╞═══════════════╡
│ 1000.0000     │
└───────────────┘

In [123]:
# Chuẩn hóa giá trị Unisex → Không xác định
df_no_outlier = df_no_outlier.with_columns(
    pl.col("gender_target").replace("Unisex", "Không xác định")
)

print("Đã chuyển toàn bộ Unisex thành 'Không xác định'.")
print(df_no_outlier["gender_target"].value_counts())

Đã chuyển toàn bộ Unisex thành 'Không xác định'.
shape: (4, 2)
┌────────────────┬───────┐
│ gender_target  ┆ count │
│ ---            ┆ ---   │
│ str            ┆ u32   │
╞════════════════╪═══════╡
│ Bé Trai        ┆ 3318  │
│ Bé Gái         ┆ 4108  │
│ Sơ sinh        ┆ 1862  │
│ Không xác định ┆ 18035 │
└────────────────┴───────┘

In [124]:
df_no_outlier.head(5)

shape: (5, 12)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ item_id   ┆ price     ┆ category_ ┆ category_ ┆ … ┆ gender_ta ┆ age_group ┆ item_type ┆ descript │
│ ---       ┆ ---       ┆ l1        ┆ l2        ┆   ┆ rget      ┆ ---       ┆ ---       ┆ ion_new  │
│ str       ┆ decimal[3 ┆ ---       ┆ ---       ┆   ┆ ---       ┆ str       ┆ str       ┆ ---      │
│           ┆ 8,4]      ┆ str       ┆ str       ┆   ┆ str       ┆           ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 050202000 ┆ 99000.000 ┆ Babycare  ┆ Bình sữa, ┆ … ┆ Không xác ┆ Không xác ┆ Không xác ┆ Chi tiết │
│ 0004      ┆ 0         ┆           ┆ phụ kiện  ┆   ┆ định      ┆ định      ┆ định      ┆ sản phẩm │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ Tên sản  │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ phẩm…    │
│ 001029004 ┆ 69000.000 ┆ Thời      ┆ Cơ cấu    ┆ … ┆ Bé Gái    ┆ Từ 3Y     ┆ Bộ quần   ┆ Không    │
│ 0150      ┆ 0         ┆ trang     ┆ hàng cũ   ┆   ┆           ┆           ┆ áo        ┆ xác định │
│ 000801000 ┆ 45000.000 ┆ Đồ chơi & ┆ 0-1Y      ┆ … ┆ Không xác ┆ Không xác ┆ Không xác ┆ Chi tiết │
│ 0015      ┆ 0         ┆ Sách      ┆           ┆   ┆ định      ┆ định      ┆ định      ┆ sản phẩm │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ Tên sản  │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ phẩm…    │
│ 002001000 ┆ 401000.00 ┆ Tã        ┆ Merries   ┆ … ┆ Không xác ┆ Không xác ┆ Không xác ┆ Không    │
│ 0094      ┆ 00        ┆           ┆           ┆   ┆ định      ┆ định      ┆ định      ┆ xác định │
│ 002001000 ┆ 401000.00 ┆ Tã        ┆ Merries   ┆ … ┆ Không xác ┆ Không xác ┆ Không xác ┆ Không    │
│ 0098      ┆ 00        ┆           ┆           ┆   ┆ định      ┆ định      ┆ định      ┆ xác định │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

## Xử lý null

In [125]:
pl.Config.set_tbl_rows(50)             # số dòng tối đa hiển thị


# df_final = df_no_outlier
df_final = df_no_outlier

n = df_final.height

results = []

for col in df_final.columns:
    s = df_final[col]

    # NULL
    null_count = s.null_count()

    # UNKNOWN ("Không xác định")
    if s.dtype == pl.String:
        # Đếm trực tiếp bằng Python list, không lỗi
        unknown_count = s.to_list().count("Không xác định")
    else:
        unknown_count = 0

    results.append({
        "column": col,
        "dtype": s.dtype,
        "null_count": null_count,
        "null_ratio(%)": round(null_count / n * 100, 2),
        "unknown_count": unknown_count,
        "unknown_ratio(%)": round(unknown_count / n * 100, 2)
    })

df_missing_report = pl.DataFrame(results)

print(df_missing_report)

shape: (12, 6)
┌─────────────────┬─────────────────┬────────────┬───────────────┬───────────────┬─────────────────┐
│ column          ┆ dtype           ┆ null_count ┆ null_ratio(%) ┆ unknown_count ┆ unknown_ratio(% │
│ ---             ┆ ---             ┆ ---        ┆ ---           ┆ ---           ┆ )               │
│ str             ┆ object          ┆ i64        ┆ f64           ┆ i64           ┆ ---             │
│                 ┆                 ┆            ┆               ┆               ┆ f64             │
╞═════════════════╪═════════════════╪════════════╪═══════════════╪═══════════════╪═════════════════╡
│ item_id         ┆ String          ┆ 0          ┆ 0.0           ┆ 0             ┆ 0.0             │
│ price           ┆ Decimal(precisi ┆ 0          ┆ 0.0           ┆ 0             ┆ 0.0             │
│                 ┆ on=38, scale=4) ┆            ┆               ┆               ┆                 │
│ category_l1     ┆ String          ┆ 0          ┆ 0.0           ┆ 0             ┆ 0.0             │
│ category_l2     ┆ String          ┆ 0          ┆ 0.0           ┆ 0             ┆ 0.0             │
│ category_l3     ┆ String          ┆ 0          ┆ 0.0           ┆ 0             ┆ 0.0             │
│ category        ┆ String          ┆ 0          ┆ 0.0           ┆ 0             ┆ 0.0             │
│ description     ┆ String          ┆ 0          ┆ 0.0           ┆ 18621         ┆ 68.15           │
│ brand           ┆ String          ┆ 0          ┆ 0.0           ┆ 5472          ┆ 20.03           │
│ gender_target   ┆ String          ┆ 0          ┆ 0.0           ┆ 18035         ┆ 66.01           │
│ age_group       ┆ String          ┆ 0          ┆ 0.0           ┆ 15803         ┆ 57.84           │
│ item_type       ┆ String          ┆ 0          ┆ 0.0           ┆ 9812          ┆ 35.91           │
│ description_new ┆ String          ┆ 5006       ┆ 18.32         ┆ 12815         ┆ 46.9            │
└─────────────────┴─────────────────┴────────────┴───────────────┴───────────────┴─────────────────┘

### Xử lý gender_target

In [126]:

# Lọc các item thời trang nhưng gender_target = "Không xác định"
df_fashion_unknown = (
    df_no_outlier
        .filter(
            (pl.col("category_l1") == "Thời trang") &
            (pl.col("gender_target") == "Không xác định")
        )
)

print("Tổng số item thời trang có gender_target = 'Không xác định':", df_fashion_unknown.height)

# Lấy 20 dòng ngẫu nhiên
df_sample = df_fashion_unknown.sample(n=20, with_replacement=False)

pd.set_option('display.max_columns', None)
df_sample.head(10)

Tổng số item thời trang có gender_target = 'Không xác định': 7264

shape: (10, 12)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ item_id   ┆ price     ┆ category_ ┆ category_ ┆ … ┆ gender_ta ┆ age_group ┆ item_type ┆ descript │
│ ---       ┆ ---       ┆ l1        ┆ l2        ┆   ┆ rget      ┆ ---       ┆ ---       ┆ ion_new  │
│ str       ┆ decimal[3 ┆ ---       ┆ ---       ┆   ┆ ---       ┆ str       ┆ str       ┆ ---      │
│           ┆ 8,4]      ┆ str       ┆ str       ┆   ┆ str       ┆           ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 353200000 ┆ 140000.00 ┆ Thời      ┆ Cơ cấu    ┆ … ┆ Không xác ┆ Từ 6M     ┆ Quần      ┆ Không    │
│ 0003      ┆ 00        ┆ trang     ┆ hàng cũ   ┆   ┆ định      ┆           ┆           ┆ xác định │
│ 339000000 ┆ 199000.00 ┆ Thời      ┆ Modal     ┆ … ┆ Không xác ┆ 9M-12M    ┆ Bodysuit  ┆ Không    │
│ 0107      ┆ 00        ┆ trang     ┆ kháng     ┆   ┆ định      ┆           ┆           ┆ xác định │
│           ┆           ┆           ┆ khuẩn     ┆   ┆           ┆           ┆           ┆          │
│ 086300476 ┆ 49000.000 ┆ Thời      ┆ Cơ cấu    ┆ … ┆ Không xác ┆ Không xác ┆ Không xác ┆ null     │
│ 0007      ┆ 0         ┆ trang     ┆ hàng cũ   ┆   ┆ định      ┆ định      ┆ định      ┆          │
│ 353200000 ┆ 119000.00 ┆ Thời      ┆ Quần áo & ┆ … ┆ Không xác ┆ Không xác ┆ Không xác ┆ null     │
│ 0273      ┆ 00        ┆ trang     ┆ Phụ kiện  ┆   ┆ định      ┆ định      ┆ định      ┆          │
│           ┆           ┆           ┆ sơ sinh   ┆   ┆           ┆           ┆           ┆          │
│ 604800000 ┆ 249000.00 ┆ Thời      ┆ Thời      ┆ … ┆ Không xác ┆ 6M-9M     ┆ Bodysuit  ┆ Không    │
│ 0012      ┆ 00        ┆ trang     ┆ trang     ┆   ┆ định      ┆           ┆           ┆ xác định │
│           ┆           ┆           ┆ đông      ┆   ┆           ┆           ┆           ┆          │
│ 353200317 ┆ 49000.000 ┆ Thời      ┆ Cơ cấu    ┆ … ┆ Không xác ┆ Không xác ┆ Không xác ┆ null     │
│ 0001      ┆ 0         ┆ trang     ┆ hàng cũ   ┆   ┆ định      ┆ định      ┆ định      ┆          │
│ 395300000 ┆ 129000.00 ┆ Thời      ┆ Thời      ┆ … ┆ Không xác ┆ Không xác ┆ Không xác ┆ Không    │
│ 0721      ┆ 00        ┆ trang     ┆ trang bé  ┆   ┆ định      ┆ định      ┆ định      ┆ xác định │
│           ┆           ┆           ┆ trai      ┆   ┆           ┆           ┆           ┆          │
│ 348110436 ┆ 19000.000 ┆ Thời      ┆ Cơ cấu    ┆ … ┆ Không xác ┆ Không xác ┆ Không xác ┆ null     │
│ 0001      ┆ 0         ┆ trang     ┆ hàng cũ   ┆   ┆ định      ┆ định      ┆ định      ┆          │
│ 352209518 ┆ 49000.000 ┆ Thời      ┆ Cơ cấu    ┆ … ┆ Không xác ┆ Không xác ┆ Không xác ┆ null     │
│ 0001      ┆ 0         ┆ trang     ┆ hàng cũ   ┆   ┆ định      ┆ định      ┆ định      ┆          │
│ 352924113 ┆ 49000.000 ┆ Thời      ┆ Cơ cấu    ┆ … ┆ Không xác ┆ Không xác ┆ Không xác ┆ null     │
│ 0001      ┆ 0         ┆ trang     ┆ hàng cũ   ┆   ┆ định      ┆ định      ┆ định      ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [127]:
# Lọc sản phẩm thời trang có category chứa "đầm" hoặc "váy" và gender_target = "Không xác định"
df_dam_vay_unknown = (
    df_no_outlier
    .filter(
        (pl.col("category_l1") == "Thời trang")
        &
        (pl.col("gender_target") == "Không xác định")
        &
        (
            pl.col("category").str.contains("đầm", literal=False)
            | pl.col("category").str.contains("váy", literal=False)
        )
    )
)

# In thống kê số dòng
print("Tổng sản phẩm thỏa điều kiện:", df_dam_vay_unknown.height)

# Lấy mẫu 20 dòng
df_sample = df_dam_vay_unknown.sample(n=20, seed=42)

# Hiển thị đầy đủ cột
pd.set_option('display.max_columns', None)
df_sample.head(10)

Tổng sản phẩm thỏa điều kiện: 192

shape: (10, 12)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ item_id   ┆ price     ┆ category_ ┆ category_ ┆ … ┆ gender_ta ┆ age_group ┆ item_type ┆ descript │
│ ---       ┆ ---       ┆ l1        ┆ l2        ┆   ┆ rget      ┆ ---       ┆ ---       ┆ ion_new  │
│ str       ┆ decimal[3 ┆ ---       ┆ ---       ┆   ┆ ---       ┆ str       ┆ str       ┆ ---      │
│           ┆ 8,4]      ┆ str       ┆ str       ┆   ┆ str       ┆           ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 604500000 ┆ 349000.00 ┆ Thời      ┆ Cơ cấu    ┆ … ┆ Không xác ┆ Không xác ┆ Không xác ┆ null     │
│ 0002      ┆ 00        ┆ trang     ┆ hàng cũ   ┆   ┆ định      ┆ định      ┆ định      ┆          │
│ 109209385 ┆ 189000.00 ┆ Thời      ┆ Cơ cấu    ┆ … ┆ Không xác ┆ Mẹ        ┆ Áo bầu    ┆ Không    │
│ 0001      ┆ 00        ┆ trang     ┆ hàng cũ   ┆   ┆ định      ┆           ┆           ┆ xác định │
│ 108302285 ┆ 149000.00 ┆ Thời      ┆ Cơ cấu    ┆ … ┆ Không xác ┆ Mẹ        ┆ Quần bầu  ┆ Không    │
│ 0002      ┆ 00        ┆ trang     ┆ hàng cũ   ┆   ┆ định      ┆           ┆           ┆ xác định │
│ 088602677 ┆ 49000.000 ┆ Thời      ┆ Cơ cấu    ┆ … ┆ Không xác ┆ Không xác ┆ Không xác ┆ null     │
│ 0002      ┆ 0         ┆ trang     ┆ hàng cũ   ┆   ┆ định      ┆ định      ┆ định      ┆          │
│ 088702677 ┆ 49000.000 ┆ Thời      ┆ Cơ cấu    ┆ … ┆ Không xác ┆ Không xác ┆ Không xác ┆ null     │
│ 0004      ┆ 0         ┆ trang     ┆ hàng cũ   ┆   ┆ định      ┆ định      ┆ định      ┆          │
│ 089101979 ┆ 49000.000 ┆ Thời      ┆ Cơ cấu    ┆ … ┆ Không xác ┆ Không xác ┆ Không xác ┆ null     │
│ 0002      ┆ 0         ┆ trang     ┆ hàng cũ   ┆   ┆ định      ┆ định      ┆ định      ┆          │
│ 001219016 ┆ 49000.000 ┆ Thời      ┆ Cơ cấu    ┆ … ┆ Không xác ┆ Không xác ┆ Không xác ┆ Không    │
│ 0065      ┆ 0         ┆ trang     ┆ hàng cũ   ┆   ┆ định      ┆ định      ┆ định      ┆ xác định │
│ 108003386 ┆ 199000.00 ┆ Thời      ┆ Cơ cấu    ┆ … ┆ Không xác ┆ Không xác ┆ Không xác ┆ null     │
│ 0001      ┆ 00        ┆ trang     ┆ hàng cũ   ┆   ┆ định      ┆ định      ┆ định      ┆          │
│ 108000486 ┆ 189000.00 ┆ Thời      ┆ Cơ cấu    ┆ … ┆ Không xác ┆ Mẹ        ┆ Áo bầu    ┆ Không    │
│ 0001      ┆ 00        ┆ trang     ┆ hàng cũ   ┆   ┆ định      ┆           ┆           ┆ xác định │
│ 108100488 ┆ 199000.00 ┆ Thời      ┆ Cơ cấu    ┆ … ┆ Không xác ┆ Mẹ        ┆ Đầm bầu   ┆ Không    │
│ 0001      ┆ 00        ┆ trang     ┆ hàng cũ   ┆   ┆ định      ┆           ┆           ┆ xác định │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [128]:
# ============================================
#  TẠO CỘT gender_target_final
# ============================================

df_filled = df_no_outlier.with_columns(
    pl.col("gender_target").alias("gender_target_final")
)

# ============================================
#  1) FILL “SƠ SINH”
# ============================================

mask_sosinh = (
    (pl.col("category_l1") == "Thời trang")
    & (pl.col("gender_target_final") == "Không xác định")
    & (
        pl.col("category_l2").str.contains("sơ sinh", literal=False)
        | pl.col("category").str.contains("sơ sinh", literal=False)
        | pl.col("category").str.contains("0-3m", literal=False)
        | pl.col("category").str.contains("3-6m", literal=False)
        | pl.col("category").str.contains("0-12m", literal=False)
        | pl.col("category").str.contains(r"\bnb\b", literal=False)   # NB
        | pl.col("category").str.contains("newborn", literal=False)
    )
)

df_filled = df_filled.with_columns(
    pl.when(mask_sosinh)
      .then(pl.lit("Sơ sinh"))
      .otherwise(pl.col("gender_target_final"))
      .alias("gender_target_final")
)

# ============================================
#  2) FILL “BÉ GÁI”
# ============================================

mask_fashion_unknown = (
    (pl.col("category_l1") == "Thời trang")
    & (pl.col("gender_target_final") == "Không xác định")
)

mask_not_maternity = (
    (~pl.col("category").str.contains("bầu", literal=False))
    & (~pl.col("category_l2").str.contains("bầu", literal=False))
    & (~pl.col("category_l3").str.contains("bầu", literal=False))
)

mask_not_ambiguous = (
    ~pl.col("category_l3").str.contains("Thời trang bé trai, bé gái cũ", literal=False)
)

mask_girl_keyword = (
    pl.col("category").str.contains("bé gái|đầm|váy|chân váy", literal=False)
    | pl.col("category_l2").str.contains("bé gái|đầm bé gái|bộ bé gái", literal=False)
    | pl.col("category_l3").str.contains("bé gái|đầm|váy", literal=False)
)

mask_fill_girl = (
    mask_fashion_unknown
    & mask_not_maternity
    & mask_not_ambiguous
    & mask_girl_keyword
)

df_filled = df_filled.with_columns(
    pl.when(mask_fill_girl)
      .then(pl.lit("Bé Gái"))
      .otherwise(pl.col("gender_target_final"))
      .alias("gender_target_final")
)

# ============================================
#  3) FILL “BÉ TRAI”
# ============================================

mask_boy_keyword = (
    pl.col("category").str.contains("bé trai", literal=False)
    | pl.col("category_l2").str.contains("bé trai|bộ bé trai", literal=False)
    | pl.col("category_l3").str.contains("bé trai", literal=False)
)

mask_fill_boy = (
    mask_fashion_unknown
    & mask_not_ambiguous
    & mask_boy_keyword
)

df_filled = df_filled.with_columns(
    pl.when(mask_fill_boy)
      .then(pl.lit("Bé Trai"))
      .otherwise(pl.col("gender_target_final"))
.alias("gender_target_final")
)

# ============================================
# 4) KIỂM TRA KẾT QUẢ FILL
# ============================================

print("\nTổng số dòng được fill:",
      df_filled.filter(pl.col("gender_target") != pl.col("gender_target_final")).height
)


total_rows = df_filled.height

unknown_original = df_filled.filter(
    pl.col("gender_target") == "Không xác định"
).height

unknown_final = df_filled.filter(
    pl.col("gender_target_final") == "Không xác định"
).height

ratio_unknown_final = unknown_final / total_rows * 100

print("\n=== THỐNG KÊ 'Không xác định' ===")
print(f"1) gender_target ban đầu = 'Không xác định': {unknown_original:,}")
print(f"2) gender_target_final    = 'Không xác định': {unknown_final:,}")
print(f"3) Tỷ lệ 'Không xác định' sau fill: {ratio_unknown_final:.2f}% (trên {total_rows:,} dòng)")

# Xuất ra 5 dòng mẫu sau khi fill
print("\n=== 5 dòng mẫu đã được fill ===")
print(
    df_filled
    .filter(
        (pl.col("gender_target") == "Không xác định")
        & (pl.col("gender_target_final") != "Không xác định")
    )
    .head(5)
)

Tổng số dòng được fill: 3333

=== THỐNG KÊ 'Không xác định' ===
1) gender_target ban đầu = 'Không xác định': 18,035
2) gender_target_final    = 'Không xác định': 14,702
3) Tỷ lệ 'Không xác định' sau fill: 53.81% (trên 27,323 dòng)

=== 5 dòng mẫu đã được fill ===
shape: (5, 13)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ item_id   ┆ price     ┆ category_ ┆ category_ ┆ … ┆ age_group ┆ item_type ┆ descripti ┆ gender_t │
│ ---       ┆ ---       ┆ l1        ┆ l2        ┆   ┆ ---       ┆ ---       ┆ on_new    ┆ arget_fi │
│ str       ┆ decimal[3 ┆ ---       ┆ ---       ┆   ┆ str       ┆ str       ┆ ---       ┆ nal      │
│           ┆ 8,4]      ┆ str       ┆ str       ┆   ┆           ┆           ┆ str       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 603400000 ┆ 149000.00 ┆ Thời      ┆ Thời      ┆ … ┆ Không xác ┆ Không xác ┆ Không xác ┆ Bé Trai  │
│ 0117      ┆ 00        ┆ trang     ┆ trang bé  ┆   ┆ định      ┆ định      ┆ định      ┆          │
│           ┆           ┆           ┆ trai      ┆   ┆           ┆           ┆           ┆          │
│ 353300000 ┆ 119000.00 ┆ Thời      ┆ Quần áo & ┆ … ┆ Không xác ┆ Không xác ┆ null      ┆ Sơ sinh  │
│ 0262      ┆ 00        ┆ trang     ┆ Phụ kiện  ┆   ┆ định      ┆ định      ┆           ┆          │
│           ┆           ┆           ┆ sơ sinh   ┆   ┆           ┆           ┆           ┆          │
│ 395100000 ┆ 239000.00 ┆ Thời      ┆ Thời      ┆ … ┆ Không xác ┆ Không xác ┆ Không xác ┆ Bé Trai  │
│ 0365      ┆ 00        ┆ trang     ┆ trang bé  ┆   ┆ định      ┆ định      ┆ định      ┆          │
│           ┆           ┆           ┆ trai      ┆   ┆           ┆           ┆           ┆          │
│ 353210417 ┆ 49000.000 ┆ Thời      ┆ Cơ cấu    ┆ … ┆ Không xác ┆ Không xác ┆ null      ┆ Sơ sinh  │
│ 0002      ┆ 0         ┆ trang     ┆ hàng cũ   ┆   ┆ định      ┆ định      ┆           ┆          │
│ 098000466 ┆ 49000.000 ┆ Thời      ┆ Cơ cấu    ┆ … ┆ Không xác ┆ Áo        ┆ Không xác ┆ Sơ sinh  │
│ 0001      ┆ 0         ┆ trang     ┆ hàng cũ   ┆   ┆ định      ┆           ┆ định      ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [129]:

# Lọc các sản phẩm thuộc Phụ kiện và gender_target = "Không xác định"
df_phukien_unknown = (
    df_no_outlier
    .filter(
        (pl.col("category_l1") == "Phụ kiện") &
        (pl.col("gender_target") == "Không xác định")
    )
)

# Kiểm tra số lượng
print("Tổng số sản phẩm Phụ kiện có gender_target = 'Không xác định':",
      df_phukien_unknown.height)

# Lấy ngẫu nhiên 10 dòng
df_sample = df_phukien_unknown.sample(n=10, seed=42)

# In ra toàn bộ cột để bạn xem xét thật chi tiết
pd.set_option('display.max_columns', None)
df_sample.head(10)

Tổng số sản phẩm Phụ kiện có gender_target = 'Không xác định': 1666

shape: (10, 12)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ item_id   ┆ price     ┆ category_ ┆ category_ ┆ … ┆ gender_ta ┆ age_group ┆ item_type ┆ descript │
│ ---       ┆ ---       ┆ l1        ┆ l2        ┆   ┆ rget      ┆ ---       ┆ ---       ┆ ion_new  │
│ str       ┆ decimal[3 ┆ ---       ┆ ---       ┆   ┆ ---       ┆ str       ┆ str       ┆ ---      │
│           ┆ 8,4]      ┆ str       ┆ str       ┆   ┆ str       ┆           ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 605300000 ┆ 49000.000 ┆ Phụ kiện  ┆ Cơ cấu    ┆ … ┆ Không xác ┆ 1Y-3Y     ┆ Giày      ┆ Chi tiết │
│ 0007      ┆ 0         ┆           ┆ hàng cũ   ┆   ┆ định      ┆           ┆           ┆ sản phẩm │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ Tên sản  │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ phẩm…    │
│ 605500000 ┆ 49000.000 ┆ Phụ kiện  ┆ Cơ cấu    ┆ … ┆ Không xác ┆ Không xác ┆ Giày      ┆ Chi tiết │
│ 0002      ┆ 0         ┆           ┆ hàng cũ   ┆   ┆ định      ┆ định      ┆           ┆ sản phẩm │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ Tên sản  │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ phẩm…    │
│ 480400000 ┆ 249000.00 ┆ Phụ kiện  ┆ Phụ kiện  ┆ … ┆ Không xác ┆ Từ 2Y     ┆ Balo      ┆ Chi tiết │
│ 0016      ┆ 00        ┆           ┆ khác      ┆   ┆ định      ┆           ┆           ┆ sản phẩm │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ Tên sản  │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ phẩm…    │
│ 479400000 ┆ 139000.00 ┆ Phụ kiện  ┆ Cơ cấu    ┆ … ┆ Không xác ┆ Không xác ┆ Không xác ┆ null     │
│ 0015      ┆ 00        ┆           ┆ hàng cũ   ┆   ┆ định      ┆ định      ┆ định      ┆          │
│ 481200000 ┆ 99000.000 ┆ Phụ kiện  ┆ Cơ cấu    ┆ … ┆ Không xác ┆ Không xác ┆ Không xác ┆ null     │
│ 0011      ┆ 0         ┆           ┆ hàng cũ   ┆   ┆ định      ┆ định      ┆ định      ┆          │
│ 605500000 ┆ 119000.00 ┆ Phụ kiện  ┆ Giày tập  ┆ … ┆ Không xác ┆ Không xác ┆ Không xác ┆ Chi tiết │
│ 0036      ┆ 00        ┆           ┆ đi        ┆   ┆ định      ┆ định      ┆ định      ┆ sản phẩm │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ Tên sản  │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ phẩm…    │
│ 001452104 ┆ 9000.0000 ┆ Phụ kiện  ┆ Cơ cấu    ┆ … ┆ Không xác ┆ Không xác ┆ Kẹp tóc   ┆ Chi tiết │
│ 0104      ┆           ┆           ┆ hàng cũ   ┆   ┆ định      ┆ định      ┆           ┆ sản phẩm │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ Tên sản  │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ phẩm…    │
│ 400300000 ┆ 229000.00 ┆ Phụ kiện  ┆ Giày tập  ┆ … ┆ Không xác ┆ 0-24M     ┆ Giày tập  ┆ Chi tiết │
│ 0014      ┆ 00        ┆           ┆ đi        ┆   ┆ định      ┆           ┆ đi        ┆ sản      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ phẩmTên  │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ sản      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ phẩm:    │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ Giày tập │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ đi chút  │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ ch…      │
│ 402700000 ┆ 139000.00 ┆ Phụ kiện  ┆ Nón       ┆ … ┆ Không xác ┆ 0-12M     ┆ Nón       ┆ Chi tiết │
│ 0049      ┆ 00        ┆           ┆           ┆   ┆ định      ┆           ┆           ┆ sản phẩm │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ Tên sản  │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ phẩm…    │
│ 095200000 ┆ 165000.00 ┆ Phụ kiện  ┆ Giày tập  ┆ … ┆ Không xác ┆ Không xác ┆ Không xác ┆ null     │
│ 0078      ┆ 00        ┆           ┆ đi        ┆   ┆ định      ┆ định      ┆ định      ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

### Xử lý age_group

In [130]:
# Lọc các sản phẩm Thời trang nhưng age_group = "Không xác định"
df_fashion_age_unknown = (
    df_no_outlier
    .filter(
        (pl.col("category_l1") == "Thời trang") &
        (pl.col("age_group") == "Không xác định")
    )
)

# Kiểm tra số lượng
total = df_fashion_age_unknown.height
print("Tổng số sản phẩm Thời trang có age_group = 'Không xác định':", total)

# -----------------------------
# Thống kê description & description_new
# -----------------------------

count_desc_unknown = df_fashion_age_unknown.filter(pl.col("description") == "Không xác định").height
count_desc_new_unknown = df_fashion_age_unknown.filter(pl.col("description_new") == "Không xác định").height

print("\nThống kê tình trạng mô tả trong nhóm này:")
print(f"- description = 'Không xác định': {count_desc_unknown} / {total} ({count_desc_unknown/total*100:.2f}%)")
print(f"- description_new = 'Không xác định': {count_desc_new_unknown} / {total} ({count_desc_new_unknown/total*100:.2f}%)")

# -----------------------------
# Lấy ngẫu nhiên 20 dòng để quan sát
# -----------------------------
df_sample_age = df_fashion_age_unknown.sample(n=20, seed=42)

pd.set_option('display.max_columns', None)
df_sample_age.head(20)

Tổng số sản phẩm Thời trang có age_group = 'Không xác định': 6058

Thống kê tình trạng mô tả trong nhóm này:
- description = 'Không xác định': 5435 / 6058 (89.72%)
- description_new = 'Không xác định': 2593 / 6058 (42.80%)

shape: (20, 12)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ item_id   ┆ price     ┆ category_ ┆ category_ ┆ … ┆ gender_ta ┆ age_group ┆ item_type ┆ descript │
│ ---       ┆ ---       ┆ l1        ┆ l2        ┆   ┆ rget      ┆ ---       ┆ ---       ┆ ion_new  │
│ str       ┆ decimal[3 ┆ ---       ┆ ---       ┆   ┆ ---       ┆ str       ┆ str       ┆ ---      │
│           ┆ 8,4]      ┆ str       ┆ str       ┆   ┆ str       ┆           ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 352300000 ┆ 99000.000 ┆ Thời      ┆ Quần áo & ┆ … ┆ Không xác ┆ Không xác ┆ Không xác ┆ null     │
│ 0021      ┆ 0         ┆ trang     ┆ Phụ kiện  ┆   ┆ định      ┆ định      ┆ định      ┆          │
│           ┆           ┆           ┆ sơ sinh   ┆   ┆           ┆           ┆           ┆          │
│ 332001683 ┆ 69000.000 ┆ Thời      ┆ Cơ cấu    ┆ … ┆ Không xác ┆ Không xác ┆ Không xác ┆ null     │
│ 0007      ┆ 0         ┆ trang     ┆ hàng cũ   ┆   ┆ định      ┆ định      ┆ định      ┆          │
│ 093000236 ┆ 19000.000 ┆ Thời      ┆ Cơ cấu    ┆ … ┆ Sơ sinh   ┆ Không xác ┆ Tã vải    ┆ Không    │
│ 0001      ┆ 0         ┆ trang     ┆ hàng cũ   ┆   ┆           ┆ định      ┆           ┆ xác định │
│ 353300000 ┆ 119000.00 ┆ Thời      ┆ Quần áo & ┆ … ┆ Không xác ┆ Không xác ┆ Không xác ┆ null     │
│ 0241      ┆ 00        ┆ trang     ┆ Phụ kiện  ┆   ┆ định      ┆ định      ┆ định      ┆          │
│           ┆           ┆           ┆ sơ sinh   ┆   ┆           ┆           ┆           ┆          │
│ 603400000 ┆ 129000.00 ┆ Thời      ┆ Thời      ┆ … ┆ Không xác ┆ Không xác ┆ Không xác ┆ Không    │
│ 0360      ┆ 00        ┆ trang     ┆ trang bé  ┆   ┆ định      ┆ định      ┆ định      ┆ xác định │
│           ┆           ┆           ┆ gái       ┆   ┆           ┆           ┆           ┆          │
│ 395100000 ┆ 139000.00 ┆ Thời      ┆ Thời      ┆ … ┆ Không xác ┆ Không xác ┆ Không xác ┆ Không    │
│ 0444      ┆ 00        ┆ trang     ┆ trang bé  ┆   ┆ định      ┆ định      ┆ định      ┆ xác định │
│           ┆           ┆           ┆ trai      ┆   ┆           ┆           ┆           ┆          │
│ 089110405 ┆ 49000.000 ┆ Thời      ┆ Cơ cấu    ┆ … ┆ Bé Gái    ┆ Không xác ┆ Quần      ┆ Không    │
│ 0001      ┆ 0         ┆ trang     ┆ hàng cũ   ┆   ┆           ┆ định      ┆           ┆ xác định │
│ 699800000 ┆ 379000.00 ┆ Thời      ┆ Modal     ┆ … ┆ Không xác ┆ Không xác ┆ Không xác ┆ Không    │
│ 0086      ┆ 00        ┆ trang     ┆ kháng     ┆   ┆ định      ┆ định      ┆ định      ┆ xác định │
│           ┆           ┆           ┆ khuẩn     ┆   ┆           ┆           ┆           ┆          │
│ 341401683 ┆ 89000.000 ┆ Thời      ┆ Cơ cấu    ┆ … ┆ Không xác ┆ Không xác ┆ Không xác ┆ null     │
│ 0002      ┆ 0         ┆ trang     ┆ hàng cũ   ┆   ┆ định      ┆ định      ┆ định      ┆          │
│ 394900000 ┆ 215000.00 ┆ Thời      ┆ Thời      ┆ … ┆ Không xác ┆ Không xác ┆ Không xác ┆ null     │
│ 0018      ┆ 00        ┆ trang     ┆ trang bé  ┆   ┆ định      ┆ định      ┆ định      ┆          │
│           ┆           ┆           ┆ gái       ┆   ┆           ┆           ┆           ┆          │
│ 098328513 ┆ 140000.00 ┆ Thời      ┆ Cơ cấu    ┆ … ┆ Không xác ┆ Không xác ┆ Không xác ┆ null     │
│ 0001      ┆ 00        ┆ trang     ┆ hàng cũ   ┆   ┆ định      ┆ định      ┆ định      ┆          │
│ 603300000 ┆ 219000.00 ┆ Thời      ┆ Thời      ┆ … ┆ Không xác ┆ Không xác ┆ Không xác ┆ Không    │
│ 0114      ┆ 00        ┆ trang     ┆ trang bé  ┆   ┆ định      ┆ định      ┆ định      ┆ xác định │
│           ┆           ┆           ┆ gái       ┆   ┆           ┆           ┆           ┆          │
│ 098710451 ┆ 159000.00 ┆ Thời      ┆ Cơ cấu    ┆ … ┆ Sơ sinh   ┆ Không xác ┆ Bộ quần   ┆ Không    │
│ 0005      ┆ 00        ┆ trang     ┆ hàng cũ   ┆   ┆           ┆ định      ┆ áo        ┆ xác định │
│ 081210448 ┆ 49000.000 ┆ Thời      ┆ Cơ cấu    ┆ … ┆ Không xác ┆ Không xác ┆ Không xác ┆ null     │
│ 0003      ┆ 0         ┆ trang     ┆ hàng cũ   ┆   ┆ định      ┆ định      ┆ định      ┆          │
│ 699700000 ┆ 349000.00 ┆ Thời      ┆ Modal     ┆ … ┆ Không xác ┆ Không xác ┆ Không xác ┆ Không    │
│ 0154      ┆ 00        ┆ trang     ┆ kháng     ┆   ┆ định      ┆ định      ┆ định      ┆ xác định │
│           ┆           ┆           ┆ khuẩn     ┆   ┆           ┆           ┆           ┆          │
│ 395300000 ┆ 129000.00 ┆ Thời      ┆ Thời      ┆ … ┆ Không xác ┆ Không xác ┆ Không xác ┆ Không    │
│ 0765      ┆ 00        ┆ trang     ┆ trang bé  ┆   ┆ định      ┆ định      ┆ định      ┆ xác định │
│           ┆           ┆           ┆ trai      ┆   ┆           ┆           ┆           ┆          │
│ 082300448 ┆ 69000.000 ┆ Thời      ┆ Cơ cấu    ┆ … ┆ Không xác ┆ Không xác ┆ Không xác ┆ null     │
│ 0006      ┆ 0         ┆ trang     ┆ hàng cũ   ┆   ┆ định      ┆ định      ┆ định      ┆          │
│ 001120016 ┆ 59000.000 ┆ Thời      ┆ Cơ cấu    ┆ … ┆ Không xác ┆ Không xác ┆ Không xác ┆ Không    │
│ 0074      ┆ 0         ┆ trang     ┆ hàng cũ   ┆   ┆ định      ┆ định      ┆ định      ┆ xác định │
│ 699800000 ┆ 379000.00 ┆ Thời      ┆ Modal     ┆ … ┆ Không xác ┆ Không xác ┆ Không xác ┆ Không    │
│ 0058      ┆ 00        ┆ trang     ┆ kháng     ┆   ┆ định      ┆ định      ┆ định      ┆ xác định │
│           ┆           ┆           ┆ khuẩn     ┆   ┆           ┆           ┆           ┆          │
│ 353200000 ┆ 99000.000 ┆ Thời      ┆ Quần áo & ┆ … ┆ Không xác ┆ Không xác ┆ Không xác ┆ null     │
│ 0076      ┆ 0         ┆ trang     ┆ Phụ kiện  ┆   ┆ định      ┆ định      ┆ định      ┆          │
│           ┆           ┆           ┆ sơ sinh   ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

#### Thống kê `age_group` xuất hiện trong `category_l1` (top 15 `age_group`)

In [131]:
import polars as pl

# Các category_l1 muốn thống kê riêng
target_cat_l1 = [
    "Babycare",
    "Thời trang",
    "Đồ chơi & Sách",
    "Tã",
    "Textile",
    "Phụ kiện",
    "Thực phẩm cho bé",        # nhớ check lại đúng tên trong data
    "Sữa",
    "Hóa mỹ phẩm cho bé",      # check lại spelling "Hóa/Hoá"
    "Thực phẩm cho gia đình",  # check lại spelling
    "Vệ sinh",
    "Sữa nước",
    "TPCN",
]

# Lặp qua từng category_l1 và in bảng thống kê age_group cho riêng category đó
for cat in target_cat_l1:
    print(f"\n================= {cat} =================")

    sub_stats = (
        df_filled
        .filter(pl.col("category_l1") == cat)
        .group_by("age_group")
        .agg(pl.len().alias("count"))
        .sort("count", descending=True)
        .head(15)          # giữ top 15 age_group của riêng category này
    )

    print(sub_stats)

================= Babycare =================
shape: (15, 2)
┌────────────────┬───────┐
│ age_group      ┆ count │
│ ---            ┆ ---   │
│ str            ┆ u32   │
╞════════════════╪═══════╡
│ Không xác định ┆ 1667  │
│ Từ 6M          ┆ 59    │
│ Mẹ             ┆ 37    │
│ Từ 0M          ┆ 37    │
│ Từ 1Y          ┆ 23    │
│ 0-6M           ┆ 19    │
│ Từ 3Y          ┆ 15    │
│ Từ 3M          ┆ 13    │
│ Từ 2Y          ┆ 11    │
│ 3M-6M          ┆ 10    │
│ 0-3M           ┆ 9     │
│ 2M-6M          ┆ 9     │
│ 0-36M          ┆ 9     │
│ Từ 4M          ┆ 8     │
│ Từ 9M          ┆ 7     │
└────────────────┴───────┘

================= Thời trang =================
shape: (15, 2)
┌────────────────┬───────┐
│ age_group      ┆ count │
│ ---            ┆ ---   │
│ str            ┆ u32   │
╞════════════════╪═══════╡
│ Không xác định ┆ 6058  │
│ 9M-12M         ┆ 844   │
│ 6M-9M          ┆ 671   │
│ 3M-6M          ┆ 535   │
│ Từ 2Y          ┆ 493   │
│ Từ 1Y          ┆ 438   │
│ 12M-18M        ┆ 424   │
│ Từ 4Y          ┆ 419   │
│ 18M-24M        ┆ 407   │
│ Từ 3Y          ┆ 392   │
│ Từ 9M          ┆ 374   │
│ 2Y-3Y          ┆ 339   │
│ Từ 6M          ┆ 301   │
│ Từ 0M          ┆ 290   │
│ Từ 6Y          ┆ 253   │
└────────────────┴───────┘

================= Đồ chơi & Sách =================
shape: (15, 2)
┌────────────────┬───────┐
│ age_group      ┆ count │
│ ---            ┆ ---   │
│ str            ┆ u32   │
╞════════════════╪═══════╡
│ Không xác định ┆ 2274  │
│ Từ 3Y          ┆ 471   │
│ Từ 18M         ┆ 69    │
│ Từ 0M          ┆ 31    │
│ Từ 3M          ┆ 26    │
│ Từ 1Y          ┆ 22    │
│ Từ 6M          ┆ 22    │
│ Từ 2Y          ┆ 7     │
│ Từ 6Y          ┆ 7     │
│ 4Y-5Y          ┆ 5     │
│ Từ 9M          ┆ 4     │
│ 0-36M          ┆ 4     │
│ Từ 10M         ┆ 3     │
│ 2Y-6Y          ┆ 3     │
│ 1Y-3Y          ┆ 1     │
└────────────────┴───────┘

================= Tã =================
shape: (4, 2)
┌────────────────┬───────┐
│ age_group      ┆ count │
│ ---            ┆ ---   │
│ str            ┆ u32   │
╞════════════════╪═══════╡
│ Không xác định ┆ 429   │
│ Từ 6M          ┆ 5     │
│ 0-10M          ┆ 3     │
│ Từ 1M          ┆ 1     │
└────────────────┴───────┘

================= Textile =================
shape: (13, 2)
┌────────────────┬───────┐
│ age_group      ┆ count │
│ ---            ┆ ---   │
│ str            ┆ u32   │
╞════════════════╪═══════╡
│ Không xác định ┆ 507   │
│ Từ 0M          ┆ 17    │
│ 1Y-3Y          ┆ 9     │
│ Từ 3M          ┆ 6     │
│ 0-12M          ┆ 3     │
│ 2Y-6Y          ┆ 3     │
│ Từ 1Y          ┆ 2     │
│ 0-5Y           ┆ 2     │
│ Từ 2M          ┆ 1     │
│ 0-36M          ┆ 1     │
│ 1M-15M         ┆ 1     │
│ 1Y-2Y          ┆ 1     │
│ 1M-12M         ┆ 1     │
└────────────────┴───────┘

================= Phụ kiện =================
shape: (15, 2)
┌────────────────┬───────┐
│ age_group      ┆ count │
│ ---            ┆ ---   │
│ str            ┆ u32   │
╞════════════════╪═══════╡
│ Không xác định ┆ 2586  │
│ 1Y-3Y          ┆ 168   │
│ 0-12M          ┆ 123   │
│ 1Y-6Y          ┆ 64    │
│ 3Y-6Y          ┆ 28    │
│ 0-24M          ┆ 27    │
│ Từ 2Y          ┆ 16    │
│ 3Y-4Y          ┆ 14    │
│ 5Y-6Y          ┆ 13    │
│ 4Y-5Y          ┆ 13    │
│ 2Y-3Y          ┆ 12    │
│ 9M-20M         ┆ 10    │
│ 2Y-6Y          ┆ 8     │
│ 6M-18M         ┆ 8     │
│ Từ 5Y          ┆ 8     │
└────────────────┴───────┘

================= Thực phẩm cho bé =================
shape: (15, 2)
┌────────────────┬───────┐
│ age_group      ┆ count │
│ ---            ┆ ---   │
│ str            ┆ u32   │
╞════════════════╪═══════╡
│ Không xác định ┆ 636   │
│ Từ 6M          ┆ 106   │
│ Từ 3Y          ┆ 44    │
│ Từ 1Y          ┆ 40    │
│ Từ 7M          ┆ 32    │
│ Từ 4M          ┆ 31    │
│ Từ 9M          ┆ 28    │
│ Từ 8M          ┆ 23    │
│ Từ 5M          ┆ 7     │
│ Từ 2Y          ┆ 6     │
│ 1Y-16Y         ┆ 4     │
│ 8Y-14Y         ┆ 4     │
│ Từ 5Y          ┆ 3     │
│ 6M-36M         ┆ 3     │
│ Từ 18M         ┆ 2     │
└────────────────┴───────┘

================= Sữa =================
shape: (15, 2)
┌────────────────┬───────┐
│ age_group      ┆ count │
│ ---            ┆ ---   │
│ str            ┆ u32   │
╞════════════════╪═══════╡
│ Không xác định ┆ 97    │
│ 0-12M          ┆ 58    │
│ 0-6M           ┆ 50    │
│ 1Y-2Y          ┆ 47    │
│ 6M-12M         ┆ 37    │
│ 2Y-6Y          ┆ 30    │
│ Từ 2Y          ┆ 24    │
│ 1Y-3Y          ┆ 22    │
│ 1Y-10Y         ┆ 12    │
│ Từ 1Y          ┆ 10    │
│ Từ 3Y          ┆ 7     │
│ Mẹ             ┆ 7     │
│ 1Y-9Y          ┆ 4     │
│ 6M-24M         ┆ 4     │
│ 0-36M          ┆ 3     │
└────────────────┴───────┘

================= Hóa mỹ phẩm cho bé =================
shape: (14, 2)
┌────────────────┬───────┐
│ age_group      ┆ count │
│ ---            ┆ ---   │
│ str            ┆ u32   │
╞════════════════╪═══════╡
│ Không xác định ┆ 256   │
│ Từ 0M          ┆ 49    │
│ 0-36M          ┆ 6     │
│ 0-6Y           ┆ 6     │
│ Từ 3M          ┆ 5     │
│ Từ 3Y          ┆ 4     │
│ 2Y-6Y          ┆ 3     │
│ 0-24M          ┆ 3     │
│ Từ 1Y          ┆ 3     │
│ Từ 2Y          ┆ 3     │
│ Từ 6M          ┆ 3     │
│ Trên 1Y        ┆ 2     │
│ 0-6M           ┆ 1     │
│ 0-4Y           ┆ 1     │
└────────────────┴───────┘

================= Thực phẩm cho gia đình =================
shape: (7, 2)
┌────────────────┬───────┐
│ age_group      ┆ count │
│ ---            ┆ ---   │
│ str            ┆ u32   │
╞════════════════╪═══════╡
│ Không xác định ┆ 455   │
│ Từ 2Y          ┆ 7     │
│ Từ 6M          ┆ 2     │
│ Từ 3Y          ┆ 2     │
│ Từ 1Y          ┆ 2     │
│ Từ 4Y          ┆ 1     │
│ Mẹ             ┆ 1     │
└────────────────┴───────┘

================= Vệ sinh =================
shape: (2, 2)
┌────────────────┬───────┐
│ age_group      ┆ count │
│ ---            ┆ ---   │
│ str            ┆ u32   │
╞════════════════╪═══════╡
│ Không xác định ┆ 131   │
│ Từ 0M          ┆ 1     │
└────────────────┴───────┘

================= Sữa nước =================
shape: (6, 2)
┌────────────────┬───────┐
│ age_group      ┆ count │
│ ---            ┆ ---   │
│ str            ┆ u32   │
╞════════════════╪═══════╡
│ Không xác định ┆ 75    │
│ Từ 1Y          ┆ 64    │
│ Từ 2Y          ┆ 10    │
│ Từ 6M          ┆ 8     │
│ 1Y-10Y         ┆ 7     │
│ Từ 3Y          ┆ 2     │
└────────────────┴───────┘

================= TPCN =================
shape: (15, 2)
┌────────────────┬───────┐
│ age_group      ┆ count │
│ ---            ┆ ---   │
│ str            ┆ u32   │
╞════════════════╪═══════╡
│ Không xác định ┆ 247   │
│ Từ 1Y          ┆ 5     │
│ Từ 0M          ┆ 2     │
│ 1Y-9Y          ┆ 1     │
│ 6M-12Y         ┆ 1     │
│ Từ 6M          ┆ 1     │
│ 1Y-3Y          ┆ 1     │
│ Từ 7M          ┆ 1     │
│ 3Y-12Y         ┆ 1     │
│ 0-4Y           ┆ 1     │
│ 0-36M          ┆ 1     │
│ 4M-4Y          ┆ 1     │
│ Từ 13Y         ┆ 1     │
│ 1Y-11Y         ┆ 1     │
│ Từ 4M          ┆ 1     │
└────────────────┴───────┘

#### Kiểm tra `age_group` trong `"Thời trang"`

In [132]:
import polars as pl

CAT_L1 = "Thời trang"

df_fashion = df_filled.filter(pl.col("category_l1") == CAT_L1)

# 1) Tất cả class trong category_l2
cat2_classes = (
    df_fashion
    .select("category_l2")
    .unique()                 # lấy giá trị duy nhất
    .sort("category_l2")      # sắp xếp cho dễ nhìn (optional)
)

print("\n=== Tất cả class category_l2 của Thời trang ===")
print(cat2_classes)

# 2) Tất cả class trong category_l3
cat3_classes = (
    df_fashion
    .select("category_l3")
    .unique()
    .sort("category_l3")
)

print("\n=== Tất cả class category_l3 của Thời trang ===")
print(cat3_classes)

# 3) Tất cả class trong category (tên chi tiết)
cat_classes = (
    df_fashion
    .select("category")
    .unique()
    .sort("category")
)

print("\n=== Tất cả class category (tên hiển thị) của Thời trang ===")
print(cat_classes)

=== Tất cả class category_l2 của Thời trang ===
shape: (7, 1)
┌────────────────────────────┐
│ category_l2                │
│ ---                        │
│ str                        │
╞════════════════════════════╡
│ Cho mẹ                     │
│ Cơ cấu hàng cũ             │
│ Modal kháng khuẩn          │
│ Quần áo & Phụ kiện sơ sinh │
│ Thời trang bé gái          │
│ Thời trang bé trai         │
│ Thời trang đông            │
└────────────────────────────┘

=== Tất cả class category_l3 của Thời trang ===
shape: (24, 1)
┌────────────────────────────────┐
│ category_l3                    │
│ ---                            │
│ str                            │
╞════════════════════════════════╡
│ Bao tay chân, nón              │
│ Bodysuit                       │
│ Bodysuit Modal                 │
│ Bodysuit bé gái                │
│ Bodysuit bé trai               │
│ Bodysuit đông                  │
│ Bộ Modal                       │
│ Bộ bé gái                      │
│ Bộ bé trai                     │
│ Bộ đông                        │
│ Phụ kiện cho bé                │
│ Phụ kiện cho mẹ                │
│ Phụ kiện khác                  │
│ Quần                           │
│ Quần bé gái                    │
│ Quần bé trai                   │
│ Quần, áo & phụ kiện sơ sinh cũ │
│ Thời trang bé trai, bé gái cũ  │
│ Áo                             │
│ Áo bé gái                      │
│ Áo bé trai                     │
│ Áo, Quần đông                  │
│ Đầm bé gái                     │
│ Đồ bầu                         │
└────────────────────────────────┘

=== Tất cả class category (tên hiển thị) của Thời trang ===
shape: (90, 1)
┌────────────────────────────────────┐
│ category                           │
│ ---                                │
│ str                                │
╞════════════════════════════════════╡
│ 0-12M Bodysuit bé trai đùi         │
│ 0-12M Bodysuit tam giác            │
│ 0-12M Bodysuit đông vải mỏng       │
│ 0-12M Bộ nón tay chân sơ sinh bo   │
│ 0-12M Quần sơ sinh ngắn            │
│ 0-12M Áo sơ sinh cài chéo tay ngắn │
│ 0-24M Áo thun bé trai tay dài đông │
│ 0-3Y Bộ đông bé trai dài           │
│ Bao tay chân                       │
│ Bodysuit                           │
│ Bodysuit Animo                     │
│ Bodysuit Animo Easy                │
│ Bodysuit Chống muỗi set 2          │
│ Bodysuit Modal lẻ                  │
│ Bodysuit Modal set 2               │
│ Bodysuit bé gái dài                │
│ Bodysuit bé gái tam giác           │
│ Bodysuit bé gái đùi                │
│ Bodysuit bé trai dài               │
│ Bodysuit bé trai tam giác          │
│ Bodysuit bé trai đùi               │
│ Bodysuit cũ                        │
│ Bodysuit tam giác                  │
│ Bodysuit đông vải dày              │
│ Bodysuit đông vải mỏng             │
│ …                                  │
│ Túi ngủ                            │
│ Túi ngủ, swaddle                   │
│ Vớ                                 │
│ Vớ cho mẹ                          │
│ Yếm                                │
│ Yếm nhập khẩu                      │
│ Áo bé gái                          │
│ Áo bé gái Animo                    │
│ Áo bé gái Animo Easy               │
│ Áo bé gái cũ                       │
│ Áo bé trai                         │
│ Áo bé trai Animo                   │
│ Áo bé trai Animo Easy              │
│ Áo bé trai cũ                      │
│ Áo ghile đông                      │
│ Áo khoác                           │
│ Áo ngực bầu                        │
│ Áo ngực cho mẹ                     │
│ Áo sơ sinh                         │
│ Áo sơ sinh Animo                   │
│ Áo sơ sinh Animo Easy              │
│ Đầm                                │
│ Đầm bé gái Animo                   │
│ Đầm bé gái Animo Easy              │
│ Đầm cũ                             │
└────────────────────────────────────┘

In [133]:
categories = cat_classes.get_column("category").to_list()

print(f"Tổng số class category trong Thời trang: {len(categories)}\n")

for c in categories:
    print(c)

Tổng số class category trong Thời trang: 90

0-12M Bodysuit bé trai đùi
0-12M Bodysuit tam giác
0-12M Bodysuit đông vải mỏng
0-12M Bộ nón tay chân sơ sinh bo
0-12M Quần sơ sinh ngắn
0-12M Áo sơ sinh cài chéo tay ngắn
0-24M Áo thun bé trai tay dài đông
0-3Y Bộ đông bé trai dài
Bao tay chân
Bodysuit
Bodysuit Animo
Bodysuit Animo Easy
Bodysuit Chống muỗi set 2
Bodysuit Modal lẻ
Bodysuit Modal set 2
Bodysuit bé gái dài
Bodysuit bé gái tam giác
Bodysuit bé gái đùi
Bodysuit bé trai dài
Bodysuit bé trai tam giác
Bodysuit bé trai đùi
Bodysuit cũ
Bodysuit tam giác
Bodysuit đông vải dày
Bodysuit đông vải mỏng
Bộ Modal lẻ
Bộ Modal set 2
Bộ bé gái Animo
Bộ bé gái Animo Easy
Bộ bé trai Animo
Bộ bé trai Animo Easy
Bộ chống muỗi set 2
Bộ nón bao tay chân
Bộ quần áo bé gái
Bộ quần áo bé trai
Bộ đông bé gái dài
Bộ đông bé trai dài
Hero lẻ 129k
Hộp quà
Khăn voan
Khẩu trang
Nón sơ sinh
Nón sơ sinh nhập khẩu
Phụ kiện cũ khác
Quần bé trai
Quần bé trai cũ
Quần dài bé trai
Quần legging bé gái
Quần lót bầu
Quần lót cho bé
Quần short bé gái
Quần short bé trai
Quần sơ sinh
Quần sơ sinh Animo
Quần sơ sinh Animo Easy
Quần đông
Quần, chân váy bé gái
Quần, áo, đầm bầu
Set 2 Bộ bao tay chân
Set 2 Nón sơ sinh
Set 2 đôi vớ
Set 3 quần lót bé gái
Set 6 Bộ bao tay chân
Tã vải
Tã vải cũ
Túi ngủ
Túi ngủ, swaddle
Vớ
Vớ cho mẹ
Yếm
Yếm nhập khẩu
Áo bé gái
Áo bé gái Animo
Áo bé gái Animo Easy
Áo bé gái cũ
Áo bé trai
Áo bé trai Animo
Áo bé trai Animo Easy
Áo bé trai cũ
Áo ghile đông
Áo khoác
Áo ngực bầu
Áo ngực cho mẹ
Áo sơ sinh
Áo sơ sinh Animo
Áo sơ sinh Animo Easy
Đầm
Đầm bé gái Animo
Đầm bé gái Animo Easy
Đầm cũ

In [134]:
import polars as pl

# Các category bạn phát hiện được
categories_to_check = [
    "0-12M Bodysuit bé trai đùi",
    "0-12M Bodysuit tam giác",
    "0-12M Bodysuit đông vải mỏng",
    "0-12M Bộ nón tay chân sơ sinh bo",
    "0-12M Quần sơ sinh ngắn",
    "0-12M Áo sơ sinh cài chéo tay ngắn",
    "0-24M Áo thun bé trai tay dài đông",
    "0-3Y Bộ đông bé trai dài",
]

# 1) Lọc subset Thời trang & age_group = "Không xác định"
fashion_unknown = df_filled.filter(
    (pl.col("category_l1") == "Thời trang")
    & (pl.col("age_group") == "Không xác định")
)

# 2) Tìm các dòng có category thuộc danh sách trên
matches = fashion_unknown.filter(
    pl.col("category").is_in(categories_to_check)
)

print("Số dòng match:", matches.height)
matches.head()

Số dòng match: 39

shape: (5, 13)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ item_id   ┆ price     ┆ category_ ┆ category_ ┆ … ┆ age_group ┆ item_type ┆ descripti ┆ gender_t │
│ ---       ┆ ---       ┆ l1        ┆ l2        ┆   ┆ ---       ┆ ---       ┆ on_new    ┆ arget_fi │
│ str       ┆ decimal[3 ┆ ---       ┆ ---       ┆   ┆ str       ┆ str       ┆ ---       ┆ nal      │
│           ┆ 8,4]      ┆ str       ┆ str       ┆   ┆           ┆           ┆ str       ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ str      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 002417104 ┆ 19000.000 ┆ Thời      ┆ Cơ cấu    ┆ … ┆ Không xác ┆ Không xác ┆ Không xác ┆ Bé Trai  │
│ 0022      ┆ 0         ┆ trang     ┆ hàng cũ   ┆   ┆ định      ┆ định      ┆ định      ┆          │
│ 352200000 ┆ 139000.00 ┆ Thời      ┆ Quần áo & ┆ … ┆ Không xác ┆ Không xác ┆ null      ┆ Sơ sinh  │
│ 0140      ┆ 00        ┆ trang     ┆ Phụ kiện  ┆   ┆ định      ┆ định      ┆           ┆          │
│           ┆           ┆           ┆ sơ sinh   ┆   ┆           ┆           ┆           ┆          │
│ 090928586 ┆ 19000.000 ┆ Thời      ┆ Cơ cấu    ┆ … ┆ Không xác ┆ Đồ ngủ,   ┆ Không xác ┆ Bé Trai  │
│ 0001      ┆ 0         ┆ trang     ┆ hàng cũ   ┆   ┆ định      ┆ đồ lót    ┆ định      ┆          │
│ 604800000 ┆ 229000.00 ┆ Thời      ┆ Thời      ┆ … ┆ Không xác ┆ Không xác ┆ null      ┆ Không    │
│ 0048      ┆ 00        ┆ trang     ┆ trang     ┆   ┆ định      ┆ định      ┆           ┆ xác định │
│           ┆           ┆           ┆ đông      ┆   ┆           ┆           ┆           ┆          │
│ 349600000 ┆ 75000.000 ┆ Thời      ┆ Quần áo & ┆ … ┆ Không xác ┆ Không xác ┆ null      ┆ Sơ sinh  │
│ 0010      ┆ 0         ┆ trang     ┆ Phụ kiện  ┆   ┆ định      ┆ định      ┆           ┆          │
│           ┆           ┆           ┆ sơ sinh   ┆   ┆           ┆           ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

####
"0-12M Bodysuit bé trai đùi",
"0-12M Bodysuit tam giác",
"0-12M Bodysuit đông vải mỏng",
"0-12M Bộ nón tay chân sơ sinh bo",
"0-12M Quần sơ sinh ngắn",
"0-12M Áo sơ sinh cài chéo tay ngắn",
"0-24M Áo thun bé trai tay dài đông",
"0-3Y Bộ đông bé trai dài",

fill các `category` sau cho `age_group`

In [135]:
import polars as pl

# Giả sử df_filled là dataframe hiện tại (đã có gender_target_final, v.v.)
df_age = df_filled.with_columns(
    pl.col("age_group").alias("age_group_final")
)

mask_fashion_unknown_age = (
    (pl.col("category_l1") == "Thời trang")
    & (pl.col("age_group_final") == "Không xác định")
)

# Rule 1 – Fill cho các category bắt đầu bằng 0-12M
mask_012M = (
    mask_fashion_unknown_age
    & pl.col("category").str.starts_with("0-12M")
)

df_age = df_age.with_columns(
    pl.when(mask_012M)
      .then(pl.lit("0-12M"))
      .otherwise(pl.col("age_group_final"))
      .alias("age_group_final")
)

# Rule 2 – Fill cho các category bắt đầu bằng 0-24M
mask_024M = (
    mask_fashion_unknown_age
    & pl.col("category").str.starts_with("0-24M")
)

df_age = df_age.with_columns(
    pl.when(mask_024M)
      .then(pl.lit("0-24M"))
      .otherwise(pl.col("age_group_final"))
      .alias("age_group_final")
)

# Rule 3 – Fill cho các category bắt đầu bằng 0-3Y
mask_03Y = (
    mask_fashion_unknown_age
    & pl.col("category").str.starts_with("0-3Y")
)

df_age = df_age.with_columns(
    pl.when(mask_03Y)
      .then(pl.lit("0-3Y"))
      .otherwise(pl.col("age_group_final"))
      .alias("age_group_final")
)

In [136]:
filled_rows = df_age.filter(
    (pl.col("age_group") == "Không xác định")
    & (pl.col("age_group_final") != "Không xác định")
).height

print("Tổng số dòng được fill từ category:", filled_rows)

Tổng số dòng được fill từ category: 39

#### Lọc ra các class có trong mỗi `category`

In [137]:
import polars as pl

df = df_age   # hoặc df_filled tùy bạn đang dùng

# Hàm tiện dụng để lấy danh sách unique của 1 cột
def get_unique_list(df, col):
    return (
        df.select(col)
          .unique()
          .sort(col)
          .get_column(col)
          .to_list()
    )

# Lấy tất cả class
cat_l1_list = get_unique_list(df, "category_l1")
cat_l2_list = get_unique_list(df, "category_l2")
cat_l3_list = get_unique_list(df, "category_l3")
cat_list    = get_unique_list(df, "category")
age_list    = get_unique_list(df, "age_group")

# Gom vào dictionary
category_dict = {
    "category_l1": cat_l1_list,
    "category_l2": cat_l2_list,
    "category_l3": cat_l3_list,
    "category": cat_list,
    # "age_group": age_list
}

# In ra theo từng dòng, rất dễ đọc
print("\n=== DANH SÁCH TẤT CẢ CLASS CỦA TỪNG CATEGORY ===\n")
for key, value in category_dict.items():
    print(f"{key}: {value}\n")

=== DANH SÁCH TẤT CẢ CLASS CỦA TỪNG CATEGORY ===

category_l1: ['Babycare', 'Gói Hội Viên', 'Hóa mỹ phẩm cho bé', 'Hóa mỹ phẩm gia đình', 'Phụ kiện', 'Sữa', 'Sữa nước', 'TPCN', 'Textile', 'Thời trang', 'Thực phẩm cho bé', 'Thực phẩm cho gia đình', 'Tã', 'Vệ sinh', 'Đồ chơi & Sách']

category_l2: ['0-1Y', '1Y+', 'A2 milk company', 'Abbott', 'Alphagen', 'Animo', 'Anlene', 'Anmum', 'Appekidz', 'Aptamil', 'Aptamil Úc', 'Bellamy', 'Blackmores', 'Bobby', 'Bubs', 'Bánh', 'Bánh & Kẹo cho bé', 'Bé ngủ', 'Bình sữa, phụ kiện', 'Bông gạc', 'Bông tẩy trang', 'Băng vệ sinh', 'Bột lắc sữa', 'Bột ăn dặm', 'Caryn', 'Cho mẹ', 'Cháo ăn dặm', 'Chăm sóc cơ thể', 'Chăm sóc da', 'Chăm sóc da bé', 'Chăm sóc gia đình', 'Chăm sóc mẹ trước & sau sinh', 'Chăm sóc răng miệng', 'Chăm sóc sức khỏe bé', 'Chăm sóc tóc', 'Chăn', 'Chăn ga gối gia đình', 'Confidence', 'Cơ cấu hàng cũ', 'Cơ cấu hàng tồn', 'Dad and Me', 'Dầu sức khỏe', 'Dầu ăn & Gia vị', 'Elprairie', 'Enfa', 'FCV', 'Genki', 'Giày dép 1-3Y', 'Giày tập đi', 'Giấy', 'Giặt xả cho bé', 'Giặt xả gia đình', 'Glico', 'Goon', 'Gói Hội Viên BẦU', 'Gói Hội Viên Mass', 'Gối', 'Hipp', 'Huggies', 'Humana', 'Ildong', 'Kabrita', 'Khăn em bé', 'Khăn gia đình', 'Khăn khô', 'Khăn ướt', 'Khẩu trang', 'Kid Essential', 'Kẹo', 'Kế hoạch gia đình', 'Maeil', 'Meiji', 'Meiji Nội địa', 'Merries', 'Modal kháng khuẩn', 'Molfix', 'Moony', 'Morinaga', 'Mì & Đồ khô ăn liền', 'Mứt & Bơ phết', 'Nestle', 'Nutifood', 'Nutricare', 'Nón', 'Nước rửa bình sữa', 'Pampers', 'Phụ kiện khác', 'Purelac', 'Quần áo & Phụ kiện sơ sinh', 'Rascal', 'SP mùa vụ', 'Snack', 'Snack ăn dặm', 'Sweety', 'Sách & VPP', 'Sức khỏe gia đình', 'Sữa bột pha sẵn', 'Sữa cho mẹ', 'Sữa chua uống', 'Sữa có vị', 'Sữa hạt', 'Sữa tươi tiệt trùng', 'Sữa đặc trị pha sẵn', 'TP bảo quản lạnh', 'TP từ sữa (bảo quản lạnh)', 'TP từ sữa (bảo quản thường)', 'TPCN cho bé', 'TPCN cho gia đình', 'TPCN cho mẹ', 'Takato', 'Thiết bị điện gia dụng', 'Thơm không gian', 'Thời trang bé gái', 'Thời trang bé trai', 'Thời trang đông', 'Thức ăn nghiền cho bé', 'Thực phẩm đông lạnh', 'Trà & Cà phê', 'Trái cây', 'Vinamilk', 'Vitadairy', 'Vệ sinh cho bé', 'Vệ sinh dụng cụ & bề mặt', 'Wakodo', 'Whito', 'Whoopee', 'XO', 'Đồ dùng bé ngủ ngon', 'Đồ dùng cho mẹ', 'Đồ dùng ra ngoài', 'Đồ dùng vệ sinh', 'Đồ dùng ăn uống', 'Đồ uống']

category_l3: ['A2 milk', 'A2 milk company', 'Abbott', 'Abbott Grow', 'Agusha', 'Alphagen', 'An toàn xe máy/ xe hơi', 'Animo', 'Anlene', 'Anmum', 'Appekidz', 'Aptamil', 'Aptamil Hà Lan', 'Aptamil NZ', 'Aptamil Úc', "Australia's Own", 'Bao cao su', 'Bao tay chân, nón', 'Bellamy', 'Blackmores', 'Bobby Antimos', 'Bobby Fresh', 'Bobby Quần Mở Một Bên', 'Bodysuit', 'Bodysuit Modal', 'Bodysuit bé gái', 'Bodysuit bé trai', 'Bodysuit đông', 'Boost', 'Bubs A2', 'Bubs Full Cream', 'Bubs Goat', 'Bubs Organic', 'Bàn chải', 'Bàn ủi hơi nước', 'Bánh Bolo', 'Bánh Trung Thu', 'Bánh bông lan & Pie', 'Bánh cho bé từ 2 tuổi', 'Bánh gạo', 'Bánh mì', 'Bánh quy', 'Bánh quế', 'Bánh xốp', 'Bé ngủ ngừng bán', 'Bình nước/ Bình giữ nhiệt', 'Bình sữa', 'Bình sữa, phụ kiện ngừng bán', 'Bình tập uống', 'Bông gạc', 'Bông tẩy trang Nhật', 'Bông tẩy trang Thổ Nhĩ Kì', 'Băng vệ sinh sau sinh', 'Băng vệ sinh thường', 'Bơ lạt', 'Bơ mặn', 'Bổ sung vitamin và vi chất', 'Bộ Modal', 'Bộ bé gái', 'Bộ bé trai', 'Bộ chăn gối nệm', 'Bộ đông', 'Bột cho bé từ 4 tháng', 'Bột cho bé từ 6 tháng', 'Bột cháo khô', 'Bột rau', 'Calcium', 'Calcium + D3', 'Caryn', 'Cháo sữa', 'Cháo tươi', 'Chăm sóc da', 'Chăm sóc dáng', 'Chăm sóc gia đình ngừng bán', 'Chăm sóc mắt', 'Chăm sóc quần áo', 'Chăn bông', 'Chăn cũ', 'Chăn lưới, chăn len', 'Chăn vải chần bông', 'Chăn xô, chăn Linen', 'Chả giò', 'Collagen', 'Colos Gain', 'ColosCare', 'ColosGold', 'Colosbaby', 'Colosbaby Bio Gold', 'Colosbaby D3K2', 'Colosbaby DHA', 'Colosbaby IQ Gold', 'Colosbaby Opti', 'Colosbaby Pedia', 'Confidence', 'Cà phê', 'Cài, kẹp, cột', 'Các loại hạt', 'DHA', 'DHA/Omega-3', 'Dad and Me', 'Dessert', 'Devondale', 'Dielac', 'Dielac Alpha Gold', 'Dielac Grow Plus', 'Dung dịch vệ sinh cho bé', 'Dung dịch vệ sinh phụ nữ', 'Dép sục', 'Dưỡng da', 'Dưỡng môi', 'Dưỡng tóc', 'Dưỡng ẩm cơ thể', 'Dưỡng ẩm mặt', 'Dầu Mù U', 'Dầu gió', 'Dầu gội', 'Dầu khuynh diệp', 'Dầu massage', 'Dầu màng tang', 'Dầu tràm', 'Dầu xả', 'Dầu ăn', 'Dụng cụ học tập', 'Dụng cụ ăn uống', 'Dừa', 'EVERON', 'Elprairie AW', 'Enfa', 'Enfa A2', 'Enfa C-sec', 'Enfa US', 'Enfa gentle care', 'Enfamil A2', 'Enspire', 'Enspire Thai', 'Ensure', 'FCV', 'Famna', 'Fish Oil', 'Friso', 'Friso ( Hà Lan )', 'Friso Prestige', 'Friso Pro', 'Fruto', 'Gel bôi trơn', 'GenKi', 'Ghế ngồi ô tô', 'Ghế ngồi ăn', 'Ginkgo', 'Giày chút chít 179k', 'Giày dép tồn', 'Giày sơ sinh 119k', 'Giày tập đi 149k', 'Giày tập đi 89k', 'Giày và sandal bé gái', 'Giấy vệ sinh', 'Giặt cho bé', 'Giặt gia đình', 'Glico', 'Glucerna', 'Goon Friend', 'Goon Mommy Kiss', 'Goon Premium', 'Grow Plus Xanh', 'Grow Plus trắng', 'Grow Plus Đỏ', 'Grow plus vàng', 'Gummies', 'Gói Hội Viên BẦU', 'Gói Hội Viên Mass', 'Gạc, rơ lưỡi', 'Gạo', 'Gặm nướu', 'Gối chặn', 'Gối chống trào ngược', 'Gối cũ', 'Gối nằm bông gòn', 'Gối nằm cao su', 'Gối ôm', 'Height Boosting', 'Hikid', 'Hipp', 'Ho cảm', 'Huggies Platinum', 'Huggies Skin Perfect', 'Huggies Thin & Soft', 'Huggies Thường', 'Humana', 'Há cảo', 'Hâm sữa, tiệt trùng', 'Hút sữa', 'Hạ sốt', 'Hạnh Nhân', 'Hạt nêm & Dashi', 'Học tập và phát triển tư duy', 'Hỗ trợ trí não', 'Immunel', 'Kabrita', 'Kem', 'Kem chống hăm', 'Kem chống nắng', 'Kem đánh răng', 'Kem đặc trị', 'Kenko', 'Khoai tây chiên', 'Khăn bếp', 'Khăn choàng ủ', 'Khăn cũ', 'Khăn giấy bỏ túi', 'Khăn giấy rút', 'Khăn gạc, khăn sữa', 'Khăn lau tóc', 'Khăn mặt', 'Khăn tay đa năng', 'Khăn tắm', 'Khăn tắm gia đình', 'Khăn tắm trẻ em đa năng', 'Khăn vải khô', 'Khăn ăn', 'Khăn ướt bột giấy', 'Khăn ướt gia dụng', 'Khăn ướt vải', 'Khẩu trang cho bé', 'Khẩu trang người lớn', 'Khử mùi cơ thể', 'Kid Essential', 'Kids Boost', 'Kit test SARS-CoV-2', 'Kiwi', 'Kun', 'Kẹo Gum', 'Kẹo Socola', 'Kẹo cứng', 'Kẹo dẻo', 'Kẹo mềm', 'Kẹo socola & Socola', 'Kẹo the', 'Kẹo đồ chơi', 'Kẽm', 'Lactoferrin', 'Lecithin', 'Maeil', 'Meadow Fresh', 'Meiji', 'Meiji nội địa', 'Men tiêu hóa', 'Men vi sinh', 'Merries', 'Merries 1st Premium', 'Merries Volume Up', 'Metacare', 'Miếng lót thấm sữa', 'Mochi', 'Molfix', 'Moony', 'Moony Natural', 'Morinaga', 'Multiple Vitamin', 'Máy hút bụi', 'Máy rửa bình sữa', 'Máy tạo ẩm', 'Máy vắt cam', 'Máy xay', 'Mì & Miến ăn liền', 'Mùng cho bé', 'Mật ong', 'Mắc ca', 'Mặt nạ', 'Mứt', 'NAN', 'NAN Expert', 'NAN Nga', 'NAN Organic', 'NAN Supreme', 'NIN HOUSE', 'Nan A2 InfiniPro', 'Nestle', 'Nestle đặc trị', 'Ngũ cốc & Yến mạch', 'Ngũ cốc ăn sáng', 'Ngủ ngon', 'Nhân sâm', 'Nhập vai', 'Nui & Mì', 'Nutifood', 'Nutramigen', 'Nutren', 'NutriBoost', 'Nutricare', 'Nuvi Grow', 'Nêm & Muối đường', 'Nón bé gái', 'Nón bé trai', 'Nón sơ sinh', 'Nón tồn', 'Nôi, cũi, võng', 'Núm ty', 'Nước cân bằng', 'Nước có thạch', 'Nước gạo', 'Nước hoa cho bé', 'Nước lau sàn', 'Nước mắm', 'Nước ngọt', 'Nước rửa bình sữa nhập khẩu', 'Nước rửa bình sữa trong nước', 'Nước rửa chén', 'Nước rửa tay', 'Nước rửa đa năng', 'Nước suối', 'Nước súc miệng', 'Nước trái cây', 'Nước tương', 'Nước tẩy toilet', 'Nước uống có ga', 'Nước uống có thạch', 'Nước yến', 'Nước ép trái cây cho bé', 'Nệm', 'Nệm mát, Chiếu', 'Nồi nấu chậm', 'Oggi Gold', 'Oldenburger', 'Optimum', 'Pampers Nhật', 'Pampers Overnight', 'Pampers Thường', 'Pasta', 'Pasta & Somen', 'Pedia Kenji', 'Pediasure', 'Phát triển giác quan', 'Phô mai', 'Phô mai que', 'Phô mai sấy', 'Phương tiện giao thông', 'Phấn rôm & phấn thơm', 'Phụ  kiện tồn', 'Phụ kiện bình sữa', 'Phụ kiện cho bé', 'Phụ kiện cho mẹ', 'Phụ kiện khác', 'Phụ kiện làm đẹp tồn', 'Pin', 'PreNAN', 'Provital', 'Puff', 'Purelac', 'Quần', 'Quần bé gái', 'Quần bé trai', 'Quần lót tiện lợi', 'Quần, áo & phụ kiện sơ sinh cũ', 'Rascal', 'Rau củ nghiền', 'Rong biển', 'Rắc', 'S26', 'Sandal bé trai', 'Similac', 'Similac Neosure', 'Similac Protection', 'Similac Total Comfort', 'Snack', 'Sweety', 'Sách', 'Sáp thơm', 'Súp', 'Sắt', 'Sức khoẻ nam giới', 'Sữa chua khô', 'Sữa chua uống', 'Sữa chua ăn', 'Sữa hạt khác', 'Sữa non', 'Sữa ong chúa', 'Sữa rửa mặt', 'Sữa tươi thanh trùng', 'Sữa tắm', 'TH Milk', 'Tai mũi họng', 'Takato', 'Thanh cua', 'Thau tắm/ Bô vệ sinh', 'Thiết bị y tế', 'Thạch', 'Thảm chơi & kệ chữ A', 'Thảo dược', 'Thế Giới Động Vật', 'Thịt viên', 'Thời trang bé trai, bé gái cũ', 'Thức uống dinh dưỡng', 'Thử Thai', 'Thực phẩm lợi sữa', 'Tinh dầu hoa anh thảo', 'Tinh dầu thơm', 'Tiệc, Trang trí & Lưu niệm', 'Trà', 'Trà cho bé', 'Trà uống liền', 'Trái cây nghiền', 'Trái cây sấy', 'Trái cây sấy cho bé', 'Trị muỗi, côn trùng', 'Trị mụn & sẹo', 'Trữ sữa', 'Ty ngậm', 'Táo', 'Táo bón', 'Túi xách, Ba lô', 'Tăng cường hệ miễn dịch', 'Tăng cường sức đề kháng', 'Tương & Sốt', 'Tấm lót chống thấm', 'Tẩy trang', 'Tẩy tế bào chết cơ thể', 'Tẩy tế bào chết da mặt', 'Tắm gội cho bé', 'Varna', 'Vinamilk', 'Vinamilk Organic', 'Vitadairy', 'Vitamin C', 'Vitamin D', 'Vitamin E', 'Vitamin mẹ bầu', 'Viên sủi Vitamin', 'Váng sữa', 'Vòng tay, vòng cổ', 'Vận động ngoài trời', 'Vận động trong nhà', 'Vệ sinh & sức khỏe', 'Vệ sinh cơ thể', 'Vệ sinh nhà bếp', 'Wakodo', 'Whito', 'Whoopee', 'XO', 'Xe nhún / Ghế bập bênh', 'Xe tập đi', 'Xe đẩy', 'Xúc xích', 'Xúc xắc', 'Xả vải cho bé', 'Xả vải gia đình', 'Xịt côn trùng', 'Xịt răng miệng', 'Yoko', 'Yếm cho bé', 'Áo', 'Áo bé gái', 'Áo bé trai', 'Áo, Quần đông', 'Óc chó', 'Ăn ngon', 'Đun nước, pha sữa', 'Đầm bé gái', 'Đậu nành', 'Địu', 'Đồ bầu', 'Đồ chơi nhồi bông', 'Đồ chơi nước', 'Đồ dùng bé ngủ cũ', 'Đồ dùng cho mẹ ngừng bán', 'Đồ dùng gia đình', 'Đồ dùng ra ngoài ngừng bán', 'Đồ dùng vệ sinh ngừng bán', 'Đồ dùng ăn uống ngừng bán', 'Đồ hộp']


In [138]:
# Gom vào dictionary
category_dict = {
    "age_group": age_list
}

# In ra theo từng dòng, rất dễ đọc
print("\n=== DANH SÁCH TẤT CẢ CLASS CỦA age_group ===\n")
for key, value in category_dict.items():
    print(f"{key}: {value}\n")

=== DANH SÁCH TẤT CẢ CLASS CỦA age_group ===

age_group: ['0-10M', '0-12M', '0-12Y', '0-18M', '0-1M', '0-24M', '0-2M', '0-36M', '0-3M', '0-4Y', '0-5M', '0-5Y', '0-6M', '0-6Y', '0-9M', '10Y-12Y', '11Y-12Y', '12M-18M', '12M-4Y', '13M-24M', '18M-24M', '18M-36M', '18M-4Y', '1M-12M', '1M-15M', '1M-3M', '1Y-10Y', '1Y-11Y', '1Y-12Y', '1Y-16Y', '1Y-2Y', '1Y-3Y', '1Y-4Y', '1Y-6Y', '1Y-9Y', '2M-15M', '2M-6M', '2Y-10Y', '2Y-3Y', '2Y-6Y', '3M-12M', '3M-18M', '3M-24M', '3M-6M', '3Y-10Y', '3Y-12Y', '3Y-4Y', '3Y-5Y', '3Y-6Y', '4M-4Y', '4M-6M', '4Y-5Y', '5Y-6Y', '6M-10M', '6M-12M', '6M-12Y', '6M-15M', '6M-18M', '6M-24M', '6M-36M', '6M-5Y', '6M-6Y', '6M-9M', '7Y-10Y', '7Y-14Y', '7Y-8Y', '8Y-14Y', '9M-12M', '9M-15M', '9M-20M', '9M-24M', '9M-36M', '9M-4Y', '9M-6Y', '9Y-10Y', 'Không xác định', 'Mẹ', 'Trên 1Y', 'Trên 2Y', 'Trên 3Y', 'Trên 6M', 'Từ 0M', 'Từ 10M', 'Từ 10Y', 'Từ 12Y', 'Từ 13Y', 'Từ 18M', 'Từ 19M', 'Từ 19Y', 'Từ 1M', 'Từ 1Y', 'Từ 2M', 'Từ 2Y', 'Từ 3M', 'Từ 3Y', 'Từ 4M', 'Từ 4Y', 'Từ 5M', 'Từ 5Y', 'Từ 6M', 'Từ 6Y', 'Từ 7M', 'Từ 7Y', 'Từ 8M', 'Từ 9M', '["Từ 0M", "Từ 3M", "Từ 6M"]', '["Từ 0M", "Từ 3M"]', '["Từ 3M", "Từ 6M", "Từ 1Y"]', '["Từ 3M", "Từ 6M", "Từ 9M", "Từ 1Y"]', '["Từ 3M", "Từ 6M", "Từ 9M"]', '["Từ 3M", "Từ 6M"]', '["Từ 6M", "Từ 9M", "Từ 1Y"]']

#### Các `class` của mỗi `category` liên quan đến keyword "mẹ"

In [139]:
import polars as pl

df = df_age  # hoặc df_filled nếu bạn dùng dataframe khác

# === Danh sách bạn cung cấp ===

cat_l2_me = [
    "0-1Y",
    "1Y+",
    "Giày dép 1-3Y",
    "Cho mẹ",
    "Chăm sóc mẹ trước & sau sinh",
    "Gói Hội Viên BẦU",
    "Sữa cho mẹ",
    "TPCN cho mẹ",
    "Đồ dùng cho mẹ",
]

cat_l3_me = [
    "Dung dịch vệ sinh phụ nữ",
    "Gói Hội Viên BẦU",
    "Phụ kiện cho mẹ",
    "Vitamin mẹ bầu",
    "Đồ dùng cho mẹ ngừng bán",
]

cat_me = [
    "Balo, túi cho mẹ",
    "Bàn chải 0-1Y",
    "Bàn chải 1-2Y",
    "Bàn chải 2Y+",
    "Băng vệ sinh Diana sau sinh",
    "Colosbaby Mom",
    "Dung dịch vệ sinh phụ nữ Bimunica",
    "Dung dịch vệ sinh phụ nữ Chilly",
    "Dung dịch vệ sinh phụ nữ Crevil",
    "Dung dịch vệ sinh phụ nữ Felce Azzurra",
    "Dung dịch vệ sinh phụ nữ Fremfesh",
    "Dung dịch vệ sinh phụ nữ Lactacyd",
    "Dung dịch vệ sinh phụ nữ Lovely",
    "Dung dịch vệ sinh phụ nữ SAFORELLE",
    "Enfa Mom",
    "Gói Hội Viên Pink MOM All in",
    "Gói Hội Viên Pink MOM Easy",
    "Gói Hội Viên Pink MOM Upgrade",
    "Hi Mom",
    "Meiji Mom",
    "Miếng lót thấm sữa Aga-ae",
    "Miếng lót thấm sữa ChuchuBaby",
    "Miếng lót thấm sữa Pigeon",
    "Miếng lót thấm sữa ngừng bán",
    "Nịt bụng cho mẹ",
    "Phụ kiện cho mẹ ngừng bán",
    "Quần lót bầu",
    "Quần, áo, đầm bầu",
    "Similac Mom",
    "Vớ cho mẹ",
    "Wakodo Mom",
    "XO Mom",
    "Áo ngực cho mẹ",
]

In [140]:
print("\n=== category_l2: số lượng age_group = 'Không xác định' ===")

stats_l2 = (
    df.filter(
        (pl.col("category_l2").is_in(cat_l2_me))
        & (pl.col("age_group") == "Không xác định")
    )
    .group_by("category_l2")
    .agg(pl.len().alias("count_khong_xac_dinh"))
    .sort("count_khong_xac_dinh", descending=True)
)

print(stats_l2)

=== category_l2: số lượng age_group = 'Không xác định' ===
shape: (9, 2)
┌──────────────────────────────┬──────────────────────┐
│ category_l2                  ┆ count_khong_xac_dinh │
│ ---                          ┆ ---                  │
│ str                          ┆ u32                  │
╞══════════════════════════════╪══════════════════════╡
│ 1Y+                          ┆ 1138                 │
│ 0-1Y                         ┆ 415                  │
│ Giày dép 1-3Y                ┆ 333                  │
│ Đồ dùng cho mẹ               ┆ 54                   │
│ TPCN cho mẹ                  ┆ 44                   │
│ Chăm sóc mẹ trước & sau sinh ┆ 18                   │
│ Cho mẹ                       ┆ 3                    │
│ Gói Hội Viên BẦU             ┆ 3                    │
│ Sữa cho mẹ                   ┆ 1                    │
└──────────────────────────────┴──────────────────────┘

In [141]:
print("\n=== category_l3: số lượng age_group = 'Không xác định' ===")

stats_l3 = (
    df.filter(
        (pl.col("category_l3").is_in(cat_l3_me))
        & (pl.col("age_group") == "Không xác định")
    )
    .group_by("category_l3")
    .agg(pl.len().alias("count_khong_xac_dinh"))
    .sort("count_khong_xac_dinh", descending=True)
)

print(stats_l3)

=== category_l3: số lượng age_group = 'Không xác định' ===
shape: (5, 2)
┌──────────────────────────┬──────────────────────┐
│ category_l3              ┆ count_khong_xac_dinh │
│ ---                      ┆ ---                  │
│ str                      ┆ u32                  │
╞══════════════════════════╪══════════════════════╡
│ Đồ dùng cho mẹ ngừng bán ┆ 26                   │
│ Dung dịch vệ sinh phụ nữ ┆ 12                   │
│ Vitamin mẹ bầu           ┆ 10                   │
│ Phụ kiện cho mẹ          ┆ 3                    │
│ Gói Hội Viên BẦU         ┆ 3                    │
└──────────────────────────┴──────────────────────┘

In [142]:
print("\n=== category (tên chi tiết): số lượng age_group = 'Không xác định' ===")

stats_cat = (
    df.filter(
        (pl.col("category").is_in(cat_me))
        & (pl.col("age_group") == "Không xác định")
    )
    .group_by("category")
    .agg(pl.len().alias("count_khong_xac_dinh"))
    .sort("count_khong_xac_dinh", descending=True)
)

print(stats_cat)

=== category (tên chi tiết): số lượng age_group = 'Không xác định' ===
shape: (29, 2)
┌────────────────────────────────────────┬──────────────────────┐
│ category                               ┆ count_khong_xac_dinh │
│ ---                                    ┆ ---                  │
│ str                                    ┆ u32                  │
╞════════════════════════════════════════╪══════════════════════╡
│ Quần lót bầu                           ┆ 29                   │
│ Bàn chải 2Y+                           ┆ 28                   │
│ Balo, túi cho mẹ                       ┆ 15                   │
│ Bàn chải 0-1Y                          ┆ 10                   │
│ Enfa Mom                               ┆ 8                    │
│ Bàn chải 1-2Y                          ┆ 8                    │
│ Nịt bụng cho mẹ                        ┆ 6                    │
│ Dung dịch vệ sinh phụ nữ Lactacyd      ┆ 4                    │
│ Quần, áo, đầm bầu                      ┆ 4                    │
│ Wakodo Mom                             ┆ 4                    │
│ Vớ cho mẹ                              ┆ 3                    │
│ Dung dịch vệ sinh phụ nữ Felce Azzurra ┆ 2                    │
│ Phụ kiện cho mẹ ngừng bán              ┆ 2                    │
│ Miếng lót thấm sữa Pigeon              ┆ 2                    │
│ Miếng lót thấm sữa ngừng bán           ┆ 2                    │
│ Dung dịch vệ sinh phụ nữ Chilly        ┆ 2                    │
│ Similac Mom                            ┆ 2                    │
│ Dung dịch vệ sinh phụ nữ Fremfesh      ┆ 1                    │
│ Hi Mom                                 ┆ 1                    │
│ Dung dịch vệ sinh phụ nữ Bimunica      ┆ 1                    │
│ Gói Hội Viên Pink MOM Upgrade          ┆ 1                    │
│ Miếng lót thấm sữa Aga-ae              ┆ 1                    │
│ Gói Hội Viên Pink MOM All in           ┆ 1                    │
│ Dung dịch vệ sinh phụ nữ SAFORELLE     ┆ 1                    │
│ Dung dịch vệ sinh phụ nữ Crevil        ┆ 1                    │
│ Miếng lót thấm sữa ChuchuBaby          ┆ 1                    │
│ Băng vệ sinh Diana sau sinh            ┆ 1                    │
│ Gói Hội Viên Pink MOM Easy             ┆ 1                    │
│ Meiji Mom                              ┆ 1                    │
└────────────────────────────────────────┴──────────────────────┘

In [143]:
import polars as pl

df = df_age   # hoặc df_filled nếu bạn dùng dataframe khác

cat_l2_me = [
    "0-1Y",
    "1Y+",
    "Giày dép 1-3Y",
    "Cho mẹ",
    "Chăm sóc mẹ trước & sau sinh",
    "Gói Hội Viên BẦU",
    "Sữa cho mẹ",
    "TPCN cho mẹ",
    "Đồ dùng cho mẹ",
]

cat_l3_me = [
    "Dung dịch vệ sinh phụ nữ",
    "Gói Hội Viên BẦU",
    "Phụ kiện cho mẹ",
    "Vitamin mẹ bầu",
    "Đồ dùng cho mẹ ngừng bán",
]

cat_me = [
    "Balo, túi cho mẹ",
    "Bàn chải 0-1Y",
    "Bàn chải 1-2Y",
    "Bàn chải 2Y+",
    "Băng vệ sinh Diana sau sinh",
    "Colosbaby Mom",
    "Dung dịch vệ sinh phụ nữ Bimunica",
    "Dung dịch vệ sinh phụ nữ Chilly",
    "Dung dịch vệ sinh phụ nữ Crevil",
    "Dung dịch vệ sinh phụ nữ Felce Azzurra",
    "Dung dịch vệ sinh phụ nữ Fremfesh",
    "Dung dịch vệ sinh phụ nữ Lactacyd",
    "Dung dịch vệ sinh phụ nữ Lovely",
    "Dung dịch vệ sinh phụ nữ SAFORELLE",
    "Enfa Mom",
    "Gói Hội Viên Pink MOM All in",
    "Gói Hội Viên Pink MOM Easy",
    "Gói Hội Viên Pink MOM Upgrade",
    "Hi Mom",
    "Meiji Mom",
    "Miếng lót thấm sữa Aga-ae",
    "Miếng lót thấm sữa ChuchuBaby",
    "Miếng lót thấm sữa Pigeon",
    "Miếng lót thấm sữa ngừng bán",
    "Nịt bụng cho mẹ",
    "Phụ kiện cho mẹ ngừng bán",
    "Quần lót bầu",
    "Quần, áo, đầm bầu",
    "Similac Mom",
    "Vớ cho mẹ",
    "Wakodo Mom",
    "XO Mom",
    "Áo ngực cho mẹ",
]

# =============================
# TẠO DATAFRAME GỘP TẤT CẢ CLASS MẸ CÓ age_group = "Không xác định"
# =============================
df_me_unknown = (
    df.filter(
        (pl.col("age_group") == "Không xác định")
        & (
            pl.col("category_l2").is_in(cat_l2_me)
            | pl.col("category_l3").is_in(cat_l3_me)
            | pl.col("category").is_in(cat_me)
        )
    )
)

print(df_me_unknown)
print("\nSố dòng:", df_me_unknown.height)

shape: (2_116, 14)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ item_id   ┆ price     ┆ category_ ┆ category_ ┆ … ┆ item_type ┆ descripti ┆ gender_ta ┆ age_grou │
│ ---       ┆ ---       ┆ l1        ┆ l2        ┆   ┆ ---       ┆ on_new    ┆ rget_fina ┆ p_final  │
│ str       ┆ decimal[3 ┆ ---       ┆ ---       ┆   ┆ str       ┆ ---       ┆ l         ┆ ---      │
│           ┆ 8,4]      ┆ str       ┆ str       ┆   ┆           ┆ str       ┆ ---       ┆ str      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ str       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 000801000 ┆ 45000.000 ┆ Đồ chơi & ┆ 0-1Y      ┆ … ┆ Không xác ┆ Chi tiết  ┆ Không xác ┆ Không    │
│ 0015      ┆ 0         ┆ Sách      ┆           ┆   ┆ định      ┆ sản phẩm  ┆ định      ┆ xác định │
│           ┆           ┆           ┆           ┆   ┆           ┆ Tên sản   ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ phẩm…     ┆           ┆          │
│ 000818000 ┆ 425000.00 ┆ Đồ chơi & ┆ 0-1Y      ┆ … ┆ Không xác ┆ Chi tiết  ┆ Không xác ┆ Không    │
│ 0017      ┆ 00        ┆ Sách      ┆           ┆   ┆ định      ┆ sản phẩm  ┆ định      ┆ xác định │
│           ┆           ┆           ┆           ┆   ┆           ┆ Tên sản   ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ phẩm…     ┆           ┆          │
│ 000817000 ┆ 69000.000 ┆ Đồ chơi & ┆ 0-1Y      ┆ … ┆ Không xác ┆ Chi tiết  ┆ Không xác ┆ Không    │
│ 0021      ┆ 0         ┆ Sách      ┆           ┆   ┆ định      ┆ sản phẩm  ┆ định      ┆ xác định │
│           ┆           ┆           ┆           ┆   ┆           ┆ Tên sản   ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ phẩm…     ┆           ┆          │
│ 000802000 ┆ 108000.00 ┆ Đồ chơi & ┆ 0-1Y      ┆ … ┆ Thú nhồi  ┆ Không xác ┆ Không xác ┆ Không    │
│ 0220      ┆ 00        ┆ Sách      ┆           ┆   ┆ bông      ┆ định      ┆ định      ┆ xác định │
│ 000804000 ┆ 345000.00 ┆ Đồ chơi & ┆ 1Y+       ┆ … ┆ Không xác ┆ Chi tiết  ┆ Không xác ┆ Không    │
│ 0040      ┆ 00        ┆ Sách      ┆           ┆   ┆ định      ┆ sản phẩm  ┆ định      ┆ xác định │
│           ┆           ┆           ┆           ┆   ┆           ┆ Tên sản   ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ phẩm…     ┆           ┆          │
│ 210200000 ┆ 790000.00 ┆ Đồ chơi & ┆ 1Y+       ┆ … ┆ Scooter   ┆ Chi tiết  ┆ Không xác ┆ Không    │
│ 0002      ┆ 00        ┆ Sách      ┆           ┆   ┆           ┆ sản       ┆ định      ┆ xác định │
│           ┆           ┆           ┆           ┆   ┆           ┆ phẩmTên   ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ sản phẩm: ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ Xe        ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ scooter 2 ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ bánh E…   ┆           ┆          │
│ 207400000 ┆ 195000.00 ┆ Đồ chơi & ┆ 1Y+       ┆ … ┆ Bóng,     ┆ Chi tiết  ┆ Không xác ┆ Không    │
│ 0004      ┆ 00        ┆ Sách      ┆           ┆   ┆ banh nhà  ┆ sản phẩm  ┆ định      ┆ xác định │
│           ┆           ┆           ┆           ┆   ┆ banh      ┆ Tên sản   ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ phẩm…     ┆           ┆          │
│ 000817000 ┆ 65000.000 ┆ Đồ chơi & ┆ 0-1Y      ┆ … ┆ Không xác ┆ Chi tiết  ┆ Không xác ┆ Không    │
│ 0052      ┆ 0         ┆ Sách      ┆           ┆   ┆ định      ┆ sản phẩm  ┆ định      ┆ xác định │
│           ┆           ┆           ┆           ┆   ┆           ┆ Tên sản   ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ phẩm…     ┆           ┆          │
│ 002001000 ┆ 219000.00 ┆ Sữa       ┆ Wakodo    ┆ … ┆ Sữa bầu   ┆ Không xác ┆ Không xác ┆ Không    │
│ 0492      ┆ 00        ┆           ┆           ┆   ┆           ┆ định      ┆ định      ┆ xác định │
│ 000929000 ┆ 169000.00 ┆ Đồ chơi & ┆ 1Y+       ┆ … ┆ Không xác ┆ Chi tiết  ┆ Không xác ┆ Không    │
│ 0249      ┆ 00        ┆ Sách      ┆           ┆   ┆ định      ┆ sản phẩm  ┆ định      ┆ xác định │
│           ┆           ┆           ┆           ┆   ┆           ┆ Tên sản   ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ phẩm…     ┆           ┆          │
│ 000921000 ┆ 59000.000 ┆ Đồ chơi & ┆ 1Y+       ┆ … ┆ Không xác ┆ Chi tiết  ┆ Không xác ┆ Không    │
│ 0020      ┆ 0         ┆ Sách      ┆           ┆   ┆ định      ┆ sản phẩm  ┆ định      ┆ xác định │
│           ┆           ┆           ┆           ┆   ┆           ┆ Tên sản   ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ phẩm…     ┆           ┆          │
│ 000921000 ┆ 169000.00 ┆ Đồ chơi & ┆ 1Y+       ┆ … ┆ Không xác ┆ Chi tiết  ┆ Không xác ┆ Không    │
│ 0103      ┆ 00        ┆ Sách      ┆           ┆   ┆ định      ┆ sản phẩm  ┆ định      ┆ xác định │
│           ┆           ┆           ┆           ┆   ┆           ┆ Tên sản   ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ phẩm…     ┆           ┆          │
│ 000803000 ┆ 950000.00 ┆ Đồ chơi & ┆ 1Y+       ┆ … ┆ Xe đạp,   ┆ Chi tiết  ┆ Không xác ┆ Không    │
│ 0252      ┆ 00        ┆ Sách      ┆           ┆   ┆ xe 3 bánh ┆ sản phẩm  ┆ định      ┆ xác định │
│           ┆           ┆           ┆           ┆   ┆           ┆ Tên sản   ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ phẩm…     ┆           ┆          │
│ 000817000 ┆ 89000.000 ┆ Đồ chơi & ┆ 0-1Y      ┆ … ┆ Không xác ┆ Chi tiết  ┆ Không xác ┆ Không    │
│ 0251      ┆ 0         ┆ Sách      ┆           ┆   ┆ định      ┆ sản phẩm  ┆ định      ┆ xác định │
│           ┆           ┆           ┆           ┆   ┆           ┆ Tên sản   ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ phẩm…     ┆           ┆          │
│ 000803000 ┆ 2790000.0 ┆ Đồ chơi & ┆ 1Y+       ┆ … ┆ Xe đạp,   ┆ Chi tiết  ┆ Không xác ┆ Không    │
│ 0102      ┆ 000       ┆ Sách      ┆           ┆   ┆ xe 3 bánh ┆ sản phẩm  ┆ định      ┆ xác định │
│           ┆           ┆           ┆           ┆   ┆           ┆ Tên sản   ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ phẩm…     ┆           ┆          │
│ 000925000 ┆ 199000.00 ┆ Đồ chơi & ┆ 1Y+       ┆ … ┆ Không xác ┆ Chi tiết  ┆ Không xác ┆ Không    │
│ 0229      ┆ 00        ┆ Sách      ┆           ┆   ┆ định      ┆ sản phẩm  ┆ định      ┆ xác định │
│           ┆           ┆           ┆           ┆   ┆           ┆ Tên sản   ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ phẩm…     ┆           ┆          │
│ 000817000 ┆ 69000.000 ┆ Đồ chơi & ┆ 0-1Y      ┆ … ┆ Không xác ┆ Không xác ┆ Không xác ┆ Không    │
│ 0010      ┆ 0         ┆ Sách      ┆           ┆   ┆ định      ┆ định      ┆ định      ┆ xác định │
│ 000028000 ┆ 195000.00 ┆ Đồ chơi & ┆ 1Y+       ┆ … ┆ Không xác ┆ null      ┆ Không xác ┆ Không    │
│ 0114      ┆ 00        ┆ Sách      ┆           ┆   ┆ định      ┆           ┆ định      ┆ xác định │
│ 234600000 ┆ 35000.000 ┆ Đồ chơi & ┆ 1Y+       ┆ … ┆ Đồ chơi   ┆ Chi tiết  ┆ Không xác ┆ Không    │
│ 0035      ┆ 0         ┆ Sách      ┆           ┆   ┆ ghép      ┆ sản phẩm  ┆ định      ┆ xác định │
│           ┆           ┆           ┆           ┆   ┆ hình, xếp ┆ Tên sản   ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ hình, lắp ┆ phẩm…     ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆ ráp       ┆           ┆           ┆          │
│ 429600000 ┆ 139000.00 ┆ Đồ chơi & ┆ 1Y+       ┆ … ┆ Nhập vai  ┆ Chi tiết  ┆ Không xác ┆ Không    │
│ 0005      ┆ 00        ┆ Sách      ┆           ┆   ┆           ┆ sản       ┆ định      ┆ xác định │
│           ┆           ┆           ┆           ┆   ┆           ┆ phẩmTên   ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ sản phẩm: ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ Túi xách  ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ nhập vai  ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ b…        ┆           ┆          │
│ 000803004 ┆ 1090000.0 ┆ Đồ chơi & ┆ 1Y+       ┆ … ┆ Không xác ┆ Chi tiết  ┆ Không xác ┆ Không    │
│ 0002      ┆ 000       ┆ Sách      ┆           ┆   ┆ định      ┆ sản phẩm  ┆ định      ┆ xác định │
│           ┆           ┆           ┆           ┆   ┆           ┆ Tên sản   ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ phẩm…     ┆           ┆          │
│ 401400000 ┆ 165000.00 ┆ Phụ kiện  ┆ Giày dép  ┆ … ┆ Dép sục   ┆ Chi tiết  ┆ Không xác ┆ Không    │
│ 0013      ┆ 00        ┆           ┆ 1-3Y      ┆   ┆           ┆ sản phẩm  ┆ định      ┆ xác định │
│           ┆           ┆           ┆           ┆   ┆           ┆ Tên sản   ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ phẩm…     ┆           ┆          │
│ 000934000 ┆ 115000.00 ┆ Đồ chơi & ┆ 1Y+       ┆ … ┆ Bóng,     ┆ Chi tiết  ┆ Không xác ┆ Không    │
│ 0004      ┆ 00        ┆ Sách      ┆           ┆   ┆ banh nhà  ┆ sản phẩm  ┆ định      ┆ xác định │
│           ┆           ┆           ┆           ┆   ┆ banh      ┆ Tên sản   ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ phẩm…     ┆           ┆          │
│ 000716000 ┆ 21000.000 ┆ Babycare  ┆ Đồ dùng   ┆ … ┆ Không xác ┆ Chi tiết  ┆ Không xác ┆ Không    │
│ 0012      ┆ 0         ┆           ┆ vệ sinh   ┆   ┆ định      ┆ sản phẩm  ┆ định      ┆ xác định │
│           ┆           ┆           ┆           ┆   ┆           ┆ Tên sản   ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ phẩm…     ┆           ┆          │
│ 000716000 ┆ 169000.00 ┆ Babycare  ┆ Đồ dùng   ┆ … ┆ Không xác ┆ Chi tiết  ┆ Không xác ┆ Không    │
│ 0039      ┆ 00        ┆           ┆ vệ sinh   ┆   ┆ định      ┆ sản phẩm  ┆ định      ┆ xác định │
│           ┆           ┆           ┆           ┆   ┆           ┆ Tên sản   ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ phẩm…     ┆           ┆          │
│ …         ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 095000000 ┆ 165000.00 ┆ Phụ kiện  ┆ Giày dép  ┆ … ┆ Dép sục   ┆ Chi tiết  ┆ Bé Trai   ┆ Không    │
│ 0051      ┆ 00        ┆           ┆ 1-3Y      ┆   ┆           ┆ sản phẩm  ┆           ┆ xác định │
│           ┆           ┆           ┆           ┆   ┆           ┆ Tên sản   ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ phẩm…     ┆           ┆          │
│ 686700000 ┆ 480000.00 ┆ TPCN      ┆ TPCN cho  ┆ … ┆ Không xác ┆ Chi tiết  ┆ Không xác ┆ Không    │
│ 0001      ┆ 00        ┆           ┆ mẹ        ┆   ┆ định      ┆ sản phẩm  ┆ định      ┆ xác định │
│           ┆           ┆           ┆           ┆   ┆           ┆ Tên sản   ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ phẩm:     ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ Thực…     ┆           ┆          │
│ 092100000 ┆ 195000.00 ┆ Phụ kiện  ┆ Giày dép  ┆ … ┆ Sandal    ┆ Không xác ┆ Bé Trai   ┆ Không    │
│ 0089      ┆ 00        ┆           ┆ 1-3Y      ┆   ┆           ┆ định      ┆           ┆ xác định │
│ 092100000 ┆ 195000.00 ┆ Phụ kiện  ┆ Giày dép  ┆ … ┆ Sandal    ┆ Không xác ┆ Bé Trai   ┆ Không    │
│ 0094      ┆ 00        ┆           ┆ 1-3Y      ┆   ┆           ┆ định      ┆           ┆ xác định │
│ 096600000 ┆ 195000.00 ┆ Phụ kiện  ┆ Giày dép  ┆ … ┆ Sandal    ┆ Chi tiết  ┆ Bé Trai   ┆ Không    │
│ 0029      ┆ 00        ┆           ┆ 1-3Y      ┆   ┆           ┆ sản phẩm  ┆           ┆ xác định │
│           ┆           ┆           ┆           ┆   ┆           ┆ Tên sản   ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ phẩm…     ┆           ┆          │
│ 094900000 ┆ 189000.00 ┆ Phụ kiện  ┆ Giày dép  ┆ … ┆ Dép sục   ┆ Xin lỗi,  ┆ Bé Gái    ┆ Không    │
│ 0031      ┆ 00        ┆           ┆ 1-3Y      ┆   ┆           ┆ nhưng tôi ┆           ┆ xác định │
│           ┆           ┆           ┆           ┆   ┆           ┆ không thể ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ thực hiện ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ yêu cầu   ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ này…      ┆           ┆          │
│ 095000000 ┆ 189000.00 ┆ Phụ kiện  ┆ Giày dép  ┆ … ┆ Dép sục   ┆ Chi tiết  ┆ Không xác ┆ Không    │
│ 0059      ┆ 00        ┆           ┆ 1-3Y      ┆   ┆           ┆ sản phẩm  ┆ định      ┆ xác định │
│           ┆           ┆           ┆           ┆   ┆           ┆ Tên sản   ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ phẩm…     ┆           ┆          │
│ 095700000 ┆ 165000.00 ┆ Phụ kiện  ┆ Giày dép  ┆ … ┆ Dép sục   ┆ Chi tiết  ┆ Bé Gái    ┆ Không    │
│ 0065      ┆ 00        ┆           ┆ 1-3Y      ┆   ┆           ┆ sản phẩm  ┆           ┆ xác định │
│           ┆           ┆           ┆           ┆   ┆           ┆ Tên sản   ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ phẩm…     ┆           ┆          │
│ 095800000 ┆ 165000.00 ┆ Phụ kiện  ┆ Giày dép  ┆ … ┆ Dép sục   ┆ Chi tiết  ┆ Bé Gái    ┆ Không    │
│ 0051      ┆ 00        ┆           ┆ 1-3Y      ┆   ┆           ┆ sản phẩm  ┆           ┆ xác định │
│           ┆           ┆           ┆           ┆   ┆           ┆ Tên sản   ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ phẩm…     ┆           ┆          │
│ 713700000 ┆ 595000.00 ┆ TPCN      ┆ TPCN cho  ┆ … ┆ Không xác ┆ Không xác ┆ Không xác ┆ Không    │
│ 0002      ┆ 00        ┆           ┆ mẹ        ┆   ┆ định      ┆ định      ┆ định      ┆ xác định │
│ 091900000 ┆ 229000.00 ┆ Phụ kiện  ┆ Giày dép  ┆ … ┆ Sandal    ┆ Chi tiết  ┆ Bé Trai   ┆ Không    │
│ 0125      ┆ 00        ┆           ┆ 1-3Y      ┆   ┆           ┆ sản phẩm  ┆           ┆ xác định │
│           ┆           ┆           ┆           ┆   ┆           ┆ Tên sản   ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ phẩm…     ┆           ┆          │
│ 092100000 ┆ 195000.00 ┆ Phụ kiện  ┆ Giày dép  ┆ … ┆ Sandal    ┆ Chi tiết  ┆ Bé Trai   ┆ Không    │
│ 0097      ┆ 00        ┆           ┆ 1-3Y      ┆   ┆           ┆ sản phẩm  ┆           ┆ xác định │
│           ┆           ┆           ┆           ┆   ┆           ┆ Tên sản   ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ phẩm…     ┆           ┆          │
│ 095700000 ┆ 165000.00 ┆ Phụ kiện  ┆ Giày dép  ┆ … ┆ Dép sục   ┆ Chi tiết  ┆ Bé Trai   ┆ Không    │
│ 0073      ┆ 00        ┆           ┆ 1-3Y      ┆   ┆           ┆ sản phẩm  ┆           ┆ xác định │
│           ┆           ┆           ┆           ┆   ┆           ┆ Tên sản   ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ phẩm…     ┆           ┆          │
│ 095700000 ┆ 165000.00 ┆ Phụ kiện  ┆ Giày dép  ┆ … ┆ Không xác ┆ Chi tiết  ┆ Không xác ┆ Không    │
│ 0071      ┆ 00        ┆           ┆ 1-3Y      ┆   ┆ định      ┆ sản phẩm  ┆ định      ┆ xác định │
│           ┆           ┆           ┆           ┆   ┆           ┆ Tên sản   ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ phẩm…     ┆           ┆          │
│ 091900000 ┆ 195000.00 ┆ Phụ kiện  ┆ Giày dép  ┆ … ┆ Sandal    ┆ Chi tiết  ┆ Bé Trai   ┆ Không    │
│ 0118      ┆ 00        ┆           ┆ 1-3Y      ┆   ┆           ┆ sản phẩm  ┆           ┆ xác định │
│           ┆           ┆           ┆           ┆   ┆           ┆ Tên sản   ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ phẩm…     ┆           ┆          │
│ 091900000 ┆ 195000.00 ┆ Phụ kiện  ┆ Giày dép  ┆ … ┆ Sandal    ┆ Chi tiết  ┆ Bé Trai   ┆ Không    │
│ 0120      ┆ 00        ┆           ┆ 1-3Y      ┆   ┆           ┆ sản phẩm  ┆           ┆ xác định │
│           ┆           ┆           ┆           ┆   ┆           ┆ Tên sản   ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ phẩm…     ┆           ┆          │
│ 208600000 ┆ 229000.00 ┆ Phụ kiện  ┆ Giày dép  ┆ … ┆ Sandal    ┆ Chi tiết  ┆ Bé Gái    ┆ Không    │
│ 0021      ┆ 00        ┆           ┆ 1-3Y      ┆   ┆           ┆ sản phẩm  ┆           ┆ xác định │
│           ┆           ┆           ┆           ┆   ┆           ┆ Tên sản   ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ phẩm…     ┆           ┆          │
│ 208600000 ┆ 229000.00 ┆ Phụ kiện  ┆ Giày dép  ┆ … ┆ Sandal    ┆ Chi tiết  ┆ Bé Gái    ┆ Không    │
│ 0023      ┆ 00        ┆           ┆ 1-3Y      ┆   ┆           ┆ sản phẩm  ┆           ┆ xác định │
│           ┆           ┆           ┆           ┆   ┆           ┆ Tên sản   ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ phẩm…     ┆           ┆          │
│ 096600000 ┆ 185000.00 ┆ Phụ kiện  ┆ Giày dép  ┆ … ┆ Sandal    ┆ Chi tiết  ┆ Bé Trai   ┆ Không    │
│ 0017      ┆ 00        ┆           ┆ 1-3Y      ┆   ┆           ┆ sản phẩm  ┆           ┆ xác định │
│           ┆           ┆           ┆           ┆   ┆           ┆ Tên sản   ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ phẩm…     ┆           ┆          │
│ 095700000 ┆ 165000.00 ┆ Phụ kiện  ┆ Giày dép  ┆ … ┆ Dép sục   ┆ Không xác ┆ Không xác ┆ Không    │
│ 0080      ┆ 00        ┆           ┆ 1-3Y      ┆   ┆           ┆ định      ┆ định      ┆ xác định │
│ 204400000 ┆ 175000.00 ┆ Đồ chơi & ┆ 1Y+       ┆ … ┆ Không xác ┆ Chi tiết  ┆ Không xác ┆ Không    │
│ 0228      ┆ 00        ┆ Sách      ┆           ┆   ┆ định      ┆ sản phẩm  ┆ định      ┆ xác định │
│           ┆           ┆           ┆           ┆   ┆           ┆ Tên sản   ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ phẩm…     ┆           ┆          │
│ 427900000 ┆ 175000.00 ┆ Đồ chơi & ┆ 0-1Y      ┆ … ┆ Không xác ┆ Chi tiết  ┆ Không xác ┆ Không    │
│ 0134      ┆ 00        ┆ Sách      ┆           ┆   ┆ định      ┆ sản       ┆ định      ┆ xác định │
│           ┆           ┆           ┆           ┆   ┆           ┆ phẩmTên   ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ sản       ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ phẩm:Bộ   ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ câu cá    ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ hình xe   ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ mặ…       ┆           ┆          │
│ 427900000 ┆ 185000.00 ┆ Đồ chơi & ┆ 0-1Y      ┆ … ┆ Không xác ┆ Chi tiết  ┆ Không xác ┆ Không    │
│ 0136      ┆ 00        ┆ Sách      ┆           ┆   ┆ định      ┆ sản phẩm  ┆ định      ┆ xác định │
│           ┆           ┆           ┆           ┆   ┆           ┆ Tên sản   ┆           ┆          │

#### Fill các `class` của mỗi `category` trên vào cột `age_group`
-> Ngoài ra còn nhận thấy cột `gender_target` cũng có nhiều giá trị "không xác định" tại các giá trị class này -> đề xuất thêm một `gender_target` là `Phụ Nữ`

Fill giá trị "Mẹ"
Rule:

- Fill age_group_final = "Mẹ" nếu:

    1. age_group_final hiện tại = "Không xác định" và

    2. Một trong các điều kiện sau:

        - category ∈
        "Băng vệ sinh Abena sau sinh",
        "Băng vệ sinh Goodfeel"

        - HOẶC category == "Băng vệ sinh khác" và description chứa "Laurier Happy Skin".

In [144]:
import polars as pl

# ==========================================
# 0) KHỞI TẠO age_group_final
# ==========================================
df_age = df_filled.with_columns(
    pl.col("age_group").alias("age_group_final")
)

# ==========================================
# 1) THỐNG KÊ TRƯỚC KHI FILL
# ==========================================
total_rows = df_age.height

unknown_before = df_age.filter(
    pl.col("age_group_final") == "Không xác định"
).height

ratio_before = unknown_before / total_rows * 100

print("=== TRƯỚC KHI FILL AGE_GROUP ===")
print(f"Số dòng 'Không xác định': {unknown_before:,} / {total_rows:,} "
      f"({ratio_before:.2f}%)")

# ==========================================
# 2) KHAI BÁO CÁC CLASS LIÊN QUAN ĐẾN MẸ
# ==========================================

cat_l2_me = [
    "0-1Y",
    "1Y+",
    "Giày dép 1-3Y",
    "Cho mẹ",
    "Chăm sóc mẹ trước & sau sinh",
    "Gói Hội Viên BẦU",
    "Sữa cho mẹ",
    "TPCN cho mẹ",
    "Đồ dùng cho mẹ",
]

cat_l3_me = [
    "Dung dịch vệ sinh phụ nữ",
    "Gói Hội Viên BẦU",
    "Phụ kiện cho mẹ",
    "Vitamin mẹ bầu",
    "Đồ dùng cho mẹ ngừng bán",
]

cat_me = [
    "Balo, túi cho mẹ",
    "Bàn chải 0-1Y",
    "Bàn chải 1-2Y",
    "Bàn chải 2Y+",
    "Băng vệ sinh Diana sau sinh",
    "Băng vệ sinh Abena sau sinh",
    "Băng vệ sinh Goodfeel",
    "Colosbaby Mom",
    "Dung dịch vệ sinh phụ nữ Bimunica",
    "Dung dịch vệ sinh phụ nữ Chilly",
    "Dung dịch vệ sinh phụ nữ Crevil",
    "Dung dịch vệ sinh phụ nữ Felce Azzurra",
    "Dung dịch vệ sinh phụ nữ Fremfesh",
    "Dung dịch vệ sinh phụ nữ Lactacyd",
    "Dung dịch vệ sinh phụ nữ Lovely",
    "Dung dịch vệ sinh phụ nữ SAFORELLE",
    "Enfa Mom",
    "Gói Hội Viên Pink MOM All in",
    "Gói Hội Viên Pink MOM Easy",
    "Gói Hội Viên Pink MOM Upgrade",
    "Hi Mom",
    "Meiji Mom",
    "Miếng lót thấm sữa Aga-ae",
    "Miếng lót thấm sữa ChuchuBaby",
    "Miếng lót thấm sữa Pigeon",
    "Miếng lót thấm sữa ngừng bán",
    "Nịt bụng cho mẹ",
    "Phụ kiện cho mẹ ngừng bán",
    "Quần lót bầu",
    "Quần, áo, đầm bầu",
    "Similac Mom",
    "Vớ cho mẹ",
    "Wakodo Mom",
    "XO Mom",
    "Áo ngực cho mẹ",
]

# Chỉ fill cho các dòng hiện đang "Không xác định"
base_mask_unknown = pl.col("age_group_final") == "Không xác định"

# ==========================================
# 3) FILL CÁC CLASS CÓ MỐC TUỔI RÕ RÀNG
#    3.1. Từ category (Bàn chải ...)
# ==========================================

mask_cat_brush_01 = base_mask_unknown & (pl.col("category") == "Bàn chải 0-1Y")
mask_cat_brush_12 = base_mask_unknown & (pl.col("category") == "Bàn chải 1-2Y")
mask_cat_brush_2p = base_mask_unknown & (pl.col("category") == "Bàn chải 2Y+")

df_age = df_age.with_columns(
    pl.when(mask_cat_brush_01)
      .then(pl.lit("0-1Y"))
      .when(mask_cat_brush_12)
      .then(pl.lit("1-2Y"))
      .when(mask_cat_brush_2p)
      .then(pl.lit("2Y+"))
      .otherwise(pl.col("age_group_final"))
      .alias("age_group_final")
)

# ==========================================
#    3.2. Từ category_l2 (0-1Y, 1Y+, Giày dép 1-3Y)
# ==========================================

# Cập nhật lại base_mask_unknown sau lần fill trên
base_mask_unknown = pl.col("age_group_final") == "Không xác định"

mask_l2_01 = base_mask_unknown & (pl.col("category_l2") == "0-1Y")
mask_l2_1p = base_mask_unknown & (pl.col("category_l2") == "1Y+")
mask_l2_shoes_13 = base_mask_unknown & (pl.col("category_l2") == "Giày dép 1-3Y")

df_age = df_age.with_columns(
    pl.when(mask_l2_01)
      .then(pl.lit("0-1Y"))
      .when(mask_l2_1p)
      .then(pl.lit("Từ 1Y"))   # theo yêu cầu: 1Y+ → "Từ 1Y"
      .when(mask_l2_shoes_13)
      .then(pl.lit("1-3Y"))
      .otherwise(pl.col("age_group_final"))
      .alias("age_group_final")
)

# ==========================================
# 4) FILL CÁC CLASS LIÊN QUAN ĐẾN "MẸ"
#    (ngoại trừ các class tuổi đã fill vì giờ chúng không còn "Không xác định")
# ==========================================

base_mask_unknown = pl.col("age_group_final") == "Không xác định"

mask_laurier = (
    base_mask_unknown
    & (pl.col("category") == "Băng vệ sinh khác")
    & pl.col("description").str.contains("Laurier Happy Skin", literal=False)
)

mask_me = base_mask_unknown & (
    pl.col("category_l2").is_in(cat_l2_me)
    | pl.col("category_l3").is_in(cat_l3_me)
    | pl.col("category").is_in(cat_me)
)

mask_me_all = mask_me | mask_laurier

df_age = df_age.with_columns(
    pl.when(mask_me_all)
      .then(pl.lit("Mẹ"))
      .otherwise(pl.col("age_group_final"))
      .alias("age_group_final")
)

# ==========================================
# 5) THỐNG KÊ SAU KHI FILL
# ==========================================

unknown_after = df_age.filter(
    pl.col("age_group_final") == "Không xác định"
).height

ratio_after = unknown_after / total_rows * 100

print("\n=== SAU KHI FILL AGE_GROUP (TUỔI + MẸ) ===")
print(f"Số dòng 'Không xác định': {unknown_after:,} / {total_rows:,} "
      f"({ratio_after:.2f}%)")

# Nếu muốn xem nhanh các dòng đã được fill từ "Không xác định" → khác:
df_filled_age_changes = df_age.filter(
    (pl.col("age_group") == "Không xác định")
    & (pl.col("age_group_final") != "Không xác định")
)

print("\nSố dòng được fill từ 'Không xác định' → giá trị khác:",
      df_filled_age_changes.height)
print("\n5 dòng mẫu đã được fill:")
print(df_filled_age_changes.head(5))

=== TRƯỚC KHI FILL AGE_GROUP ===
Số dòng 'Không xác định': 15,803 / 27,323 (57.84%)

=== SAU KHI FILL AGE_GROUP (TUỔI + MẸ) ===
Số dòng 'Không xác định': 13,681 / 27,323 (50.07%)

Số dòng được fill từ 'Không xác định' → giá trị khác: 2122

5 dòng mẫu đã được fill:
shape: (5, 14)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ item_id   ┆ price     ┆ category_ ┆ category_ ┆ … ┆ item_type ┆ descripti ┆ gender_ta ┆ age_grou │
│ ---       ┆ ---       ┆ l1        ┆ l2        ┆   ┆ ---       ┆ on_new    ┆ rget_fina ┆ p_final  │
│ str       ┆ decimal[3 ┆ ---       ┆ ---       ┆   ┆ str       ┆ ---       ┆ l         ┆ ---      │
│           ┆ 8,4]      ┆ str       ┆ str       ┆   ┆           ┆ str       ┆ ---       ┆ str      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ str       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 000801000 ┆ 45000.000 ┆ Đồ chơi & ┆ 0-1Y      ┆ … ┆ Không xác ┆ Chi tiết  ┆ Không xác ┆ 0-1Y     │
│ 0015      ┆ 0         ┆ Sách      ┆           ┆   ┆ định      ┆ sản phẩm  ┆ định      ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ Tên sản   ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ phẩm…     ┆           ┆          │
│ 000818000 ┆ 425000.00 ┆ Đồ chơi & ┆ 0-1Y      ┆ … ┆ Không xác ┆ Chi tiết  ┆ Không xác ┆ 0-1Y     │
│ 0017      ┆ 00        ┆ Sách      ┆           ┆   ┆ định      ┆ sản phẩm  ┆ định      ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ Tên sản   ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ phẩm…     ┆           ┆          │
│ 000817000 ┆ 69000.000 ┆ Đồ chơi & ┆ 0-1Y      ┆ … ┆ Không xác ┆ Chi tiết  ┆ Không xác ┆ 0-1Y     │
│ 0021      ┆ 0         ┆ Sách      ┆           ┆   ┆ định      ┆ sản phẩm  ┆ định      ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ Tên sản   ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ phẩm…     ┆           ┆          │
│ 000802000 ┆ 108000.00 ┆ Đồ chơi & ┆ 0-1Y      ┆ … ┆ Thú nhồi  ┆ Không xác ┆ Không xác ┆ 0-1Y     │
│ 0220      ┆ 00        ┆ Sách      ┆           ┆   ┆ bông      ┆ định      ┆ định      ┆          │
│ 000804000 ┆ 345000.00 ┆ Đồ chơi & ┆ 1Y+       ┆ … ┆ Không xác ┆ Chi tiết  ┆ Không xác ┆ Từ 1Y    │
│ 0040      ┆ 00        ┆ Sách      ┆           ┆   ┆ định      ┆ sản phẩm  ┆ định      ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ Tên sản   ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ phẩm…     ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

#### Lọc tất cả các dòng có category chứa cụm “Băng vệ sinh” để soi và tiếp tục thiết kế rule fill.

In [145]:
import polars as pl

# 1) Lọc tất cả dòng có 'Băng vệ sinh' trong category
df_bangveSinh = (
    df_age
    .filter(
        pl.col("category").str.contains("Băng vệ sinh", literal=False)
    )
)

print("\n=== TẤT CẢ DÒNG CÓ 'Băng vệ sinh' TRONG category ===")
print("\nSố dòng:", df_bangveSinh.height)
df_bangveSinh.head()

=== TẤT CẢ DÒNG CÓ 'Băng vệ sinh' TRONG category ===

Số dòng: 32

shape: (5, 14)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ item_id   ┆ price     ┆ category_ ┆ category_ ┆ … ┆ item_type ┆ descripti ┆ gender_ta ┆ age_grou │
│ ---       ┆ ---       ┆ l1        ┆ l2        ┆   ┆ ---       ┆ on_new    ┆ rget_fina ┆ p_final  │
│ str       ┆ decimal[3 ┆ ---       ┆ ---       ┆   ┆ str       ┆ ---       ┆ l         ┆ ---      │
│           ┆ 8,4]      ┆ str       ┆ str       ┆   ┆           ┆ str       ┆ ---       ┆ str      │
│           ┆           ┆           ┆           ┆   ┆           ┆           ┆ str       ┆          │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 178200000 ┆ 89000.000 ┆ Vệ sinh   ┆ Băng vệ   ┆ … ┆ Băng vệ   ┆ Chi tiết  ┆ Không xác ┆ Mẹ       │
│ 0001      ┆ 0         ┆           ┆ sinh      ┆   ┆ sinh      ┆ sản phẩm  ┆ định      ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ Tên sản   ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ phẩm…     ┆           ┆          │
│ 194400000 ┆ 115000.00 ┆ Vệ sinh   ┆ Băng vệ   ┆ … ┆ Băng vệ   ┆ Chi tiết  ┆ Không xác ┆ Mẹ       │
│ 0133      ┆ 00        ┆           ┆ sinh      ┆   ┆ sinh      ┆ sản phẩm  ┆ định      ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ Tên sản   ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ phẩm…     ┆           ┆          │
│ 714900000 ┆ 89000.000 ┆ Vệ sinh   ┆ Băng vệ   ┆ … ┆ Băng vệ   ┆ Chi tiết  ┆ Không xác ┆ Mẹ       │
│ 0001      ┆ 0         ┆           ┆ sinh      ┆   ┆ sinh      ┆ sản phẩm  ┆ định      ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ Tên sản   ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ phẩm…     ┆           ┆          │
│ 000719000 ┆ 21000.000 ┆ Vệ sinh   ┆ Băng vệ   ┆ … ┆ Băng vệ   ┆ Chi tiết  ┆ Không xác ┆ Không    │
│ 0004      ┆ 0         ┆           ┆ sinh      ┆   ┆ sinh      ┆ sản phẩm  ┆ định      ┆ xác định │
│           ┆           ┆           ┆           ┆   ┆           ┆ Tên sản   ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ phẩm…     ┆           ┆          │
│ 326900000 ┆ 92000.000 ┆ Vệ sinh   ┆ Băng vệ   ┆ … ┆ Băng vệ   ┆ Chi tiết  ┆ Không xác ┆ Không    │
│ 0001      ┆ 0         ┆           ┆ sinh      ┆   ┆ sinh      ┆ sản phẩm  ┆ định      ┆ xác định │
│           ┆           ┆           ┆           ┆   ┆           ┆ Tên sản   ┆           ┆          │
│           ┆           ┆           ┆           ┆   ┆           ┆ phẩm…     ┆           ┆          │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

Không thể fill được nữa

In [146]:
# import polars as pl

# # Lọc các dòng có 'Băng vệ sinh' trong category
# df_bvs = (
#     df_age
#     .filter(
#         pl.col("category").str.contains("Băng vệ sinh", literal=False)
#     )
#     .select([
#         "category",
#         "description",
#         "description_new",
#         "age_group_final",
#     ])
#     .with_row_count("idx")   # tạo index 0,1,2,...
# )

# # In chỉ dòng đầu tiên
# if df_bvs.height > 0:
#     row = df_bvs.row(17, named=True)   # lấy dòng đầu tiên
#     print("\n===== DÒNG ĐẦU TIÊN =====")
#     print("idx             :", row["idx"])
#     print("category        :", row["category"])
#     print("description     :", row["description"])
#     print("description_new :", row["description_new"])
#     print("age_group_final :", row["age_group_final"])
# else:
#     print("Không có dòng nào chứa 'Băng vệ sinh' trong category.")

In [147]:
DATA_PATH = r".././dataset/sales_pers.item_chunk_0.parquet"

df_raw = pl.read_parquet(DATA_PATH)

In [148]:
# a = df.filter(pl.col("brand") == "Chupa Chups")
a = df_raw.filter(pl.col("category").str.to_lowercase() == "la vie")
a

shape: (6, 34)
┌────────┬────────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ p_id   ┆ item_id    ┆ price      ┆ category_ ┆ … ┆ volume    ┆ material  ┆ sale_stat ┆ descripti │
│ ---    ┆ ---        ┆ ---        ┆ l1_id     ┆   ┆ ---       ┆ ---       ┆ us        ┆ on_new    │
│ i32    ┆ str        ┆ decimal[38 ┆ ---       ┆   ┆ str       ┆ str       ┆ ---       ┆ ---       │
│        ┆            ┆ ,4]        ┆ i32       ┆   ┆           ┆           ┆ i32       ┆ str       │
╞════════╪════════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 108796 ┆ 5114000000 ┆ 8000.0000  ┆ 5126      ┆ … ┆ Không xác ┆ Không xác ┆ 0         ┆ Chi tiết  │
│        ┆ 002        ┆            ┆           ┆   ┆ định      ┆ định      ┆           ┆ sản phẩm  │
│        ┆            ┆            ┆           ┆   ┆           ┆           ┆           ┆ Tên sản   │
│        ┆            ┆            ┆           ┆   ┆           ┆           ┆           ┆ phẩm…     │
│ 108798 ┆ 5114000000 ┆ 12000.0000 ┆ 5126      ┆ … ┆ Không xác ┆ Không xác ┆ 0         ┆ Chi tiết  │
│        ┆ 004        ┆            ┆           ┆   ┆ định      ┆ định      ┆           ┆ sản phẩm  │
│        ┆            ┆            ┆           ┆   ┆           ┆           ┆           ┆ Tên sản   │
│        ┆            ┆            ┆           ┆   ┆           ┆           ┆           ┆ phẩm…     │
│ 108797 ┆ 5114000000 ┆ 10000.0000 ┆ 5126      ┆ … ┆ Không xác ┆ Không xác ┆ 0         ┆ Chi tiết  │
│        ┆ 003        ┆            ┆           ┆   ┆ định      ┆ định      ┆           ┆ sản phẩm  │
│        ┆            ┆            ┆           ┆   ┆           ┆           ┆           ┆ Tên sản   │
│        ┆            ┆            ┆           ┆   ┆           ┆           ┆           ┆ phẩm…     │
│ 108795 ┆ 5114000000 ┆ 6000.0000  ┆ 5126      ┆ … ┆ Không xác ┆ Không xác ┆ 1         ┆ Chi tiết  │
│        ┆ 001        ┆            ┆           ┆   ┆ định      ┆ định      ┆           ┆ sản phẩm  │
│        ┆            ┆            ┆           ┆   ┆           ┆           ┆           ┆ Tên sản   │
│        ┆            ┆            ┆           ┆   ┆           ┆           ┆           ┆ phẩm:     │
│        ┆            ┆            ┆           ┆   ┆           ┆           ┆           ┆ Nước…     │
│ 136079 ┆ 5679000000 ┆ 6000.0000  ┆ 5126      ┆ … ┆ Không xác ┆ Không xác ┆ 1         ┆ null      │
│        ┆ 001        ┆            ┆           ┆   ┆ định      ┆ định      ┆           ┆           │
│ 124828 ┆ 4124000000 ┆ 5000.0000  ┆ 5126      ┆ … ┆ Không xác ┆ Không xác ┆ 1         ┆ null      │
│        ┆ 011        ┆            ┆           ┆   ┆ định      ┆ định      ┆           ┆           │
└────────┴────────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

#### Ý tưởng 1 – Dùng regex bắt tuổi/tháng ghi rõ trong mô tả (độ chắc chắn rất cao)

Thống kê

In [149]:
import re

# ==============================
# 1. Cấu hình context & từ khóa
# ==============================

import re

# ==============================
# 1. Cấu hình context & từ khóa
# ==============================

POS_CONTEXT = [
    "bé", "trẻ", "trẻ em", "em bé",
    "baby", "kid", "child", "children",
    "thiếu nhi", "newborn", "sơ sinh",
    "tháng tuổi", "months old", "years old",
]

CHILD_WORDS = [
    "bé", "trẻ", "trẻ em", "em bé",
    "baby", "kid", "child", "children",
]

NEG_STRONG = [
    # hạn sử dụng / bảo quản
    "sử dụng trong vòng",
    "hạn sử dụng", "thời hạn", "hạn dùng", "hạn sử dụng tốt nhất",
    "bảo quản", "kể từ ngày sản xuất", "sau khi mở nắp",

    # không dùng / không phù hợp cho trẻ
    "không thích hợp cho trẻ",
    "không thích hợp với trẻ",
    "không dùng cho trẻ",
    "không nên dùng cho trẻ",
    "không phù hợp cho trẻ",
    "không phù hợp với trẻ",
    "không sử dụng sản phẩm cho trẻ",
    "không sử dụng cho trẻ",

    # tiếng Anh
    "not suitable for children",
    "do not use for children",
]

# Từ khóa liên quan tới cân nặng (để loại khỏi tuổi)
WEIGHT_WORDS = [
    "kg", "kilogram", "ký", "kí", "cân", "nặng", "trọng lượng", "weight"
]

MONTH_WORDS = ["tháng", "thang", "month", "months"]
YEAR_WORDS  = ["tuổi", "year", "years"]
WEEK_WORDS  = ["tuần", "tuan", "week", "weeks"]

WINDOW_POS = 20   # window cho POS context
WINDOW_NEG = 80  # window cho NEG context


# ==============================
# 2. Regex patterns cho EXTRACT
# ==============================

# 2.1. Range kiểu "0-6 tháng ... đến ... 3 tuổi"
CROSS_MONTH_RANGE_TO_YEAR_PATTERN = re.compile(
    r"(?P<m_start>\d{1,2})\s*-\s*(?P<m_end>\d{1,2})\s*"
    r"(?:tháng|thang|month|months)"
    r".{0,40}?(?:đến|tới|to)\s*.{0,40}?"
    r"(?P<y_end>\d{1,2}(?:[.,]\d+)?)\s*(?:tuổi|year|years)",
)

# 2.2. Newborn range "sơ sinh ... đến ... 3 tuổi"
NEWBORN_RANGE_PATTERN = re.compile(
    r"(?:từ\s+giai\s*đoạn\s+)?sơ\s*sinh"
    r".{0,30}?(?:đến|tới|to|-).{0,30}?"
    r"\d{1,2}(?:[.,]\d+)?\s*(tháng|thang|month|months|tuổi|year|years)",
)

# 2.3. "độ tuổi từ 2 đến 6" (có thể có chữ 'phù hợp', ':', ...)
AGE_WORD_RANGE_PATTERN = re.compile(
    r"độ\s*tuổi[^0-9]{0,20}"      # 'độ tuổi', 'độ tuổi phù hợp:'
    r"(?:từ\s*)?"
    r"(?P<n1>\d{1,2}(?:[.,]\d+)?)\s*(?:-|–|—|đến|to)\s*"
    r"(?P<n2>\d{1,2}(?:[.,]\d+)?)"
)

# 2.4. Range 2 đơn vị: "6 tháng đến 5 tuổi", "1 tuần - 1 tuổi"
RANGE_BOTH_UNITS_PATTERN = re.compile(
    r"(?P<n1>\d{1,2}(?:[.,]\d+)?)\s*"
    r"(?P<u1>tháng tuổi|tháng|thang|month|months|tuổi|year|years|tuần|tuan|week|weeks)\s*"
    r"(?:-|–|—|đến|to)\s*"
    r"(?P<n2>\d{1,2}(?:[.,]\d+)?)\s*"
    r"(?P<u2>tháng tuổi|tháng|thang|month|months|tuổi|year|years|tuần|tuan|week|weeks)"
)

# 2.5. Range 1 đơn vị: "0-12 tháng", "2-6 tuổi", "2-4 tuần"
RANGE_ONE_UNIT_PATTERN = re.compile(
    r"(?:(?:từ)\s*)?"
    r"(?P<n1>\d{1,2}(?:[.,]\d+)?)\s*"
    r"(?:-|–|—|đến|to)\s*"
    r"(?P<n2>\d{1,2}(?:[.,]\d+)?)\s*"
    r"(?P<u>tháng tuổi|tháng|thang|month|months|tuổi|year|years|tuần|tuan|week|weeks)"
)

# 2.6. Single: "6 tháng", "từ 6 tháng", "trên 1 tuổi", "dưới 12 tháng",
#              "6 tháng tuổi trở lên", "sau 6 tháng tuổi", "từ 2.5 tuổi", ...
SINGLE_PATTERN = re.compile(
    r"(?:(?P<cmp>dưới|under|<|từ|trên|hơn|sau|>=|over|more than)\s*)?"
    r"(?P<n>\d{1,2}(?:[.,]\d+)?)\s*"
    r"(?P<u>tháng tuổi|tháng|thang|month|months|tuổi|year|years|tuần|tuan|week|weeks)"
    r"(?:\s*(?P<suffix>trở lên|\+))?"
)



# ==============================
# 3. Hàm context POS/NEG
# ==============================

def has_pos_context(context: str) -> bool:
    return any(tok in context for tok in POS_CONTEXT)


def has_neg_context(context: str) -> bool:
    ctx = context

    # 1) Các cụm NEG mạnh (hạn sử dụng, bảo quản, ...)
    if any(phrase in ctx for phrase in NEG_STRONG):
        return True

    # 2) "không ... (phù hợp/thích hợp/dùng/sử dụng) ... trẻ"
    if "không" in ctx and any(v in ctx for v in ["phù hợp", "thích hợp", "dùng", "sử dụng"]):
        if any(c in ctx for c in CHILD_WORDS):
            return True

    # 3) "tránh dùng / tránh sử dụng ... cho trẻ"
    if any(start in ctx for start in ["tránh dùng", "tránh sử dụng"]):
        if any(c in ctx for c in CHILD_WORDS):
            return True

    # 4) English NEG
    if "not suitable" in ctx and any(c in ctx for c in ["child", "children", "kid", "baby"]):
        return True
    if "do not use" in ctx and any(c in ctx for c in ["child", "children", "kid", "baby"]):
        return True

    # 5) CASE THỜI LƯỢNG "6 tháng đầu", "trong 6 tháng đầu", "giai đoạn 6 tháng đầu"
    if "tháng đầu" in ctx or "tháng đầu đời" in ctx:
        if any(k in ctx for k in ["trong ", "trong vòng", "giai đoạn"]):
            return True

    # 6) CASE CÂN NẶNG: có "nặng", "kg", "cân", ... -> không coi là tuổi
    if any(w in ctx for w in WEIGHT_WORDS):
        return True

    return False


# ==============================
# 4. Hàm extract_age_phrases
# ==============================

def extract_age_phrases(desc: str) -> list[str]:
    """
    Trả về list các cụm tuổi/tháng trong desc, gồm:
      - range: '0-3 tháng', '3-6 tháng tuổi', '6 đến 11 tháng',
               '1-3 tuổi', '6 tháng đến 5 tuổi',
               '0-6 tháng đến bé 3 tuổi',
               'sơ sinh đến 3 tuổi', 'độ tuổi từ 2 đến 6',
               'trẻ từ 1 tuần - 1 tuổi', ...
      - single: 'dưới 12 tháng', 'từ 1 tuổi', 'trên 1 tuổi',
                '6 tháng tuổi trở lên', 'sau 6 tháng tuổi',
                'từ 2.5 tuổi', 'từ 3.5 tuổi', ...

    Rule:
      - CHỈ nhìn phần TRƯỚC "Lưu ý".
      - Phải có POS context (bé/trẻ/...) trong WINDOW_POS.
      - Nếu trong WINDOW_NEG có NEG context ('không phù hợp/không sử dụng/...'
        hoặc '6 tháng đầu', 'trong 6 tháng đầu', 'trẻ nặng ...', ...) thì BỎ.
      - Với single, nếu trái có 'độ tuổi phù hợp' thì coi là min age -> ép 'từ ...'.
    """
    if desc is None:
        return []

    full_text = desc.lower()

    # Cắt bỏ phần sau 'lưu ý'
    m_luuy = re.search(r"lưu\s*ý\b", full_text)
    if m_luuy:
        text = full_text[:m_luuy.start()]
    else:
        text = full_text

    matches: list[str] = []
    used_spans: list[tuple[int, int]] = []

    def overlap_span(start: int, end: int) -> bool:
        return any(not (end <= s or start >= e) for (s, e) in used_spans)

    def get_contexts(start_idx: int, end_idx: int) -> tuple[str, str]:
        left_pos = max(0, start_idx - WINDOW_POS)
        right_pos = min(len(text), end_idx + WINDOW_POS)
        context_pos = text[left_pos:right_pos]

        left_neg = max(0, start_idx - WINDOW_NEG)
        right_neg = min(len(text), end_idx + WINDOW_NEG)
        context_neg = text[left_neg:right_neg]

        return context_pos, context_neg

    # 0) Range kiểu "0-6 tháng ... đến ... 3 tuổi"
    for m in CROSS_MONTH_RANGE_TO_YEAR_PATTERN.finditer(text):
        start_idx, end_idx = m.span()
        context_pos, context_neg = get_contexts(start_idx, end_idx)
        if not has_pos_context(context_pos) or has_neg_context(context_neg):
            continue
        matches.append(text[start_idx:end_idx].strip())
        used_spans.append((start_idx, end_idx))

    # 1) Range newborn "sơ sinh ... đến ... 3 tuổi"
    for m in NEWBORN_RANGE_PATTERN.finditer(text):
        start_idx, end_idx = m.span()
        if overlap_span(start_idx, end_idx):
            continue
        context_pos, context_neg = get_contexts(start_idx, end_idx)
        if not has_pos_context(context_pos) or has_neg_context(context_neg):
            continue
        matches.append(text[start_idx:end_idx].strip())
        used_spans.append((start_idx, end_idx))

    # 2) Range 2 đơn vị: '6 tháng đến 5 tuổi', 'từ 1 tuần - 1 tuổi'
    for m in RANGE_BOTH_UNITS_PATTERN.finditer(text):
        start_idx, end_idx = m.span()
        if overlap_span(start_idx, end_idx):
            continue
        context_pos, context_neg = get_contexts(start_idx, end_idx)
        if not has_pos_context(context_pos) or has_neg_context(context_neg):
            continue
        matches.append(text[start_idx:end_idx].strip())
        used_spans.append((start_idx, end_idx))

    # 3) Range 1 đơn vị: '0-12 tháng', '2-6 tuổi', '1-4 tuần'
    for m in RANGE_ONE_UNIT_PATTERN.finditer(text):
        start_idx, end_idx = m.span()
        if overlap_span(start_idx, end_idx):
            continue
        context_pos, context_neg = get_contexts(start_idx, end_idx)
        if not has_pos_context(context_pos) or has_neg_context(context_neg):
            continue
        matches.append(text[start_idx:end_idx].strip())
        used_spans.append((start_idx, end_idx))

    # 4) "độ tuổi từ 2 đến 6"
    for m in AGE_WORD_RANGE_PATTERN.finditer(text):
        start_idx, end_idx = m.span()
        if overlap_span(start_idx, end_idx):
            continue
        context_pos, context_neg = get_contexts(start_idx, end_idx)
        if not has_pos_context(context_pos) or has_neg_context(context_neg):
            continue
        matches.append(text[start_idx:end_idx].strip())
        used_spans.append((start_idx, end_idx))

    # 5) Single: "dưới 12 tháng", "từ 6 tháng", "6 tháng tuổi trở lên",
    #            "sau 6 tháng tuổi", "từ 2.5 tuổi", ...
    for m in SINGLE_PATTERN.finditer(text):
        start_idx, end_idx = m.span()
        if overlap_span(start_idx, end_idx):
            continue

        context_pos, context_neg = get_contexts(start_idx, end_idx)
        if not has_pos_context(context_pos) or has_neg_context(context_neg):
            continue

        match_text = text[start_idx:end_idx].strip()

        # Nếu trước cụm này có 'độ tuổi phù hợp' ... => ép thành "từ ..."
        ctx_left = text[max(0, start_idx - 60):start_idx]
        if any(kw in ctx_left for kw in [
            "độ tuổi phù hợp", "độ tuổi sử dụng", "độ tuổi khuyến nghị", "độ tuổi khuyên dùng"
        ]):
            if not re.search(r"\b(từ|trên|hơn|sau|dưới|under|over|more than)\b", match_text):
                match_text = "từ " + match_text

        matches.append(match_text)
        used_spans.append((start_idx, end_idx))

    return matches


# ==============================
# 5. Hàm normalize_age_phrase
# ==============================

def _to_months(num_str: str, unit: str) -> int:
    """Chuyển '1', '1,5', '2.5' -> số tháng theo unit (tháng / tuổi / tuần)."""
    val = float(num_str.replace(",", "."))
    unit = unit.lower()

    if unit in MONTH_WORDS:
        return int(round(val))          # 1.5 tháng -> 2 tháng (hiếm gặp)
    elif unit in YEAR_WORDS:
        return int(round(val * 12))     # 1.5 tuổi -> 18 tháng
    elif unit in WEEK_WORDS:
        # 1 tuần ~ 7/30 tháng
        m = int(round(val * 7.0 / 30.0))
        return max(0, m)
    else:
        raise ValueError(f"Unit không hợp lệ: {unit}")


def normalize_age_phrase(raw: str) -> str | None:
    """
    Chuẩn hóa 1 cụm tuổi/tháng về canonical theo THÁNG.

    Kết quả:
      - '6-11M'    : 6–11 tháng
      - '0-12M'    : 0–12 tháng / dưới 12 tháng / sơ sinh đến 12 tháng
      - '12-36M'   : 1–3 tuổi
      - '6-60M'    : 6 tháng đến 5 tuổi
      - '0-18M'    : 0–1,5 tuổi
      - '6M+'      : từ 6 tháng / sau 6 tháng / 6 tháng trở lên
      - '30M+'     : từ 2.5 tuổi trở lên
      - '0M+'      : từ sơ sinh
    """

    if not raw:
        return None

    s = raw.strip().lower()

    # Chuẩn hóa 'tháng tuổi' -> 'tháng'
    s2 = s.replace("tháng tuổi", " tháng ")
    s2 = s2.replace("thang tuoi", " thang ")
    s2 = re.sub(r"\s+", " ", s2)

    # ==========================
    # 1) CASE 'sơ sinh'
    # ==========================
    if "sơ sinh" in s2:
        # 1.1. '(từ giai đoạn) sơ sinh ... đến ... N tháng/tuổi'
        m_nb_range = re.search(
            r"(?:từ\s+giai\s*đoạn\s+)?sơ\s*sinh"
            r".{0,30}?(?:đến|tới|to|-).{0,30}?"
            r"(\d{1,2}(?:[.,]\d+)?)\s*"
            r"(tháng|thang|month|months|tuổi|year|years)",
            s2,
        )
        if m_nb_range:
            n_str = m_nb_range.group(1)
            unit  = m_nb_range.group(2)
            end_m = _to_months(n_str, unit)
            if end_m <= 0:
                return None
            return f"0-{end_m}M"

        # 1.2. 'từ sơ sinh' -> 0M+
        m_nb_from0 = re.search(r"từ\s+sơ\s*sinh\b(?:\s*(trở lên|\+))?", s2)
        if m_nb_from0:
            return "0M+"

        # 1.3. 'sơ sinh từ/hơn/trên N tháng/tuổi' -> NM+
        m_nb_plus = re.search(
            r"sơ\s*sinh\s*(từ|hơn|trên|sau|>=|over|more than)\s*"
            r"(\d{1,2}(?:[.,]\d+)?)\s*"
            r"(tháng|thang|month|months|tuổi|year|years)"
            r"(?:\s*(trở lên|\+))?",
            s2,
        )
        if m_nb_plus:
            n_str = m_nb_plus.group(2)
            unit  = m_nb_plus.group(3)
            start_m = _to_months(n_str, unit)
            return f"{start_m}M+"

        # còn lại: 'sơ sinh' mô tả, không coi là mốc tuổi

    # ==========================
    # 2) CROSS RANGE đặc biệt '0-6 tháng ... đến ... 3 tuổi'
    # ==========================
    m_cross = re.search(
        r"(\d{1,2})\s*-\s*(\d{1,2})\s*"
        r"(tháng|thang|month|months)"
        r".{0,40}?(?:đến|tới|to)\s*.{0,40}?"
        r"(\d{1,2}(?:[.,]\d+)?)\s*(tuổi|year|years)",
        s2,
    )
    if m_cross:
        # Semantics: '0-6 tháng đến 3 tuổi' ~ 0 -> 3 tuổi
        y_end_str = m_cross.group(4)
        end_m = _to_months(y_end_str, "tuổi")
        return f"0-{end_m}M"

    # ==========================
    # 3) UNDER: 'dưới 12 tháng', 'under 2 years'
    # ==========================
    m_under = re.search(
        r"(dưới|under|<)\s*(\d{1,2}(?:[.,]\d+)?)\s*"
        r"(tháng|thang|month|months|tuổi|year|years|tuần|tuan|week|weeks)",
        s2,
    )
    if m_under:
        n_str = m_under.group(2)
        unit  = m_under.group(3)
        end_m = _to_months(n_str, unit)
        if end_m <= 0:
            return None
        return f"0-{end_m}M"

    # ==========================
    # 4) FROM / OVER / SAU: 'từ 1 tuổi', 'trên 1 tuổi', 'sau 6 tháng'
    #      -> XM+
    # ==========================
    m_from = re.search(
        r"(từ|trên|hơn|sau|>=|over|more than)\s*"
        r"(\d{1,2}(?:[.,]\d+)?)\s*"
        r"(tháng|thang|month|months|tuổi|year|years|tuần|tuan|week|weeks)"
        r"(?:\s*(trở lên|\+))?",
        s2,
    )
    if m_from:
        n_str = m_from.group(2)
        unit  = m_from.group(3)
        start_m = _to_months(n_str, unit)
        return f"{start_m}M+"

    # ==========================
    # 5) PLUS (hậu tố): '6 tháng tuổi trở lên', '2 tuổi trở lên'
    #      -> XM+
    # ==========================
    m_suffix_plus = re.search(
        r"(\d{1,2}(?:[.,]\d+)?)\s*"
        r"(tháng|thang|month|months|tuổi|year|years|tuần|tuan|week|weeks)\s*"
        r"(trở lên|\+)",
        s2,
    )
    if m_suffix_plus:
        n_str = m_suffix_plus.group(1)
        unit  = m_suffix_plus.group(2)
        start_m = _to_months(n_str, unit)
        return f"{start_m}M+"

    # ==========================
    # 6) Range 2 đơn vị: '6 tháng đến 5 tuổi', 'từ 1 tuần - 1 tuổi'
    # ==========================
    m_both = re.search(
        r"(?:từ\s*)?"
        r"(\d{1,2}(?:[.,]\d+)?)\s*"
        r"(tháng|thang|month|months|tuổi|year|years|tuần|tuan|week|weeks)\s*"
        r"(?:-|–|—|đến|to)\s*"
        r"(\d{1,2}(?:[.,]\d+)?)\s*"
        r"(tháng|thang|month|months|tuổi|year|years|tuần|tuan|week|weeks)",
        s2,
    )
    if m_both:
        a_str, u1, b_str, u2 = m_both.group(1), m_both.group(2), m_both.group(3), m_both.group(4)
        start_m = _to_months(a_str, u1)
        end_m   = _to_months(b_str, u2)
        if start_m > end_m:
            start_m, end_m = end_m, start_m
        return f"{start_m}-{end_m}M"

    # ==========================
    # 7) Range 1 đơn vị explicit: '0-12 tháng', '2-6 tuổi', '1-4 tuần'
    # ==========================
    m_range_unit = re.search(
        r"(\d{1,2}(?:[.,]\d+)?)\s*"
        r"(?:-|–|—|đến|to)\s*"
        r"(\d{1,2}(?:[.,]\d+)?)\s*"
        r"(tháng|thang|month|months|tuổi|year|years|tuần|tuan|week|weeks)",
        s2,
    )
    if m_range_unit:
        a_str = m_range_unit.group(1)
        b_str = m_range_unit.group(2)
        unit  = m_range_unit.group(3)
        start_m = _to_months(a_str, unit)
        end_m   = _to_months(b_str, unit)
        if start_m > end_m:
            start_m, end_m = end_m, start_m
        return f"{start_m}-{end_m}M"

    # ==========================
    # 8) Range "độ tuổi từ 2 đến 6." (mặc định đơn vị = tuổi)
    # ==========================
    m_ageword = re.search(
        r"độ\s*tuổi[^0-9]{0,20}"
        r"(?:từ\s*)?"
        r"(\d{1,2}(?:[.,]\d+)?)\s*(?:-|–|—|đến|to)\s*"
        r"(\d{1,2}(?:[.,]\d+)?)",
        s2,
    )
    if m_ageword:
        a_str = m_ageword.group(1)
        b_str = m_ageword.group(2)
        start_m = _to_months(a_str, "tuổi")
        end_m   = _to_months(b_str, "tuổi")
        if start_m > end_m:
            start_m, end_m = end_m, start_m
        return f"{start_m}-{end_m}M"

    # 9) Single còn lại -> bỏ (để tránh '3 tuổi' lẻ loi)
    return None

# ==============================
# 6. Hàm normalize_age_phrase_list
# ==============================

def _parse_canonical(c: str) -> tuple[int, int | None, bool]:
    """
    Trả (start_m, end_m, is_plus)
      - '6M'    -> (6, 6, False)
      - '6-36M' -> (6, 36, False)
      - '12M+'  -> (12, None, True)
    """
    if c.endswith("M+"):
        start = int(c[:-2])
        return start, None, True

    if not c.endswith("M"):
        raise ValueError(f"Canonical age phải kết thúc bằng 'M' hoặc 'M+': {c}")

    body = c[:-1]
    if "-" in body:
        a, b = body.split("-", 1)
        return int(a), int(b), False
    else:
        v = int(body)
        return v, v, False


def normalize_age_phrase_list(raw_list: list[str] | None) -> list[str]:
    if raw_list is None:
        return []

    # 1) Chuẩn hoá từng cụm
    canon: list[str] = []
    for raw in raw_list:
        norm = normalize_age_phrase(raw)
        if norm is not None:
            canon.append(norm)

    # 2) unique theo thứ tự
    uniq: list[str] = []
    for c in canon:
        if c not in uniq:
            uniq.append(c)

    if not uniq:
        return []

    # 3) loại các mốc bị "bao phủ" bởi 1 khoảng khác
    parsed = [_parse_canonical(c) for c in uniq]
    keep = [True] * len(uniq)

    for i, (si, ei, plus_i) in enumerate(parsed):
        if not keep[i]:
            continue
        for j, (sj, ej, plus_j) in enumerate(parsed):
            if i == j:
                continue

            # j bao phủ i?
            if plus_j:
                # KHÔNG cho khoảng 'sjM+' cover khoảng hữu hạn [si, ei]
                # => nếu i là finite, bỏ qua luôn
                if not plus_i:
                    continue

                # j là 'sjM+' -> [sj, +∞)
                if ei is None:
                    # cả 2 đều '+': giữ cái xuất hiện trước
                    if j < i:
                        keep[i] = False
                        break
                else:
                    if si >= sj:
                        keep[i] = False
                        break
            else:
                # j là khoảng hữu hạn [sj, ej]
                if ei is None:
                    # khoảng vô hạn không bị cover bởi hữu hạn
                    continue
                if sj <= si and ej >= ei:
                    keep[i] = False
                    break

    result = [c for c, k in zip(uniq, keep) if k]
    return result

In [150]:
df_unknown = (
    df_age
    .filter(pl.col("age_group_final") == "Không xác định")
    .with_columns(
        pl.concat_str(
            [
                pl.col("description").fill_null(""),
                pl.col("description_new").fill_null(""),
            ],
            separator=" "
        )
        .str.to_lowercase()
        .alias("desc_all")
    )
    .with_columns(
        pl.col("desc_all").map_elements(
            extract_age_phrases,
            return_dtype=pl.List(pl.Utf8)
        ).alias("age_phrases_raw")
    )
    .with_columns(
        pl.col("age_phrases_raw").map_elements(
            normalize_age_phrase_list,
            return_dtype=pl.List(pl.Utf8)
        ).alias("age_ranges_norm")
    )
)

In [151]:
# Lấy tất cả canonical ranges đã detect
target_norm_list = (
    df_unknown
    .select(pl.col("age_ranges_norm"))
    .explode("age_ranges_norm")
    .filter(pl.col("age_ranges_norm").is_not_null())
    .unique()
    .to_series()
    .to_list()
)

print("Số lượng target_norm:", len(target_norm_list))
target_norm_list

Số lượng target_norm: 148

['6-48M',
 '5-8M',
 '24-60M',
 '60M+',
 '12M+',
 '96-144M',
 '60-84M',
 '1-12M',
 '0-12M',
 '48-144M',
 '12-60M',
 '14-17M',
 '0-9M',
 '6-18M',
 '7-60M',
 '24-120M',
 '1-24M',
 '36-120M',
 '6-24M',
 '10M+',
 '9-11M',
 '7-24M',
 '24-108M',
 '72-144M',
 '7-8M',
 '9-12M',
 '4-30M',
 '4M+',
 '9-48M',
 '60-72M',
 '0-5M',
 '0M+',
 '0-4M',
 '12-24M',
 '0-48M',
 '2M+',
 '7M+',
 '0-144M',
 '48-72M',
 '0-1M',
 '36-84M',
 '36M+',
 '9-20M',
 '3-18M',
 '18M+',
 '48-60M',
 '6-60M',
 '108-132M',
 '1M+',
 '84M+',
 '60-132M',
 '0-25M',
 '5M+',
 '12-120M',
 '9M+',
 '12-192M',
 '0-36M',
 '24-96M',
 '0-11M',
 '18-24M',
 '1-2M',
 '4-24M',
 '18-21M',
 '36-72M',
 '36-288M',
 '6-144M',
 '0-72M',
 '12-14M',
 '13-16M',
 '0-24M',
 '24-30M',
 '12-108M',
 '144-216M',
 '6-8M',
 '6-72M',
 '6-9M',
 '12-96M',
 '84-120M',
 '144M+',
 '12-48M',
 '72-108M',
 '4-72M',
 '17-18M',
 '9-72M',
 '19-25M',
 '108-144M',
 '9-24M',
 '4-6M',
 '0-3M',
 '120M+',
 '17M+',
 '3-24M',
 '0-84M',
 '3-6M',
 '36-48M',
 '36-192M',
 '108-120M',
 '1-18M',
 '15M+',
 '1-3M',
 '8M+',
 '10-12M',
 '6-12M',
 '30-36M',
 '1-36M',
 '84-96M',
 '48-96M',
 '7-15M',
 '13-17M',
 '0-120M',
 '16M+',
 '168M+',
 '13M+',
 '0-14M',
 '36-144M',
 '12-72M',
 '84-108M',
 '84-144M',
 '0-60M',
 '21-24M',
 '24M+',
 '24-72M',
 '6M+',
 '16-19M',
 '108-156M',
 '72M+',
 '24-36M',
 '6-15M',
 '6-84M',
 '48M+',
 '19M+',
 '24-48M',
 '84-132M',
 '12-36M',
 '48-156M',
 '0-6M',
 '6-36M',
 '15-18M',
 '156M+',
 '12-15M',
 '8-24M',
 '1-4M',
 '3M+',
 '0-30M',
 '36-216M',
 '12-144M',
 '12-18M',
 '6-30M']

Các trường hợp age_group bắt được -> đã check kĩ

In [152]:
import textwrap

pl.Config.set_fmt_str_lengths(100)
pl.Config.set_tbl_rows(50)

# Hàm wrap text 175 ký tự
def wrap175(text):
    if text is None:
        return ""
    return textwrap.fill(text, width=175)

with open("output_age_norm.txt", "w", encoding="utf-8") as f:

    for tg in target_norm_list:
        f.write(f"\n=== VÍ DỤ CHO TARGET_NORM = {tg} ===\n\n")
        target_norm = tg

        examples = (
            df_unknown
            .filter(pl.col("age_ranges_norm").list.contains(target_norm))
            .select([
                "item_id",
                "age_group_final",
                "age_phrases_raw",
                "age_ranges_norm",
                "description",
                "description_new",
            ])
            .head(20)
        )

        for row in examples.iter_rows(named=True):
            f.write("======================================\n")
            f.write(f"item_id: {row['item_id']}\n")
            f.write(f"age_group_final: {row['age_group_final']}\n")
            f.write(f"age_phrases_raw: {row['age_phrases_raw']}\n")
            f.write(f"age_ranges_norm: {row['age_ranges_norm']}\n\n")

            f.write("description:\n")
            f.write(wrap175(str(row["description"])) + "\n\n")

            f.write("description_new:\n")
            f.write(wrap175(str(row["description_new"])) + "\n\n")

print("Đã xuất file: output_age_norm.txt")

Đã xuất file: output_age_norm.txt

Fill các trường hợp `age_group` bắt được từ 2 description (chắc chắn)

In [153]:
def build_age_group_value(age_ranges_norm, age_phrases_raw):
    """
    age_ranges_norm: list các canonical như ['0-6M', '6-12M'] hoặc ['6M+'] …
    age_phrases_raw: list các câu raw đã match từ 2 description.

    Trả về:
      - None: nếu không có mốc nào (list rỗng / None)
      - '6-12M': nếu chỉ có 1 mốc
      - dict {...}: nếu >= 2 mốc
    """
    if not age_ranges_norm:
        return None

    # Chỉ 1 mốc -> fill thẳng là string
    if len(age_ranges_norm) == 1:
        return age_ranges_norm[0]

    # Nhiều mốc -> trả dict để bạn soi/giữ full info
    return {
        "source": "description",
        "ranges_norm": age_ranges_norm,
        "phrases_raw": age_phrases_raw,
    }

In [154]:
import polars as pl

# 1.1. Gộp description + description_new
df_age = df_age.with_columns(
    pl.concat_str(
        [
            pl.col("description").fill_null(""),
            pl.col("description_new").fill_null(""),
        ],
        separator=" "
    )
    .str.to_lowercase()
    .alias("desc_all")
)

# 1.2. Bắt các cụm tuổi thô từ desc_all
df_age = df_age.with_columns(
    pl.col("desc_all")
    .map_elements(
        extract_age_phrases,              # hàm Python đã viết
        return_dtype=pl.List(pl.Utf8),
    )
    .alias("age_phrases_raw")
)

# 1.3. Chuẩn hoá về dạng canonical tháng ('0-12M', '6M+', ...)
df_age = df_age.with_columns(
    pl.col("age_phrases_raw")
    .map_elements(
        normalize_age_phrase_list,        # hàm Python đã viết
        return_dtype=pl.List(pl.Utf8),
    )
    .alias("age_ranges_norm")
)

In [155]:
df_age.select(["item_id", "age_group_final", "age_phrases_raw", "age_ranges_norm"]).head(5)

shape: (5, 4)
┌───────────────┬─────────────────┬──────────────────────────────────────────┬─────────────────┐
│ item_id       ┆ age_group_final ┆ age_phrases_raw                          ┆ age_ranges_norm │
│ ---           ┆ ---             ┆ ---                                      ┆ ---             │
│ str           ┆ str             ┆ list[str]                                ┆ list[str]       │
╞═══════════════╪═════════════════╪══════════════════════════════════════════╪═════════════════╡
│ 0502020000004 ┆ Không xác định  ┆ ["trên 9 tháng", "trên 9 tháng", "trên 9 ┆ ["9M+"]         │
│               ┆                 ┆ tháng tuổi"]                             ┆                 │
│ 0010290040150 ┆ Từ 3Y           ┆ []                                       ┆ []              │
│ 0008010000015 ┆ 0-1Y            ┆ []                                       ┆ []              │
│ 0020010000094 ┆ Không xác định  ┆ []                                       ┆ []              │
│ 0020010000098 ┆ Không xác định  ┆ []                                       ┆ []              │
└───────────────┴─────────────────┴──────────────────────────────────────────┴─────────────────┘

In [156]:
df_age = df_age.with_columns(
    pl.struct(["age_ranges_norm", "age_phrases_raw"])
    .map_elements(
        lambda row: build_age_group_value(
            row["age_ranges_norm"],
            row["age_phrases_raw"],
        ),
        return_dtype=pl.Object,   # để chứa được cả str và dict
    )
    .alias("age_group_from_desc")
)

In [157]:
import json
import polars as pl

df_age = df_age.with_columns(
    pl.col("age_group_from_desc")
    .map_elements(
        lambda v: (
            None
            if v is None
            else (v if isinstance(v, str) else json.dumps(v, ensure_ascii=False))
        ),
        return_dtype=pl.Utf8,
    )
    .alias("age_group_from_desc_str")
)

In [158]:
df_age = df_age.with_columns(
    pl.when(
        (pl.col("age_group_final") == "Không xác định")
        & pl.col("age_group_from_desc_str").is_not_null()
    )
    .then(pl.col("age_group_from_desc_str"))
    .otherwise(pl.col("age_group_final"))
    .alias("age_group_final")
)

In [159]:
pl.Config.set_fmt_str_lengths(50)
pl.Config.set_tbl_rows(50)

polars.config.Config

In [160]:
df_age = df_age.drop([
    "age_phrases_raw",
    "age_ranges_norm",
    "age_group_from_desc",
    "age_group_from_desc_str",
])

In [161]:
total = df_age.height

unknown = (
    df_age
    .filter(pl.col("age_group_final") == "Không xác định")
    .height
)

ratio = unknown / total * 100

print("Tổng số dòng:", total)
print("Số dòng còn 'Không xác định':", unknown)
print(f"Tỷ lệ còn lại: {ratio:.2f}%")

Tổng số dòng: 27323
Số dòng còn 'Không xác định': 11784
Tỷ lệ còn lại: 43.13%

#### Ý tưởng 2:

# Task 3: Phân tích tương đồng và xác định xem các thuộc tính tương tự nhau. Từ đó loại bỏ đặc trưng thừa.

# Task 4: Chuẩn hóa dữ liệu (nếu có), biến đổi dữ liệu

# Task 5: Nhóm hãy suy nghĩ xem, với bài toán dự đoán mua hàng, ta có thể tạo mới những đặc trưng nào. Sau đó tiến hành rút trích thêm các đặc trưng. Task này rất quan trọng vì ảnh hưởng hiệu quả của hệ thống.