# Import thư viện và load data

In [1]:
import os
import polars as pl
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [2]:
def read_parquet_transaction(train_path: str):
    # Lấy tất cả các file parquet trong thư mục
    files = [os.path.join(train_path, f) for f in os.listdir(train_path) if f.endswith('.parquet')]
    
    # Phân loại các file theo loại tên
    purchase_chunk_files = [file for file in files if 'purchase_history_daily_chunk' in file]
        
    # Đọc các file riêng biệt thành DataFrame
    purchase_chunk_df = pl.concat([pl.read_parquet(file) for file in purchase_chunk_files]) if purchase_chunk_files else None
        
    # Trả về một dictionary chứa các DataFrame
    return purchase_chunk_df

In [3]:
def read_parquet_item(train_path: str):
    # Lấy tất cả các file parquet trong thư mục
    files = [os.path.join(train_path, f) for f in os.listdir(train_path) if f.endswith('.parquet')]
    
    # Phân loại các file theo loại tên
    item_chunk_files = [file for file in files if 'item_chunk' in file]
        
    # Đọc các file riêng biệt thành DataFrame
    item_chunk_df = pl.concat([pl.read_parquet(file) for file in item_chunk_files]) if item_chunk_files else None
        
    # Trả về một dictionary chứa các DataFrame
    return item_chunk_df

In [4]:
item = read_parquet_item('dataset')
item.head()

shape: (5, 34)
┌───────┬────────────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ p_id  ┆ item_id    ┆ price      ┆ category_l ┆ … ┆ volume    ┆ material  ┆ sale_stat ┆ descripti │
│ ---   ┆ ---        ┆ ---        ┆ 1_id       ┆   ┆ ---       ┆ ---       ┆ us        ┆ on_new    │
│ i32   ┆ str        ┆ decimal[38 ┆ ---        ┆   ┆ str       ┆ str       ┆ ---       ┆ ---       │
│       ┆            ┆ ,4]        ┆ i32        ┆   ┆           ┆           ┆ i32       ┆ str       │
╞═══════╪════════════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 17065 ┆ 0502020000 ┆ 99000.0000 ┆ 1          ┆ … ┆ Không xác ┆ Không xác ┆ 0         ┆ Chi tiết  │
│       ┆ 004        ┆            ┆            ┆   ┆ định      ┆ định      ┆           ┆ sản phẩm  │
│       ┆            ┆            ┆            ┆   ┆           ┆           ┆           ┆ …         │
│ 72370 ┆ 0010290040 ┆ 69000.0000 ┆ 3292       ┆ … ┆ Không xác ┆ Không xác ┆ 0         ┆ Không xác │
│       ┆ 150        ┆            ┆            ┆   ┆ định      ┆ định      ┆           ┆ định      │
│ 31154 ┆ 0008010000 ┆ 45000.0000 ┆ 351        ┆ … ┆ Không xác ┆ Không xác ┆ 0         ┆ Chi tiết  │
│       ┆ 015        ┆            ┆            ┆   ┆ định      ┆ định      ┆           ┆ sản phẩm  │
│       ┆            ┆            ┆            ┆   ┆           ┆           ┆           ┆ …         │
│ 46123 ┆ 0020010000 ┆ 401000.000 ┆ 2222       ┆ … ┆ Không xác ┆ Giấy, bột ┆ 0         ┆ Không xác │
│       ┆ 094        ┆ 0          ┆            ┆   ┆ định      ┆ giấy, vải ┆           ┆ định      │
│       ┆            ┆            ┆            ┆   ┆           ┆ không     ┆           ┆           │
│       ┆            ┆            ┆            ┆   ┆           ┆ dệt,…     ┆           ┆           │
│ 46127 ┆ 0020010000 ┆ 401000.000 ┆ 2222       ┆ … ┆ Không xác ┆ Giấy, bột ┆ 0         ┆ Không xác │
│       ┆ 098        ┆ 0          ┆            ┆   ┆ định      ┆ giấy, vải ┆           ┆ định      │
│       ┆            ┆            ┆            ┆   ┆           ┆ không     ┆           ┆           │
│       ┆            ┆            ┆            ┆   ┆           ┆ dệt,…     ┆           ┆           │
└───────┴────────────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [5]:
trans = read_parquet_transaction("./dataset")
trans.head()

shape: (5, 16)
┌────────────┬───────────┬───────────┬───────────┬───┬──────────┬──────────┬───────────┬───────────┐
│ timestamp  ┆ user_id   ┆ item_id   ┆ event_typ ┆ … ┆ payment  ┆ location ┆ discount  ┆ is_delete │
│ ---        ┆ ---       ┆ ---       ┆ e         ┆   ┆ ---      ┆ ---      ┆ ---       ┆ d         │
│ i64        ┆ str       ┆ str       ┆ ---       ┆   ┆ str      ┆ i32      ┆ decimal[3 ┆ ---       │
│            ┆           ┆           ┆ str       ┆   ┆          ┆          ┆ 8,4]      ┆ bool      │
╞════════════╪═══════════╪═══════════╪═══════════╪═══╪══════════╪══════════╪═══════════╪═══════════╡
│ 1735064221 ┆ ca12702dd ┆ 711500000 ┆ Purchase  ┆ … ┆ VietQR   ┆ 656      ┆ 0.0000    ┆ false     │
│            ┆ f55acaa9f ┆ 0004      ┆           ┆   ┆          ┆          ┆           ┆           │
│            ┆ b767e10fa ┆           ┆           ┆   ┆          ┆          ┆           ┆           │
│            ┆ aa6…      ┆           ┆           ┆   ┆          ┆          ┆           ┆           │
│ 1735068481 ┆ 54314ce86 ┆ 002913000 ┆ Purchase  ┆ … ┆ Tiền mặt ┆ 143      ┆ 0.0000    ┆ false     │
│            ┆ 269f4849f ┆ 0030      ┆           ┆   ┆          ┆          ┆           ┆           │
│            ┆ 9a4c3fc85 ┆           ┆           ┆   ┆          ┆          ┆           ┆           │
│            ┆ d94…      ┆           ┆           ┆   ┆          ┆          ┆           ┆           │
│ 1735069843 ┆ 4799de402 ┆ 349600000 ┆ Purchase  ┆ … ┆ MoMo     ┆ 213      ┆ 0.0000    ┆ false     │
│            ┆ 2b58689b2 ┆ 0053      ┆           ┆   ┆          ┆          ┆           ┆           │
│            ┆ b9fb37122 ┆           ┆           ┆   ┆          ┆          ┆           ┆           │
│            ┆ 479…      ┆           ┆           ┆   ┆          ┆          ┆           ┆           │
│ 1735069779 ┆ 4799de402 ┆ 270000000 ┆ Purchase  ┆ … ┆ MoMo     ┆ 213      ┆ 13000.000 ┆ false     │
│            ┆ 2b58689b2 ┆ 0002      ┆           ┆   ┆          ┆          ┆ 0         ┆           │
│            ┆ b9fb37122 ┆           ┆           ┆   ┆          ┆          ┆           ┆           │
│            ┆ 479…      ┆           ┆           ┆   ┆          ┆          ┆           ┆           │
│ 1735379373 ┆ 3b2423f73 ┆ 002911000 ┆ Purchase  ┆ … ┆ MoMo     ┆ 590      ┆ 10000.000 ┆ false     │
│            ┆ 0815273df ┆ 0036      ┆           ┆   ┆          ┆          ┆ 0         ┆           │
│            ┆ d6f6220b0 ┆           ┆           ┆   ┆          ┆          ┆           ┆           │
│            ┆ c5c…      ┆           ┆           ┆   ┆          ┆          ┆           ┆           │
└────────────┴───────────┴───────────┴───────────┴───┴──────────┴──────────┴───────────┴───────────┘

In [9]:
trans.shape
# ví dụ: (1250000, 34)

(35729825, 16)

In [10]:
trans.select(pl.col("customer_id").n_unique())

shape: (1, 1)
┌─────────────┐
│ customer_id │
│ ---         │
│ u32         │
╞═════════════╡
│ 2442306     │
└─────────────┘

In [6]:
def split_parquet_lazy(input_path, num_files, output_dir):
    os.makedirs(output_dir, exist_ok=True)

    lf = pl.scan_parquet(input_path)
    total_rows = lf.count().collect().item()

    rows_per_file = total_rows // num_files

    for i in range(num_files):
        start = i * rows_per_file
        end = (i + 1) * rows_per_file if i < num_files - 1 else total_rows

        out_path = os.path.join(output_dir, f"chunk_{i}.parquet")

        (
            lf.slice(start, end - start)
              .collect(streaming=True)
              .write_parquet(out_path)
        )
        print("Đã lưu:", out_path)

# Drop

In [8]:
cols_to_drop = [
    "timestamp",
    "event_type",
    "event_value",
    "date_key",
    "user_id",
    "updated_date",
    "is_deleted",
]

df = trans.drop(cols_to_drop)
df.head()

shape: (5, 9)
┌────────────┬────────────┬──────────┬────────────┬───┬──────────┬──────────┬──────────┬───────────┐
│ item_id    ┆ price      ┆ quantity ┆ customer_i ┆ … ┆ channel  ┆ payment  ┆ location ┆ discount  │
│ ---        ┆ ---        ┆ ---      ┆ d          ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---       │
│ str        ┆ decimal[38 ┆ i32      ┆ ---        ┆   ┆ str      ┆ str      ┆ i32      ┆ decimal[3 │
│            ┆ ,4]        ┆          ┆ i32        ┆   ┆          ┆          ┆          ┆ 8,4]      │
╞════════════╪════════════╪══════════╪════════════╪═══╪══════════╪══════════╪══════════╪═══════════╡
│ 7115000000 ┆ 49000.0000 ┆ 1        ┆ 5254214    ┆ … ┆ In-Store ┆ VietQR   ┆ 656      ┆ 0.0000    │
│ 004        ┆            ┆          ┆            ┆   ┆          ┆          ┆          ┆           │
│ 0029130000 ┆ 69000.0000 ┆ 1        ┆ 7573232    ┆ … ┆ In-Store ┆ Tiền mặt ┆ 143      ┆ 0.0000    │
│ 030        ┆            ┆          ┆            ┆   ┆          ┆          ┆          ┆           │
│ 3496000000 ┆ 75000.0000 ┆ 2        ┆ 8187418    ┆ … ┆ In-Store ┆ MoMo     ┆ 213      ┆ 0.0000    │
│ 053        ┆            ┆          ┆            ┆   ┆          ┆          ┆          ┆           │
│ 2700000000 ┆ 58500.0000 ┆ 2        ┆ 8187418    ┆ … ┆ In-Store ┆ MoMo     ┆ 213      ┆ 13000.000 │
│ 002        ┆            ┆          ┆            ┆   ┆          ┆          ┆          ┆ 0         │
│ 0029110000 ┆ 89000.0000 ┆ 1        ┆ 6931560    ┆ … ┆ Android  ┆ MoMo     ┆ 590      ┆ 10000.000 │
│ 036        ┆            ┆          ┆            ┆   ┆          ┆          ┆          ┆ 0         │
└────────────┴────────────┴──────────┴────────────┴───┴──────────┴──────────┴──────────┴───────────┘

In [9]:
df = df.with_columns([
    pl.col("created_date").dt.date().alias("created_date")
])
df.head()

shape: (5, 9)
┌────────────┬────────────┬──────────┬────────────┬───┬──────────┬──────────┬──────────┬───────────┐
│ item_id    ┆ price      ┆ quantity ┆ customer_i ┆ … ┆ channel  ┆ payment  ┆ location ┆ discount  │
│ ---        ┆ ---        ┆ ---      ┆ d          ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---       │
│ str        ┆ decimal[38 ┆ i32      ┆ ---        ┆   ┆ str      ┆ str      ┆ i32      ┆ decimal[3 │
│            ┆ ,4]        ┆          ┆ i32        ┆   ┆          ┆          ┆          ┆ 8,4]      │
╞════════════╪════════════╪══════════╪════════════╪═══╪══════════╪══════════╪══════════╪═══════════╡
│ 7115000000 ┆ 49000.0000 ┆ 1        ┆ 5254214    ┆ … ┆ In-Store ┆ VietQR   ┆ 656      ┆ 0.0000    │
│ 004        ┆            ┆          ┆            ┆   ┆          ┆          ┆          ┆           │
│ 0029130000 ┆ 69000.0000 ┆ 1        ┆ 7573232    ┆ … ┆ In-Store ┆ Tiền mặt ┆ 143      ┆ 0.0000    │
│ 030        ┆            ┆          ┆            ┆   ┆          ┆          ┆          ┆           │
│ 3496000000 ┆ 75000.0000 ┆ 2        ┆ 8187418    ┆ … ┆ In-Store ┆ MoMo     ┆ 213      ┆ 0.0000    │
│ 053        ┆            ┆          ┆            ┆   ┆          ┆          ┆          ┆           │
│ 2700000000 ┆ 58500.0000 ┆ 2        ┆ 8187418    ┆ … ┆ In-Store ┆ MoMo     ┆ 213      ┆ 13000.000 │
│ 002        ┆            ┆          ┆            ┆   ┆          ┆          ┆          ┆ 0         │
│ 0029110000 ┆ 89000.0000 ┆ 1        ┆ 6931560    ┆ … ┆ Android  ┆ MoMo     ┆ 590      ┆ 10000.000 │
│ 036        ┆            ┆          ┆            ┆   ┆          ┆          ┆          ┆ 0         │
└────────────┴────────────┴──────────┴────────────┴───┴──────────┴──────────┴──────────┴───────────┘

# Kiểm tra outlier price

In [10]:
import polars as pl

pl.Config.set_tbl_rows(None)
pl.Config.set_tbl_cols(None)
pl.Config.set_fmt_str_lengths(200)

polars.config.Config

In [10]:
df_before = df.clone()

p99_value = df_before.select(pl.col("price").quantile(0.99)).item()

items_clipped = (
    df_before
        .filter(pl.col("price") > p99_value)
        .select(["item_id", "price"])
        .unique()
)

print("Số lượng item bị clip:", items_clipped.height)

items_small = item.select([
    "item_id",
    "category",
    "description"
])

items_info = (
    items_clipped
        .join(items_small, on="item_id", how="left")
)

print(items_info.head(30))

Số lượng item bị clip: 52856
shape: (30, 4)
┌───────────────┬───────────────┬────────────────────────┬─────────────────────────────────────────┐
│ item_id       ┆ price         ┆ category               ┆ description                             │
│ ---           ┆ ---           ┆ ---                    ┆ ---                                     │
│ str           ┆ decimal[38,4] ┆ str                    ┆ str                                     │
╞═══════════════╪═══════════════╪════════════════════════╪═════════════════════════════════════════╡
│ 6903000000002 ┆ 840334.4482   ┆ Aptamil Úc Step 3      ┆ ﻿﻿﻿﻿﻿﻿﻿﻿Với mong muốn giúp cho thế hệ trẻ em    │
│               ┆               ┆                        ┆ trên toàn thế giới có một hệ tư duy     │
│               ┆               ┆                        ┆ thông minh và ham học hỏi hơn, góp phần │
│               ┆               ┆                        ┆ cho tương lai sau này, Nutricia đã      │
│               ┆               ┆                        ┆ nghiên cứu và bổ sung tăng cường hàm    │
│               ┆               ┆                        ┆ lượng D…                                │
│ 7242000000002 ┆ 839675.3247   ┆ Enspire Thái Step 3    ┆ ﻿Sữa Enfagrow Enspire 2 là sản phẩm dành │
│               ┆               ┆                        ┆ cho các bé từ 1 đến 3 tuổi. Với thành   │
│               ┆               ┆                        ┆ phần Lactoferrin, sản phẩm ﻿﻿hỗ trợ giảm  │
│               ┆               ┆                        ┆ các triệu chứng về đường tiêu hóa và hô │
│               ┆               ┆                        ┆ hấp cho bé. Ư…                          │
│ 2406000000006 ┆ 942678.5759   ┆ Enfa Step 2            ┆ ﻿Enfamil A+ số 2 là sữa bột công thức    │
│               ┆               ┆                        ┆ dành riêng cho trẻ từ 6 đến 12 tháng    │
│               ┆               ┆                        ┆ tuổi. Con Cưng mời ba mẹ tham khảo      │
│               ┆               ┆                        ┆ thông tin chi tiết về sữa Enfamil A+ số │
│               ┆               ┆                        ┆ 2 cụ thể trong bảng tổng hợp dưới đây.  │
│               ┆               ┆                        ┆ Sữa Enfamil…                            │
│ 5898000000003 ┆ 1301769.3995  ┆ Hút sữa rảnh tay Animo ┆ ﻿﻿﻿﻿Máy hút sữa rảnh tay & không dây Animo  │
│               ┆               ┆                        ┆ với thiết kế không dây nhỏ gọn chắc     │
│               ┆               ┆                        ┆ chắn sẽ mang đến cho mẹ sự thoải mái và │
│               ┆               ┆                        ┆ tiện lợi cả khi làm việc hay chăm       │
│               ┆               ┆                        ┆ bé. Ưu điểm nổi bật . Thiết kế nhỏ gọn  │
│               ┆               ┆                        ┆ không dâ…                               │
│ 2520000000002 ┆ 829990.4489   ┆ Similac Step 4         ┆ ﻿﻿﻿﻿﻿Phát triển trí não và tăng cường miễn   │
│               ┆               ┆                        ┆ dịch đều rất quan trọng trong những năm │
│               ┆               ┆                        ┆ đầu đời. Để bé không bỏ lỡ giai đoạn    │
│               ┆               ┆                        ┆ phát triển vàng, ngay từ những ngày     │
│               ┆               ┆                        ┆ đầu, bé cần được cung cấp đầy đủ các    │
│               ┆               ┆                        ┆ dưỡng c…                                │
│ …             ┆ …             ┆ …                      ┆ …                                       │
│ 2513000000001 ┆ 1076579.3380  ┆ Pediasure Step 0       ┆ ﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿Thực phẩm dinh dưỡng y học Pediasure bổ │
│               ┆               ┆                        ┆ sung dinh dưỡng đầy đủ và cân đối,      │
│               ┆               ┆                        ┆ vitamin, khoáng chất giúp phục hồi sức  │
│               ┆               ┆                        ┆ khỏe, tăng trưởng tốt. Được phát triển  │
│               ┆               ┆                        ┆ liên tục từ năm 1988, PediaSure® …      │
│ 7243000000002 ┆ 849988.4270   ┆ Enspire Thái Step 4    ┆ ﻿﻿Sữa Enfagrow Enspire 3 là sản phẩm dành │
│               ┆               ┆                        ┆ cho các bé từ 2 đến 6 tuổi. Với thành   │
│               ┆               ┆                        ┆ phần Lactoferrin, sản phẩm ﻿﻿hỗ trợ giảm  │
│               ┆               ┆                        ┆ các triệu chứng về đường tiêu hóa và hô │
│               ┆               ┆                        ┆ hấp cho bé. …                           │
│ 5884000000004 ┆ 4835847.8660  ┆ Ghế nôi Joie           ┆ ﻿Nôi đưa giúp bé có giấc ngủ ngon và sâu │
│               ┆               ┆                        ┆ hơn, để mẹ đỡ vất vả ru bé ngủ mỗi      │
│               ┆               ┆                        ┆ ngày. Chứa hết, Sansa 2in1 là nôi đưa   │
│               ┆               ┆                        ┆ có thể tách ghế ra khỏi khung để di     │
│               ┆               ┆                        ┆ chuyển dễ dàng, giúp bé yêu luôn bên    │
│               ┆               ┆                        ┆ cạnh bạn tron…                          │
│ 2419000000004 ┆ 903000.0000   ┆ Ensure Adult           ┆ ﻿﻿Ensure Gold được chứng minh lâm sàng    │
│               ┆               ┆                        ┆ GIÚP TĂNG CƯỜNG SỨC KHỎE TRONG 8 TUẦN*﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿﻿  │
│               ┆               ┆                        ┆ Ưu điểm nổi bật. HMB giúp tăng cường    │
│               ┆               ┆                        ┆ sức khỏe khối cơ trong 8 tuần*.. YBG    │
│               ┆               ┆                        ┆ (Beta Glucan từ nấm men) và 12 dưỡng …  │
│ 6004000000005 ┆ 1566000.0000  ┆ Hút sữa điện đôi Fatz  ┆ Máy Hút Sữa Điện Đôi Resonance 3 Plus   │
│               ┆               ┆                        ┆ Fatzbaby FB1161VN là sự lựa chọn tuyệt  │
│               ┆               ┆                        ┆ vời giúp mẹ nuôi con bằng sữa mẹ nhàn   │
│               ┆               ┆                        ┆ tênh. ﻿﻿﻿﻿﻿﻿﻿Ưu điểm nổi bật . Kích thích sữa  │
│               ┆               ┆                        ┆ mẹ tiết ra nhiều hơn, làm dịu cơn đau   │
│               ┆               ┆                        ┆ t…                                      │
└───────────────┴───────────────┴────────────────────────┴─────────────────────────────────────────┘

In [18]:
import polars as pl

# 1. Lọc các item có giá > 10 triệu, lấy thêm quantity
items_over_10m = (
    df
    .filter(pl.col("price") < 3_000)
    .select(["item_id", "price", "quantity","discount"])
    .unique()
)

print("Số item có giá > 10 triệu:", items_over_10m.height)

# 2. Chuẩn bị bảng item chỉ giữ 2 cột để tối ưu
items_small = item.select([
    "item_id",
    "category_l1",
    "description",
    "sale_status",
    "price"
])

# 3. Join để xem category + description
items_info = (
    items_over_10m
    .join(items_small, on="item_id", how="left")
)

# 4. In toàn bộ bảng không bị rút gọn
pl.Config.set_tbl_rows(None)
pl.Config.set_tbl_cols(None)
pl.Config.set_fmt_str_lengths(200)

items_info.head(1000)

Số item có giá > 10 triệu: 23477

shape: (1_000, 8)
┌────────────┬────────────┬──────────┬────────────┬────────────┬───────────┬───────────┬───────────┐
│ item_id    ┆ price      ┆ quantity ┆ discount   ┆ category_l ┆ descripti ┆ sale_stat ┆ price_rig │
│ ---        ┆ ---        ┆ ---      ┆ ---        ┆ 1          ┆ on        ┆ us        ┆ ht        │
│ str        ┆ decimal[38 ┆ i32      ┆ decimal[38 ┆ ---        ┆ ---       ┆ ---       ┆ ---       │
│            ┆ ,4]        ┆          ┆ ,4]        ┆ str        ┆ str       ┆ i32       ┆ decimal[3 │
│            ┆            ┆          ┆            ┆            ┆           ┆           ┆ 8,4]      │
╞════════════╪════════════╪══════════╪════════════╪════════════╪═══════════╪═══════════╪═══════════╡
│ 0020020000 ┆ 118.9591   ┆ 1        ┆ 47881.0409 ┆ Thực phẩm  ┆ Custard   ┆ 0         ┆ 48000.000 │
│ 127        ┆            ┆          ┆            ┆ cho bé     ┆ Vani cho  ┆           ┆ 0         │
│            ┆            ┆          ┆            ┆            ┆ trẻ từ 6  ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ tháng     ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ tuổi trở  ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ lên -     ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ Heinz     ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ Vanilla   ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ Custard   ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ là thức   ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ ăn được   ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ chế biến  ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ sẵn từ    ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ thiên     ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ nhiên,    ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ đảm bảo   ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ đầy đủ    ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ dinh      ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ dưỡng cho ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ bé. Đặc   ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ điểm sản  ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ phẩm: -   ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ Thức ăn   ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ được chế  ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ biến sẵn  ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ từ th…    ┆           ┆           │
│ 1416000000 ┆ 2660.0000  ┆ 2        ┆ 43680.0000 ┆ Thực phẩm  ┆ Không xác ┆ 0         ┆ 35000.000 │
│ 002        ┆            ┆          ┆            ┆ cho bé     ┆ định      ┆           ┆ 0         │
│ 1320000000 ┆ 2900.0000  ┆ 1        ┆ 33500.0000 ┆ Thực phẩm  ┆ ﻿Thành     ┆ 1         ┆ 61000.000 │
│ 008        ┆            ┆          ┆            ┆ cho bé     ┆ phần      ┆           ┆ 0         │
│            ┆            ┆          ┆            ┆            ┆ nguyên    ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ liệu: Bột ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ mì,       ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ đường,    ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ dầu cọ,   ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ bột ca    ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ cao giảm  ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ chất béo  ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ (3,8%),   ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ si rô     ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ đường     ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ nghịch    ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ chuyển,   ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ chất tạo  ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ xốp (INS  ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ 500(i),   ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ INS       ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ 450(i)),  ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ bơ, sữa   ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ bột       ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ nguyên    ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ kem,      ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ muối,     ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ chất nhũ  ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ hóa từ    ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ đậu nàn…  ┆           ┆           │
│ 6994000000 ┆ 2656.7164  ┆ 1        ┆ 86343.2836 ┆ Thời trang ┆ Không xác ┆ 0         ┆ 69000.000 │
│ 003        ┆            ┆          ┆            ┆            ┆ định      ┆           ┆ 0         │
│ 2707000000 ┆ 2857.0476  ┆ 2        ┆ 285.9048   ┆ Thực phẩm  ┆ Kẹo dẻo   ┆ 1         ┆ 3000.0000 │
│ 001        ┆            ┆          ┆            ┆ cho bé     ┆ trái cây  ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ Chupa     ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ Chups 8g  ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ với hương ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ vị thơm   ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ ngon sẽ   ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ là món đồ ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ ăn vặt    ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ siêu hấp  ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ dẫn đối   ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ với mọi   ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ lứa       ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ tuổi. Ưu  ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ điểm nổi  ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ bật Kẹo   ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ dẻo Chupa ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ Chups nổi ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ tiếng,    ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ dai ngon  ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ hấp       ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ dẫnHướng  ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ dẫn sử    ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ dụngĂn    ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ trực ti…  ┆           ┆           │
│ …          ┆ …          ┆ …        ┆ …          ┆ …          ┆ …         ┆ …         ┆ …         │
│ 6501000000 ┆ 200.0000   ┆ 1        ┆ 58800.0000 ┆ Thực phẩm  ┆ Xúc Xích  ┆ 1         ┆ 59000.000 │
│ 006        ┆            ┆          ┆            ┆ cho bé     ┆ Tiệt      ┆           ┆ 0         │
│            ┆            ┆          ┆            ┆            ┆ Trùng     ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ Goldkids  ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ Cá hồi &  ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ Phô       ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ Mai ﻿mang  ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ trọn      ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ dưỡng     ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ chất từ   ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ cá tươi   ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ của C.P.  ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ kết hợp   ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ cùng phô  ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ mai béo   ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ ngon hấp  ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ dẫn, bổ   ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ sung thêm ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ DHA,      ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ vitamin   ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ D3, kẽm   ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ hỗ trợ sự ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ phát      ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ triển của ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ con.Ưu    ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ điểm nổ…  ┆           ┆           │
│ 0020020000 ┆ 2884.6154  ┆ 4        ┆ 108461.538 ┆ Thực phẩm  ┆ ﻿﻿﻿Chúng tôi ┆ 1         ┆ 25000.000 │
│ 173        ┆            ┆          ┆ 4          ┆ cho bé     ┆ biết rằng ┆           ┆ 0         │
│            ┆            ┆          ┆            ┆            ┆ bữa ăn    ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ tốt cho   ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ trẻ là từ ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ các món   ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ ăn mẹ     ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ nấu. Vì   ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ vậy chúng ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ tôi tạo   ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ ra sản    ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ phẩm Cháo ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ tươi Sài  ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ Gòn       ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ Food theo ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ đúng cách ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ mà bạn    ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ nấu ăn    ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ tại       ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ nhà.Bao   ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ bì mớiBao ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ bì cũ ĐẶC ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ ĐIỂM SẢN  ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ PHẨM Sả…  ┆           ┆           │
│ 5506000000 ┆ 100.0000   ┆ 1        ┆ 118900.000 ┆ Thực phẩm  ┆ ﻿﻿Bánh gạo  ┆ 1         ┆ 119000.00 │
│ 004        ┆            ┆          ┆ 0          ┆ cho bé     ┆ hữu cơ    ┆           ┆ 00        │
│            ┆            ┆          ┆            ┆            ┆ Gerber    ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ Organic   ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ vị xoài   ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ chuối cà  ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ rốt được  ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ làm từ    ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ trái cây  ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ thật,     ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ không     ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ chứa      ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ hương     ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ liệu nên  ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ an toàn   ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ cho sức   ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ khoẻ bé   ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ yêu. Sản  ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ phẩm với  ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ vị xoài,  ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ chuối     ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ cùng cà   ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ rốt giúp  ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ kích      ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ thích vị  ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ giác …    ┆           ┆           │
│ 2793000000 ┆ 2023.2824  ┆ 1        ┆ 59976.7176 ┆ Thực phẩm  ┆ ﻿﻿﻿﻿Váng sữa  ┆ 1         ┆ 66000.000 │
│ 003        ┆            ┆          ┆            ┆ cho bé     ┆ Hoff -    ┆           ┆ 0         │
│            ┆            ┆          ┆            ┆            ┆ Vani (Lốc ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ 4 hủ)Bao  ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ bì mới    ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ Bao bì cũ ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ Ưu điểm   ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ nổi bật.  ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ Váng sữa  ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ Hoff chứa ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ nhiều     ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ dưỡng     ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ chất vượt ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ trội cần  ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ thiết cho ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ nhu cầu   ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ hàng ngày ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ của trẻ   ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ như:      ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ protein,  ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ năng      ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ lượng,    ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ chất béo, ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ vitam…    ┆           ┆           │
│ 6889000000 ┆ 149.5826   ┆ 1        ┆ 31850.4174 ┆ Thực phẩm  ┆ ﻿Mỳ Ý thịt ┆ 1         ┆ 32000.000 │
│ 005        ┆            ┆          ┆            ┆ cho bé     ┆ thăn xốt  ┆           ┆ 0         │
│            ┆            ┆          ┆            ┆            ┆ cà chua   ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ SG Food   ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ 200g là   ┆           ┆           │
│            ┆            ┆          ┆            ┆            ┆ thức ăn   ┆           ┆           │

In [34]:
trans_small = df.select([
    "item_id",
    "price",
    "discount",
    "quantity",
    "created_date"
])

item_small = item.select([
    "item_id",
    "sale_status",
    "category_l1"
])

trans_item = trans_small.join(item_small, on="item_id", how="left")

In [25]:
trans_item.columns

['item_id', 'price', 'discount', 'quantity', 'sale_status']

In [28]:
trans_item = trans_item.with_columns([
    pl.col("price").cast(pl.Float64),
    pl.col("discount").cast(pl.Float64)
])

In [29]:
trans_item.group_by("sale_status").agg([
    pl.count().alias("num_tx"),
    pl.col("price").mean(),
    pl.col("discount").mean(),
    pl.col("quantity").mean()
])

C:\Users\tncn2\AppData\Local\Temp\ipykernel_16404\2491929959.py:2: DeprecationWarning: `pl.count()` is deprecated. Please use `pl.len()` instead.
(Deprecated in version 0.20.5)
  pl.count().alias("num_tx"),

shape: (2, 5)
┌─────────────┬──────────┬───────────────┬──────────────┬──────────┐
│ sale_status ┆ num_tx   ┆ price         ┆ discount     ┆ quantity │
│ ---         ┆ ---      ┆ ---           ┆ ---          ┆ ---      │
│ i32         ┆ u32      ┆ f64           ┆ f64          ┆ f64      │
╞═════════════╪══════════╪═══════════════╪══════════════╪══════════╡
│ 1           ┆ 25534698 ┆ 160351.71657  ┆ 14008.991442 ┆ 1.600646 │
│ 0           ┆ 10195127 ┆ 191321.942816 ┆ 25317.140324 ┆ 1.276304 │
└─────────────┴──────────┴───────────────┴──────────────┴──────────┘

In [32]:
trans_item.group_by(["category_l1", "sale_status"]).agg(pl.count())

C:\Users\tncn2\AppData\Local\Temp\ipykernel_16404\2152445573.py:1: DeprecationWarning: `pl.count()` is deprecated. Please use `pl.len()` instead.
(Deprecated in version 0.20.5)
  trans_item.group_by(["category_l1", "sale_status"]).agg(pl.count())

shape: (28, 3)
┌──────────────────────┬─────────────┬─────────┐
│ category_l1          ┆ sale_status ┆ count   │
│ ---                  ┆ ---         ┆ ---     │
│ str                  ┆ i32         ┆ u32     │
╞══════════════════════╪═════════════╪═════════╡
│ Textile              ┆ 0           ┆ 248346  │
│ Hóa mỹ phẩm cho bé   ┆ 0           ┆ 549677  │
│ Đồ chơi & Sách       ┆ 0           ┆ 411757  │
│ Sữa                  ┆ 1           ┆ 3253920 │
│ Thực phẩm cho bé     ┆ 0           ┆ 1598052 │
│ …                    ┆ …           ┆ …       │
│ TPCN                 ┆ 1           ┆ 1089423 │
│ Hóa mỹ phẩm gia đình ┆ 0           ┆ 252096  │
│ Thời trang           ┆ 1           ┆ 124443  │
│ Thời trang           ┆ 0           ┆ 1898264 │
│ Textile              ┆ 1           ┆ 419295  │
└──────────────────────┴─────────────┴─────────┘

In [35]:
trans_item = trans_item.with_columns(
    pl.col("created_date").dt.strftime("%Y-%m").alias("year_month")
)

In [36]:
status_timeline = (
    trans_item
    .group_by(["item_id", "year_month"])
    .agg([
        pl.col("sale_status").n_unique().alias("status_unique"),
        pl.col("sale_status").mode().alias("status_mode"),
        pl.count().alias("num_tx")
    ])
)

C:\Users\tncn2\AppData\Local\Temp\ipykernel_16404\3911286663.py:7: DeprecationWarning: `pl.count()` is deprecated. Please use `pl.len()` instead.
(Deprecated in version 0.20.5)
  pl.count().alias("num_tx")

In [37]:
changed_items = (
    status_timeline
    .group_by("item_id")
    .agg(pl.col("status_mode").n_unique().alias("num_statuses"))
    .filter(pl.col("num_statuses") > 1)
)

In [39]:
changed_items.head()

shape: (0, 2)
┌─────────┬──────────────┐
│ item_id ┆ num_statuses │
│ ---     ┆ ---          │
│ str     ┆ u32          │
╞═════════╪══════════════╡
└─────────┴──────────────┘

In [11]:
pl.Config.set_tbl_rows(None)
pl.Config.set_tbl_cols(None)
pl.Config.set_fmt_str_lengths(10_000)

polars.config.Config

In [12]:
df = df.join(
    item.select(["item_id", "category_l1"]),
    on="item_id",
    how="left"
)

In [40]:
import polars as pl

# 1. Lọc item có giá > 10 triệu
items_over_10m = (
    df
    .filter(pl.col("price") < 1_000)
    .select(["item_id"])
    .unique()
)

# 2. Chỉ lấy item_id + category từ bảng item
items_small = item.select([
    "item_id",
    "category"
])

# 3. Join để gắn category vào danh sách item >10tr
joined = (
    items_over_10m
        .join(items_small, on="item_id", how="left")
)

# 4. Group by category và đếm số lượng
category_count = (
    joined
        .group_by("category")
        .agg(pl.count().alias("num_items_over_10m"))
        .sort("num_items_over_10m", descending=True)
)

# 5. In kết quả
pl.Config.set_tbl_rows(None)
print(category_count)

shape: (743, 2)
┌─────────────────────────────────┬────────────────────┐
│ category                        ┆ num_items_over_10m │
│ ---                             ┆ ---                │
│ str                             ┆ u32                │
╞═════════════════════════════════╪════════════════════╡
│ Bộ bé trai Animo                ┆ 127                │
│ Bộ Modal lẻ                     ┆ 103                │
│ Xe mô hình/hoạt hình            ┆ 55                 │
│ Bộ bé gái Animo                 ┆ 51                 │
│ Bộ bé trai Animo Easy           ┆ 50                 │
│ …                               ┆ …                  │
│ Kids Boost Step 3               ┆ 1                  │
│ Blackmores                      ┆ 1                  │
│ Phụ kiện Edison                 ┆ 1                  │
│ Dầu tràm khác                   ┆ 1                  │
│ Khăn tắm gia đình Sợi sồi Animo ┆ 1                  │
└─────────────────────────────────┴────────────────────┘

C:\Users\tncn2\AppData\Local\Temp\ipykernel_13564\1418590508.py:27: DeprecationWarning: `pl.count()` is deprecated. Please use `pl.len()` instead.
(Deprecated in version 0.20.5)
  .agg(pl.count().alias("num_items_over_10m"))

In [36]:
stats = (
    df.join(item.select(["item_id", "category"]), on="item_id")
      .filter(pl.col("category") == "Abbott Grow")
      .select([
          pl.col("price").quantile(0.01).alias("p1"),
          pl.col("price").quantile(0.05).alias("p5"),
          pl.col("price").median().alias("median")
      ])
)

In [37]:
print(stats)

shape: (1, 3)
┌─────────┬────────────┬─────────┐
│ p1      ┆ p5         ┆ median  │
│ ---     ┆ ---        ┆ ---     │
│ f64     ┆ f64        ┆ f64     │
╞═════════╪════════════╪═════════╡
│ 35000.0 ┆ 41965.1838 ┆ 50000.0 │
└─────────┴────────────┴─────────┘

# 2

## discount_rate

In [12]:
df.head()

shape: (5, 9)
┌────────────┬────────────┬──────────┬────────────┬───┬──────────┬──────────┬──────────┬───────────┐
│ item_id    ┆ price      ┆ quantity ┆ customer_i ┆ … ┆ channel  ┆ payment  ┆ location ┆ discount  │
│ ---        ┆ ---        ┆ ---      ┆ d          ┆   ┆ ---      ┆ ---      ┆ ---      ┆ ---       │
│ str        ┆ decimal[38 ┆ i32      ┆ ---        ┆   ┆ str      ┆ str      ┆ i32      ┆ decimal[3 │
│            ┆ ,4]        ┆          ┆ i32        ┆   ┆          ┆          ┆          ┆ 8,4]      │
╞════════════╪════════════╪══════════╪════════════╪═══╪══════════╪══════════╪══════════╪═══════════╡
│ 7115000000 ┆ 49000.0000 ┆ 1        ┆ 5254214    ┆ … ┆ In-Store ┆ VietQR   ┆ 656      ┆ 0.0000    │
│ 004        ┆            ┆          ┆            ┆   ┆          ┆          ┆          ┆           │
│ 0029130000 ┆ 69000.0000 ┆ 1        ┆ 7573232    ┆ … ┆ In-Store ┆ Tiền mặt ┆ 143      ┆ 0.0000    │
│ 030        ┆            ┆          ┆            ┆   ┆          ┆          ┆          ┆           │
│ 3496000000 ┆ 75000.0000 ┆ 2        ┆ 8187418    ┆ … ┆ In-Store ┆ MoMo     ┆ 213      ┆ 0.0000    │
│ 053        ┆            ┆          ┆            ┆   ┆          ┆          ┆          ┆           │
│ 2700000000 ┆ 58500.0000 ┆ 2        ┆ 8187418    ┆ … ┆ In-Store ┆ MoMo     ┆ 213      ┆ 13000.000 │
│ 002        ┆            ┆          ┆            ┆   ┆          ┆          ┆          ┆ 0         │
│ 0029110000 ┆ 89000.0000 ┆ 1        ┆ 6931560    ┆ … ┆ Android  ┆ MoMo     ┆ 590      ┆ 10000.000 │
│ 036        ┆            ┆          ┆            ┆   ┆          ┆          ┆          ┆ 0         │
└────────────┴────────────┴──────────┴────────────┴───┴──────────┴──────────┴──────────┴───────────┘

In [11]:
# df: transaction dataframe
# item: item dataframe

# 1. Join transaction với item để lấy price gốc + category_l1
df_joined = (
    df.join(
        item.select(["item_id", "price", "category_l2"])  # price gốc từ item
             .rename({"price": "list_price"}),          # đổi tên để tránh trùng
        on="item_id",
        how="left"
    )
)

# 2. Tính discount_rate
df_with_discount = df_joined.with_columns([
    (1 - (pl.col("price") / pl.col("list_price")))  # price trong df là giá sau giảm
        .alias("discount_rate")
])

df_with_discount.head()

shape: (5, 12)
┌───────────┬───────────┬──────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ item_id   ┆ price     ┆ quantity ┆ customer_ ┆ … ┆ discount  ┆ list_pric ┆ category_ ┆ discount_ │
│ ---       ┆ ---       ┆ ---      ┆ id        ┆   ┆ ---       ┆ e         ┆ l2        ┆ rate      │
│ str       ┆ decimal[3 ┆ i32      ┆ ---       ┆   ┆ decimal[3 ┆ ---       ┆ ---       ┆ ---       │
│           ┆ 8,4]      ┆          ┆ i32       ┆   ┆ 8,4]      ┆ decimal[3 ┆ str       ┆ decimal[3 │
│           ┆           ┆          ┆           ┆   ┆           ┆ 8,4]      ┆           ┆ 8,4]      │
╞═══════════╪═══════════╪══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 711500000 ┆ 49000.000 ┆ 1        ┆ 5254214   ┆ … ┆ 0.0000    ┆ 49000.000 ┆ Snack ăn  ┆ 0.0000    │
│ 0004      ┆ 0         ┆          ┆           ┆   ┆           ┆ 0         ┆ dặm       ┆           │
│ 002913000 ┆ 69000.000 ┆ 1        ┆ 7573232   ┆ … ┆ 0.0000    ┆ 74000.000 ┆ Bột ăn    ┆ 0.0676    │
│ 0030      ┆ 0         ┆          ┆           ┆   ┆           ┆ 0         ┆ dặm       ┆           │
│ 349600000 ┆ 75000.000 ┆ 2        ┆ 8187418   ┆ … ┆ 0.0000    ┆ 75000.000 ┆ Quần áo & ┆ 0.0000    │
│ 0053      ┆ 0         ┆          ┆           ┆   ┆           ┆ 0         ┆ Phụ kiện  ┆           │
│           ┆           ┆          ┆           ┆   ┆           ┆           ┆ sơ sinh   ┆           │
│ 270000000 ┆ 58500.000 ┆ 2        ┆ 8187418   ┆ … ┆ 13000.000 ┆ 65000.000 ┆ Khăn khô  ┆ 0.1000    │
│ 0002      ┆ 0         ┆          ┆           ┆   ┆ 0         ┆ 0         ┆           ┆           │
│ 002911000 ┆ 89000.000 ┆ 1        ┆ 6931560   ┆ … ┆ 10000.000 ┆ 99000.000 ┆ Snack ăn  ┆ 0.1010    │
│ 0036      ┆ 0         ┆          ┆           ┆   ┆ 0         ┆ 0         ┆ dặm       ┆           │
└───────────┴───────────┴──────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [12]:
df_with_discount = df_with_discount.with_columns([
    pl.col("discount_rate").clip(lower_bound=0).alias("discount_rate")
])

In [13]:
df_with_discount.select([
    pl.col("discount_rate").min().alias("min"),
    pl.col("discount_rate").quantile(0.25).alias("q25"),
    pl.col("discount_rate").median().alias("median"),
    pl.col("discount_rate").quantile(0.75).alias("q75"),
    pl.col("discount_rate").max().alias("max"),
    pl.col("discount_rate").mean().alias("mean"),
    pl.col("discount_rate").std().alias("std"),
])

shape: (1, 7)
┌───────────────┬─────┬────────┬──────┬───────────────┬──────────┬──────────┐
│ min           ┆ q25 ┆ median ┆ q75  ┆ max           ┆ mean     ┆ std      │
│ ---           ┆ --- ┆ ---    ┆ ---  ┆ ---           ┆ ---      ┆ ---      │
│ decimal[38,4] ┆ f64 ┆ f64    ┆ f64  ┆ decimal[38,4] ┆ f64      ┆ f64      │
╞═══════════════╪═════╪════════╪══════╪═══════════════╪══════════╪══════════╡
│ 0.0000        ┆ 0.0 ┆ 0.0575 ┆ 0.15 ┆ 1.0000        ┆ 0.103784 ┆ 0.139744 │
└───────────────┴─────┴────────┴──────┴───────────────┴──────────┴──────────┘

In [21]:
def split_and_save_parquet(df, num_files, output_dir):
    """
    Tách DataFrame thành nhiều file Parquet và lưu vào thư mục đích.
    
    :param df: DataFrame cần tách
    :param num_files: Số lượng file Parquet muốn tách
    :param output_dir: Thư mục lưu các file Parquet
    """
    # Đảm bảo thư mục tồn tại
    os.makedirs(output_dir, exist_ok=True)
    
    # Tính số dòng mỗi file sẽ có
    num_rows = df.height
    rows_per_file = num_rows // num_files

    # Tách DataFrame thành các phần và lưu mỗi phần vào một file Parquet
    for i in range(num_files):
        start_row = i * rows_per_file
        # Đảm bảo phần cuối cùng sẽ chứa tất cả các dòng còn lại
        end_row = (i + 1) * rows_per_file if i < num_files - 1 else num_rows
        
        # Tách phần DataFrame
        split_df = df[start_row:end_row]
        
        # Lưu phần DataFrame vào file .parquet
        file_path = os.path.join(output_dir, f"sale_pers.purchase_history_daily_chunk_{i}.parquet")
        split_df.write_parquet(file_path)
        print(f"Đã lưu file: {file_path}")

In [22]:
split_and_save_parquet(
    df=df_with_discount,
    num_files=20,
    output_dir="preprocessed/transaction"
)

Đã lưu file: preprocessed/transaction\sale_pers.purchase_history_daily_chunk_0.parquet
Đã lưu file: preprocessed/transaction\sale_pers.purchase_history_daily_chunk_1.parquet
Đã lưu file: preprocessed/transaction\sale_pers.purchase_history_daily_chunk_2.parquet
Đã lưu file: preprocessed/transaction\sale_pers.purchase_history_daily_chunk_3.parquet
Đã lưu file: preprocessed/transaction\sale_pers.purchase_history_daily_chunk_4.parquet
Đã lưu file: preprocessed/transaction\sale_pers.purchase_history_daily_chunk_5.parquet
Đã lưu file: preprocessed/transaction\sale_pers.purchase_history_daily_chunk_6.parquet
Đã lưu file: preprocessed/transaction\sale_pers.purchase_history_daily_chunk_7.parquet
Đã lưu file: preprocessed/transaction\sale_pers.purchase_history_daily_chunk_8.parquet
Đã lưu file: preprocessed/transaction\sale_pers.purchase_history_daily_chunk_9.parquet
Đã lưu file: preprocessed/transaction\sale_pers.purchase_history_daily_chunk_10.parquet
Đã lưu file: preprocessed/transaction\sale_pers.purchase_history_daily_chunk_11.parquet
Đã lưu file: preprocessed/transaction\sale_pers.purchase_history_daily_chunk_12.parquet
Đã lưu file: preprocessed/transaction\sale_pers.purchase_history_daily_chunk_13.parquet
Đã lưu file: preprocessed/transaction\sale_pers.purchase_history_daily_chunk_14.parquet
Đã lưu file: preprocessed/transaction\sale_pers.purchase_history_daily_chunk_15.parquet
Đã lưu file: preprocessed/transaction\sale_pers.purchase_history_daily_chunk_16.parquet
Đã lưu file: preprocessed/transaction\sale_pers.purchase_history_daily_chunk_17.parquet
Đã lưu file: preprocessed/transaction\sale_pers.purchase_history_daily_chunk_18.parquet
Đã lưu file: preprocessed/transaction\sale_pers.purchase_history_daily_chunk_19.parquet