# Load Data

In [1]:
import os
import polars as pl
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

In [2]:
def read_parquet_user(train_path: str):
    # Lấy tất cả các file parquet trong thư mục
    files = [os.path.join(train_path, f) for f in os.listdir(train_path) if f.endswith('.parquet')]
    
    # Phân loại các file theo loại tên
    user_chunk_files = [file for file in files if 'user_chunk' in file]
        
    # Đọc các file riêng biệt thành DataFrame
    user_chunk_df = pl.concat([pl.read_parquet(file) for file in user_chunk_files]) if user_chunk_files else None
        
    # Trả về một dictionary chứa các DataFrame
    return user_chunk_df

In [3]:
def read_parquet_item(train_path: str):
    # Lấy tất cả các file parquet trong thư mục
    files = [os.path.join(train_path, f) for f in os.listdir(train_path) if f.endswith('.parquet')]
    
    # Phân loại các file theo loại tên
    item_chunk_files = [file for file in files if 'item_chunk' in file]
        
    # Đọc các file riêng biệt thành DataFrame
    item_chunk_df = pl.concat([pl.read_parquet(file) for file in item_chunk_files]) if item_chunk_files else None
        
    # Trả về một dictionary chứa các DataFrame
    return item_chunk_df

In [4]:
def read_parquet_transaction(train_path: str):
    # Lấy tất cả các file parquet trong thư mục
    files = [os.path.join(train_path, f) for f in os.listdir(train_path) if f.endswith('.parquet')]
    
    # Phân loại các file theo loại tên
    purchase_chunk_files = [file for file in files if 'purchase_history_daily_chunk' in file]
        
    # Đọc các file riêng biệt thành DataFrame
    purchase_chunk_df = pl.concat([pl.read_parquet(file) for file in purchase_chunk_files]) if purchase_chunk_files else None
        
    # Trả về một dictionary chứa các DataFrame
    return purchase_chunk_df

In [5]:
def split_and_save_parquet(df, num_files, output_dir):
    """
    Tách DataFrame thành nhiều file Parquet và lưu vào thư mục đích.
    
    :param df: DataFrame cần tách
    :param num_files: Số lượng file Parquet muốn tách
    :param output_dir: Thư mục lưu các file Parquet
    """
    # Đảm bảo thư mục tồn tại
    os.makedirs(output_dir, exist_ok=True)
    
    # Tính số dòng mỗi file sẽ có
    num_rows = df.height
    rows_per_file = num_rows // num_files

    # Tách DataFrame thành các phần và lưu mỗi phần vào một file Parquet
    for i in range(num_files):
        start_row = i * rows_per_file
        # Đảm bảo phần cuối cùng sẽ chứa tất cả các dòng còn lại
        end_row = (i + 1) * rows_per_file if i < num_files - 1 else num_rows
        
        # Tách phần DataFrame
        split_df = df[start_row:end_row]
        
        # Lưu phần DataFrame vào file .parquet
        file_path = os.path.join(output_dir, f"sale_pers.user_chunk_{i}.parquet")
        split_df.write_parquet(file_path)
        print(f"Đã lưu file: {file_path}")

In [22]:
item = read_parquet_item('dataset')
item.head()

shape: (5, 34)
┌───────┬────────────┬────────────┬────────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ p_id  ┆ item_id    ┆ price      ┆ category_l ┆ … ┆ volume    ┆ material  ┆ sale_stat ┆ descripti │
│ ---   ┆ ---        ┆ ---        ┆ 1_id       ┆   ┆ ---       ┆ ---       ┆ us        ┆ on_new    │
│ i32   ┆ str        ┆ decimal[38 ┆ ---        ┆   ┆ str       ┆ str       ┆ ---       ┆ ---       │
│       ┆            ┆ ,4]        ┆ i32        ┆   ┆           ┆           ┆ i32       ┆ str       │
╞═══════╪════════════╪════════════╪════════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 17065 ┆ 0502020000 ┆ 99000.0000 ┆ 1          ┆ … ┆ Không xác ┆ Không xác ┆ 0         ┆ Chi tiết  │
│       ┆ 004        ┆            ┆            ┆   ┆ định      ┆ định      ┆           ┆ sản phẩm  │
│       ┆            ┆            ┆            ┆   ┆           ┆           ┆           ┆ …         │
│ 72370 ┆ 0010290040 ┆ 69000.0000 ┆ 3292       ┆ … ┆ Không xác ┆ Không xác ┆ 0         ┆ Không xác │
│       ┆ 150        ┆            ┆            ┆   ┆ định      ┆ định      ┆           ┆ định      │
│ 31154 ┆ 0008010000 ┆ 45000.0000 ┆ 351        ┆ … ┆ Không xác ┆ Không xác ┆ 0         ┆ Chi tiết  │
│       ┆ 015        ┆            ┆            ┆   ┆ định      ┆ định      ┆           ┆ sản phẩm  │
│       ┆            ┆            ┆            ┆   ┆           ┆           ┆           ┆ …         │
│ 46123 ┆ 0020010000 ┆ 401000.000 ┆ 2222       ┆ … ┆ Không xác ┆ Giấy, bột ┆ 0         ┆ Không xác │
│       ┆ 094        ┆ 0          ┆            ┆   ┆ định      ┆ giấy, vải ┆           ┆ định      │
│       ┆            ┆            ┆            ┆   ┆           ┆ không     ┆           ┆           │
│       ┆            ┆            ┆            ┆   ┆           ┆ dệt,…     ┆           ┆           │
│ 46127 ┆ 0020010000 ┆ 401000.000 ┆ 2222       ┆ … ┆ Không xác ┆ Giấy, bột ┆ 0         ┆ Không xác │
│       ┆ 098        ┆ 0          ┆            ┆   ┆ định      ┆ giấy, vải ┆           ┆ định      │
│       ┆            ┆            ┆            ┆   ┆           ┆ không     ┆           ┆           │
│       ┆            ┆            ┆            ┆   ┆           ┆ dệt,…     ┆           ┆           │
└───────┴────────────┴────────────┴────────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [8]:
trans = read_parquet_transaction("./preprocessed")
trans.head()

shape: (5, 12)
┌───────────┬───────────┬──────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ item_id   ┆ price     ┆ quantity ┆ customer_ ┆ … ┆ discount  ┆ list_pric ┆ category_ ┆ discount_ │
│ ---       ┆ ---       ┆ ---      ┆ id        ┆   ┆ ---       ┆ e         ┆ l2        ┆ rate      │
│ str       ┆ decimal[3 ┆ i32      ┆ ---       ┆   ┆ decimal[3 ┆ ---       ┆ ---       ┆ ---       │
│           ┆ 8,4]      ┆          ┆ i32       ┆   ┆ 8,4]      ┆ decimal[3 ┆ str       ┆ decimal[3 │
│           ┆           ┆          ┆           ┆   ┆           ┆ 8,4]      ┆           ┆ 8,4]      │
╞═══════════╪═══════════╪══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 711500000 ┆ 49000.000 ┆ 1        ┆ 5254214   ┆ … ┆ 0.0000    ┆ 49000.000 ┆ Snack ăn  ┆ 0.0000    │
│ 0004      ┆ 0         ┆          ┆           ┆   ┆           ┆ 0         ┆ dặm       ┆           │
│ 002913000 ┆ 69000.000 ┆ 1        ┆ 7573232   ┆ … ┆ 0.0000    ┆ 74000.000 ┆ Bột ăn    ┆ 0.0676    │
│ 0030      ┆ 0         ┆          ┆           ┆   ┆           ┆ 0         ┆ dặm       ┆           │
│ 349600000 ┆ 75000.000 ┆ 2        ┆ 8187418   ┆ … ┆ 0.0000    ┆ 75000.000 ┆ Quần áo & ┆ 0.0000    │
│ 0053      ┆ 0         ┆          ┆           ┆   ┆           ┆ 0         ┆ Phụ kiện  ┆           │
│           ┆           ┆          ┆           ┆   ┆           ┆           ┆ sơ sinh   ┆           │
│ 270000000 ┆ 58500.000 ┆ 2        ┆ 8187418   ┆ … ┆ 13000.000 ┆ 65000.000 ┆ Khăn khô  ┆ 0.1000    │
│ 0002      ┆ 0         ┆          ┆           ┆   ┆ 0         ┆ 0         ┆           ┆           │
│ 002911000 ┆ 89000.000 ┆ 1        ┆ 6931560   ┆ … ┆ 10000.000 ┆ 99000.000 ┆ Snack ăn  ┆ 0.1010    │
│ 0036      ┆ 0         ┆          ┆           ┆   ┆ 0         ┆ 0         ┆ dặm       ┆           │
└───────────┴───────────┴──────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

# Discount user: Người dùng đó có mua hàng discount hay k. Tính dựa trên số lần mua trong tháng
Đo xu hướng săn discount dài hạn của user, không phụ thuộc vào một tháng cụ thể.
Trung bình mỗi tháng, user này mua bao nhiêu giao dịch có discount?

In [ ]:
user_month = (
    trans
    .with_columns([
        pl.col("created_date").dt.truncate("1mo").alias("month"),
        (pl.col("discount_rate") > 0).cast(pl.Int8).alias("is_discount")
    ])
    .group_by(["customer_id", "month"])
    .agg([
        pl.count().alias("total_tx_count"),
        pl.sum("is_discount").alias("discount_tx_count")
    ])
    .with_columns(
        (pl.col("discount_tx_count") / pl.col("total_tx_count"))
        .fill_null(0)
        .alias("discount_ratio")
    )
)

C:\Users\tncn2\AppData\Local\Temp\ipykernel_25196\1278981641.py:9: DeprecationWarning: `pl.count()` is deprecated. Please use `pl.len()` instead.
(Deprecated in version 0.20.5)
  pl.count().alias("total_tx_count"),

In [10]:
user_discount_profile = (
    user_month
    .group_by("customer_id")
    .agg([
        pl.mean("discount_tx_count").alias("avg_discount_tx_per_month"),
        pl.mean("discount_ratio").alias("avg_discount_ratio"),
        pl.count().alias("active_months")
    ])
)

C:\Users\tncn2\AppData\Local\Temp\ipykernel_25196\1261084741.py:7: DeprecationWarning: `pl.count()` is deprecated. Please use `pl.len()` instead.
(Deprecated in version 0.20.5)
  pl.count().alias("active_months")

In [11]:
X = user_discount_profile.select([
    "avg_discount_tx_per_month",
    "avg_discount_ratio"
]).to_numpy()

In [12]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

In [13]:
from sklearn.cluster import KMeans

kmeans = KMeans(
    n_clusters=3,
    random_state=42,
    n_init=10
)

cluster_raw = kmeans.fit_predict(X_scaled)

In [14]:
user_discount_profile = user_discount_profile.with_columns(
    pl.Series("discount_cluster_raw", cluster_raw)
)

In [ ]:
cluster_order = (
    user_discount_profile
    .group_by("discount_cluster_raw")
    .agg([
        pl.mean("avg_discount_tx_per_month").alias("mean_tx"),
        pl.mean("avg_discount_ratio").alias("mean_ratio")
    ])
    .sort(["mean_tx", "mean_ratio"])
    .with_row_index("discount_behavior_level")  
)

In [16]:
user_discount_profile = (
    user_discount_profile
    .join(
        cluster_order.select([
            "discount_cluster_raw",
            "discount_behavior_level"
        ]),
        on="discount_cluster_raw",
        how="left"
    )
    .drop("discount_cluster_raw")
)

In [17]:
user_discount_profile.head()

shape: (5, 5)
┌─────────────┬───────────────────────┬────────────────────┬───────────────┬───────────────────────┐
│ customer_id ┆ avg_discount_tx_per_m ┆ avg_discount_ratio ┆ active_months ┆ discount_behavior_lev │
│ ---         ┆ onth                  ┆ ---                ┆ ---           ┆ el                    │
│ i32         ┆ ---                   ┆ f64                ┆ u32           ┆ ---                   │
│             ┆ f64                   ┆                    ┆               ┆ u32                   │
╞═════════════╪═══════════════════════╪════════════════════╪═══════════════╪═══════════════════════╡
│ 5072549     ┆ 0.75                  ┆ 0.5625             ┆ 8             ┆ 0                     │
│ 7661624     ┆ 1.0                   ┆ 1.0                ┆ 1             ┆ 1                     │
│ 7333941     ┆ 1.0                   ┆ 1.0                ┆ 2             ┆ 1                     │
│ 6871619     ┆ 7.166667              ┆ 0.635943           ┆ 12            ┆ 2                     │
│ 8176263     ┆ 1.0                   ┆ 1.0                ┆ 1             ┆ 1                     │
└─────────────┴───────────────────────┴────────────────────┴───────────────┴───────────────────────┘

- avg_discount_tx_per_month: Trung bình, mỗi tháng user mua bao nhiêu giao dịch giảm giá?
- avg_discount_ratio: tỷ lệ trung bình các giao dịch có giảm giá của một người dùng, được tính trên tất cả các tháng người dùng có phát sinh giao dịch
- active_months: Số tháng user có ít nhất 1 giao dịch
- discount_behavior_level: mức độ mua hàng discount của user (0,1,2)

In [18]:
user_discount_profile.group_by("discount_behavior_level").agg(
    pl.count().alias("num_users")
).sort("discount_behavior_level")

C:\Users\tncn2\AppData\Local\Temp\ipykernel_25196\632212740.py:2: DeprecationWarning: `pl.count()` is deprecated. Please use `pl.len()` instead.
(Deprecated in version 0.20.5)
  pl.count().alias("num_users")

shape: (3, 2)
┌─────────────────────────┬───────────┐
│ discount_behavior_level ┆ num_users │
│ ---                     ┆ ---       │
│ u32                     ┆ u32       │
╞═════════════════════════╪═══════════╡
│ 0                       ┆ 926886    │
│ 1                       ┆ 1335024   │
│ 2                       ┆ 180396    │
└─────────────────────────┴───────────┘

In [19]:
user_discount_profile.group_by("discount_behavior_level").agg([
    pl.mean("avg_discount_tx_per_month").alias("mean_discount_tx_per_month"),
    pl.median("avg_discount_tx_per_month").alias("median_discount_tx_per_month"),
    pl.mean("avg_discount_ratio").alias("mean_discount_ratio"),
    pl.mean("active_months").alias("mean_active_months")
]).sort("discount_behavior_level")

shape: (3, 5)
┌───────────────────┬───────────────────┬───────────────────┬───────────────────┬──────────────────┐
│ discount_behavior ┆ mean_discount_tx_ ┆ median_discount_t ┆ mean_discount_rat ┆ mean_active_mont │
│ _level            ┆ per_month         ┆ x_per_month       ┆ io                ┆ hs               │
│ ---               ┆ ---               ┆ ---               ┆ ---               ┆ ---              │
│ u32               ┆ f64               ┆ f64               ┆ f64               ┆ f64              │
╞═══════════════════╪═══════════════════╪═══════════════════╪═══════════════════╪══════════════════╡
│ 0                 ┆ 0.798092          ┆ 0.666667          ┆ 0.23787           ┆ 2.289935         │
│ 1                 ┆ 2.061093          ┆ 2.0               ┆ 0.85754           ┆ 3.056415         │
│ 2                 ┆ 8.438825          ┆ 7.0               ┆ 0.69611           ┆ 6.457294         │
└───────────────────┴───────────────────┴───────────────────┴───────────────────┴──────────────────┘

In [20]:
user_discount_profile.head()

shape: (5, 5)
┌─────────────┬───────────────────────┬────────────────────┬───────────────┬───────────────────────┐
│ customer_id ┆ avg_discount_tx_per_m ┆ avg_discount_ratio ┆ active_months ┆ discount_behavior_lev │
│ ---         ┆ onth                  ┆ ---                ┆ ---           ┆ el                    │
│ i32         ┆ ---                   ┆ f64                ┆ u32           ┆ ---                   │
│             ┆ f64                   ┆                    ┆               ┆ u32                   │
╞═════════════╪═══════════════════════╪════════════════════╪═══════════════╪═══════════════════════╡
│ 5072549     ┆ 0.75                  ┆ 0.5625             ┆ 8             ┆ 0                     │
│ 7661624     ┆ 1.0                   ┆ 1.0                ┆ 1             ┆ 1                     │
│ 7333941     ┆ 1.0                   ┆ 1.0                ┆ 2             ┆ 1                     │
│ 6871619     ┆ 7.166667              ┆ 0.635943           ┆ 12            ┆ 2                     │
│ 8176263     ┆ 1.0                   ┆ 1.0                ┆ 1             ┆ 1                     │
└─────────────┴───────────────────────┴────────────────────┴───────────────┴───────────────────────┘

In [21]:
split_and_save_parquet(
    df=user_discount_profile,
    num_files=1,
    output_dir="feature_engineered"
)

Đã lưu file: feature_engineered\sale_pers.user_chunk_0.parquet

In [35]:
# Chỉ giữ cột cần thiết để tránh nặng
item_cat = item.select(["item_id", "category_l1"])

# Join category vào transaction
trans_cat = (
    trans
    .select(["customer_id", "item_id"])
    .join(item_cat, on="item_id", how="left")
    .filter(pl.col("category_l1").is_not_null())
)

In [36]:
user_cat_cnt = (
    trans_cat
    .group_by(["customer_id", "category_l1"])
    .agg(
        pl.count().alias("cnt")
    )
)

C:\Users\tncn2\AppData\Local\Temp\ipykernel_25196\3875378938.py:5: DeprecationWarning: `pl.count()` is deprecated. Please use `pl.len()` instead.
(Deprecated in version 0.20.5)
  pl.count().alias("cnt")

In [37]:
user_cat_wide = (
    user_cat_cnt
    .pivot(
        index="customer_id",
        columns="category_l1",
        values="cnt"
    )
    .fill_null(0)
)

C:\Users\tncn2\AppData\Local\Temp\ipykernel_25196\4116182049.py:3: DeprecationWarning: the argument `columns` for `DataFrame.pivot` is deprecated. It was renamed to `on` in version 1.0.0.
  .pivot(

In [38]:
user_cat_wide = (
    user_cat_cnt
    .pivot(
        index="customer_id",
        columns="category_l1",
        values="cnt"
    )
    .fill_null(0)
)

C:\Users\tncn2\AppData\Local\Temp\ipykernel_25196\4116182049.py:3: DeprecationWarning: the argument `columns` for `DataFrame.pivot` is deprecated. It was renamed to `on` in version 1.0.0.
  .pivot(

In [39]:
user_cat_wide.head()

shape: (5, 15)
┌─────────────┬───────┬─────────────┬──────────┬───┬─────────┬─────────────┬─────────┬─────────────┐
│ customer_id ┆ Thời  ┆ Thực phẩm   ┆ Babycare ┆ … ┆ Vệ sinh ┆ Hóa mỹ phẩm ┆ Textile ┆ Đồ chơi &   │
│ ---         ┆ trang ┆ cho bé      ┆ ---      ┆   ┆ ---     ┆ gia đình    ┆ ---     ┆ Sách        │
│ i32         ┆ ---   ┆ ---         ┆ u32      ┆   ┆ u32     ┆ ---         ┆ u32     ┆ ---         │
│             ┆ u32   ┆ u32         ┆          ┆   ┆         ┆ u32         ┆         ┆ u32         │
╞═════════════╪═══════╪═════════════╪══════════╪═══╪═════════╪═════════════╪═════════╪═════════════╡
│ 6998849     ┆ 10    ┆ 46          ┆ 29       ┆ … ┆ 2       ┆ 4           ┆ 0       ┆ 1           │
│ 6782461     ┆ 0     ┆ 3           ┆ 15       ┆ … ┆ 0       ┆ 0           ┆ 2       ┆ 0           │
│ 931246      ┆ 4     ┆ 1           ┆ 1        ┆ … ┆ 2       ┆ 0           ┆ 0       ┆ 2           │
│ 3481145     ┆ 0     ┆ 1           ┆ 0        ┆ … ┆ 0       ┆ 4           ┆ 0       ┆ 0           │
│ 7252039     ┆ 1     ┆ 16          ┆ 4        ┆ … ┆ 0       ┆ 1           ┆ 0       ┆ 1           │
└─────────────┴───────┴─────────────┴──────────┴───┴─────────┴─────────────┴─────────┴─────────────┘

In [40]:
rename_map = {
    col: f"cnt_cat_{col}"
    for col in user_cat_wide.columns
    if col != "customer_id"
}

user_cat_wide = user_cat_wide.rename(rename_map)

In [41]:
user_cat_wide = user_cat_wide.with_columns(
    pl.sum_horizontal(
        [pl.col(c) for c in user_cat_wide.columns if c != "customer_id"]
    ).alias("total_cat_tx")
)

In [42]:
ratio_exprs = []

for col in user_cat_wide.columns:
    if col.startswith("cnt_cat_"):
        ratio_exprs.append(
            (pl.col(col) / pl.col("total_cat_tx"))
            .alias(col.replace("cnt_", "ratio_"))
        )

user_cat_wide = user_cat_wide.with_columns(ratio_exprs)

In [43]:
user_cat_ratio = user_cat_wide.drop("total_cat_tx")

In [44]:
user_cat_ratio.head()

shape: (5, 29)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ customer_ ┆ cnt_cat_T ┆ cnt_cat_T ┆ cnt_cat_B ┆ … ┆ ratio_cat ┆ ratio_cat ┆ ratio_cat ┆ ratio_ca │
│ id        ┆ hời trang ┆ hực phẩm  ┆ abycare   ┆   ┆ _Vệ sinh  ┆ _Hóa mỹ   ┆ _Textile  ┆ t_Đồ     │
│ ---       ┆ ---       ┆ cho bé    ┆ ---       ┆   ┆ ---       ┆ phẩm gia  ┆ ---       ┆ chơi &   │
│ i32       ┆ u32       ┆ ---       ┆ u32       ┆   ┆ f64       ┆ đình      ┆ f64       ┆ Sách     │
│           ┆           ┆ u32       ┆           ┆   ┆           ┆ ---       ┆           ┆ ---      │
│           ┆           ┆           ┆           ┆   ┆           ┆ f64       ┆           ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 6998849   ┆ 10        ┆ 46        ┆ 29        ┆ … ┆ 0.012903  ┆ 0.025806  ┆ 0.0       ┆ 0.006452 │
│ 6782461   ┆ 0         ┆ 3         ┆ 15        ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.086957  ┆ 0.0      │
│ 931246    ┆ 4         ┆ 1         ┆ 1         ┆ … ┆ 0.105263  ┆ 0.0       ┆ 0.0       ┆ 0.105263 │
│ 3481145   ┆ 0         ┆ 1         ┆ 0         ┆ … ┆ 0.0       ┆ 0.08      ┆ 0.0       ┆ 0.0      │
│ 7252039   ┆ 1         ┆ 16        ┆ 4         ┆ … ┆ 0.0       ┆ 0.02381   ┆ 0.0       ┆ 0.02381  │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [46]:
cols_to_drop = [c for c in user_cat_ratio.columns if c.startswith("cnt_")]

user_cat_ratio = user_cat_ratio.drop(cols_to_drop)

In [47]:
user_cat_ratio.head()

shape: (5, 15)
┌───────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ customer_ ┆ ratio_cat ┆ ratio_cat ┆ ratio_cat ┆ … ┆ ratio_cat ┆ ratio_cat ┆ ratio_cat ┆ ratio_ca │
│ id        ┆ _Thời     ┆ _Thực     ┆ _Babycare ┆   ┆ _Vệ sinh  ┆ _Hóa mỹ   ┆ _Textile  ┆ t_Đồ     │
│ ---       ┆ trang     ┆ phẩm cho  ┆ ---       ┆   ┆ ---       ┆ phẩm gia  ┆ ---       ┆ chơi &   │
│ i32       ┆ ---       ┆ bé        ┆ f64       ┆   ┆ f64       ┆ đình      ┆ f64       ┆ Sách     │
│           ┆ f64       ┆ ---       ┆           ┆   ┆           ┆ ---       ┆           ┆ ---      │
│           ┆           ┆ f64       ┆           ┆   ┆           ┆ f64       ┆           ┆ f64      │
╞═══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 6998849   ┆ 0.064516  ┆ 0.296774  ┆ 0.187097  ┆ … ┆ 0.012903  ┆ 0.025806  ┆ 0.0       ┆ 0.006452 │
│ 6782461   ┆ 0.0       ┆ 0.130435  ┆ 0.652174  ┆ … ┆ 0.0       ┆ 0.0       ┆ 0.086957  ┆ 0.0      │
│ 931246    ┆ 0.210526  ┆ 0.052632  ┆ 0.052632  ┆ … ┆ 0.105263  ┆ 0.0       ┆ 0.0       ┆ 0.105263 │
│ 3481145   ┆ 0.0       ┆ 0.02      ┆ 0.0       ┆ … ┆ 0.0       ┆ 0.08      ┆ 0.0       ┆ 0.0      │
│ 7252039   ┆ 0.02381   ┆ 0.380952  ┆ 0.095238  ┆ … ┆ 0.0       ┆ 0.02381   ┆ 0.0       ┆ 0.02381  │
└───────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

In [48]:
output_path = "feature_engineered/user_cat_ratio.parquet"

user_cat_ratio.write_parquet(output_path)

print(f"Đã lưu user_cat_ratio tại: {output_path}")

Đã lưu user_cat_ratio tại: feature_engineered/user_cat_ratio.parquet